# Generated by Django 5.2.12 on 2026-03-19 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('crm', '0019_seed_celery_beat_procurement_demand_insights'),
        ('facility_management', '0005_facilityspaceprofile_spaceallocation_spacebooking'),
        ('finance', '0032_alter_paymentvoucher_status'),
        ('properties', '0016_servicerequest_assigned_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='corporate', max_length=20)),
                ('status', models.CharField(choices=[('pending_move_in', 'Pending Move In'), ('active', 'Active'), ('moved_out', 'Moved Out'), ('inactive', 'Inactive')], default='pending_move_in', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('lease_start_date', models.DateField(blank=True, null=True)),
                ('lease_end_date', models.DateField(blank=True, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('occupant_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to='crm.contactaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to='finance.customer')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to='facility_management.facility')),
                ('facility_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to='facility_management.facilityunitspace')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profiles', to='accounts.organization')),
                ('primary_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to='properties.unit')),
            ],
            options={
                'ordering': ['display_name', 'id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='tenant_prof_org_status_idx'), models.Index(fields=['organization', 'property'], name='tenant_prof_org_prop_idx'), models.Index(fields=['organization', 'facility_space'], name='tenant_prof_org_space_idx')],
            },
        ),
    ]
