# Generated by Django 5.2.12 on 2026-03-20 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantCommunicationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interaction_type", models.CharField(choices=[("note", "Note"), ("phone", "Phone Call"), ("email", "Email"), ("whatsapp", "WhatsApp"), ("invoice_generated", "Invoice Generated"), ("payment_reminder", "Payment Reminder"), ("eviction_notice", "Eviction Notice"), ("system", "System")], default="note", max_length=30)),
                ("channel", models.CharField(choices=[("internal_note", "Internal Note"), ("phone", "Phone Call"), ("email", "Email"), ("whatsapp", "WhatsApp"), ("system", "System")], default="internal_note", max_length=20)),
                ("direction", models.CharField(choices=[("internal", "Internal"), ("outbound", "Outbound"), ("inbound", "Inbound")], default="internal", max_length=10)),
                ("status", models.CharField(choices=[("recorded", "Recorded"), ("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed")], default="recorded", max_length=15)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("happened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tenant_communication_logs", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tenant_communication_logs", to="accounts.organization")),
                ("tenant_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="communication_logs", to="tenants.tenantprofile")),
            ],
            options={
                "ordering": ["-happened_at", "-id"],
                "indexes": [
                    models.Index(fields=["organization", "tenant_profile", "-happened_at"], name="tenant_comm_org_profile_idx"),
                    models.Index(fields=["organization", "interaction_type", "-happened_at"], name="tenant_comm_org_type_idx"),
                ],
            },
        ),
    ]
