# Generated by Django 5.2.12 on 2026-03-20 07:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('properties', '0016_servicerequest_assigned_agent_and_more'),
        ('tenants', '0002_tenantcommunicationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantIdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('nin', 'NIN'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID'), ('rc_certificate', 'RC Certificate'), ('tax_id', 'Tax ID'), ('other', 'Other')], default='other', max_length=30)),
                ('document_number', models.CharField(max_length=120)),
                ('holder_name', models.CharField(blank=True, max_length=255)),
                ('issuing_country', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('scan_on_file', models.BooleanField(default=False)),
                ('scan_reference', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_identity_documents', to='accounts.organization')),
                ('tenant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='tenants.tenantprofile')),
            ],
            options={
                'ordering': ['document_type', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'tenant_profile'], name='tent_iddoc_org_prof_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantIncidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('lease_violation', 'Lease Violation'), ('maintenance_issue', 'Maintenance Issue'), ('damage', 'Damage'), ('noise', 'Noise Complaint'), ('security', 'Security Incident'), ('payment_breach', 'Payment Breach'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateField(default=django.utils.timezone.localdate)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_incident_records', to='accounts.organization')),
                ('tenant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_records', to='tenants.tenantprofile')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_incident_records', to='properties.workorder')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'tenant_profile', 'status'], name='tent_inc_org_stat_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('status', models.CharField(choices=[('provided', 'Provided'), ('returned', 'Returned'), ('missing', 'Missing'), ('damaged', 'Damaged')], default='provided', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_inventory_items', to='accounts.organization')),
                ('tenant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='tenants.tenantprofile')),
            ],
            options={
                'ordering': ['item_name', 'id'],
                'indexes': [models.Index(fields=['organization', 'tenant_profile'], name='tent_inv_org_prof_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantRelationshipContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_role', models.CharField(choices=[('next_of_kin', 'Next of Kin'), ('emergency', 'Emergency Contact')], default='emergency', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_relationship_contacts', to='accounts.organization')),
                ('tenant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_contacts', to='tenants.tenantprofile')),
            ],
            options={
                'ordering': ['contact_role', '-is_primary', 'full_name'],
                'indexes': [models.Index(fields=['organization', 'tenant_profile', 'contact_role'], name='tent_rel_org_role_idx')],
            },
        ),
    ]
