# Generated by Django 5.2.12 on 2026-03-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('facility_management', '0011_seed_celery_beat_health_safety_compliance_workflows'),
        ('properties', '0016_servicerequest_assigned_agent_and_more'),
        ('tenants', '0005_seed_celery_beat_tenant_operations_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseAccessProvisioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('revoked', 'Revoked')], default='queued', max_length=20)),
                ('facility_access_active', models.BooleanField(default=False)),
                ('security_access_active', models.BooleanField(default=False)),
                ('portal_access_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_access_provisioning_records', to='facility_management.facility')),
                ('facility_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_access_provisioning_records', to='facility_management.facilityunitspace')),
                ('lease_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_provisioning', to='tenants.leaseagreement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_access_provisioning_records', to='accounts.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_access_provisioning_records', to='properties.property')),
                ('tenant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_access_provisioning_records', to='tenants.tenantprofile')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_access_provisioning_records', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='tenant_access_org_status_idx'), models.Index(fields=['organization', 'tenant_profile'], name='tenant_access_org_profile_idx')],
            },
        ),
    ]
