# Generated by Django 5.2.12 on 2026-03-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('facility_management', '0011_seed_celery_beat_health_safety_compliance_workflows'),
        ('properties', '0016_servicerequest_assigned_agent_and_more'),
        ('tenants', '0006_leaseaccessprovisioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantVacancyRiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('forecasted_vacancy_date', models.DateField(blank=True, null=True)),
                ('days_to_vacancy', models.IntegerField(default=0)),
                ('tenant_notified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_vacancy_risk_alerts', to='facility_management.facility')),
                ('facility_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_vacancy_risk_alerts', to='facility_management.facilityunitspace')),
                ('lease_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_risk_alert', to='tenants.leaseagreement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_vacancy_risk_alerts', to='accounts.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_vacancy_risk_alerts', to='properties.property')),
                ('tenant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_risk_alerts', to='tenants.tenantprofile')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_vacancy_risk_alerts', to='properties.unit')),
            ],
            options={
                'ordering': ['-risk_score', 'forecasted_vacancy_date', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='tenant_vacancy_org_status_idx'), models.Index(fields=['organization', 'risk_level'], name='tenant_vacancy_org_level_idx'), models.Index(fields=['organization', 'forecasted_vacancy_date'], name='tenant_vacancy_org_date_idx')],
            },
        ),
    ]
