# Generated by Django 5.2.12 on 2026-03-20 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('facility_management', '0011_seed_celery_beat_health_safety_compliance_workflows'),
        ('finance', '0032_alter_paymentvoucher_status'),
        ('properties', '0016_servicerequest_assigned_agent_and_more'),
        ('tenants', '0007_tenantvacancyriskalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDepositSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('assessed_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('refundable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('additional_amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending_inspection', 'Pending Inspection'), ('pending_refund', 'Pending Refund'), ('pending_collection', 'Pending Collection'), ('settled', 'Settled')], default='pending_inspection', max_length=25)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_deposit_settlements', to='finance.invoice')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_deposit_settlements', to='facility_management.facility')),
                ('facility_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_deposit_settlements', to='facility_management.facilityunitspace')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_settlements', to='tenants.tenantinspection')),
                ('lease_agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_settlement', to='tenants.leaseagreement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_deposit_settlements', to='accounts.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_deposit_settlements', to='properties.property')),
                ('tenant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_settlements', to='tenants.tenantprofile')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_deposit_settlements', to='properties.unit')),
            ],
            options={
                'ordering': ['status', 'move_out_date', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='tenant_depstl_org_status_idx'), models.Index(fields=['organization', 'move_out_date'], name='tenant_depstl_org_moveout_idx')],
            },
        ),
    ]
