# Generated by Django 5.2.12 on 2026-03-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenantdepositsettlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantprofile",
            name="last_satisfaction_feedback_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenantprofile",
            name="satisfaction_response_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tenantprofile",
            name="satisfaction_score",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
