# Generated by Django 5.2.12 on 2026-03-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_seed_platform_roles"),
        ("facility_management", "0011_seed_celery_beat_health_safety_compliance_workflows"),
        ("properties", "0017_servicerequest_tenant_profile"),
        ("tenants", "0009_tenantprofile_satisfaction_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaseUtilityTracking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("queued", "Queued"), ("active", "Active"), ("inactive", "Inactive")], default="queued", max_length=20)),
                ("utility_tracking_active", models.BooleanField(default=False)),
                ("tracked_utility_types", models.JSONField(blank=True, default=list)),
                ("tracked_meter_count", models.PositiveIntegerField(default=0)),
                ("visible_utility_bill_count", models.PositiveIntegerField(default=0)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("facility", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lease_utility_tracking_records", to="facility_management.facility")),
                ("facility_space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lease_utility_tracking_records", to="facility_management.facilityunitspace")),
                ("lease_agreement", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="utility_tracking", to="tenants.leaseagreement")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lease_utility_tracking_records", to="accounts.organization")),
                ("property", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lease_utility_tracking_records", to="properties.property")),
                ("tenant_profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lease_utility_tracking_records", to="tenants.tenantprofile")),
                ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lease_utility_tracking_records", to="properties.unit")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["organization", "status"], name="tent_utktrk_org_stat_idx"),
                    models.Index(fields=["organization", "tenant_profile"], name="tent_utktrk_org_prof_idx"),
                ],
            },
        ),
    ]
