import type {
  BonusListItem,
  DeductionListItem,
  EmployeeDirectoryItem,
  PayslipDetail,
  PayslipListItem,
  PayrollRunListItem,
  ProjectListItem,
  ProjectWorkforceLog,
  TaxRecordListItem,
} from "$lib/types";

const TS = "2026-03-25T09:00:00Z";

export const PREVIEW_PAYROLL_DASHBOARD_DATA: {
  employees: EmployeeDirectoryItem[];
  payrollRuns: PayrollRunListItem[];
  payslips: PayslipListItem[];
  taxRecords: TaxRecordListItem[];
  deductions: DeductionListItem[];
  bonuses: BonusListItem[];
  workforceLogs: ProjectWorkforceLog[];
  projects: ProjectListItem[];
} = {
  employees: [
    {
      id: 1,
      user_id: 101,
      full_name: "Amina Bello",
      email: "amina.bello@example.com",
      employee_id: "HR-001",
      job_title: "Project Manager",
      department_name: "Projects",
      position_title: "Project Manager",
      employment_type: "permanent",
      manager_name: "Musa Yusuf",
      office_location: "Victoria Island Site",
      profile_photo: null,
      user_status: "active",
      employment_status: "active",
      hire_date: "2024-02-12",
      contract_type: "permanent",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 2,
      user_id: 102,
      full_name: "Chinedu Okoro",
      email: "chinedu.okoro@example.com",
      employee_id: "HR-014",
      job_title: "Site Engineer",
      department_name: "Engineering",
      position_title: "Senior Engineer",
      employment_type: "permanent",
      manager_name: "Amina Bello",
      office_location: "Lekki Phase 1",
      profile_photo: null,
      user_status: "active",
      employment_status: "active",
      hire_date: "2024-08-03",
      contract_type: "permanent",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 3,
      user_id: 103,
      full_name: "Zainab Musa",
      email: "zainab.musa@example.com",
      employee_id: "HR-021",
      job_title: "Quantity Surveyor",
      department_name: "Cost Control",
      position_title: "QS Lead",
      employment_type: "contract",
      manager_name: "Amina Bello",
      office_location: "Abuja Hub",
      profile_photo: null,
      user_status: "active",
      employment_status: "probation",
      hire_date: "2026-01-06",
      contract_type: "fixed_term",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 4,
      user_id: 104,
      full_name: "Tega James",
      email: "tega.james@example.com",
      employee_id: "HR-005",
      job_title: "Finance Lead",
      department_name: "Finance",
      position_title: "Finance Lead",
      employment_type: "permanent",
      manager_name: "CFO Desk",
      office_location: "HQ Operations",
      profile_photo: null,
      user_status: "active",
      employment_status: "active",
      hire_date: "2023-05-15",
      contract_type: "permanent",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 5,
      user_id: 105,
      full_name: "Ifeoma Nwosu",
      email: "ifeoma.nwosu@example.com",
      employee_id: "HR-029",
      job_title: "Admin Officer",
      department_name: "Operations",
      position_title: "Admin Officer",
      employment_type: "permanent",
      manager_name: "Tega James",
      office_location: "HQ Operations",
      profile_photo: null,
      user_status: "active",
      employment_status: "active",
      hire_date: "2025-04-20",
      contract_type: "permanent",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 6,
      user_id: 106,
      full_name: "Sade Akinyemi",
      email: "sade.akinyemi@example.com",
      employee_id: "HR-041",
      job_title: "MEP Coordinator",
      department_name: "Engineering",
      position_title: "MEP Coordinator",
      employment_type: "permanent",
      manager_name: "Chinedu Okoro",
      office_location: "Lekki Phase 1",
      profile_photo: null,
      user_status: "active",
      employment_status: "active",
      hire_date: "2025-09-10",
      contract_type: "permanent",
      created_at: TS,
      updated_at: TS,
    },
  ],
  payrollRuns: [
    {
      id: 11,
      name: "March 2026 — Monthly Salaries",
      period_start: "2026-03-01",
      period_end: "2026-03-31",
      run_date: "2026-03-27",
      status: "processing",
      total_gross: "3690000.00",
      total_deductions: "640000.00",
      total_net: "3050000.00",
      currency: "NGN",
      processed_by: 104,
      processed_by_name: "Tega James",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 12,
      name: "Week 12 2026 — Site Wages",
      period_start: "2026-03-16",
      period_end: "2026-03-22",
      run_date: "2026-03-23",
      status: "draft",
      total_gross: "10040000.00",
      total_deductions: "770000.00",
      total_net: "9270000.00",
      currency: "NGN",
      processed_by: null,
      processed_by_name: null,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 13,
      name: "Roofing Complete Bonus",
      period_start: "2026-03-01",
      period_end: "2026-03-31",
      run_date: "2026-03-20",
      status: "completed",
      total_gross: "980000.00",
      total_deductions: "50000.00",
      total_net: "930000.00",
      currency: "NGN",
      processed_by: 104,
      processed_by_name: "Tega James",
      created_at: TS,
      updated_at: TS,
    },
  ],
  payslips: [
    {
      id: 201,
      employee: 1,
      employee_name: "Amina Bello",
      payroll_run: 11,
      payroll_run_name: "March 2026 — Monthly Salaries",
      period_start: "2026-03-01",
      period_end: "2026-03-31",
      gross_salary: "1020000.00",
      net_salary: "850000.00",
      currency: "NGN",
      status: "acknowledged",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 202,
      employee: 2,
      employee_name: "Chinedu Okoro",
      payroll_run: 11,
      payroll_run_name: "March 2026 — Monthly Salaries",
      period_start: "2026-03-01",
      period_end: "2026-03-31",
      gross_salary: "730000.00",
      net_salary: "600000.00",
      currency: "NGN",
      status: "generated",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 204,
      employee: 4,
      employee_name: "Tega James",
      payroll_run: 11,
      payroll_run_name: "March 2026 — Monthly Salaries",
      period_start: "2026-03-01",
      period_end: "2026-03-31",
      gross_salary: "640000.00",
      net_salary: "520000.00",
      currency: "NGN",
      status: "sent",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 205,
      employee: 5,
      employee_name: "Ifeoma Nwosu",
      payroll_run: 11,
      payroll_run_name: "March 2026 — Monthly Salaries",
      period_start: "2026-03-01",
      period_end: "2026-03-31",
      gross_salary: "460000.00",
      net_salary: "380000.00",
      currency: "NGN",
      status: "acknowledged",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 206,
      employee: 6,
      employee_name: "Sade Akinyemi",
      payroll_run: 11,
      payroll_run_name: "March 2026 — Monthly Salaries",
      period_start: "2026-03-01",
      period_end: "2026-03-31",
      gross_salary: "840000.00",
      net_salary: "700000.00",
      currency: "NGN",
      status: "sent",
      created_at: TS,
      updated_at: TS,
    },
  ],
  taxRecords: [
    {
      id: 301,
      employee: 1,
      employee_name: "Amina Bello",
      fiscal_year: "2026",
      tax_type: "income_tax",
      tax_amount: "420000.00",
      tax_paid: "210000.00",
      balance: "210000.00",
      currency: "NGN",
      filing_status: "assessed",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 302,
      employee: 2,
      employee_name: "Chinedu Okoro",
      fiscal_year: "2026",
      tax_type: "social_security",
      tax_amount: "180000.00",
      tax_paid: "90000.00",
      balance: "90000.00",
      currency: "NGN",
      filing_status: "filed",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 303,
      employee: 4,
      employee_name: "Tega James",
      fiscal_year: "2026",
      tax_type: "municipal",
      tax_amount: "60000.00",
      tax_paid: "0.00",
      balance: "60000.00",
      currency: "NGN",
      filing_status: "pending",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 304,
      employee: 6,
      employee_name: "Sade Akinyemi",
      fiscal_year: "2026",
      tax_type: "income_tax",
      tax_amount: "260000.00",
      tax_paid: "150000.00",
      balance: "110000.00",
      currency: "NGN",
      filing_status: "filed",
      created_at: TS,
      updated_at: TS,
    },
  ],
  deductions: [
    {
      id: 401,
      employee: 1,
      employee_name: "Amina Bello",
      deduction_type: "pension",
      name: "Pension Contribution",
      amount: "90000.00",
      currency: "NGN",
      frequency: "monthly",
      is_active: true,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 402,
      employee: 2,
      employee_name: "Chinedu Okoro",
      deduction_type: "tax",
      name: "PAYE",
      amount: "75000.00",
      currency: "NGN",
      frequency: "monthly",
      is_active: true,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 403,
      employee: 4,
      employee_name: "Tega James",
      deduction_type: "pension",
      name: "PenCom",
      amount: "55000.00",
      currency: "NGN",
      frequency: "monthly",
      is_active: true,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 404,
      employee: 5,
      employee_name: "Ifeoma Nwosu",
      deduction_type: "pension",
      name: "Pension Contribution",
      amount: "40000.00",
      currency: "NGN",
      frequency: "monthly",
      is_active: true,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 405,
      employee: 6,
      employee_name: "Sade Akinyemi",
      deduction_type: "tax",
      name: "PAYE",
      amount: "68000.00",
      currency: "NGN",
      frequency: "monthly",
      is_active: true,
      created_at: TS,
      updated_at: TS,
    },
  ],
  bonuses: [
    {
      id: 501,
      employee: 1,
      employee_name: "Amina Bello",
      bonus_type: "project",
      amount: "480000.00",
      currency: "NGN",
      date: "2026-03-19",
      status: "approved",
      approved_by: 104,
      approved_by_name: "Tega James",
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 502,
      employee: 2,
      employee_name: "Chinedu Okoro",
      bonus_type: "performance",
      amount: "250000.00",
      currency: "NGN",
      date: "2026-03-22",
      status: "pending",
      approved_by: null,
      approved_by_name: null,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 503,
      employee: 6,
      employee_name: "Sade Akinyemi",
      bonus_type: "project",
      amount: "200000.00",
      currency: "NGN",
      date: "2026-03-20",
      status: "paid",
      approved_by: 104,
      approved_by_name: "Tega James",
      created_at: TS,
      updated_at: TS,
    },
  ],
  workforceLogs: [
    {
      id: 601,
      project: 1001,
      project_name: "Victoria Island",
      worker_id: "WF-1001",
      employee: 1,
      employee_name: "Amina Bello",
      trade: "Project Management",
      contractor: null,
      contractor_name: null,
      report_date: "2026-03-24",
      daily_attendance: "present",
      shift: "day",
      task_assigned: null,
      task_assigned_name: null,
      productivity: "94.00",
      overtime_hours: "2.00",
      laborers_count: 0,
      skilled_count: 0,
      supervisors_count: 1,
      subcontractors_count: 0,
      equipment_operators_count: 0,
      notes: "Final approvals for facade package.",
      hr_employment_status: "active",
      payroll_status: "synced",
      latest_payslip_period_end: "2026-03-31",
      latest_payslip_net_salary: "850000.00",
      safety_training_status: "compliant",
      total_headcount: 1,
      created_by: 104,
      updated_by: 104,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 602,
      project: 1002,
      project_name: "Lekki Phase 1",
      worker_id: "WF-1002",
      employee: 2,
      employee_name: "Chinedu Okoro",
      trade: "Site Engineering",
      contractor: null,
      contractor_name: null,
      report_date: "2026-03-24",
      daily_attendance: "present",
      shift: "day",
      task_assigned: null,
      task_assigned_name: null,
      productivity: "88.00",
      overtime_hours: "6.00",
      laborers_count: 0,
      skilled_count: 0,
      supervisors_count: 0,
      subcontractors_count: 0,
      equipment_operators_count: 0,
      notes: "MEP coordination and snag close-out.",
      hr_employment_status: "active",
      payroll_status: "synced",
      latest_payslip_period_end: "2026-03-31",
      latest_payslip_net_salary: "600000.00",
      safety_training_status: "compliant",
      total_headcount: 1,
      created_by: 104,
      updated_by: 104,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 603,
      project: 1002,
      project_name: "Lekki Phase 1",
      worker_id: "WF-1002",
      employee: 2,
      employee_name: "Chinedu Okoro",
      trade: "Site Engineering",
      contractor: null,
      contractor_name: null,
      report_date: "2026-03-19",
      daily_attendance: "present",
      shift: "day",
      task_assigned: null,
      task_assigned_name: null,
      productivity: "85.00",
      overtime_hours: "4.00",
      laborers_count: 0,
      skilled_count: 0,
      supervisors_count: 0,
      subcontractors_count: 0,
      equipment_operators_count: 0,
      notes: "Client walkthrough support.",
      hr_employment_status: "active",
      payroll_status: "synced",
      latest_payslip_period_end: "2026-03-31",
      latest_payslip_net_salary: "600000.00",
      safety_training_status: "compliant",
      total_headcount: 1,
      created_by: 104,
      updated_by: 104,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 604,
      project: 1001,
      project_name: "Victoria Island",
      worker_id: "WF-1002",
      employee: 2,
      employee_name: "Chinedu Okoro",
      trade: "Site Engineering",
      contractor: null,
      contractor_name: null,
      report_date: "2026-03-11",
      daily_attendance: "present",
      shift: "day",
      task_assigned: null,
      task_assigned_name: null,
      productivity: "81.00",
      overtime_hours: "3.00",
      laborers_count: 0,
      skilled_count: 0,
      supervisors_count: 0,
      subcontractors_count: 0,
      equipment_operators_count: 0,
      notes: "Temporary support for waterproofing inspection.",
      hr_employment_status: "active",
      payroll_status: "synced",
      latest_payslip_period_end: "2026-03-31",
      latest_payslip_net_salary: "600000.00",
      safety_training_status: "compliant",
      total_headcount: 1,
      created_by: 104,
      updated_by: 104,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 605,
      project: 1002,
      project_name: "Lekki Phase 1",
      worker_id: "WF-1006",
      employee: 6,
      employee_name: "Sade Akinyemi",
      trade: "MEP Coordination",
      contractor: null,
      contractor_name: null,
      report_date: "2026-03-23",
      daily_attendance: "present",
      shift: "day",
      task_assigned: null,
      task_assigned_name: null,
      productivity: "91.00",
      overtime_hours: "5.00",
      laborers_count: 0,
      skilled_count: 0,
      supervisors_count: 0,
      subcontractors_count: 0,
      equipment_operators_count: 0,
      notes: "Close-out of fire alarm interfaces.",
      hr_employment_status: "active",
      payroll_status: "synced",
      latest_payslip_period_end: "2026-03-31",
      latest_payslip_net_salary: "700000.00",
      safety_training_status: "compliant",
      total_headcount: 1,
      created_by: 104,
      updated_by: 104,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 606,
      project: 1003,
      project_name: "Abuja Hub",
      worker_id: "WF-1003",
      employee: 3,
      employee_name: "Zainab Musa",
      trade: "Quantity Surveying",
      contractor: null,
      contractor_name: null,
      report_date: "2026-03-24",
      daily_attendance: "present",
      shift: "day",
      task_assigned: null,
      task_assigned_name: null,
      productivity: "72.00",
      overtime_hours: "14.00",
      laborers_count: 0,
      skilled_count: 0,
      supervisors_count: 0,
      subcontractors_count: 0,
      equipment_operators_count: 0,
      notes: "Measurement sheet still pending final approval.",
      hr_employment_status: "probation",
      payroll_status: "pending",
      latest_payslip_period_end: null,
      latest_payslip_net_salary: null,
      safety_training_status: "pending",
      total_headcount: 1,
      created_by: 104,
      updated_by: 104,
      created_at: TS,
      updated_at: TS,
    },
    {
      id: 607,
      project: 1003,
      project_name: "Abuja Hub",
      worker_id: "WF-CREW-40",
      employee: null,
      employee_name: null,
      trade: "Site Crew",
      contractor: null,
      contractor_name: null,
      report_date: "2026-03-24",
      daily_attendance: "present",
      shift: "full_day",
      task_assigned: null,
      task_assigned_name: null,
      productivity: "78.00",
      overtime_hours: "86.00",
      laborers_count: 24,
      skilled_count: 9,
      supervisors_count: 3,
      subcontractors_count: 2,
      equipment_operators_count: 2,
      notes: "Concrete frame acceleration with night support team.",
      hr_employment_status: null,
      payroll_status: "not_linked",
      latest_payslip_period_end: null,
      latest_payslip_net_salary: null,
      safety_training_status: "not_linked",
      total_headcount: 40,
      created_by: 104,
      updated_by: 104,
      created_at: TS,
      updated_at: TS,
    },
  ],
  projects: [
    {
      id: 1001,
      name: "Victoria Island",
      property: null,
      property_name: null,
      status: "in_progress",
      project_type: "mixed_use",
      number_of_units: 42,
      location: "Lagos",
      gps_latitude: null,
      gps_longitude: null,
      map_available: false,
      spv_entity: "VI Prime SPV",
      land_status: "",
      risk_rating: "medium",
      compliance_score: "93.00",
      compliance_status: "compliant",
      compliance_last_evaluated_at: TS,
      start_date: "2025-10-01",
      target_end_date: "2026-12-31",
      actual_end_date: null,
      budget: "480000000.00",
      target_irr: "18.50",
      project_manager: "Amina Bello",
      description: "Premium mixed-use waterfront development.",
      created_at: TS,
      updated_at: TS,
      phase_count: 6,
      progress: 58,
    },
    {
      id: 1002,
      name: "Lekki Phase 1",
      property: null,
      property_name: null,
      status: "in_progress",
      project_type: "residential",
      number_of_units: 68,
      location: "Lagos",
      gps_latitude: null,
      gps_longitude: null,
      map_available: false,
      spv_entity: "Lekki Heights SPV",
      land_status: "",
      risk_rating: "medium",
      compliance_score: "88.00",
      compliance_status: "warning",
      compliance_last_evaluated_at: TS,
      start_date: "2025-08-01",
      target_end_date: "2026-10-31",
      actual_end_date: null,
      budget: "360000000.00",
      target_irr: "16.20",
      project_manager: "Amina Bello",
      description: "Mid-rise residential delivery program.",
      created_at: TS,
      updated_at: TS,
      phase_count: 5,
      progress: 64,
    },
    {
      id: 1003,
      name: "Abuja Hub",
      property: null,
      property_name: null,
      status: "in_progress",
      project_type: "commercial",
      number_of_units: 20,
      location: "Abuja",
      gps_latitude: null,
      gps_longitude: null,
      map_available: false,
      spv_entity: "Abuja Gateway SPV",
      land_status: "",
      risk_rating: "high",
      compliance_score: "84.00",
      compliance_status: "warning",
      compliance_last_evaluated_at: TS,
      start_date: "2025-11-01",
      target_end_date: "2026-09-30",
      actual_end_date: null,
      budget: "420000000.00",
      target_irr: "17.00",
      project_manager: "Zainab Musa",
      description: "Commercial logistics and support campus.",
      created_at: TS,
      updated_at: TS,
      phase_count: 4,
      progress: 46,
    },
  ],
};

export const PREVIEW_PAYSLIP_DETAILS: Record<number, PayslipDetail> = {
  201: {
    id: 201,
    employee: 1,
    employee_name: "Amina Bello",
    payroll_run: 11,
    payroll_run_name: "March 2026 — Monthly Salaries",
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    gross_salary: "1020000.00",
    net_salary: "850000.00",
    currency: "NGN",
    status: "acknowledged",
    created_at: TS,
    updated_at: TS,
    basic_salary: "720000.00",
    total_allowances: "420000.00",
    total_deductions: "170000.00",
    generated_at: TS,
    sent_at: TS,
  },
  202: {
    id: 202,
    employee: 2,
    employee_name: "Chinedu Okoro",
    payroll_run: 11,
    payroll_run_name: "March 2026 — Monthly Salaries",
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    gross_salary: "730000.00",
    net_salary: "600000.00",
    currency: "NGN",
    status: "generated",
    created_at: TS,
    updated_at: TS,
    basic_salary: "510000.00",
    total_allowances: "220000.00",
    total_deductions: "130000.00",
    generated_at: TS,
    sent_at: null,
  },
  204: {
    id: 204,
    employee: 4,
    employee_name: "Tega James",
    payroll_run: 11,
    payroll_run_name: "March 2026 — Monthly Salaries",
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    gross_salary: "640000.00",
    net_salary: "520000.00",
    currency: "NGN",
    status: "sent",
    created_at: TS,
    updated_at: TS,
    basic_salary: "430000.00",
    total_allowances: "210000.00",
    total_deductions: "120000.00",
    generated_at: TS,
    sent_at: TS,
  },
  205: {
    id: 205,
    employee: 5,
    employee_name: "Ifeoma Nwosu",
    payroll_run: 11,
    payroll_run_name: "March 2026 — Monthly Salaries",
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    gross_salary: "460000.00",
    net_salary: "380000.00",
    currency: "NGN",
    status: "acknowledged",
    created_at: TS,
    updated_at: TS,
    basic_salary: "320000.00",
    total_allowances: "140000.00",
    total_deductions: "80000.00",
    generated_at: TS,
    sent_at: TS,
  },
  206: {
    id: 206,
    employee: 6,
    employee_name: "Sade Akinyemi",
    payroll_run: 11,
    payroll_run_name: "March 2026 — Monthly Salaries",
    period_start: "2026-03-01",
    period_end: "2026-03-31",
    gross_salary: "840000.00",
    net_salary: "700000.00",
    currency: "NGN",
    status: "sent",
    created_at: TS,
    updated_at: TS,
    basic_salary: "590000.00",
    total_allowances: "250000.00",
    total_deductions: "140000.00",
    generated_at: TS,
    sent_at: TS,
  },
};
