# Generated by Django 5.2 on 2026-03-04 21:56

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('finance', '0012_spventity_paymentplan_paymentinstallment'),
        ('projects', '0015_projecttaskcomment_projecttask_assigned_external_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Default commission percentage', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Broker',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('secondary_phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('pipeline_stage', models.CharField(choices=[('inquiry', 'Inquiry'), ('qualified', 'Qualified'), ('site_visit', 'Site Visit'), ('offer_made', 'Offer Made'), ('reservation', 'Reservation'), ('spa_issued', 'SPA Issued'), ('closed', 'Closed')], default='inquiry', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('disqualified', 'Disqualified')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('lead_type', models.CharField(choices=[('buyer', 'Buyer'), ('tenant', 'Tenant'), ('investor', 'Investor')], default='buyer', max_length=10)),
                ('referral_name', models.CharField(blank=True, max_length=255)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_capability', models.CharField(choices=[('cash', 'Cash Buyer'), ('mortgage', 'Mortgage / Bank Finance'), ('installment', 'Installment Plan'), ('mixed', 'Mixed (Cash + Finance)'), ('undetermined', 'Undetermined')], default='undetermined', max_length=20)),
                ('inquiry_date', models.DateField(default=datetime.date.today)),
                ('qualified_date', models.DateField(blank=True, null=True)),
                ('site_visit_date', models.DateField(blank=True, null=True)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('spa_issued_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('score', models.PositiveIntegerField(default=0, help_text='Lead score 0-100')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.broker')),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='finance.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Lead',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('site_visit', 'Site Visit'), ('note', 'Note'), ('follow_up', 'Follow-up'), ('document', 'Document Sent'), ('other', 'Other')], default='note', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sources', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Lead Source',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadsource'),
        ),
        migrations.CreateModel(
            name='LeadStageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('inquiry', 'Inquiry'), ('qualified', 'Qualified'), ('site_visit', 'Site Visit'), ('offer_made', 'Offer Made'), ('reservation', 'Reservation'), ('spa_issued', 'SPA Issued'), ('closed', 'Closed')], max_length=20)),
                ('to_stage', models.CharField(choices=[('inquiry', 'Inquiry'), ('qualified', 'Qualified'), ('site_visit', 'Site Visit'), ('offer_made', 'Offer Made'), ('reservation', 'Reservation'), ('spa_issued', 'SPA Issued'), ('closed', 'Closed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('transitioned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='crm.lead')),
                ('transitioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Stage Transition',
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadUnitPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('office', 'Office'), ('retail', 'Retail'), ('warehouse', 'Warehouse'), ('land', 'Land'), ('other', 'Other')], default='apartment', max_length=20)),
                ('min_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('max_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('min_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('floor_preference', models.CharField(blank=True, help_text='e.g. High floor, Ground, 5-10', max_length=100)),
                ('view_preference', models.CharField(blank=True, help_text='e.g. Sea view, Garden, City', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_preferences', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead Unit Preference',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadProjectInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_interests', to='crm.lead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interests', to='projects.project')),
            ],
            options={
                'verbose_name': 'Lead Project Interest',
                'ordering': ['-created_at'],
                'unique_together': {('lead', 'project')},
            },
        ),
    ]
