# Generated by Django 5.2 on 2026-03-04 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFinancialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('existing_liabilities', models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding loans, debts, credit card balances', max_digits=15, null=True)),
                ('liquid_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Cash, savings, liquid investments', max_digits=15, null=True)),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('business_owner', 'Business Owner'), ('retired', 'Retired'), ('unemployed', 'Unemployed'), ('other', 'Other')], max_length=20)),
                ('employment_duration_months', models.PositiveIntegerField(blank=True, help_text='Months in current employment', null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('affordability_score', models.PositiveIntegerField(blank=True, help_text='Affordability score 0-100 (auto-computed or manual override)', null=True)),
                ('max_affordable_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum property price the lead can afford', max_digits=15, null=True)),
                ('debt_to_income_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='DTI ratio as percentage', max_digits=5, null=True)),
                ('mortgage_prequalified', models.BooleanField(default=False)),
                ('mortgage_prequalification_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mortgage_provider', models.CharField(blank=True, max_length=255)),
                ('mortgage_tenure_months', models.PositiveIntegerField(blank=True, help_text='Pre-approved mortgage tenure in months', null=True)),
                ('mortgage_interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate %', max_digits=5, null=True)),
                ('mortgage_notes', models.TextField(blank=True)),
                ('risk_score', models.PositiveIntegerField(blank=True, help_text='Risk score 0-100 (higher = riskier)', null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of identified risk factors')),
                ('recommended_plan', models.CharField(blank=True, choices=[('cash', 'Cash Purchase'), ('mortgage', 'Mortgage / Bank Finance'), ('installment', 'Developer Installment Plan'), ('mixed', 'Mixed (Cash + Finance)')], max_length=20)),
                ('recommended_down_payment_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommended_monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_assessments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_assessment', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead Financial Assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadPaymentScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Scenario A — 20% down + mortgage'", max_length=200)),
                ('plan_type', models.CharField(choices=[('cash', 'Cash Purchase'), ('mortgage', 'Mortgage'), ('installment', 'Installment Plan'), ('mixed', 'Mixed')], default='mortgage', max_length=20)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('down_payment_pct', models.DecimalField(decimal_places=2, default=20, help_text='Down payment percentage', max_digits=5)),
                ('financed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate %', max_digits=5, null=True)),
                ('tenure_months', models.PositiveIntegerField(default=240, help_text='Repayment period in months')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost including interest over full tenure', max_digits=15, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_affordable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='crm.leadfinancialassessment')),
            ],
            options={
                'verbose_name': 'Lead Payment Scenario',
                'ordering': ['created_at'],
            },
        ),
    ]
