# Generated by Django 5.2 on 2026-03-04 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('crm', '0002_leadfinancialassessment_leadpaymentscenario'),
        ('projects', '0015_projecttaskcomment_projecttask_assigned_external_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCommissionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage of Deal Value'), ('fixed', 'Fixed Amount'), ('tiered', 'Tiered (by deal value brackets)')], default='percentage', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=2.0, help_text='Base commission rate (percentage)', max_digits=5)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed commission amount (when type = fixed)', max_digits=15, null=True)),
                ('tiered_brackets', models.JSONField(blank=True, default=list, help_text='Brackets for tiered commissions: [{min: 0, max: 500000, rate: 3}, ...]')),
                ('trigger_stage', models.CharField(choices=[('reservation', 'On Reservation'), ('spa_issued', 'On SPA Issuance'), ('closed', 'On Deal Close'), ('milestone', 'Milestone-Based')], default='closed', max_length=20)),
                ('payment_split', models.CharField(choices=[('upfront', '100% Upfront at Trigger'), ('split_50_50', '50% at Trigger / 50% on Completion'), ('split_30_70', '30% at Trigger / 70% on Completion'), ('milestone', 'Milestone-Based Payments')], default='upfront', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='If true, applies as org-wide default when no specific structure matches')),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_structures', to='crm.broker')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_structures', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_structures', to='projects.project')),
            ],
            options={
                'verbose_name': 'Commission Structure',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrokerCommissionEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Actual commission rate applied', max_digits=5)),
                ('base_commission', models.DecimalField(decimal_places=2, help_text='Commission before tier multiplier and bonus', max_digits=15)),
                ('tier_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_commission', models.DecimalField(decimal_places=2, help_text='Final commission = base * multiplier + bonus', max_digits=15)),
                ('trigger_stage', models.CharField(choices=[('reservation', 'On Reservation'), ('spa_issued', 'On SPA Issuance'), ('closed', 'On Deal Close'), ('milestone', 'Milestone-Based')], max_length=20)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('processing', 'Processing Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_earnings', to='crm.broker')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_earnings', to='crm.lead')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_earnings', to='projects.project')),
                ('commission_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='crm.brokercommissionstructure')),
            ],
            options={
                'verbose_name': 'Commission Earning',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrokerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Platinum, Gold, Silver, Bronze', max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('min_deals', models.PositiveIntegerField(default=0, help_text='Minimum closed deals to qualify')),
                ('min_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Minimum revenue generated to qualify', max_digits=15)),
                ('commission_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier applied to base commission (e.g. 1.2 = 20% bonus)', max_digits=4)),
                ('bonus_pct', models.DecimalField(decimal_places=2, default=0, help_text='Additional bonus percentage on top of commission', max_digits=5)),
                ('evaluation_period_months', models.PositiveIntegerField(default=12, help_text='Rolling period in months for tier qualification')),
                ('benefits', models.TextField(blank=True, help_text='Text description of tier benefits')),
                ('color', models.CharField(blank=True, help_text='Hex color for UI badge', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_tiers', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Broker Tier',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='broker',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokers', to='crm.brokertier'),
        ),
    ]
