# Generated by Django 5.2 on 2026-03-05 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('crm', '0004_campaign_communicationlog_campaignrecipient_and_more'),
        ('documents', '0017_alter_documentauditevent_event_type_and_more'),
        ('finance', '0012_spventity_paymentplan_paymentinstallment'),
        ('projects', '0015_projecttaskcomment_projecttask_assigned_external_ref_and_more'),
        ('properties', '0008_inspection_compliance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('hold', 'Hold'), ('reserved', 'Reserved'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('converting', 'Converting'), ('converted', 'Converted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='hold', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Agreed unit price', max_digits=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Required deposit / earnest money', max_digits=15)),
                ('reservation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Non-refundable reservation fee', max_digits=15)),
                ('hold_expires_at', models.DateTimeField(help_text='When the temporary hold expires if not confirmed')),
                ('payment_deadline', models.DateTimeField(blank=True, help_text='When deposit payment must be received', null=True)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='finance.customer')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_reservations', to='accounts.organization')),
                ('payment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='finance.paymentplan')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_reservations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='projects.project')),
                ('reservation_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='documents.document')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Unit Reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hold_placed', 'Hold Placed'), ('hold_extended', 'Hold Extended'), ('reservation_confirmed', 'Reservation Confirmed'), ('form_generated', 'Reservation Form Generated'), ('payment_instruction_sent', 'Payment Instruction Sent'), ('deposit_received', 'Deposit Received'), ('full_payment_received', 'Full Payment Received'), ('customer_created', 'Customer Created'), ('unit_transferred', 'Unit Transferred'), ('hold_expired', 'Hold Expired'), ('cancelled', 'Cancelled'), ('note_added', 'Note Added')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_events', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.unitreservation')),
            ],
            options={
                'verbose_name': 'Reservation Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unitreservation',
            index=models.Index(fields=['organization', 'status'], name='crm_unitres_organiz_376eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='unitreservation',
            index=models.Index(fields=['lead', '-created_at'], name='crm_unitres_lead_id_27cfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='unitreservation',
            index=models.Index(fields=['unit', 'status'], name='crm_unitres_unit_id_c8c828_idx'),
        ),
        migrations.AddIndex(
            model_name='unitreservation',
            index=models.Index(fields=['status', 'hold_expires_at'], name='crm_unitres_status_9eb692_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationevent',
            index=models.Index(fields=['reservation', '-created_at'], name='crm_reserva_reserva_092e2c_idx'),
        ),
    ]
