# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('crm', '0006_lead_archived_at_lead_archived_reason_and_more'),
        ('finance', '0015_add_organization_fk'),
        ('projects', '0017_add_organization_fk'),
        ('properties', '0010_assetcomponent_prop_ac_org_created_idx_and_more'),
        ('settings', '0056_autoescalationrule_set_aer_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['organization', 'status'], name='crm_brkr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['organization', '-created_at'], name='crm_brkr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='brokercommissionearning',
            index=models.Index(fields=['broker', 'status'], name='crm_bce_broker_status_idx'),
        ),
        migrations.AddIndex(
            model_name='brokercommissionearning',
            index=models.Index(fields=['broker', '-created_at'], name='crm_bce_broker_created_idx'),
        ),
        migrations.AddIndex(
            model_name='brokercommissionstructure',
            index=models.Index(fields=['organization', '-created_at'], name='crm_bcs_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='brokertier',
            index=models.Index(fields=['organization', '-created_at'], name='crm_btier_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', 'status'], name='crm_camp_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', '-created_at'], name='crm_camp_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='crm_crec_camp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='followuprule',
            index=models.Index(fields=['organization', '-created_at'], name='crm_frul_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', 'status'], name='crm_lead_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization', '-created_at'], name='crm_lead_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='crm_lact_lead_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leadfinancialassessment',
            index=models.Index(fields=['status', '-created_at'], name='crm_lfa_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpaymentscenario',
            index=models.Index(fields=['assessment', '-created_at'], name='crm_lps_assess_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprojectinterest',
            index=models.Index(fields=['lead', '-created_at'], name='crm_lpi_lead_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['organization', '-created_at'], name='crm_lsrc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstagetransition',
            index=models.Index(fields=['lead', '-transitioned_at'], name='crm_lst_lead_trans_idx'),
        ),
        migrations.AddIndex(
            model_name='leadunitpreference',
            index=models.Index(fields=['lead', '-created_at'], name='crm_lup_lead_created_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrecord',
            index=models.Index(fields=['lead', '-scheduled_start'], name='crm_meet_lead_sched_idx'),
        ),
    ]
