# Generated by Django 5.2 on 2026-03-16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_subscription_tier"),
        ("crm", "0008_lead_tags"),
        ("finance", "0012_spventity_paymentplan_paymentinstallment"),
        ("projects", "0015_projecttaskcomment_projecttask_assigned_external_ref_and_more"),
        ("properties", "0008_inspection_compliance_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("organization", "Organization")],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("tax_identification_number", models.CharField(blank=True, max_length=100)),
                ("primary_contact_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("secondary_phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("pending_review", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                ("kyc_reference_number", models.CharField(blank=True, max_length=100)),
                ("kyc_last_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("annual_income", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("net_worth", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("liquidity_estimate", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("budget_min", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("budget_max", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                (
                    "risk_profile",
                    models.CharField(
                        choices=[
                            ("undisclosed", "Undisclosed"),
                            ("conservative", "Conservative"),
                            ("balanced", "Balanced"),
                            ("aggressive", "Aggressive"),
                        ],
                        default="undisclosed",
                        max_length=20,
                    ),
                ),
                ("preferred_locations", models.JSONField(blank=True, default=list)),
                ("preferred_property_types", models.JSONField(blank=True, default=list)),
                ("preference_notes", models.TextField(blank=True)),
                ("interaction_summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("finance_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contact_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finance_customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_contact_accounts",
                        to="finance.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_accounts",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_contact_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Account",
                "verbose_name_plural": "Contact Accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactDealLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deal_name", models.CharField(blank=True, max_length=255)),
                ("stage", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("on_hold", "On Hold"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deal_value", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("close_probability", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_links",
                        to="crm.contactaccount",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_deal_links",
                        to="crm.lead",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_deal_links",
                        to="crm.unitreservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Deal Link",
                "ordering": ["-linked_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "National ID"),
                            ("passport", "Passport"),
                            ("company_registration", "Company Registration"),
                            ("proof_of_funds", "Proof of Funds"),
                            ("utility_bill", "Utility Bill"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_url", models.CharField(blank=True, max_length=500)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("is_kyc_document", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="crm.contactaccount",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Document",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactInteraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("site_visit", "Site Visit"),
                            ("whatsapp", "WhatsApp"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                ("happened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.contactaccount",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Interaction",
                "ordering": ["-happened_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactPropertyLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("shortlisted", "Shortlisted"),
                            ("reserved", "Reserved"),
                            ("purchased", "Purchased"),
                            ("leased", "Leased"),
                            ("investor_target", "Investor Target"),
                        ],
                        default="interested",
                        max_length=20,
                    ),
                ),
                ("budget_estimate", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("notes", models.TextField(blank=True)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_links",
                        to="crm.contactaccount",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_property_links",
                        to="projects.project",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_property_links",
                        to="properties.property",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_property_links",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Property Link",
                "ordering": ["-linked_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactComplianceReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_reviews",
                        to="crm.contactaccount",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_reviews",
                        to="crm.contactdocument",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_contact_compliance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_contact_compliance_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Compliance Review",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contactaccount",
            index=models.Index(fields=["organization", "entity_type"], name="crm_cnt_org_entity_idx"),
        ),
        migrations.AddIndex(
            model_name="contactaccount",
            index=models.Index(fields=["organization", "kyc_status"], name="crm_cnt_org_kyc_idx"),
        ),
        migrations.AddIndex(
            model_name="contactaccount",
            index=models.Index(fields=["organization", "-created_at"], name="crm_cnt_org_created_idx"),
        ),
        migrations.AddIndex(
            model_name="contactinteraction",
            index=models.Index(fields=["contact", "-happened_at"], name="crm_cint_contact_time_idx"),
        ),
        migrations.AddIndex(
            model_name="contactdeallink",
            index=models.Index(fields=["contact", "status"], name="crm_cdl_contact_status_idx"),
        ),
        migrations.AddIndex(
            model_name="contactpropertylink",
            index=models.Index(fields=["contact", "relationship_type"], name="crm_cpl_contact_rel_idx"),
        ),
        migrations.AddIndex(
            model_name="contactdocument",
            index=models.Index(fields=["contact", "is_kyc_document"], name="crm_cdoc_contact_kyc_idx"),
        ),
        migrations.AddIndex(
            model_name="contactdocument",
            index=models.Index(fields=["expires_at"], name="crm_cdoc_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="contactcompliancereview",
            index=models.Index(fields=["contact", "status"], name="crm_ccr_contact_status_idx"),
        ),
        migrations.AddIndex(
            model_name="contactcompliancereview",
            index=models.Index(fields=["status", "-requested_at"], name="crm_ccr_status_requested_idx"),
        ),
    ]
