# Generated by Django 5.2.12 on 2026-03-17 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_contact_account_management'),
        ('crm', '0009_contactaccount_contactdeallink_contactdocument_and_more'),
    ]

    operations = [
    ]
