# Generated by Django 5.2.12 on 2026-03-17 12:55

import decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_subscription_tier"),
        ("crm", "0010_merge_20260317_0153"),
        ("projects", "0029_projectworkforcelog_contractor_and_more"),
        ("properties", "0013_unit_category_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="preferred_locations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Preferred locations for matching, e.g. ["Lekki", "Victoria Island"]',
            ),
        ),
        migrations.CreateModel(
            name="LeadPropertyMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "candidate_type",
                    models.CharField(choices=[("unit", "Unit"), ("project", "Project")], max_length=20),
                ),
                (
                    "match_score",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=5),
                ),
                ("score_breakdown", models.JSONField(blank=True, default=dict)),
                ("reason_summary", models.TextField(blank=True)),
                ("budget_fit", models.BooleanField(default=False)),
                ("location_fit", models.BooleanField(default=False)),
                ("unit_type_fit", models.BooleanField(default=False)),
                ("payment_eligibility_fit", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("viewed", "Viewed"),
                            ("shortlisted", "Shortlisted"),
                            ("dismissed", "Dismissed"),
                            ("converted", "Converted"),
                        ],
                        default="suggested",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("qualified_lead", "Qualified Lead"),
                            ("property_launch", "Property Launch"),
                            ("manual_refresh", "Manual Refresh"),
                        ],
                        default="manual_refresh",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_matches",
                        to="crm.lead",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_property_matches",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_matches",
                        to="projects.project",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_matches",
                        to="properties.property",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_matches",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Property Match",
                "verbose_name_plural": "Lead Property Matches",
                "ordering": ["-match_score", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="leadpropertymatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(candidate_type="unit", unit__isnull=False),
                fields=("lead", "unit"),
                name="crm_lpm_unique_lead_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="leadpropertymatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(candidate_type="project", project__isnull=False),
                fields=("lead", "project"),
                name="crm_lpm_unique_lead_project",
            ),
        ),
        migrations.AddIndex(
            model_name="leadpropertymatch",
            index=models.Index(fields=["organization", "lead", "is_active"], name="crm_lpm_org_lead_act_idx"),
        ),
        migrations.AddIndex(
            model_name="leadpropertymatch",
            index=models.Index(fields=["organization", "status", "is_active"], name="crm_lpm_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="leadpropertymatch",
            index=models.Index(fields=["organization", "-match_score"], name="crm_lpm_org_score_idx"),
        ),
        migrations.AddIndex(
            model_name="leadpropertymatch",
            index=models.Index(fields=["organization", "-updated_at"], name="crm_lpm_org_updated_idx"),
        ),
    ]
