# Generated by Django 5.2.12 on 2026-03-18 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_add_in_app_communication_channel'),
        ('documents', '0020_document_source_app_label_document_source_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitreservation',
            name='allocation_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_reservations', to='documents.document'),
        ),
    ]
