# Generated by Django 5.2 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_project_manager_projectphase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="risk_rating",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
