# Generated by Django 5.2 on 2026-03-01

import decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_risk_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="compliance_last_evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="compliance_score",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("100.00"),
                help_text="Project compliance score derived from controlled-document expiries.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("compliant", "Compliant"),
                    ("warning", "Warning"),
                    ("non_compliant", "Non-Compliant"),
                ],
                default="compliant",
                max_length=20,
            ),
        ),
    ]
