# Generated by Django 5.2 on 2026-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_phase6_project_compliance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='construction_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='land_acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='land_status',
            field=models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('under_contract', 'Under Contract'), ('to_acquire', 'To Acquire'), ('joint_venture', 'Joint Venture')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Project site address or location description', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='ownership_structure',
            field=models.TextField(blank=True, help_text='Description of ownership / equity structure'),
        ),
        migrations.AddField(
            model_name='project',
            name='permit_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('mixed_use', 'Mixed-Use'), ('commercial', 'Commercial'), ('infrastructure', 'Infrastructure')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='raci_summary',
            field=models.JSONField(blank=True, default=dict, help_text='RACI matrix summary: { role: responsibility_level }'),
        ),
        migrations.AddField(
            model_name='project',
            name='spv_entity',
            field=models.CharField(blank=True, help_text='Special Purpose Vehicle or legal entity for this project', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='target_irr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target Internal Rate of Return (%)', max_digits=6, null=True),
        ),
    ]
