# Generated by Django 5.2 on 2026-03-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_project_metadata_fields'),
        ('properties', '0007_add_full_maintenance_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='properties.property'),
        ),
    ]
