# Generated by Django 5.2 on 2026-03-03 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('projects', '0006_alter_project_property'),
        ('settings', '0020_seed_notification_sla_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRiskRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('likelihood_key', models.CharField(default='medium', max_length=32)),
                ('likelihood_score', models.PositiveSmallIntegerField(default=3)),
                ('impact_key', models.CharField(default='medium', max_length=32)),
                ('impact_score', models.PositiveSmallIntegerField(default=3)),
                ('risk_score', models.PositiveIntegerField(default=9)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('treatment', models.CharField(choices=[('mitigate', 'Mitigate'), ('avoid', 'Avoid'), ('transfer', 'Transfer'), ('accept', 'Accept')], default='mitigate', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True)),
                ('mitigation_actions', models.TextField(blank=True)),
                ('contingency_plan', models.TextField(blank=True)),
                ('response_time_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('escalation_required', models.BooleanField(default=False)),
                ('identified_on', models.DateField(default=django.utils.timezone.now)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_risk_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_risk_entries', to='accounts.organization')),
                ('owner_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_risk_owner_roles', to='settings.role')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_entries', to='projects.project')),
                ('risk_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_risk_entries', to='settings.riskcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_risk_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
    ]
