# Generated by Django 5.2 on 2026-03-04 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectdailysitereport_projectdailysitereportphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSupportingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.projects.models.project_supporting_attachment_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectcostentry')),
                ('escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectfieldescalation')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectmilestone')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.project')),
                ('risk_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectriskregisterentry')),
                ('site_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectdailysitereport')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projecttask')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_supporting_attachments', to=settings.AUTH_USER_MODEL)),
                ('workforce_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectworkforcelog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
