# Generated by Django 5.2 on 2026-03-04 13:54

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_rename_documents_d_documen_b8c25f_idx_documents_d_documen_832316_idx_and_more'),
        ('projects', '0009_projectsupportingattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVariationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_number', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('change_summary', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('requested_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_variation_orders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_orders', to='projects.project')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variation_orders', to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_variation_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='projectsupportingattachment',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectvariationorder'),
        ),
        migrations.AddIndex(
            model_name='projectvariationorder',
            index=models.Index(fields=['status', 'created_at'], name='projects_pr_status_6dd065_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvariationorder',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_f294e8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvariationorder',
            index=models.Index(fields=['contract_value', 'status'], name='projects_pr_contrac_f6dd08_idx'),
        ),
    ]
