# Generated by Django 5.2 on 2026-03-04 14:54

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projectvariationorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExecutionInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('inspection_type', models.CharField(choices=[('material_receipt', 'Material Receipt'), ('workmanship', 'Workmanship'), ('mep', 'MEP Installation'), ('finishes', 'Finishes'), ('safety_quality', 'Safety & Quality'), ('pre_handover', 'Pre-Handover'), ('other', 'Other')], default='workmanship', max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('closed', 'Closed')], default='planned', max_length=20)),
                ('inspected_on', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('full_day', 'Full Day')], default='day', max_length=16)),
                ('work_package', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('inspector_name', models.CharField(max_length=255)),
                ('inspector_role', models.CharField(blank=True, max_length=255)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('critical_findings', models.PositiveIntegerField(default=0)),
                ('major_findings', models.PositiveIntegerField(default=0)),
                ('minor_findings', models.PositiveIntegerField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_execution_inspections', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_inspections', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_inspections', to='projects.project')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='projects.projectdailysitereport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_execution_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspected_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectsupportingattachment',
            name='quality_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_attachments', to='projects.projectexecutioninspection'),
        ),
        migrations.CreateModel(
            name='ProjectExecutionInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('checklist_group', models.CharField(blank=True, max_length=120)),
                ('checklist_item', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('hold', 'Hold'), ('na', 'Not Applicable')], default='pass', max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('action_owner', models.CharField(blank=True, max_length=255)),
                ('action_due_date', models.DateField(blank=True, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='projects.projectexecutioninspection')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='projectexecutioninspection',
            index=models.Index(fields=['project', 'status', 'inspected_on'], name='projects_pr_project_3ef78c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexecutioninspection',
            index=models.Index(fields=['inspection_type', 'status', 'inspected_on'], name='projects_pr_inspect_d764d7_idx'),
        ),
    ]
