# Generated by Django 5.2 on 2026-03-04 15:07

from decimal import Decimal

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectexecutioninspection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfieldescalation',
            options={'ordering': ['-issue_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='estimated_cost_impact',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='estimated_schedule_impact_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='immediate_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='impact_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='issue_category',
            field=models.CharField(choices=[('weather', 'Weather'), ('safety', 'Safety'), ('quality', 'Quality'), ('schedule', 'Schedule'), ('cost', 'Cost'), ('workforce', 'Workforce'), ('procurement', 'Procurement'), ('equipment', 'Equipment'), ('design', 'Design'), ('compliance', 'Compliance'), ('logistics', 'Logistics'), ('community', 'Community'), ('operations', 'Operations'), ('external', 'External'), ('other', 'Other')], default='operations', max_length=24),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='issue_type',
            field=models.CharField(choices=[('weather_delay', 'Weather Delay'), ('extreme_rain_flooding', 'Extreme Rain / Flooding'), ('high_wind', 'High Wind'), ('lightning_storm', 'Lightning Storm'), ('extreme_heat', 'Extreme Heat'), ('material_shortage', 'Material Shortage'), ('material_damage', 'Material Damage'), ('late_delivery', 'Late Delivery'), ('vendor_non_performance', 'Vendor Non-Performance'), ('subcontractor_non_performance', 'Subcontractor Non-Performance'), ('workforce_shortage', 'Workforce Shortage'), ('labor_dispute', 'Labor Dispute'), ('equipment_breakdown', 'Equipment Breakdown'), ('equipment_unavailable', 'Equipment Unavailable'), ('quality_defect', 'Quality Defect'), ('rework_required', 'Rework Required'), ('inspection_failure', 'Inspection Failure'), ('test_failure', 'Test Failure'), ('safety_incident', 'Safety Incident'), ('near_miss', 'Near Miss'), ('accident_injury', 'Accident / Injury'), ('security_breach', 'Security Breach'), ('theft_vandalism', 'Theft / Vandalism'), ('design_change', 'Design Change'), ('drawing_conflict', 'Drawing Conflict'), ('rfi_pending', 'RFI Pending'), ('permit_hold', 'Permit Hold'), ('regulatory_stop_notice', 'Regulatory Stop Notice'), ('environmental_non_compliance', 'Environmental Non-Compliance'), ('access_restriction', 'Access Restriction'), ('traffic_logistics', 'Traffic / Logistics Constraint'), ('utility_outage', 'Utility Outage'), ('community_complaint', 'Community Complaint'), ('scope_change', 'Scope Change'), ('schedule_slippage', 'Schedule Slippage'), ('cost_overrun', 'Cost Overrun'), ('payment_delay', 'Payment Delay'), ('it_system_outage', 'IT System Outage'), ('data_loss', 'Data Loss'), ('handover_defect', 'Handover Defect'), ('force_majeure', 'Force Majeure'), ('general_site_issue', 'General Site Issue'), ('other', 'Other')], default='general_site_issue', max_length=40),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='weather_condition',
            field=models.CharField(blank=True, choices=[('clear', 'Clear'), ('cloudy', 'Cloudy'), ('rain', 'Rain'), ('storm', 'Storm'), ('windy', 'Windy'), ('other', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='projectfieldescalation',
            name='weather_delay_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='projectfieldescalation',
            index=models.Index(fields=['project', 'issue_date', 'status'], name='projects_pr_project_ace690_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfieldescalation',
            index=models.Index(fields=['issue_category', 'issue_type', 'status'], name='projects_pr_issue_c_c97d90_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfieldescalation',
            index=models.Index(fields=['issue_type', 'issue_date'], name='projects_pr_issue_t_994ac3_idx'),
        ),
    ]
