# Generated by Django 5.2 on 2026-03-04 16:32

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectfieldescalation_options_and_more'),
        ('settings', '0024_integrationgovernancesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='baseline_target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='revised_target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='schedule_revision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='baseline_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='baseline_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='revised_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='revised_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='schedule_revision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectMilestoneApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_approval_rules', to='projects.project')),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_milestone_approval_rules', to='settings.role')),
            ],
            options={
                'ordering': ['phase_id', 'sequence_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestoneApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_milestone_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_milestone_approval_decisions', to='settings.role')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decisions', to='projects.projectmilestone')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='projects.projectmilestoneapprovalrule')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhaseDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('fs', 'Finish to Start'), ('ss', 'Start to Start'), ('ff', 'Finish to Finish'), ('sf', 'Start to Finish')], default='fs', max_length=2)),
                ('lag_days', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_dependencies', to='projects.project')),
                ('successor_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='projects.projectphase')),
            ],
            options={
                'ordering': ['predecessor_phase_id', 'successor_phase_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScheduleDelayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delay_type', models.CharField(choices=[('weather', 'Weather'), ('permit', 'Permit / Regulatory'), ('design', 'Design / RFI'), ('procurement', 'Procurement / Delivery'), ('workforce', 'Workforce'), ('equipment', 'Equipment'), ('safety', 'Safety Incident'), ('financial', 'Financial / Payment'), ('client', 'Client Change'), ('other', 'Other')], default='other', max_length=20)),
                ('impact_days', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason', models.TextField(blank=True)),
                ('mitigation_action', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_schedule_delay_logs', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_logs', to='projects.projectmilestone')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_logs', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_delay_logs', to='projects.project')),
                ('source_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_logs', to='projects.projectfieldescalation')),
            ],
            options={
                'ordering': ['-delay_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectmilestoneapprovalrule',
            constraint=models.UniqueConstraint(fields=('project', 'phase', 'required_role', 'sequence_order'), name='unique_project_milestone_approval_rule'),
        ),
        migrations.AddIndex(
            model_name='projectmilestoneapprovaldecision',
            index=models.Index(fields=['milestone', 'decision'], name='projects_pr_milesto_2bd6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestoneapprovaldecision',
            index=models.Index(fields=['approver_role', 'decision'], name='projects_pr_approve_515bda_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectphasedependency',
            constraint=models.UniqueConstraint(fields=('project', 'predecessor_phase', 'successor_phase'), name='unique_project_phase_dependency_edge'),
        ),
        migrations.AddConstraint(
            model_name='projectphasedependency',
            constraint=models.CheckConstraint(condition=models.Q(('predecessor_phase', models.F('successor_phase')), _negated=True), name='project_phase_dependency_no_self_loop'),
        ),
        migrations.AddIndex(
            model_name='projectscheduledelaylog',
            index=models.Index(fields=['project', 'delay_date'], name='projects_pr_project_dd21f0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectscheduledelaylog',
            index=models.Index(fields=['delay_type', 'delay_date'], name='projects_pr_delay_t_2d9016_idx'),
        ),
    ]
