# Generated by Django 5.2 on 2026-03-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_spventity_paymentplan_paymentinstallment'),
        ('projects', '0013_projectmilestone_approval_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='spv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='finance.spventity'),
        ),
    ]
