# Generated by Django 5.2 on 2026-03-04 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_documentauditevent_event_type_and_more'),
        ('projects', '0014_project_spv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='assigned_external_ref',
            field=models.CharField(blank=True, help_text='External directory/ERP/ITSM assignee reference for future integrations.', max_length=255),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='linked_documents',
            field=models.ManyToManyField(blank=True, related_name='linked_project_tasks', to='documents.document'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='linked_risks',
            field=models.ManyToManyField(blank=True, related_name='linked_tasks', to='projects.projectriskregisterentry'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='linked_variation_orders',
            field=models.ManyToManyField(blank=True, related_name='linked_tasks', to='projects.projectvariationorder'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='sla_breached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='sla_target_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='work_package',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['status', 'priority', 'due_date'], name='projects_pr_status_cbc63c_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['assigned_user', 'status'], name='projects_pr_assigne_003083_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['sla_target_at', 'status'], name='projects_pr_sla_tar_b97617_idx'),
        ),
        migrations.AddField(
            model_name='projecttaskcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttaskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projecttask'),
        ),
        migrations.AddIndex(
            model_name='projecttaskcomment',
            index=models.Index(fields=['task', 'created_at'], name='projects_pr_task_id_19623f_idx'),
        ),
    ]
