# Generated by Django 5.2 on 2026-03-07 06:01

from django.db import migrations, models

import apps.settings.currency


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projecttaskcomment_projecttask_assigned_external_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvariationorder',
            name='currency',
            field=models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3),
        ),
    ]
