import django.db.models.deletion
from django.db import migrations, models


def populate_organization(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    org = Organization.objects.first()
    if org is None:
        return
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(organization__isnull=True).update(organization=org)
    ProjectPhase = apps.get_model("projects", "ProjectPhase")
    ProjectPhase.objects.filter(organization__isnull=True).update(organization=org)
    ProjectMilestone = apps.get_model("projects", "ProjectMilestone")
    ProjectMilestone.objects.filter(organization__isnull=True).update(organization=org)
    ProjectPhaseDependency = apps.get_model("projects", "ProjectPhaseDependency")
    ProjectPhaseDependency.objects.filter(organization__isnull=True).update(organization=org)
    ProjectMilestoneApprovalRule = apps.get_model("projects", "ProjectMilestoneApprovalRule")
    ProjectMilestoneApprovalRule.objects.filter(organization__isnull=True).update(organization=org)
    ProjectMilestoneApprovalDecision = apps.get_model("projects", "ProjectMilestoneApprovalDecision")
    ProjectMilestoneApprovalDecision.objects.filter(organization__isnull=True).update(organization=org)
    ProjectTask = apps.get_model("projects", "ProjectTask")
    ProjectTask.objects.filter(organization__isnull=True).update(organization=org)
    ProjectTaskComment = apps.get_model("projects", "ProjectTaskComment")
    ProjectTaskComment.objects.filter(organization__isnull=True).update(organization=org)
    ProjectCostEntry = apps.get_model("projects", "ProjectCostEntry")
    ProjectCostEntry.objects.filter(organization__isnull=True).update(organization=org)
    ProjectRiskRegisterEntry = apps.get_model("projects", "ProjectRiskRegisterEntry")
    ProjectRiskRegisterEntry.objects.filter(organization__isnull=True).update(organization=org)
    ProjectVariationOrder = apps.get_model("projects", "ProjectVariationOrder")
    ProjectVariationOrder.objects.filter(organization__isnull=True).update(organization=org)
    ProjectWorkforceLog = apps.get_model("projects", "ProjectWorkforceLog")
    ProjectWorkforceLog.objects.filter(organization__isnull=True).update(organization=org)
    ProjectDailySiteReport = apps.get_model("projects", "ProjectDailySiteReport")
    ProjectDailySiteReport.objects.filter(organization__isnull=True).update(organization=org)
    ProjectDailySiteReportPhoto = apps.get_model("projects", "ProjectDailySiteReportPhoto")
    ProjectDailySiteReportPhoto.objects.filter(organization__isnull=True).update(organization=org)
    ProjectExecutionInspection = apps.get_model("projects", "ProjectExecutionInspection")
    ProjectExecutionInspection.objects.filter(organization__isnull=True).update(organization=org)
    ProjectExecutionInspectionItem = apps.get_model("projects", "ProjectExecutionInspectionItem")
    ProjectExecutionInspectionItem.objects.filter(organization__isnull=True).update(organization=org)
    ProjectSupportingAttachment = apps.get_model("projects", "ProjectSupportingAttachment")
    ProjectSupportingAttachment.objects.filter(organization__isnull=True).update(organization=org)
    ProjectFieldEscalation = apps.get_model("projects", "ProjectFieldEscalation")
    ProjectFieldEscalation.objects.filter(organization__isnull=True).update(organization=org)
    ProjectScheduleDelayLog = apps.get_model("projects", "ProjectScheduleDelayLog")
    ProjectScheduleDelayLog.objects.filter(organization__isnull=True).update(organization=org)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("projects", "0016_alter_projectvariationorder_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_projects",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectphase",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_phases",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_milestones",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectphasedependency",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_phase_dependencies",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestoneapprovalrule",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_milestone_approval_rules",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestoneapprovaldecision",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_milestone_approval_decisions",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projecttask",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_tasks",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projecttaskcomment",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_task_comments",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectcostentry",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_cost_entries",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectvariationorder",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_variation_orders",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectworkforcelog",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_workforce_logs",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectdailysitereport",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_daily_site_reports",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectdailysitereportphoto",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_daily_site_report_photos",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectexecutioninspection",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_execution_inspections",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectexecutioninspectionitem",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_execution_inspection_items",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectsupportingattachment",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_supporting_attachments",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectfieldescalation",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_field_escalations",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="projectscheduledelaylog",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_schedule_delay_logs",
                to="accounts.organization",
            ),
        ),
        migrations.RunPython(populate_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_projects",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectphase",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_phases",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectmilestone",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_milestones",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectphasedependency",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_phase_dependencies",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectmilestoneapprovalrule",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_milestone_approval_rules",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectmilestoneapprovaldecision",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_milestone_approval_decisions",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_tasks",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projecttaskcomment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_task_comments",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectcostentry",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_cost_entries",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectvariationorder",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_variation_orders",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectworkforcelog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_workforce_logs",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectdailysitereport",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_daily_site_reports",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectdailysitereportphoto",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_daily_site_report_photos",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecutioninspection",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_execution_inspections",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectexecutioninspectionitem",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_execution_inspection_items",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectsupportingattachment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_supporting_attachments",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectfieldescalation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_field_escalations",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="projectscheduledelaylog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_project_schedule_delay_logs",
                to="accounts.organization",
            ),
        ),
    ]
