# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('documents', '0019_controlledvocabularyterm_doc_cvt_org_status_idx_and_more'),
        ('finance', '0016_account_fin_acct_org_created_idx_and_more'),
        ('projects', '0017_add_organization_fk'),
        ('properties', '0010_assetcomponent_prop_ac_org_created_idx_and_more'),
        ('settings', '0056_autoescalationrule_set_aer_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='proj_proj_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', '-created_at'], name='proj_proj_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcostentry',
            index=models.Index(fields=['organization', '-created_at'], name='proj_cost_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdailysitereport',
            index=models.Index(fields=['organization', '-created_at'], name='proj_dsr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdailysitereportphoto',
            index=models.Index(fields=['organization', '-created_at'], name='proj_dsrp_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexecutioninspectionitem',
            index=models.Index(fields=['organization', '-created_at'], name='proj_eii_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['organization', '-created_at'], name='proj_ms_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestoneapprovalrule',
            index=models.Index(fields=['organization', '-created_at'], name='proj_mar_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['organization', 'status'], name='proj_phase_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['organization', '-created_at'], name='proj_phase_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphasedependency',
            index=models.Index(fields=['organization', '-created_at'], name='proj_pdep_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectriskregisterentry',
            index=models.Index(fields=['organization', '-created_at'], name='proj_risk_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsupportingattachment',
            index=models.Index(fields=['organization', '-created_at'], name='proj_sa_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['organization', 'status'], name='proj_task_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['organization', '-created_at'], name='proj_task_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvariationorder',
            index=models.Index(fields=['organization', 'status'], name='proj_vo_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectworkforcelog',
            index=models.Index(fields=['organization', '-created_at'], name='proj_wlog_org_created_idx'),
        ),
    ]
