# Generated by Django 5.2 on 2026-03-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_project_proj_proj_org_status_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="number_of_units",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Planned number of units for the project plan.",
                null=True,
            ),
        ),
    ]
