# Generated by Django 5.2.10 on 2026-03-11 02:01

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_number_of_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude of project site (-90 to 90)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AddField(
            model_name='project',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude of project site (-180 to 180)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
    ]
