# Generated by Django 5.2.10 on 2026-03-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_organization_accounts_org_norm_name_trgm'),
        ('projects', '0020_project_gps_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConstructionWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_type', models.CharField(choices=[('site_overview_dashboard', 'Site Overview Dashboard'), ('site_mobilization_workspace', 'Site Mobilization Workspace')], max_length=48)),
                ('name', models.CharField(max_length=120)),
                ('menu_path', models.CharField(max_length=255)),
                ('menu_group', models.CharField(choices=[('dashboard', 'Dashboard'), ('pre_construction', 'Pre-Construction')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_construction_workspaces', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_workspaces', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'workspace_type'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='proj_cws_org_created_idx'), models.Index(fields=['project', 'menu_group'], name='proj_cws_proj_group_idx')],
                'unique_together': {('project', 'workspace_type')},
            },
        ),
        migrations.CreateModel(
            name='ProjectSiteMobilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('fencing_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('site_offices_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('storage_yards_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('worker_welfare_facilities_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('utilities_connection_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('temporary_roads_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('security_deployment_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('contractors_mobilized', models.BooleanField(default=False)),
                ('equipment_delivered', models.BooleanField(default=False)),
                ('material_staging', models.BooleanField(default=False)),
                ('survey_control_established', models.BooleanField(default=False)),
                ('permits_obtained', models.BooleanField(default=False)),
                ('insurance_certificates', models.BooleanField(default=False)),
                ('safety_induction', models.BooleanField(default=False)),
                ('linked_procurement_contractors_count', models.PositiveIntegerField(default=0)),
                ('linked_procurement_material_staging_count', models.PositiveIntegerField(default=0)),
                ('linked_hr_equipment_delivery_count', models.PositiveIntegerField(default=0)),
                ('linked_hr_safety_induction_count', models.PositiveIntegerField(default=0)),
                ('last_integrations_synced_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_site_mobilizations', to='accounts.organization')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_mobilization', to='projects.project')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', '-updated_at'], name='proj_sm_org_updated_idx')],
            },
        ),
    ]
