# Generated by Django 5.2 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectconstructionworkspace_projectsitemobilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='approval_authority',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='budget_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='deliverables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='estimated_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='exit_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='key_tasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='lessons_learned_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='out_of_scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='phase_owner_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='phase_risks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='raci_matrix',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='resource_requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='success_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
