# Generated by Django 5.2.10 on 2026-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_milestone_template_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='collaborators',
            field=models.JSONField(blank=True, default=list, help_text='[{"role","responsibility"}]'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='definition_of_done',
            field=models.JSONField(blank=True, default=list, help_text='[{"criterion","is_required"}]'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='estimated_effort_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Expected effort in hours.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='predecessors',
            field=models.JSONField(blank=True, default=list, help_text='[{"task","dependency_type","lag_days"}]'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Task ID, e.g. TASK-101.', max_length=100),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='reference_links',
            field=models.JSONField(blank=True, default=list, help_text='[{"title","url"}]'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='reviewer_role',
            field=models.CharField(blank=True, help_text='Role that reviews/approves the task output.', max_length=200),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='successors',
            field=models.JSONField(blank=True, default=list, help_text='[{"task","dependency_type","lag_days"}]'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='tools_required',
            field=models.JSONField(blank=True, default=list, help_text='[{"name","description"}]'),
        ),
    ]
