# Generated by Django 5.2.10 on 2026-03-13 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_task_template_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectconstructionworkspace",
            name="menu_group",
            field=models.CharField(
                choices=[
                    ("dashboard", "Dashboard"),
                    ("pre_construction", "Pre-Construction"),
                    ("execution", "Execution"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="projectconstructionworkspace",
            name="workspace_type",
            field=models.CharField(
                choices=[
                    ("site_overview_dashboard", "Site Overview Dashboard"),
                    ("site_mobilization_workspace", "Site Mobilization Workspace"),
                    ("construction_schedule_workspace", "Construction Schedule Workspace"),
                ],
                max_length=48,
            ),
        ),
        migrations.CreateModel(
            name="ProjectConstructionSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "lookahead_window_days",
                    models.PositiveSmallIntegerField(
                        default=21,
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                ("master_schedule_notes", models.TextField(blank=True)),
                ("phase_schedule_notes", models.TextField(blank=True)),
                ("lookahead_schedule_notes", models.TextField(blank=True)),
                ("task_dependency_notes", models.TextField(blank=True)),
                ("critical_path_notes", models.TextField(blank=True)),
                ("resource_assignment_notes", models.TextField(blank=True)),
                ("project_manager_updates", models.TextField(blank=True)),
                ("task_assignee_updates", models.TextField(blank=True)),
                ("site_worker_updates", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_construction_schedules",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="construction_schedule",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-updated_at"],
                        name="proj_cs_org_updated_idx",
                    )
                ],
            },
        ),
    ]
