# Generated by Django 5.2.10 on 2026-03-13 17:05

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_organization_accounts_org_norm_name_trgm'),
        ('documents', '0020_document_source_app_label_document_source_model_name_and_more'),
        ('procurement', '0005_projectprocurementworkspace'),
        ('projects', '0025_projectconstructionschedule_and_workspace_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.CharField(blank=True, help_text='Work package identifier, auto-generated as WP-##### when blank.', max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('scope_description', models.TextField(blank=True)),
                ('boq_items', models.JSONField(blank=True, default=list, help_text='List of BOQ line items.')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quality_requirements', models.TextField(blank=True)),
                ('safety_requirements', models.TextField(blank=True)),
                ('inspection_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_work_packages', to='procurement.vendor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_work_packages', to=settings.AUTH_USER_MODEL)),
                ('drawings', models.ManyToManyField(blank=True, related_name='linked_project_work_packages', to='documents.document')),
                ('linked_contractors', models.ManyToManyField(blank=True, related_name='linked_project_work_package_contractors', to='procurement.vendor')),
                ('linked_cost_entries', models.ManyToManyField(blank=True, related_name='linked_work_packages', to='projects.projectcostentry')),
                ('linked_inspections', models.ManyToManyField(blank=True, related_name='linked_work_packages', to='projects.projectexecutioninspection')),
                ('linked_purchase_orders', models.ManyToManyField(blank=True, related_name='linked_project_work_packages', to='procurement.purchaseorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_project_work_packages', to='accounts.organization')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_packages', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_work_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', '-updated_at'], name='proj_wp_org_updated_idx'), models.Index(fields=['project', 'start_date'], name='proj_wp_proj_start_idx')],
            },
        ),
    ]
