# Generated by Django 5.2.10 on 2026-03-13 17:35

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_organization_accounts_org_norm_name_trgm'),
        ('procurement', '0005_projectprocurementworkspace'),
        ('projects', '0026_projectworkpackage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectconstructionworkspace',
            name='workspace_type',
            field=models.CharField(choices=[('site_overview_dashboard', 'Site Overview Dashboard'), ('site_mobilization_workspace', 'Site Mobilization Workspace'), ('construction_schedule_workspace', 'Construction Schedule Workspace'), ('contractor_management_workspace', 'Contractor Management Workspace')], max_length=48),
        ),
        migrations.CreateModel(
            name='ProjectContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_profile', models.TextField(blank=True)),
                ('trade_specialization', models.CharField(blank=True, max_length=255)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('insurance', models.TextField(blank=True)),
                ('licenses', models.TextField(blank=True)),
                ('performance_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('payment_history', models.TextField(blank=True)),
                ('safety_record', models.TextField(blank=True)),
                ('quality_record', models.TextField(blank=True)),
                ('site_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contractor_profiles', to='procurement.vendor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_contractor_profiles', to=settings.AUTH_USER_MODEL)),
                ('inspection_results', models.ManyToManyField(blank=True, related_name='contractor_profiles', to='projects.projectexecutioninspection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contractor_profiles', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profiles', to='projects.project')),
                ('rfis', models.ManyToManyField(blank=True, related_name='contractor_profiles', to='projects.projectfieldescalation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_contractor_profiles', to=settings.AUTH_USER_MODEL)),
                ('work_packages', models.ManyToManyField(blank=True, related_name='contractor_profiles', to='projects.projectworkpackage')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', '-updated_at'], name='proj_cp_org_updated_idx'), models.Index(fields=['project', 'contractor'], name='proj_cp_project_contractor_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'contractor'), name='uniq_project_contractor_profile')],
            },
        ),
    ]
