# Generated by Django 5.2 on 2026-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_projectconstructionworkspace_workspace_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdailysitereport',
            name='equipment_operators_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='equipment_used',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='instructions_issued',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='laborers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='materials_consumed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='materials_delivered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='skilled_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='subcontractors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='supervisors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdailysitereport',
            name='visitors_log',
            field=models.TextField(blank=True),
        ),
    ]
