# Generated by Django 5.2.10 on 2026-03-13 19:11

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_allowance_hr_alw_org_created_idx_and_more'),
        ('procurement', '0005_projectprocurementworkspace'),
        ('projects', '0028_projectdailysitereport_equipment_operators_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkforcelog',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_workforce_logs', to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='projectworkforcelog',
            name='daily_attendance',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('excused', 'Excused')], default='present', max_length=16),
        ),
        migrations.AddField(
            model_name='projectworkforcelog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_workforce_logs', to='hr.employeerecord'),
        ),
        migrations.AddField(
            model_name='projectworkforcelog',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='projectworkforcelog',
            name='productivity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='projectworkforcelog',
            name='task_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_logs', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='projectworkforcelog',
            name='trade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='projectworkforcelog',
            name='worker_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
