# Generated by Django 5.2.10 on 2026-03-18 14:45

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_activesubscriptionaddon"),
        ("projects", "0029_projectworkforcelog_contractor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPlanningInsight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_module", models.CharField(choices=[("crm", "CRM"), ("projects", "Projects"), ("analytics", "Analytics")], default="crm", max_length=20)),
                ("insight_type", models.CharField(choices=[("demand_analytics", "Demand Analytics"), ("new_development", "New Development Trigger")], default="demand_analytics", max_length=32)),
                ("area_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("demand_share_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6)),
                ("lead_count", models.PositiveIntegerField(default=0)),
                ("qualified_lead_count", models.PositiveIntegerField(default=0)),
                ("won_lead_count", models.PositiveIntegerField(default=0)),
                ("window_days", models.PositiveIntegerField(default=90)),
                ("threshold_percent", models.DecimalField(decimal_places=2, default=Decimal("25.00"), max_digits=6)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("first_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_planning_insights", to="accounts.organization")),
            ],
            options={
                "ordering": ["-demand_share_percent", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectplanninginsight",
            constraint=models.UniqueConstraint(fields=("organization", "insight_type", "area_name"), name="unique_org_planning_insight_area_type"),
        ),
        migrations.AddIndex(
            model_name="projectplanninginsight",
            index=models.Index(fields=["organization", "source_module", "insight_type", "is_active"], name="proj_pi_org_type_act_idx"),
        ),
        migrations.AddIndex(
            model_name="projectplanninginsight",
            index=models.Index(fields=["organization", "-updated_at"], name="proj_pi_org_updated_idx"),
        ),
    ]
