from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0041_seed_platform_roles"),
        ("settings", "0074_templateplanscenario"),
        ("projects", "0030_projectplanninginsight"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBlueprint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("review", "Under Review"), ("committed", "Committed"), ("archived", "Archived")], default="draft", max_length=12)),
                ("work_days", models.JSONField(blank=True, default=dict)),
                ("shift_start", models.TimeField(default="08:00")),
                ("shift_end", models.TimeField(default="17:00")),
                ("hours_per_day", models.DecimalField(decimal_places=1, default=9, max_digits=4)),
                ("public_holidays", models.JSONField(blank=True, default=list)),
                ("custom_holidays", models.JSONField(blank=True, default=list)),
                ("rainy_season_buffer_enabled", models.BooleanField(default=False)),
                ("rainy_season_buffer_pct", models.DecimalField(decimal_places=1, default=15, max_digits=5)),
                ("rainy_season_months", models.JSONField(blank=True, default=list)),
                ("outdoor_task_categories", models.JSONField(blank=True, default=list)),
                ("duration_scalar_pct", models.DecimalField(decimal_places=1, default=100, max_digits=5)),
                ("resource_roles", models.JSONField(blank=True, default=list)),
                ("travel_buffer_hours", models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ("material_markup_pct", models.DecimalField(decimal_places=1, default=10, max_digits=5)),
                ("location_factor", models.CharField(default="lagos", max_length=30)),
                ("contingency_pct", models.DecimalField(decimal_places=1, default=10, max_digits=5)),
                ("equipment_daily_rate", models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ("fx_rate_usd_ngn", models.DecimalField(decimal_places=2, default=1550, max_digits=10)),
                ("projected_duration_days", models.PositiveIntegerField(default=0)),
                ("projected_total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_blueprints", to="accounts.organization")),
                ("source_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="derived_blueprints", to="settings.projecttemplate")),
                ("project", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="blueprint", to="projects.project")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_blueprints", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"], "indexes": [models.Index(fields=["organization", "status", "-updated_at"], name="bp_org_status_idx")]},
        ),
        migrations.CreateModel(
            name="BlueprintPhase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
                ("weight", models.PositiveIntegerField(default=1)),
                ("planned_budget", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("blueprint", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="phases", to="projects.projectblueprint")),
            ],
            options={"ordering": ["sort_order"]},
        ),
        migrations.CreateModel(
            name="BlueprintActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("wbs_code", models.CharField(blank=True, max_length=50)),
                ("estimated_duration_days", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_effort_hours", models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ("phase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="projects.blueprintphase")),
            ],
            options={"ordering": ["sort_order"]},
        ),
        migrations.CreateModel(
            name="BlueprintTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("reference_code", models.CharField(blank=True, max_length=100)),
                ("assigned_role", models.CharField(blank=True, max_length=200)),
                ("priority", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=20)),
                ("standard_duration_hours", models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ("estimated_effort_hours", models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ("crew_size", models.PositiveIntegerField(blank=True, null=True)),
                ("estimated_labor_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("output_unit", models.CharField(blank=True, max_length=50)),
                ("equipment_type", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("is_milestone", models.BooleanField(default=False)),
                ("complexity", models.CharField(default="medium", max_length=10)),
                ("required_materials", models.JSONField(blank=True, default=list)),
                ("required_ppe", models.JSONField(blank=True, default=list)),
                ("quality_gates", models.JSONField(blank=True, default=list)),
                ("photo_requirements", models.JSONField(blank=True, default=list)),
                ("sop_markdown", models.TextField(blank=True)),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="projects.blueprintactivity")),
                ("source_task_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="blueprint_instances", to="settings.tasktemplate")),
            ],
            options={"ordering": ["sort_order"]},
        ),
        migrations.CreateModel(
            name="BlueprintDependency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dependency_type", models.CharField(choices=[("fs", "Finish-to-Start"), ("ss", "Start-to-Start"), ("ff", "Finish-to-Finish"), ("sf", "Start-to-Finish")], default="fs", max_length=2)),
                ("lag_hours", models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ("strength", models.CharField(choices=[("hard", "Hard"), ("soft", "Soft")], default="hard", max_length=4)),
                ("risk_impact", models.PositiveSmallIntegerField(default=5)),
                ("notes", models.TextField(blank=True)),
                ("blueprint", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dependencies", to="projects.projectblueprint")),
                ("from_activity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_deps", to="projects.blueprintactivity")),
                ("from_task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_deps", to="projects.blueprinttask")),
                ("to_activity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="incoming_deps", to="projects.blueprintactivity")),
                ("to_task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="incoming_deps", to="projects.blueprinttask")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="BlueprintScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_baseline", models.BooleanField(default=False)),
                ("risk_level", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="medium", max_length=10)),
                ("duration_scalar_pct", models.DecimalField(decimal_places=1, default=100, max_digits=5)),
                ("material_markup_pct", models.DecimalField(decimal_places=1, default=10, max_digits=5)),
                ("location_factor", models.CharField(default="lagos", max_length=30)),
                ("contingency_pct", models.DecimalField(decimal_places=1, default=10, max_digits=5)),
                ("projected_duration_days", models.PositiveIntegerField(default=0)),
                ("projected_total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("blueprint", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scenarios", to="projects.projectblueprint")),
            ],
            options={"ordering": ["-is_baseline", "-created_at"]},
        ),
    ]
