# Generated by Django 5.2.12 on 2026-03-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_blueprints'),
        ('settings', '0075_alter_tasktemplate_estimated_effort_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblueprint',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Template this blueprint was seeded from (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_blueprints', to='settings.projecttemplate'),
        ),
    ]
