# Generated by Django 5.2.12 on 2026-03-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0032_alter_projectblueprint_source_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(choices=[('earthmoving', 'Earthmoving'), ('lifting', 'Lifting'), ('material_handling', 'Material Handling'), ('concrete', 'Concrete'), ('piling', 'Piling'), ('compaction', 'Compaction'), ('transport', 'Transport'), ('scaffolding', 'Scaffolding'), ('power_generation', 'Power Generation'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('in_repair', 'In Repair'), ('idle', 'Idle'), ('decommissioned', 'Decommissioned'), ('in_transit', 'In Transit')], default='idle', max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('year_of_manufacture', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('engine_number', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('na', 'N/A')], default='diesel', max_length=20)),
                ('fuel_consumption_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Litres per hour', max_digits=8, null=True)),
                ('capacity', models.CharField(blank=True, help_text='e.g. 15 Ton, 380 HP', max_length=100)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_location', models.CharField(blank=True, help_text='Site name or warehouse', max_length=255)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_operator', models.CharField(blank=True, max_length=255)),
                ('operator_license_verified', models.BooleanField(default=False)),
                ('hour_meter_reading', models.DecimalField(decimal_places=1, default=0, help_text='Current hour meter reading', max_digits=10)),
                ('odometer_reading', models.DecimalField(decimal_places=1, default=0, help_text='Current odometer (km)', max_digits=10)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('service_interval_hours', models.PositiveIntegerField(blank=True, help_text='Hours between services', null=True)),
                ('ownership', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('rented', 'Rented')], default='owned', max_length=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('internal_daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Internal rental charge per day', max_digits=12, null=True)),
                ('internal_hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Internal rental charge per hour', max_digits=12, null=True)),
                ('mobilization_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Standard fee for transport between sites', max_digits=12, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_on_site', to='projects.project')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('scheduled_service', 'Scheduled Service'), ('repair', 'Repair'), ('breakdown', 'Breakdown'), ('inspection', 'Inspection'), ('fuel_intake', 'Fuel Intake')], default='scheduled_service', max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('parts_replaced', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('hour_meter_at_service', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('downtime_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='projects.projectequipment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('operator', models.CharField(blank=True, max_length=255)),
                ('deployed_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('hours_used', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_deployments', to='projects.project')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_logs', to='projects.projectequipment')),
            ],
            options={
                'ordering': ['-deployed_date'],
            },
        ),
        migrations.AddIndex(
            model_name='projectequipment',
            index=models.Index(fields=['organization', 'status'], name='proj_eq_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectequipment',
            index=models.Index(fields=['organization', '-created_at'], name='proj_eq_org_created_idx'),
        ),
    ]
