# Generated by Django 5.2.12 on 2026-03-25 00:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0034_projectworkpackage_linked_bom_items_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_ref', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('opportunity', 'Opportunity Identified'), ('feasibility', 'Feasibility Study'), ('financial_model', 'Financial Modeling'), ('due_diligence', 'Due Diligence'), ('ic_review', 'IC Review'), ('approved', 'Approved'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], default='opportunity', max_length=20)),
                ('stage_order', models.PositiveIntegerField(default=0, help_text='Sort position within the stage column.')),
                ('development_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed-Use'), ('industrial', 'Industrial'), ('hospitality', 'Hospitality'), ('retail', 'Retail'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], default='residential', max_length=20)),
                ('land_size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('land_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('land_status', models.CharField(blank=True, help_text='e.g. MOU Signed, Under Survey, Title Verified', max_length=255)),
                ('estimated_gdv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross Development Value', max_digits=15)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total all-in development cost', max_digits=15)),
                ('expected_irr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected IRR %', max_digits=6)),
                ('hurdle_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Minimum acceptable IRR %', max_digits=6)),
                ('expected_margin_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('number_of_units', models.PositiveIntegerField(default=0)),
                ('market_analysis', models.TextField(blank=True, help_text='Absorption rates, comps, demographics.')),
                ('feasibility_notes', models.TextField(blank=True)),
                ('ic_decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('deferred', 'Deferred'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ic_review_date', models.DateField(blank=True, null=True)),
                ('ic_conditions', models.TextField(blank=True, help_text='Conditions for approval.')),
                ('ic_reviewers', models.TextField(blank=True, help_text='Comma-separated reviewer names.')),
                ('identified_date', models.DateField(blank=True, null=True)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_pipeline_opportunities', to='accounts.organization')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_opportunity', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Pipeline Opportunities',
                'ordering': ['stage', 'stage_order', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'stage'], name='pipe_org_stage_idx')],
            },
        ),
    ]
