# Generated by Django 5.2.12 on 2026-03-25 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_pipeline_opportunity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('basic_info', 'Basic Info'), ('team_allocation', 'Team Allocation'), ('phase_definition', 'Phase Definition'), ('boq_baseline', 'BoQ Baseline'), ('completed', 'Setup Complete')], default='basic_info', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('survey_plan_ref', models.CharField(blank=True, max_length=255)),
                ('certificate_of_occupancy', models.CharField(blank=True, max_length=255)),
                ('planned_phases', models.PositiveIntegerField(default=3)),
                ('boq_initialized', models.BooleanField(default=False)),
                ('template_applied', models.BooleanField(default=False)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_configs', to='projects.pipelineopportunity')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_config', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('project_manager', 'Project Manager'), ('lead_architect', 'Lead Architect'), ('structural_engineer', 'Structural Engineer'), ('mep_consultant', 'MEP Consultant'), ('quantity_surveyor', 'Quantity Surveyor'), ('site_engineer', 'Site Engineer'), ('safety_officer', 'Safety Officer'), ('project_director', 'Project Director'), ('legal_counsel', 'Legal Counsel'), ('finance_controller', 'Finance Controller'), ('other', 'Other')], default='other', max_length=30)),
                ('access_level', models.CharField(choices=[('read_only', 'Read Only'), ('contributor', 'Contributor'), ('financial_edit', 'Financial Edit'), ('full_access', 'Full Access')], default='contributor', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, help_text='External firm if consultant.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
    ]
