# Generated by Django 5.2.12 on 2026-03-25 01:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0036_project_setup_and_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_ref', models.CharField(blank=True, max_length=100, unique=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('total_sales_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Parking, facility mgmt, storage.', max_digits=15)),
                ('number_of_units', models.PositiveIntegerField(default=0)),
                ('avg_price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('avg_price_per_sqm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('land_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('land_legal_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('construction_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('professional_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('professional_fees_pct', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='% of construction cost', max_digits=5)),
                ('marketing_sales_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sales_commission_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('finance_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('contingency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('contingency_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('target_irr', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6)),
                ('expected_irr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('hurdle_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6)),
                ('breakeven_units_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of units to break even', max_digits=6)),
                ('sales_velocity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Units per month', max_digits=8)),
                ('project_duration_months', models.PositiveIntegerField(default=36)),
                ('market_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('finance_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('construction_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('demand_analysis', models.TextField(blank=True)),
                ('competitor_projects', models.JSONField(blank=True, default=list, help_text='List of {name, units, price_per_unit, price_per_sqm, status}')),
                ('pricing_benchmarks', models.TextField(blank=True)),
                ('sensitivity_matrix', models.JSONField(blank=True, default=dict, help_text='Precomputed {price_change: {cost_change: irr}}')),
                ('notes', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_feasibility_studies', to='accounts.organization')),
                ('pipeline_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feasibility_studies', to='projects.pipelineopportunity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_studies', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Feasibility Studies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'project', 'status'], name='feas_org_proj_sts_idx')],
            },
        ),
    ]
