# Generated by Django 5.2.12 on 2026-03-25 02:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0037_feasibility_study'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('land_size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('title_type', models.CharField(choices=[('c_of_o', 'Certificate of Occupancy (C of O)'), ('governors_consent', "Governor's Consent"), ('excision', 'Excision'), ('deed_of_assignment', 'Deed of Assignment'), ('right_of_occupancy', 'Right of Occupancy'), ('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('pending', 'Pending / Not Yet Determined')], default='pending', max_length=30)),
                ('verification_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'Due Diligence In Progress'), ('encumbrance_found', 'Encumbrance Found'), ('verified', 'Legally Verified'), ('registered', 'Title Registered')], default='not_started', max_length=30)),
                ('acquisition_status', models.CharField(choices=[('prospecting', 'Prospecting'), ('negotiation', 'Negotiation'), ('mou_signed', 'MOU Signed'), ('due_diligence', 'Due Diligence'), ('contract_signed', 'Contract Signed'), ('payment_in_progress', 'Payment In Progress'), ('completed', 'Acquisition Complete'), ('cancelled', 'Cancelled')], default='prospecting', max_length=30)),
                ('survey_plan_ref', models.CharField(blank=True, max_length=255)),
                ('title_document_ref', models.CharField(blank=True, max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('agency_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('legal_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('stamp_duty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('registration_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('land_search_date', models.DateField(blank=True, null=True)),
                ('land_search_registry', models.CharField(blank=True, help_text='e.g. Alausa, AGIS', max_length=255)),
                ('encumbrance_check', models.BooleanField(default=False)),
                ('encumbrance_notes', models.TextField(blank=True)),
                ('govt_approval_status', models.CharField(blank=True, max_length=255)),
                ('govt_approval_tracking', models.CharField(blank=True, help_text='LUCPS/NIBS tracking number', max_length=255)),
                ('govt_approval_days_elapsed', models.PositiveIntegerField(default=0)),
                ('escrow_holder', models.CharField(blank=True, max_length=255)),
                ('escrow_secured', models.BooleanField(default=False)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('seller_contact', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_land_acquisitions', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_acquisitions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandPaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Initial Deposit, 2nd Tranche, Final Balance', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='scheduled', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land_acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='projects.landacquisition')),
            ],
            options={
                'ordering': ['sort_order', 'due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='landacquisition',
            index=models.Index(fields=['organization', 'acquisition_status'], name='land_org_acq_sts_idx'),
        ),
    ]
