# Generated by Django 5.2.12 on 2026-03-25 03:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0038_land_acquisition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('baseline', 'Baseline Locked'), ('revised', 'Revised'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('is_baseline', models.BooleanField(default=False)),
                ('equity_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_land_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contingency_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('locked_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_dev_budgets', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_budgets', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentBudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_type', models.CharField(choices=[('hard', 'Hard Cost'), ('soft', 'Soft Cost')], default='hard', max_length=10)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('estimated', 'Estimated'), ('planned', 'Planned'), ('contracted', 'Contracted'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('sub_items', models.JSONField(blank=True, default=list, help_text='[{name, amount}]')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='projects.developmentbudget')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
