# Generated by Django 5.2.12 on 2026-03-25 19:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0039_development_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated as FIN-##### when blank.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='e.g. GTBank Construction Facility', max_length=255)),
                ('source_type', models.CharField(choices=[('bank_loan', 'Bank Loan'), ('mezzanine', 'Mezzanine Finance'), ('equity', 'Equity'), ('joint_venture', 'Joint Venture'), ('private_placement', 'Private Placement'), ('grant', 'Grant / Subsidy'), ('other', 'Other')], default='bank_loan', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('fully_drawn', 'Fully Drawn'), ('repaid', 'Repaid'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('drawn_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, help_text='Annual rate %', max_digits=6, null=True)),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=10)),
                ('rate_benchmark', models.CharField(blank=True, help_text='e.g. SOFR, NIBOR, MPR', max_length=50)),
                ('arrangement_fee_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('grace_period_months', models.PositiveIntegerField(default=0)),
                ('tenor_months', models.PositiveIntegerField(default=0, help_text='Total facility duration in months')),
                ('repayment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('bullet', 'Bullet')], default='quarterly', max_length=20)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('first_drawdown_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('next_repayment_date', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_financing_sources', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_sources', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancingRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='scheduled', max_length=20)),
                ('actual_payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='projects.financingsource')),
            ],
            options={
                'ordering': ['payment_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancingDrawdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('request_date', models.DateField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, help_text='Net after bank fees', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('milestone_reference', models.CharField(blank=True, help_text='Linked milestone or certificate of work', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdowns', to='projects.financingsource')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancingCovenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Debt-to-Equity Ratio', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('threshold', models.CharField(blank=True, help_text='e.g. ≤ 2.5x or ≥ 1.2x DSCR', max_length=100)),
                ('current_value', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('at_risk', 'At Risk'), ('breached', 'Breached'), ('not_tested', 'Not Yet Tested')], default='not_tested', max_length=20)),
                ('last_tested', models.DateField(blank=True, null=True)),
                ('next_test_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covenants', to='projects.financingsource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='financingsource',
            index=models.Index(fields=['organization', 'status'], name='finsrc_org_status_idx'),
        ),
    ]
