# Generated by Django 5.2.12 on 2026-03-25 19:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0040_project_financing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_role', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('discipline', models.CharField(choices=[('architectural', 'Architectural'), ('structural', 'Structural'), ('mep', 'MEP (Mechanical, Electrical, Plumbing)'), ('quantity_surveying', 'Quantity Surveying'), ('legal', 'Legal'), ('geotechnical', 'Geotechnical'), ('environmental', 'Environmental'), ('town_planning', 'Town Planning'), ('land_surveying', 'Land Surveying'), ('project_management', 'Project Management'), ('interior_design', 'Interior Design'), ('landscape', 'Landscape'), ('other', 'Other')], default='architectural', max_length=30)),
                ('status', models.CharField(choices=[('onboarding', 'On-Boarding'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Contract Completed'), ('terminated', 'Terminated')], default='onboarding', max_length=20)),
                ('scope_of_work', models.TextField(blank=True)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('compliance_status', models.CharField(choices=[('green', 'Green — On Track'), ('yellow', 'Yellow — Minor Delays'), ('red', 'Red — Critical Issues')], default='green', max_length=10)),
                ('insurance_policy', models.CharField(blank=True, max_length=255)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('reports_to', models.CharField(blank=True, help_text='e.g. Project Manager', max_length=255)),
                ('collaborates_with', models.JSONField(blank=True, default=list, help_text='[discipline strings]')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_project_consultants', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='projects.project')),
            ],
            options={
                'ordering': ['discipline', 'firm_name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantPaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('trigger_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='projects.projectconsultant')),
            ],
            options={
                'ordering': ['sort_order', 'trigger_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('format', models.CharField(choices=[('dwg', 'DWG'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('bim', 'BIM / Revit'), ('other', 'Other')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.projectconsultant')),
            ],
            options={
                'ordering': ['sort_order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantCommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('meeting', 'Meeting'), ('site_visit', 'Site Visit'), ('design_review', 'Design Review'), ('rfi', 'Technical Query / RFI'), ('phone_call', 'Phone Call'), ('email', 'Email'), ('other', 'Other')], default='meeting', max_length=20)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('attendees', models.TextField(blank=True)),
                ('action_items', models.TextField(blank=True)),
                ('logged_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='projects.projectconsultant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='projectconsultant',
            index=models.Index(fields=['organization', 'status'], name='cons_org_status_idx'),
        ),
    ]
