# Generated by Django 5.2.12 on 2026-03-25 19:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0041_consultants_stakeholders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated as PRM-##### when blank.', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('permit_type', models.CharField(choices=[('environmental', 'Environmental Approval (EIA)'), ('planning', 'Planning Permission'), ('building', 'Building Permit'), ('fire_safety', 'Fire Safety Approval'), ('utility_water', 'Water Connection'), ('utility_power', 'Power Connection'), ('utility_sewer', 'Sewer / Drainage'), ('road_closure', 'Road Closure / Traffic'), ('heritage', 'Heritage / Conservation'), ('aviation', 'Aviation Height Clearance'), ('occupancy', 'Certificate of Occupancy'), ('other', 'Other')], default='building', max_length=30)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('application_filed', 'Application Filed'), ('under_review', 'Under Review'), ('clarification', 'Clarification Requested'), ('approved', 'Approved'), ('conditional', 'Conditionally Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='not_started', max_length=20)),
                ('is_critical_path', models.BooleanField(default=False, help_text='Blocks the development schedule if delayed.')),
                ('authority_name', models.CharField(blank=True, max_length=255)),
                ('authority_contact', models.CharField(blank=True, max_length=255)),
                ('authority_portal', models.URLField(blank=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('expected_approval_date', models.DateField(blank=True, null=True)),
                ('actual_approval_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('application_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fee_paid', models.BooleanField(default=False)),
                ('approval_certificate_ref', models.CharField(blank=True, help_text='Certificate number once approved.', max_length=255)),
                ('conditions', models.TextField(blank=True, help_text='Conditions attached to approval.')),
                ('rejection_reason', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ForeignKey(blank=True, help_text='Permit that must be approved first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='projects.projectpermit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_project_permits', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='Rev 01', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('documents_list', models.TextField(blank=True, help_text='List of documents submitted.')),
                ('submission_date', models.DateField()),
                ('submitted_by', models.CharField(blank=True, max_length=255)),
                ('authority_receipt_ref', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.projectpermit')),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='PermitQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateField()),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assigned_consultant', models.CharField(blank=True, max_length=255)),
                ('response', models.TextField(blank=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='projects.projectpermit')),
            ],
            options={
                'ordering': ['-query_date'],
            },
        ),
        migrations.AddIndex(
            model_name='projectpermit',
            index=models.Index(fields=['organization', 'status'], name='prm_org_status_idx'),
        ),
    ]
