# Generated by Django 5.2.12 on 2026-03-25 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0042_approvals_permits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('concept', 'Concept Design'), ('schematic', 'Schematic Design'), ('detailed', 'Detailed Design'), ('construction', 'Construction Drawings'), ('as_built', 'As-Built')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('closed', 'Closed')], default='not_started', max_length=20)),
                ('total_deliverables', models.PositiveIntegerField(default=0)),
                ('approved_deliverables', models.PositiveIntegerField(default=0)),
                ('closeout_checked', models.BooleanField(default=False, help_text='Phase gate checked before advancing.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_design_phases', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_phases', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('project', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_number', models.CharField(help_text='e.g. ARCH-P1-001', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('discipline', models.CharField(choices=[('architectural', 'Architectural'), ('structural', 'Structural'), ('mep_mechanical', 'MEP — Mechanical'), ('mep_electrical', 'MEP — Electrical'), ('mep_plumbing', 'MEP — Plumbing'), ('civil', 'Civil'), ('landscape', 'Landscape'), ('interior', 'Interior Design'), ('other', 'Other')], default='architectural', max_length=20)),
                ('current_revision', models.CharField(default='Rev A', max_length=20)),
                ('approval_state', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('approved_noted', 'Approved as Noted'), ('afc', 'Approved for Construction'), ('superseded', 'Superseded'), ('revise_resubmit', 'Revise and Resubmit')], default='draft', max_length=20)),
                ('scale', models.CharField(blank=True, help_text='e.g. 1:100', max_length=50)),
                ('submitted_by', models.CharField(blank=True, max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('design_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='projects.designphase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_drawings', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='projects.project')),
            ],
            options={
                'ordering': ['discipline', 'drawing_number'],
            },
        ),
        migrations.CreateModel(
            name='DesignReviewMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('attendees', models.TextField(blank=True)),
                ('key_decisions', models.TextField(blank=True)),
                ('action_items', models.JSONField(blank=True, default=list, help_text='[{description, assigned_to, due_date}]')),
                ('minutes_notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_design_meetings', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_review_meetings', to='projects.project')),
                ('linked_drawings', models.ManyToManyField(blank=True, related_name='meetings', to='projects.drawing')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DrawingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_code', models.CharField(help_text='e.g. Rev A, Rev B', max_length=20)),
                ('change_description', models.TextField(blank=True)),
                ('submitted_by', models.CharField(blank=True, max_length=255)),
                ('submitted_date', models.DateField()),
                ('approval_state', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('approved_noted', 'Approved as Noted'), ('afc', 'Approved for Construction'), ('superseded', 'Superseded'), ('revise_resubmit', 'Revise and Resubmit')], default='draft', max_length=20)),
                ('reviewer_comments', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.drawing')),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.AddIndex(
            model_name='drawing',
            index=models.Index(fields=['organization', 'approval_state'], name='drw_org_approval_idx'),
        ),
    ]
