# Generated by Django 5.2.12 on 2026-03-25 20:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0043_design_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Piling Works, Main Shell/Core, MEP Fit-out', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('pqq', 'Prequalification'), ('tendering', 'Tendering (RFP Out)'), ('evaluation', 'Evaluation'), ('negotiation', 'Negotiation'), ('awarded', 'Contract Awarded'), ('signed', 'Contract Signed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual value once awarded', max_digits=15)),
                ('pqq_issue_date', models.DateField(blank=True, null=True)),
                ('rfp_issue_date', models.DateField(blank=True, null=True)),
                ('tender_return_date', models.DateField(blank=True, null=True)),
                ('evaluation_end_date', models.DateField(blank=True, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('awarded_to', models.CharField(blank=True, max_length=255)),
                ('award_justification', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageBidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('proposed_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('score_price', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('score_technical', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('score_timeline', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('score_safety', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_prequalified', models.BooleanField(default=True)),
                ('compliance_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='projects.procurementpackage')),
            ],
            options={
                'ordering': ['-total_score', 'firm_name'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('design_build', 'Design & Build'), ('traditional', 'Traditional'), ('management', 'Management Contracting'), ('construction_mgmt', 'Construction Management'), ('turnkey', 'Turnkey / EPC'), ('other', 'Other')], default='traditional', max_length=20)),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('contingency_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_procurement_plans', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_plans', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='procurementpackage',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='projects.procurementplan'),
        ),
    ]
