# Generated by Django 5.2.12 on 2026-03-25 20:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0044_procurement_planning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRevenueForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_development_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('marketing_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('marketing_budget_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('sales_launch_date', models.DateField(blank=True, null=True)),
                ('target_sellout_date', models.DateField(blank=True, null=True)),
                ('payment_structure', models.JSONField(blank=True, default=list, help_text='[{"stage":"Deposit","pct":30},{"stage":"Construction","pct":40},{"stage":"Handover","pct":30}]')),
                ('agents', models.JSONField(blank=True, default=list, help_text='[{"firm","commission_pct"}]')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_sales_forecasts', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecasts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesPhaseTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(help_text='e.g. Off-Plan, Construction, Post-Completion', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_units', models.PositiveIntegerField(default=0)),
                ('target_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('actual_units', models.PositiveIntegerField(default=0)),
                ('actual_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('milestone_trigger', models.CharField(blank=True, help_text='e.g. Showroom Launch, Topped Out', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_targets', to='projects.salesrevenueforecast')),
            ],
            options={
                'ordering': ['sort_order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleableUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(help_text='e.g. Apt 402, Shop G1', max_length=50)),
                ('unit_type', models.CharField(choices=[('studio', 'Studio'), ('1_bed', '1-Bedroom'), ('2_bed', '2-Bedroom'), ('3_bed', '3-Bedroom'), ('4_bed', '4-Bedroom'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('commercial', 'Commercial / Retail'), ('office', 'Office'), ('parking', 'Parking Bay'), ('storage', 'Storage Unit'), ('other', 'Other')], default='2_bed', max_length=20)),
                ('floor_location', models.CharField(blank=True, max_length=100)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asking_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('minimum_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('under_contract', 'Under Contract'), ('sold', 'Sold'), ('held', 'Held / Not for Sale')], default='available', max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('reserved_date', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.salesrevenueforecast')),
            ],
            options={
                'ordering': ['sort_order', 'unit_id'],
            },
        ),
    ]
