# Generated by Django 5.2.12 on 2026-03-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0045_sales_revenue_forecast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Pre-Construction Gate, Construction Completion Gate', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('under_review', 'Under Review'), ('open', 'Open (Passed)'), ('conditional', 'Approved with Conditions'), ('failed', 'Failed / Rejected')], default='locked', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('prerequisite_notes', models.TextField(blank=True)),
                ('scheduled_review_date', models.DateField(blank=True, null=True)),
                ('actual_review_date', models.DateField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, help_text='e.g. Investment Committee, Steering Committee', max_length=255)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, help_text='Conditions attached to approval.')),
                ('rejection_reason', models.TextField(blank=True)),
                ('baseline_date', models.DateField(blank=True, null=True)),
                ('delay_days', models.IntegerField(default=0)),
                ('delay_root_cause', models.TextField(blank=True)),
                ('recovery_plan', models.TextField(blank=True)),
                ('financial_release_triggered', models.BooleanField(default=False)),
                ('financial_release_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_stage_gates', to='accounts.organization')),
                ('prerequisite_milestones', models.ManyToManyField(blank=True, help_text='Milestones that must be achieved before this gate can open.', related_name='gate_prerequisites', to='projects.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_gates', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['organization', 'status'], name='sgate_org_status_idx')],
            },
        ),
    ]
