# Generated by Django 5.2.12 on 2026-03-26 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0046_stage_gates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutesArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(help_text='e.g. Weekly Site Meetings, Monthly Steering Committee', max_length=255)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('attendees', models.TextField(blank=True)),
                ('minutes_text', models.TextField(blank=True)),
                ('action_items', models.JSONField(blank=True, default=list, help_text='[{description, assigned_to, due_date, status}]')),
                ('recorded_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_meeting_minutes', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_minutes', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated as DOC-##### when blank.', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('folder', models.CharField(choices=[('01_feasibility', '01 — Feasibility & Strategy'), ('02_legal', '02 — Legal & Contracts'), ('03_design', '03 — Design Development'), ('04_permits', '04 — Permits & Regulatory'), ('05_governance', '05 — Governance & Minutes'), ('06_financial', '06 — Financial & Banking'), ('07_procurement', '07 — Procurement & Tenders'), ('08_construction', '08 — Construction Records'), ('09_hse', '09 — HSE & Compliance'), ('10_closeout', '10 — Closeout & Handover'), ('other', 'Other')], default='other', max_length=30)),
                ('classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('execution_status', models.CharField(choices=[('draft', 'Draft'), ('for_review', 'For Review'), ('approved', 'Approved'), ('executed', 'Original Executed'), ('scanned', 'Scanned Copy'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('current_version', models.CharField(default='v1', max_length=50)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, help_text='e.g. Legal Counsel, Lead Architect', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('retention_years', models.PositiveIntegerField(blank=True, help_text='How long to keep for audit.', null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('linked_module', models.CharField(blank=True, help_text='e.g. Consultant: Adesanya, Permit: PRM-00012', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_project_documents', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_documents', to='projects.project')),
            ],
            options={
                'ordering': ['folder', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(help_text='e.g. v1, v2, Final', max_length=50)),
                ('change_summary', models.TextField(blank=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255)),
                ('uploaded_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.projectdocument')),
            ],
            options={
                'ordering': ['-uploaded_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTransmittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmittal_ref', models.CharField(blank=True, max_length=100)),
                ('recipient', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('for_information', 'For Information'), ('for_approval', 'For Approval'), ('for_construction', 'For Construction'), ('for_record', 'For Record'), ('for_review', 'For Review')], default='for_information', max_length=20)),
                ('sent_date', models.DateField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('sent_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmittals', to='projects.projectdocument')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['organization', 'folder', 'classification'], name='doc_org_folder_class_idx'),
        ),
    ]
