# Generated by Django 5.2.12 on 2026-03-26 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0047_document_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('audience', models.CharField(choices=[('all', 'All Stakeholders'), ('internal', 'Internal Team'), ('external', 'External Stakeholders'), ('investors', 'Investors'), ('consultants', 'Consultants')], default='all', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_by', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_project_announcements', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='projects.project')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.CharField(blank=True, help_text='Auto-generated as DEC-### when blank.', max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('decided_by', models.CharField(help_text='e.g. Steering Committee, Project Director', max_length=255)),
                ('rationale', models.TextField(blank=True, help_text='Summary of the data or logic used.')),
                ('decision_date', models.DateField()),
                ('meeting_reference', models.CharField(blank=True, help_text='Link to specific meeting minutes.', max_length=255)),
                ('impact_modules', models.JSONField(blank=True, default=list, help_text='["Design","Budget","Schedule"]')),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('reversed', 'Reversed')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_project_decisions', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='projects.project')),
            ],
            options={
                'ordering': ['-decision_date'],
            },
        ),
        migrations.CreateModel(
            name='StakeholderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('ad_hoc', 'Ad-Hoc')], default='monthly', max_length=20)),
                ('report_date', models.DateField()),
                ('executive_summary', models.TextField(blank=True)),
                ('schedule_status', models.TextField(blank=True)),
                ('financial_status', models.TextField(blank=True)),
                ('risk_blockers', models.TextField(blank=True)),
                ('distribution_group', models.CharField(blank=True, help_text='e.g. Investors Group, Lending Bank', max_length=255)),
                ('recipients', models.JSONField(blank=True, default=list, help_text='[{"name","email","read":false}]')),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_stakeholder_updates', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_updates', to='projects.project')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
