# Generated by Django 5.2.12 on 2026-03-26 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_boqcategorymapping'),
        ('projects', '0048_project_communications'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprinttask',
            name='boq_item',
            field=models.ForeignKey(blank=True, help_text='Source BOQ line item (for traceability).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprint_tasks', to='inventory.bomitem'),
        ),
        migrations.AddField(
            model_name='blueprinttask',
            name='boq_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity from BOQ item.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='blueprinttask',
            name='boq_unit',
            field=models.CharField(blank=True, help_text='Unit of measure from BOQ item.', max_length=50),
        ),
        migrations.AddField(
            model_name='blueprinttask',
            name='estimated_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration calculated from BOQ quantity ÷ production rate.', null=True),
        ),
        migrations.AddField(
            model_name='projectblueprint',
            name='source_bom',
            field=models.ForeignKey(blank=True, help_text='BOM this blueprint was auto-generated from (Route B).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_blueprints', to='inventory.billofmaterials'),
        ),
    ]
