# Generated by Django 5.2.12 on 2026-03-26 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0049_blueprinttask_boq_item_blueprinttask_boq_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Auto-generated as RPT-##### when blank.', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('executive', 'Executive Summary'), ('financial', 'Financial (BvA)'), ('schedule', 'Schedule Variance'), ('risk', 'Risk & Issue Matrix'), ('investor', 'Investor / Stakeholder'), ('monthly', 'Monthly Progress'), ('custom', 'Custom')], default='executive', max_length=20)),
                ('report_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('schedule_rag', models.CharField(choices=[('green', 'Green — On Track'), ('amber', 'Amber — At Risk'), ('red', 'Red — Critical')], default='green', max_length=10)),
                ('budget_rag', models.CharField(choices=[('green', 'Green — On Track'), ('amber', 'Amber — At Risk'), ('red', 'Red — Critical')], default='green', max_length=10)),
                ('quality_rag', models.CharField(choices=[('green', 'Green — On Track'), ('amber', 'Amber — At Risk'), ('red', 'Red — Critical')], default='green', max_length=10)),
                ('safety_rag', models.CharField(choices=[('green', 'Green — On Track'), ('amber', 'Amber — At Risk'), ('red', 'Red — Critical')], default='green', max_length=10)),
                ('executive_summary', models.TextField(blank=True)),
                ('key_achievements', models.JSONField(blank=True, default=list, help_text='["Milestone achieved","Permit obtained"]')),
                ('key_issues', models.JSONField(blank=True, default=list, help_text='["Delay in permit","Budget overrun"]')),
                ('original_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('committed_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('forecast_at_completion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('contingency_used_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('schedule_variance_summary', models.TextField(blank=True)),
                ('critical_path_impact', models.TextField(blank=True)),
                ('overall_completion_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('top_risks', models.JSONField(blank=True, default=list, help_text='[{"risk","impact","probability","mitigation","owner"}]')),
                ('is_frozen', models.BooleanField(default=False, help_text='Locked snapshot — cannot be edited.')),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_project_reports', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
            options={
                'ordering': ['-report_date'],
                'indexes': [models.Index(fields=['organization', 'report_type'], name='rpt_org_type_idx')],
            },
        ),
    ]
