# Generated by Django 5.2.12 on 2026-03-26 03:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0050_project_reporting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCloseout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('completed', 'Completed'), ('archived', 'Archived')], default='in_progress', max_length=20)),
                ('practical_completion_date', models.DateField(blank=True, null=True)),
                ('final_completion_date', models.DateField(blank=True, null=True)),
                ('final_project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('original_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_variations', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retention_held', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retention_released', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retention_release_date', models.DateField(blank=True, null=True)),
                ('financial_reconciliation_done', models.BooleanField(default=False)),
                ('contracts_closed', models.BooleanField(default=False)),
                ('handover_completed', models.BooleanField(default=False)),
                ('snags_resolved', models.BooleanField(default=False)),
                ('documentation_archived', models.BooleanField(default=False)),
                ('warranties_registered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_project_closeouts', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeouts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalAccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=255)),
                ('original_contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('approved_variations', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('final_settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retention_held', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retention_released', models.BooleanField(default=False)),
                ('closeout_certificate_issued', models.BooleanField(default=False)),
                ('performance_rating', models.PositiveIntegerField(blank=True, help_text='1-5 star rating', null=True)),
                ('performance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_accounts', to='projects.projectcloseout')),
            ],
            options={
                'ordering': ['contractor_name'],
            },
        ),
        migrations.CreateModel(
            name='SnagListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsible_contractor', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('accepted', 'Accepted (As-Is)')], default='open', max_length=20)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snag_items', to='projects.projectcloseout')),
            ],
            options={
                'ordering': ['status', '-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_system', models.CharField(help_text='e.g. Roof Waterproofing, HVAC System', max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('warranty_start', models.DateField()),
                ('warranty_end', models.DateField()),
                ('claim_log', models.JSONField(blank=True, default=list, help_text='[{"date","issue","resolution","status"}]')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='projects.projectcloseout')),
            ],
            options={
                'ordering': ['warranty_end'],
            },
        ),
    ]
