# Generated by Django 5.2.12 on 2026-03-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_boq_cost_code_bridge'),
        ('projects', '0051_project_closeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom_item', models.ForeignKey(help_text='The specific BOQ item consumed.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_usages', to='inventory.bomitem')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='projects.projectdailysitereport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
