# Generated by Django 5.2.12 on 2026-03-26 03:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0017_boq_consumed_quantity'),
        ('projects', '0052_boq_cost_code_bridge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressmeasurement',
            name='bom_item',
            field=models.ForeignKey(blank=True, help_text='Optional: measure progress for a specific BOQ item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_measurements', to='inventory.bomitem'),
        ),
        migrations.AddField(
            model_name='progressmeasurement',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_measurements', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='progressmeasurement',
            name='work_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_measurements', to='projects.projectworkpackage'),
        ),
        migrations.CreateModel(
            name='InterimValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=255)),
                ('valuation_number', models.CharField(blank=True, help_text='Auto-generated as IPC-##### when blank.', max_length=100, unique=True)),
                ('valuation_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('certified', 'Certified'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='draft', max_length=20)),
                ('gross_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line item amounts', max_digits=15)),
                ('previous_certified', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('this_period_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retention_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('certified_by', models.CharField(blank=True, max_length=255)),
                ('certified_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_interim_valuations', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interim_valuations', to='projects.project')),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interim_valuations', to='projects.projectworkpackage')),
            ],
            options={
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.CreateModel(
            name='ValuationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('contract_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contract_quantity', models.DecimalField(decimal_places=2, help_text='Total BOQ quantity', max_digits=12)),
                ('previous_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity certified in prior valuations', max_digits=12)),
                ('this_period_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity completed this period', max_digits=12)),
                ('cumulative_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='previous + this period', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='cumulative_quantity × contract_rate', max_digits=15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom_item', models.ForeignKey(blank=True, help_text='Links to the specific BOQ item being valued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_line_items', to='inventory.bomitem')),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.interimvaluation')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='interimvaluation',
            index=models.Index(fields=['organization', 'project', 'status'], name='iv_org_proj_status_idx'),
        ),
    ]
