# Generated by Django 5.2.12 on 2026-03-26 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_progress_boq_fks_and_valuations'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvariationorder',
            name='cost_code_budget',
            field=models.ForeignKey(blank=True, help_text='The cost code this variation impacts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variation_orders', to='projects.costcodebudget'),
        ),
    ]
