# Generated by Django 5.2.12 on 2026-03-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_blueprintphase_blueprintactivity_blueprinttask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprintdependency',
            name='from_activity',
        ),
        migrations.RemoveField(
            model_name='blueprinttask',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='blueprintdependency',
            name='to_activity',
        ),
        migrations.RemoveField(
            model_name='blueprintdependency',
            name='blueprint',
        ),
        migrations.RemoveField(
            model_name='blueprintdependency',
            name='from_task',
        ),
        migrations.RemoveField(
            model_name='blueprintdependency',
            name='to_task',
        ),
        migrations.RemoveField(
            model_name='blueprintphase',
            name='blueprint',
        ),
        migrations.RemoveField(
            model_name='blueprintscenario',
            name='blueprint',
        ),
        migrations.RemoveField(
            model_name='blueprinttask',
            name='boq_item',
        ),
        migrations.RemoveField(
            model_name='blueprinttask',
            name='source_task_template',
        ),
        migrations.RemoveField(
            model_name='projectblueprint',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectblueprint',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='projectblueprint',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectblueprint',
            name='source_bom',
        ),
        migrations.RemoveField(
            model_name='projectblueprint',
            name='source_template',
        ),
        migrations.DeleteModel(
            name='BlueprintActivity',
        ),
        migrations.DeleteModel(
            name='BlueprintDependency',
        ),
        migrations.DeleteModel(
            name='BlueprintPhase',
        ),
        migrations.DeleteModel(
            name='BlueprintScenario',
        ),
        migrations.DeleteModel(
            name='BlueprintTask',
        ),
        migrations.DeleteModel(
            name='ProjectBlueprint',
        ),
    ]
