# Generated by Django 5.2.12 on 2026-03-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_remove_blueprintdependency_from_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioningplan',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commissioningplan',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissioningplan',
            name='certificate_number',
            field=models.CharField(blank=True, help_text='Generated on certification.', max_length=100),
        ),
        migrations.AddField(
            model_name='commissioningplan',
            name='certified_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commissioningplan',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissioningplan',
            name='client_signoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissioningplan',
            name='client_signoff_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
