# Generated by Django 5.2.12 on 2026-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_recreate_blueprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagegate',
            name='gate_type',
            field=models.CharField(choices=[('feasibility', 'Feasibility Gate'), ('investment_approval', 'Investment Approval Gate'), ('pre_construction', 'Pre-Construction Gate'), ('design_completion', 'Design Completion Gate'), ('procurement_completion', 'Procurement Completion Gate'), ('construction_midpoint', 'Construction Midpoint Gate'), ('practical_completion', 'Practical Completion Gate'), ('testing_commissioning', 'Testing & Commissioning Gate'), ('handover', 'Handover Gate'), ('closeout', 'Closeout Gate'), ('custom', 'Custom Gate')], default='custom', max_length=30),
        ),
    ]
