<script lang="ts">
</script>

<div class="min-h-screen bg-neutral-50 font-sans">
  <!-- Top Nav -->
  <div class="bg-white border-b border-neutral-200">
    <div class="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
      <a href="/help" class="text-lg">
        <span class="text-neutral-900 font-normal">developer</span><span class="text-neutral-400 font-bold">OS</span>
      </a>
      <a href="/help" class="text-sm text-neutral-500 hover:text-neutral-900 transition-colors flex items-center gap-1.5">
        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5 3 12m0 0 7.5-7.5M3 12h18" />
        </svg>
        Back to Help Center
      </a>
    </div>
  </div>

  <!-- Article -->
  <div class="max-w-3xl mx-auto px-6 py-12">
    <!-- Breadcrumb -->
    <div class="flex items-center gap-2 text-xs text-neutral-400 mb-8">
      <a href="/help" class="hover:text-neutral-600 transition-colors">Help Center</a>
      <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
      </svg>
      <span>Getting Started</span>
      <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
      </svg>
      <span class="text-neutral-600">Company Profile</span>
    </div>

    <!-- Header -->
    <div class="mb-10">
      <div class="flex items-center gap-2 mb-3">
        <span class="text-xs font-medium text-neutral-500 bg-neutral-100 px-2.5 py-1 rounded-full">Getting Started</span>
        <span class="text-xs text-neutral-400">Last updated: March 2026</span>
      </div>
      <h1 class="text-3xl font-bold text-neutral-900">Setting Up Your Organizational Identity</h1>
    </div>

    <!-- Content -->
    <div class="prose-custom">
      <section class="mb-10">
        <h2>Overview</h2>
        <p>
          Your Company Profile is the "Source of Truth" for your <span class="font-normal text-neutral-900">developer</span><span class="font-bold text-neutral-400">OS</span> instance.
          The information provided here will appear on your professional invoices,
          contract headers, and project reports.
        </p>
      </section>

      <section class="mb-10">
        <h2>Step 1: Accessing the Profile</h2>
        <div class="step-card">
          <p>
            Navigate to <strong>Settings &gt; Company Profile</strong> from the sidebar navigation.
          </p>
        </div>
      </section>

      <section class="mb-10">
        <h2>Step 2: Defining Identity</h2>

        <div class="space-y-4">
          <div class="step-card">
            <h3>Entity Name</h3>
            <p>
              Enter the legal name of your development firm. This will be used across
              all official documentation generated by the platform.
            </p>
          </div>

          <div class="step-card">
            <h3>Org Code</h3>
            <p>
              This is a unique 3-4 letter identifier (e.g., "SKY" for Skyline Devs)
              used for internal project referencing. Once set, this code will prefix
              your project IDs and purchase orders.
            </p>
          </div>

          <div class="step-card">
            <h3>Logo</h3>
            <p>
              Upload a high-resolution PNG or SVG (min 500x500px). This will appear
              on all client-facing documents including invoices, contracts, and reports.
            </p>
          </div>
        </div>
      </section>
    </div>

    <!-- Was this helpful? -->
    <div class="mt-12 pt-8 border-t border-neutral-200">
      <p class="text-sm text-neutral-500 mb-3">Was this article helpful?</p>
      <div class="flex gap-2">
        <button class="px-4 py-2 text-sm rounded-lg border border-neutral-200 bg-white hover:bg-neutral-50 transition-colors text-neutral-700">
          Yes, thanks!
        </button>
        <button class="px-4 py-2 text-sm rounded-lg border border-neutral-200 bg-white hover:bg-neutral-50 transition-colors text-neutral-700">
          Not really
        </button>
      </div>
    </div>
  </div>

  <!-- Footer -->
  <div class="border-t border-neutral-200 bg-white px-6 py-5 mt-8">
    <div class="max-w-3xl mx-auto flex items-center justify-between">
      <p class="text-xs text-neutral-400">
        &copy; {new Date().getFullYear()} <span class="font-normal text-neutral-900">developer</span><span class="font-bold text-neutral-400">OS</span>. All rights reserved.
      </p>
      <div class="flex gap-5 text-xs text-neutral-400">
        <a href="/help" class="hover:text-neutral-600 transition-colors">Help Center</a>
        <a href="/privacy" class="hover:text-neutral-600 transition-colors">Privacy Policy</a>
        <a href="/terms" class="hover:text-neutral-600 transition-colors">Terms of Service</a>
      </div>
    </div>
  </div>
</div>

<style>
  .prose-custom h2 {
    font-size: 1.125rem;
    font-weight: 600;
    color: #171717;
    margin-bottom: 0.75rem;
  }

  .prose-custom p {
    font-size: 0.875rem;
    line-height: 1.7;
    color: #525252;
  }

  .prose-custom strong {
    color: #171717;
    font-weight: 600;
  }

  .step-card {
    background: white;
    border: 1px solid #e5e5e5;
    border-radius: 0.75rem;
    padding: 1.25rem;
  }

  .step-card h3 {
    font-size: 0.8125rem;
    font-weight: 600;
    color: #171717;
    margin-bottom: 0.375rem;
  }

  .step-card p {
    margin: 0;
  }
</style>
