# Generated by Django 5.2 on 2026-03-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_address_line_1_and_more'),
        ('settings', '0002_role_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='settings.role'),
        ),
    ]
