# Generated by Django 5.2.10 on 2026-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='enterprise', max_length=20),
        ),
    ]
