# Generated by Django 5.2 on 2026-03-05 19:14

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_profile_photo_upload_to),
        ),
    ]
