# Generated by Django 5.2 on 2026-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_iam_fields_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_type',
            field=models.CharField(choices=[('user', 'User'), ('employee', 'Employee'), ('partner', 'Partner'), ('system_account', 'System Account')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('contractor', 'Contractor'), ('vendor', 'Vendor'), ('client', 'Client'), ('investor', 'Investor')], help_text="Only applicable when identity_type is 'partner'.", max_length=20),
        ),
    ]
