# Generated by Django 5.2 on 2026-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_service_account_and_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mfa_enforcement',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('optional', 'Optional'), ('required_admins', 'Required for Admins'), ('required_all', 'Required for All Users')], default='required_all', max_length=20),
        ),
    ]
