# Generated by Django 5.2 on 2026-03-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_invitation_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="approval_signature",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="business_unit",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="default_language",
            field=models.CharField(blank=True, default="en", max_length=16),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="office_location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_display_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("team", "Team"), ("organization", "Organization")],
                default="organization",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="secondary_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
