# Generated by Django 5.2 on 2026-03-06 22:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_userprofile_user_settings_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="passkey_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserAuthSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "auth_provider",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("google", "Google"),
                            ("microsoft", "Microsoft"),
                            ("apple", "Apple"),
                            ("sso_saml", "SSO / SAML"),
                            ("passkey", "Passkey / Biometric"),
                        ],
                        default="password",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_label", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSecurityEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("principal", models.CharField(blank=True, max_length=254)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("otp_challenge", "OTP Challenge"),
                            ("otp_failed", "OTP Failed"),
                            ("password_changed", "Password Changed"),
                            ("session_revoked_others", "Other Sessions Revoked"),
                            ("provider_linked", "Provider Linked"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed"), ("info", "Info")],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_label", models.CharField(blank=True, max_length=200)),
                ("detail", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userauthsession",
            index=models.Index(fields=["user", "revoked_at"], name="accounts_use_user_id_d11314_idx"),
        ),
        migrations.AddIndex(
            model_name="userauthsession",
            index=models.Index(fields=["user", "last_seen_at"], name="accounts_use_user_id_1dd1a8_idx"),
        ),
        migrations.AddIndex(
            model_name="usersecurityevent",
            index=models.Index(fields=["user", "occurred_at"], name="accounts_use_user_id_490e3e_idx"),
        ),
        migrations.AddIndex(
            model_name="usersecurityevent",
            index=models.Index(fields=["user", "event_type", "occurred_at"], name="accounts_use_user_id_1f0d2f_idx"),
        ),
        migrations.AddIndex(
            model_name="usersecurityevent",
            index=models.Index(fields=["principal", "occurred_at"], name="accounts_use_princip_19fbf7_idx"),
        ),
    ]
