# Generated by Django 5.2 on 2026-03-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_security_sessions_and_logs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userauthsession',
            new_name='accounts_us_user_id_e94dcf_idx',
            old_name='accounts_use_user_id_d11314_idx',
        ),
        migrations.RenameIndex(
            model_name='userauthsession',
            new_name='accounts_us_user_id_56b5a0_idx',
            old_name='accounts_use_user_id_1dd1a8_idx',
        ),
        migrations.RenameIndex(
            model_name='usersecurityevent',
            new_name='accounts_us_user_id_973cde_idx',
            old_name='accounts_use_user_id_490e3e_idx',
        ),
        migrations.RenameIndex(
            model_name='usersecurityevent',
            new_name='accounts_us_user_id_11e896_idx',
            old_name='accounts_use_user_id_1f0d2f_idx',
        ),
        migrations.RenameIndex(
            model_name='usersecurityevent',
            new_name='accounts_us_princip_5a62d6_idx',
            old_name='accounts_use_princip_19fbf7_idx',
        ),
    ]
