# Generated by Django 5.2 on 2026-03-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_account_security_sessions_and_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("team", "Team"),
                    ("organization", "Organization"),
                ],
                default="team",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("team", "Team"),
                    ("organization", "Organization"),
                ],
                default="team",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="online_status_visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("team", "Team"),
                    ("organization", "Organization"),
                ],
                default="team",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("team", "Team"),
                    ("organization", "Organization"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="search_discoverable",
            field=models.BooleanField(default=True),
        ),
    ]
