# Generated by Django 5.2 on 2026-03-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_accounts_use_user_id_d11314_idx_accounts_us_user_id_e94dcf_idx_and_more'),
        ('accounts', '0014_userprofile_privacy_visibility_fields'),
    ]

    operations = [
    ]
