# Generated by Django 5.2 on 2026-03-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_rename_accounts_use_user_id_d11314_idx_accounts_us_user_id_e94dcf_idx_and_more"),
        ("accounts", "0014_userprofile_privacy_visibility_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="workspace_dashboard_widget_order",
            field=models.JSONField(
                blank=True,
                default=[
                    "alerts",
                    "portfolio_kpis",
                    "operational_signals",
                    "team_workload",
                    "valuation_trend",
                    "project_status",
                    "active_projects",
                    "cash_flow_activity",
                ],
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workspace_dashboard_widget_visibility",
            field=models.JSONField(
                blank=True,
                default={
                    "alerts": True,
                    "portfolio_kpis": True,
                    "operational_signals": True,
                    "team_workload": True,
                    "valuation_trend": True,
                    "project_status": True,
                    "active_projects": True,
                    "cash_flow_activity": True,
                },
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workspace_default_dashboard",
            field=models.CharField(
                choices=[
                    ("portfolio_analytics", "Portfolio Analytics"),
                    ("board_metrics", "Board Metrics"),
                ],
                default="portfolio_analytics",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workspace_default_landing_page",
            field=models.CharField(
                choices=[
                    ("/", "Overview"),
                    ("/properties", "Properties"),
                    ("/projects", "Projects"),
                    ("/finance", "Finance"),
                    ("/procurement", "Procurement"),
                    ("/analytics", "Analytics"),
                ],
                default="/",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workspace_layout_density",
            field=models.CharField(
                choices=[("compact", "Compact"), ("comfortable", "Comfortable")],
                default="comfortable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workspace_sidebar_behavior",
            field=models.CharField(
                choices=[("expanded", "Expanded"), ("collapsed", "Collapsed")],
                default="expanded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="workspace_theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                default="system",
                max_length=10,
            ),
        ),
    ]
