# Generated by Django 5.2 on 2026-03-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20260306_2303'),
        ('accounts', '0015_userprofile_workspace_preferences_fields'),
    ]

    operations = [
    ]
