# Generated by Django 5.2 on 2026-03-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_merge_20260306_2304"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="task_approval_delegation_rule",
            field=models.CharField(
                choices=[
                    ("manual_only", "Manual Only"),
                    ("use_active_delegations", "Use Active Delegations"),
                    ("auto_when_out_of_office", "Auto Delegate When Out of Office"),
                ],
                default="use_active_delegations",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="task_auto_follow_assigned_tasks",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="task_auto_subscribe_project_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="task_default_due_date_offset_days",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="task_default_view",
            field=models.CharField(
                choices=[
                    ("list", "List"),
                    ("kanban", "Kanban"),
                    ("calendar", "Calendar"),
                ],
                default="list",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="task_reminder_minutes_before",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
