# Generated by Django 5.2 on 2026-03-07 03:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_userprofile_task_workflow_preferences_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="calendar_default_meeting_duration_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_meeting_buffer_minutes",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_sync_google_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_sync_ical_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_sync_outlook_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_timezone_override",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_working_days",
            field=models.JSONField(blank=True, default=[1, 2, 3, 4, 5]),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_working_hours_end",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="calendar_working_hours_start",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
