# Generated by Django 5.2 on 2026-03-06 23:18

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_task_workflow_preferences_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='workspace_dashboard_widget_order',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_workspace_widget_order),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workspace_dashboard_widget_visibility',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_workspace_widget_visibility),
        ),
    ]
