# Generated by Django 5.2 on 2026-03-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_userprofile_workspace_dashboard_widget_order_and_more'),
        ('accounts', '0018_userprofile_calendar_scheduling_preferences_fields'),
    ]

    operations = [
    ]
