# Generated by Django 5.2 on 2026-03-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_merge_20260306_2321"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="data_column_visibility",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="data_default_export_format",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                default="pdf",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="data_default_report_filters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="data_rows_per_page",
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="data_saved_views",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
