# Generated by Django 5.2 on 2026-03-06 23:25

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userprofile_data_export_preferences_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calendar_working_days',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_calendar_working_days),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_column_visibility',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_data_column_visibility),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_default_report_filters',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_data_report_filters),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_saved_views',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_data_saved_views),
        ),
    ]
