# Generated by Django 5.2 on 2026-03-07 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_userprofile_calendar_working_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserIntegrationConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google_drive", "Google Drive"),
                            ("dropbox", "Dropbox"),
                            ("slack", "Slack"),
                            ("teams", "Teams"),
                            ("zapier", "Zapier"),
                            ("webhooks", "Webhooks"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="connected",
                        max_length=16,
                    ),
                ),
                ("account_label", models.CharField(blank=True, max_length=200)),
                ("external_account_id", models.CharField(blank=True, max_length=255)),
                ("webhook_url", models.URLField(blank=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_token_refresh_at", models.DateTimeField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "-updated_at"],
                "unique_together": {("user", "provider")},
            },
        ),
        migrations.AddIndex(
            model_name="userintegrationconnection",
            index=models.Index(fields=["user", "provider"], name="accounts_us_user_id_fb1424_idx"),
        ),
        migrations.AddIndex(
            model_name="userintegrationconnection",
            index=models.Index(fields=["user", "status"], name="accounts_us_user_id_7428b3_idx"),
        ),
    ]
