# Generated by Django 5.2 on 2026-03-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_userintegrationconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accessibility_font_size",
            field=models.CharField(
                choices=[("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="accessibility_high_contrast_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="accessibility_keyboard_navigation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="accessibility_reduced_motion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="accessibility_screen_reader_support",
            field=models.BooleanField(default=False),
        ),
    ]
