# Generated by Django 5.2 on 2026-03-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userprofile_accessibility_preferences_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userintegrationconnection',
            new_name='accounts_us_user_id_7d84e2_idx',
            old_name='accounts_us_user_id_fb1424_idx',
        ),
        migrations.RenameIndex(
            model_name='userintegrationconnection',
            new_name='accounts_us_user_id_29d6e0_idx',
            old_name='accounts_us_user_id_7428b3_idx',
        ),
    ]
