# Generated by Django 5.2 on 2026-03-07 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_accounts_us_user_id_fb1424_idx_accounts_us_user_id_7d84e2_idx_and_more'),
        ('settings', '0053_platformedition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('growth', 'Growth'), ('scale', 'Scale'), ('custom', 'Custom')], default='scale', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('seats_purchased', models.PositiveIntegerField(default=0, help_text='0 = use edition default (max_users)')),
                ('seats_used', models.PositiveIntegerField(default=0)),
                ('storage_used_gb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('external_subscription_id', models.CharField(blank=True, max_length=255)),
                ('external_customer_id', models.CharField(blank=True, max_length=255)),
                ('payment_method_summary', models.CharField(blank=True, help_text='e.g. "Visa ending 4242"', max_length=100)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='settings.platformedition')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Organization subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('activated', 'Activated'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('renewed', 'Renewed'), ('payment_failed', 'Payment Failed'), ('payment_recovered', 'Payment Recovered'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('reactivated', 'Reactivated'), ('expired', 'Expired'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='settings.platformedition')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organizationsubscription')),
                ('to_edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='settings.platformedition')),
            ],
            options={
                'verbose_name': 'Subscription event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['status'], name='accounts_or_status_7e73e3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsubscription',
            index=models.Index(fields=['current_period_end'], name='accounts_or_current_654889_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionevent',
            index=models.Index(fields=['subscription', '-occurred_at'], name='accounts_su_subscri_d253ca_idx'),
        ),
    ]
