# Generated by Django 5.2 on 2026-03-07

from django.db import migrations

RLS_POLICY_NAME = "org_tenant_isolation"
RLS_ORG_SETTING = "app.current_organization_id"
RLS_BYPASS_SETTING = "app.bypass_rls"

_ORG_TABLE_DISCOVERY_SQL = """
SELECT DISTINCT
    n.nspname AS schema_name,
    c.relname AS table_name
FROM pg_constraint con
JOIN pg_class c
    ON c.oid = con.conrelid
JOIN pg_namespace n
    ON n.oid = c.relnamespace
JOIN pg_class cref
    ON cref.oid = con.confrelid
JOIN pg_namespace nref
    ON nref.oid = cref.relnamespace
JOIN pg_attribute a
    ON a.attrelid = con.conrelid
   AND a.attnum = ANY(con.conkey)
WHERE con.contype = 'f'
  AND c.relkind IN ('r', 'p')
  AND a.attname = 'organization_id'
  AND n.nspname = 'public'
  AND nref.nspname = 'public'
  AND cref.relname = 'accounts_organization'
ORDER BY n.nspname, c.relname
"""


def enable_org_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    quote = schema_editor.connection.ops.quote_name
    org_guard = (
        "("
        f"COALESCE(current_setting('{RLS_BYPASS_SETTING}', true), 'off') IN ('on','true','1')"
        " OR organization_id IS NULL"
        f" OR organization_id = NULLIF(current_setting('{RLS_ORG_SETTING}', true), '')::bigint"
        ")"
    )

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(_ORG_TABLE_DISCOVERY_SQL)
        tables = cursor.fetchall()
        for schema_name, table_name in tables:
            qualified_table = f"{quote(schema_name)}.{quote(table_name)}"
            policy_name = quote(RLS_POLICY_NAME)
            cursor.execute(f"ALTER TABLE {qualified_table} ENABLE ROW LEVEL SECURITY")
            cursor.execute(f"ALTER TABLE {qualified_table} FORCE ROW LEVEL SECURITY")
            cursor.execute(f"DROP POLICY IF EXISTS {policy_name} ON {qualified_table}")
            cursor.execute(
                f"CREATE POLICY {policy_name} ON {qualified_table} "
                f"USING {org_guard} "
                f"WITH CHECK {org_guard}"
            )


def disable_org_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    quote = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT schemaname, tablename
            FROM pg_policies
            WHERE policyname = %s
            ORDER BY schemaname, tablename
            """,
            [RLS_POLICY_NAME],
        )
        tables = cursor.fetchall()
        for schema_name, table_name in tables:
            qualified_table = f"{quote(schema_name)}.{quote(table_name)}"
            policy_name = quote(RLS_POLICY_NAME)
            cursor.execute(f"ALTER TABLE {qualified_table} NO FORCE ROW LEVEL SECURITY")
            cursor.execute(f"DROP POLICY IF EXISTS {policy_name} ON {qualified_table}")
            cursor.execute(f"ALTER TABLE {qualified_table} DISABLE ROW LEVEL SECURITY")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_alter_organization_subscription_tier_and_more"),
        ("compliance", "0002_add_organization_fk"),
        ("crm", "0006_lead_archived_at_lead_archived_reason_and_more"),
        ("documents", "0018_add_organization_fk"),
        ("finance", "0014_alter_paymentplan_currency"),
        ("hr", "0012_hr_documents_policies_models"),
        ("inventory", "0002_add_organization_fk"),
        ("notifications", "0005_add_organization_fk"),
        ("partners", "0004_onboardingtemplatedocumentrequirement_and_more"),
        ("procurement", "0003_goodsreceipt_organization_purchaseorder_budget_code_and_more"),
        ("projects", "0017_add_organization_fk"),
        ("properties", "0009_add_organization_fk"),
        ("settings", "0054_reportsubscription_delivery_channels"),
        ("support_desk", "0010_rename_support_des_organiz_4578f5_idx_support_des_organiz_b54493_idx_and_more"),
        ("valuations", "0002_add_organization_fk"),
        ("workflows", "0004_seed_default_process_authority"),
    ]

    operations = [
        migrations.RunPython(enable_org_rls, disable_org_rls),
    ]
