# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_enable_postgresql_rls'),
        ('settings', '0055_kpi_metrics_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['service_account', 'is_active'], name='acc_apikey_sa_active_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['service_account', '-created_at'], name='acc_apikey_sa_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['organization', 'status'], name='acc_inv_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['organization', '-created_at'], name='acc_inv_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['organization', 'status'], name='acc_sa_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaccount',
            index=models.Index(fields=['organization', '-created_at'], name='acc_sa_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization', 'user_status'], name='acc_prof_org_status_idx'),
        ),
    ]
