# Generated by Django 5.2 on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_apikey_acc_apikey_sa_active_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_demo_account",
            field=models.BooleanField(default=False),
        ),
    ]
