# Generated by Django 5.2 on 2026-03-08

import django.db.models.deletion
from django.db import migrations, models


def _bootstrap_org_name(user_id: int) -> str:
    return f"Workspace-{user_id}"


def backfill_userprofile_organizations(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    Organization = apps.get_model("accounts", "Organization")
    Invitation = apps.get_model("accounts", "Invitation")

    null_profiles = (
        UserProfile.objects
        .select_related("user")
        .filter(organization__isnull=True)
    )

    for profile in null_profiles.iterator():
        user = profile.user
        if user is None:
            continue

        org_id = None

        if getattr(user, "is_superuser", False):
            super_org, _ = Organization.objects.get_or_create(
                name="developerOS",
                defaults={"created_by_id": user.id},
            )
            org_id = super_org.id
        else:
            invitation = (
                Invitation.objects
                .filter(email__iexact=user.email, status="pending")
                .order_by("-created_at")
                .first()
            )
            if invitation and invitation.organization_id:
                org_id = invitation.organization_id
            else:
                workspace_org, _ = Organization.objects.get_or_create(
                    name=_bootstrap_org_name(user.id),
                    defaults={"created_by_id": user.id},
                )
                org_id = workspace_org.id

        if org_id is not None and profile.organization_id != org_id:
            profile.organization_id = org_id
            profile.save(update_fields=["organization"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("accounts", "0029_demorequest"),
    ]

    operations = [
        migrations.RunPython(
            backfill_userprofile_organizations,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="accounts.organization",
            ),
        ),
    ]
