# Generated by Django 5.2 on 2026-03-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_enable_pg_trgm_and_trigram_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='accounts_org_norm_name_trgm',
        ),
    ]
