# Generated by Django 5.2 on 2026-03-15 02:04

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_mfa_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.org_logo_upload_to),
        ),
    ]
