# Generated by Django 5.2.12 on 2026-03-15 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_organization_logo'),
        ('settings', '0068_subscriptionaddon_alter_featureflagdefinition_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSubscriptionAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='settings.subscriptionaddon')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_add_ons', to='accounts.organizationsubscription')),
            ],
            options={
                'verbose_name': 'Active subscription add-on',
                'unique_together': {('subscription', 'add_on')},
            },
        ),
    ]
