# Generated by Django 5.2.12 on 2026-03-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_activesubscriptionaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_platform_org',
            field=models.BooleanField(default=False, help_text='The house organization that owns the platform. Only one should be True.'),
        ),
    ]
