# Generated by Django 5.2.12 on 2026-03-18 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_org_platform_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('iam', 'Identity & Access'), ('telemetry', 'Telemetry & Monitoring'), ('billing', 'Billing & Subscriptions'), ('operations', 'Platform Operations'), ('settings', 'System Settings'), ('tenants', 'Tenant Management'), ('audit', 'Audit & Compliance')], max_length=30)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('execute', 'Execute'), ('impersonate', 'Impersonate')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['module', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tier', models.CharField(choices=[('owner', 'Platform Owner'), ('admin', 'Platform Admin'), ('support', 'Support Agent'), ('billing', 'Billing Manager'), ('devops', 'DevOps / Infrastructure'), ('viewer', 'Read-Only Viewer')], default='viewer', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platform_role',
            field=models.ForeignKey(blank=True, help_text='Platform-level role for console access. Null = no console access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.platformrole'),
        ),
        migrations.CreateModel(
            name='PlatformRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='accounts.platformpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_permissions', to='accounts.platformrole')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
