# Generated by Django 5.2.12 on 2026-05-06 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_usergroup'),
        ('settings', '0082_alter_featureflagdefinition_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_role_valid_until',
            field=models.DateTimeField(blank=True, help_text='If set, the assigned_role is temporary and is automatically cleared by the sweep_expired_access_grants Celery task once this timestamp passes. NULL means a permanent grant.', null=True),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('role_grant', 'Role grant'), ('role_elevation', 'Privilege elevation'), ('resource_access', 'Resource access')], max_length=24)),
                ('requested_resource', models.CharField(blank=True, help_text='Free-text resource identifier for kind=resource_access.', max_length=200)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('revoked', 'Revoked')], default='pending', max_length=12)),
                ('approval_decision_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('requested_valid_until', models.DateTimeField(blank=True, null=True)),
                ('granted_valid_until', models.DateTimeField(blank=True, null=True)),
                ('request_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='The user designated to decide on this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_access_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='accounts.organization')),
                ('requested_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='settings.role')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='acc_accreq_org_status_idx'), models.Index(fields=['organization', 'approver', 'status'], name='acc_accreq_org_appr_st_idx'), models.Index(fields=['organization', 'requester', '-created_at'], name='acc_accreq_org_req_dt_idx')],
            },
        ),
    ]
