# Generated by Django 5.2.12 on 2026-05-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_userprofile_assigned_role_valid_until_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_oauth_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='allow_passkey_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='allow_password_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='allow_sso_login',
            field=models.BooleanField(default=False, help_text='Enable SAML/OIDC SSO. Requires per-org IdP config (see iam/federation).'),
        ),
        migrations.AddField(
            model_name='organization',
            name='password_history_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = no history check. >0 = block reuse of the last N passwords.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='password_max_age_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = passwords never expire. >0 = users must rotate every N days.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='password_min_length',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='organization',
            name='password_require_digits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='password_require_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='password_require_uppercase',
            field=models.BooleanField(default=True),
        ),
    ]
