# Generated by Django 5.2.12 on 2026-05-06 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_userprofile_password_last_changed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurityevent',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Org context for cross-user/system events. May be NULL for unauthenticated login attempts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='usersecurityevent',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='usersecurityevent',
            name='target_id',
            field=models.CharField(blank=True, help_text='ID of the target resource. String to accommodate UUIDs.', max_length=64),
        ),
        migrations.AddField(
            model_name='usersecurityevent',
            name='target_type',
            field=models.CharField(blank=True, help_text="Resource kind acted on (e.g. 'role', 'user', 'session').", max_length=40),
        ),
        migrations.AlterField(
            model_name='usersecurityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('otp_challenge', 'OTP Challenge'), ('otp_failed', 'OTP Failed'), ('password_changed', 'Password Changed'), ('session_revoked', 'Session Revoked'), ('session_revoked_others', 'Other Sessions Revoked'), ('provider_linked', 'Provider Linked'), ('password_policy_changed', 'Password Policy Changed'), ('login_methods_changed', 'Login Methods Changed'), ('role_assigned', 'Role Assigned'), ('role_unassigned', 'Role Unassigned'), ('role_permissions_changed', 'Role Permissions Changed'), ('access_request_submitted', 'Access Request Submitted'), ('access_request_approved', 'Access Request Approved'), ('access_request_rejected', 'Access Request Rejected'), ('access_request_revoked', 'Access Request Revoked'), ('access_request_cancelled', 'Access Request Cancelled'), ('access_grant_auto_revoked', 'Access Grant Auto-Revoked')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='usersecurityevent',
            index=models.Index(fields=['organization', 'occurred_at'], name='accounts_us_organiz_150650_idx'),
        ),
        migrations.AddIndex(
            model_name='usersecurityevent',
            index=models.Index(fields=['organization', 'event_type', 'occurred_at'], name='accounts_us_organiz_87a7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='usersecurityevent',
            index=models.Index(fields=['organization', 'severity', 'occurred_at'], name='accounts_us_organiz_e61e42_idx'),
        ),
    ]
