# Generated by Django 5.2.12 on 2026-05-06 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_usersecurityevent_organization_and_more'),
        ('settings', '0082_alter_featureflagdefinition_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReviewCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('access_review', 'Access Review'), ('role_certification', 'Role Certification'), ('dormant_review', 'Dormant Account Review')], max_length=24)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_review_campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_review_campaigns', to='accounts.organization')),
                ('target_role', models.ForeignKey(blank=True, help_text='If set, the campaign reviews all users currently assigned this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_review_campaigns', to='settings.role')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Access Confirmed'), ('revoked', 'Access Removed'), ('deferred', 'Deferred')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.accessreviewcampaign')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_access_review_items', to=settings.AUTH_USER_MODEL)),
                ('role_at_review', models.ForeignKey(blank=True, help_text="Snapshot of the user's role at campaign start; preserved even if reassigned later.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='settings.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_review_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accessreviewcampaign',
            index=models.Index(fields=['organization', 'status'], name='accounts_ac_organiz_3b632a_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewcampaign',
            index=models.Index(fields=['organization', 'kind', '-created_at'], name='accounts_ac_organiz_85a431_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewitem',
            index=models.Index(fields=['campaign', 'decision'], name='accounts_ac_campaig_91c618_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewitem',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='acc_arit_campaign_user_unique'),
        ),
    ]
