# Generated by Django 5.2.12 on 2026-05-06 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_accessreviewcampaign_accessreviewitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('active_directory', 'Active Directory'), ('azure_ad', 'Azure AD / Entra ID'), ('google_workspace', 'Google Workspace'), ('ldap', 'LDAP'), ('saml_oidc', 'Generic SAML / OIDC')], max_length=24)),
                ('name', models.CharField(help_text="Admin-facing display name for this provider (e.g. 'Acme Azure tenant').", max_length=120)),
                ('is_enabled', models.BooleanField(default=False, help_text='When True, this provider appears as a sign-in option (once the integration phase lands for its kind).')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Public configuration: server URLs, base DNs, attribute mappings, scopes, etc.')),
                ('secrets', models.JSONField(blank=True, default=dict, help_text='Secret configuration: bind passwords, client secrets, signing certs. Write-only via API; GET responses mask values.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('never', 'Never run'), ('success', 'Success'), ('failed', 'Failed'), ('stub', 'Stub — integration phase pending')], default='never', max_length=10)),
                ('last_sync_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_providers', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization', 'kind', 'name'],
                'indexes': [models.Index(fields=['organization', 'kind'], name='accounts_id_organiz_949326_idx'), models.Index(fields=['organization', 'is_enabled'], name='accounts_id_organiz_2ec1db_idx')],
            },
        ),
    ]
