# Generated by Django 5.2.12 on 2026-05-06 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_identityprovider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('communication', 'Communication'), ('automation', 'Automation'), ('storage', 'Storage'), ('analytics', 'Analytics'), ('finance', 'Finance'), ('development', 'Development'), ('other', 'Other')], default='other', max_length=24)),
                ('icon_url', models.CharField(blank=True, max_length=300)),
                ('docs_url', models.CharField(blank=True, max_length=300)),
                ('is_available', models.BooleanField(default=True, help_text='Set to False to hide a connector from the catalogue without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_available'], name='accounts_co_categor_0eacce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField(max_length=500)),
                ('events', models.JSONField(blank=True, default=list, help_text='Array of event names this webhook subscribes to (e.g. ["user.created", "access_request.approved"]). Empty array = all events.')),
                ('secret', models.CharField(blank=True, help_text='HMAC-SHA256 signing secret. Set on creation; receivers verify the X-DeveloperOS-Signature header.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('last_delivery_status', models.CharField(blank=True, default='', max_length=16)),
                ('last_delivery_message', models.TextField(blank=True)),
                ('delivery_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, help_text='Truncated to 2000 chars on save.')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prefix', models.CharField(help_text="First 8 chars of the token for display, e.g. 'dvo_a1b2c3'.", max_length=12)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Array of scope strings (e.g. ["read:projects", "write:invoices"]). Empty = full org scope.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_tokens', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='accounts_ap_organiz_9ea6eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectorInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('secrets', models.JSONField(blank=True, default=dict, help_text="Write-only via API. GET responses replace each value with '********'.")),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='accounts.connector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_installations', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization', 'connector'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'connector'), name='acc_connector_install_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['organization', 'is_active'], name='accounts_we_organiz_6a8279_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', '-created_at'], name='accounts_we_webhook_a6e1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', 'status'], name='accounts_we_webhook_11ad2d_idx'),
        ),
    ]
