# Generated by Django 5.2.12 on 2026-05-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_seed_connectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_default_reminder_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Default reminder lead-time for new CalendarEvents the user creates. Per-event overrides live on CalendarEvent.reminder_minutes_before. Set to 0 to opt out of all reminders by default.'),
        ),
    ]
