# Generated by Django 5.2.12 on 2026-03-30 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('projects', '0060_stage_gate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(blank=True, help_text="Grouping name, e.g. 'Weekly Site Meeting'. Auto-set from template.", max_length=255)),
                ('meeting_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meeting_type', models.CharField(choices=[('site_progress', 'Site Progress Meeting'), ('steering_committee', 'Steering Committee'), ('design_review', 'Design Review'), ('toolbox_talk', 'Toolbox Talk / Safety Briefing'), ('investor_update', 'Investor Update'), ('client_meeting', 'Client Meeting'), ('consultant_coordination', 'Consultant Coordination'), ('procurement_review', 'Procurement Review'), ('financial_review', 'Financial Review'), ('handover', 'Handover Meeting'), ('kick_off', 'Kick-Off Meeting'), ('close_out', 'Close-Out Meeting'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('meeting_format', models.CharField(choices=[('in_person', 'In Person'), ('video_call', 'Video Call'), ('phone', 'Phone Conference'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('duration_mins', models.PositiveIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_link', models.URLField(blank=True, help_text='Video call URL', max_length=500)),
                ('agenda', models.JSONField(blank=True, default=list, help_text='[{"title":"Item","duration_mins":10,"presenter":"Name","notes":""}]')),
                ('key_decisions', models.JSONField(blank=True, default=list, help_text='[{"decision":"Text","decided_by":"Name","rationale":"Why"}]')),
                ('minutes_text', models.TextField(blank=True, help_text='Full meeting minutes — auto-generated or manual.')),
                ('minutes_generated_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_approved', models.BooleanField(default=False)),
                ('minutes_approved_by', models.CharField(blank=True, max_length=255)),
                ('minutes_approved_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.projectconsultant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.organization')),
                ('organized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='projects.project')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('assigned_to', models.CharField(max_length=255)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_meeting_actions', to='projects.projecttask')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting')),
            ],
            options={
                'ordering': ['sort_order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Weekly Site Progress, Monthly Steering Committee', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('ad_hoc', 'Ad-Hoc')], default='weekly', max_length=20)),
                ('default_agenda', models.JSONField(blank=True, default=list, help_text='[{"title":"Health & Safety","duration_mins":10},{"title":"Progress Review","duration_mins":30}]')),
                ('default_attendee_roles', models.JSONField(blank=True, default=list, help_text='["Project Manager","Lead Architect","QS","Site Supervisor"]')),
                ('auto_generate_minutes', models.BooleanField(default=True, help_text='Auto-generate minutes document from completed meeting.')),
                ('minutes_template', models.TextField(blank=True, help_text='Template text for minutes. Variables: {title}, {date}, {attendees}, {agenda}, {decisions}, {action_items}')),
                ('default_duration_mins', models.PositiveIntegerField(default=60)),
                ('default_location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this meeting was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.meetingtemplate'),
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, help_text='e.g. Project Manager, Lead Architect', max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('attendance_status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('attended', 'Attended'), ('no_show', 'No Show')], default='invited', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='meetings.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('meeting', 'email')},
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organization', 'status', '-scheduled_start'], name='mtg_org_sts_start_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organization', 'meeting_type'], name='mtg_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['project', '-scheduled_start'], name='mtg_proj_start_idx'),
        ),
    ]
