# Generated by Django 5.2.12 on 2026-03-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_organized_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='decisions_made',
            field=models.JSONField(blank=True, default=list, help_text='[{"decision":"What was decided","decided_by":"Who","rationale":"Why","impact":"What it affects"}]'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='discussion_points',
            field=models.JSONField(blank=True, default=list, help_text='[{"topic":"What was discussed","summary":"Key points","raised_by":"Name"}]'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='issues_raised',
            field=models.JSONField(blank=True, default=list, help_text='[{"issue":"Problem","raised_by":"Name","resolution":"How resolved or next steps"}]'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='live_notes',
            field=models.TextField(blank=True, help_text='Raw notes typed during the meeting. AI processes these into structured minutes.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='minutes_source',
            field=models.CharField(choices=[('not_generated', 'Not Generated'), ('ai_from_notes', 'AI — From Live Notes'), ('ai_from_form', 'AI — From Structured Form'), ('manual', 'Manually Written')], default='not_generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='minutes_text',
            field=models.TextField(blank=True, help_text='Final meeting minutes.'),
        ),
    ]
