# Generated by Django 5.2 on 2026-03-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_address_line_1_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contractors', 'Contractors'), ('compliance', 'Compliance'), ('settings', 'Settings')], max_length=30)),
                ('sub_module', models.CharField(choices=[('properties.properties', 'Properties'), ('properties.units', 'Units'), ('properties.images', 'Images'), ('properties.documents', 'Documents'), ('properties.valuations', 'Valuations'), ('properties.ownerships', 'Ownerships'), ('properties.encumbrances', 'Encumbrances'), ('projects.projects', 'Projects'), ('projects.phases', 'Phases'), ('projects.tasks', 'Tasks'), ('projects.milestones', 'Milestones'), ('projects.costs', 'Costs'), ('finance.bills', 'Bills'), ('finance.invoices', 'Invoices'), ('finance.customers', 'Customers'), ('finance.payments', 'Payments'), ('procurement.vendors', 'Vendors'), ('procurement.requisitions', 'Requisitions'), ('procurement.orders', 'Purchase Orders'), ('procurement.receipts', 'Goods Receipts'), ('documents.all', 'Documents'), ('analytics.all', 'Analytics'), ('crm.all', 'CRM'), ('tenants.all', 'Tenants'), ('contractors.all', 'Contractors'), ('compliance.all', 'Compliance'), ('settings.company_profile', 'Company Profile'), ('settings.subsidiaries', 'Subsidiaries'), ('settings.hierarchy', 'Hierarchy'), ('settings.roles', 'Roles & Permissions')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('approve', 'Approve'), ('delete', 'Delete'), ('export', 'Export'), ('assign', 'Assign')], max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='settings.role')),
            ],
            options={
                'ordering': ['module', 'sub_module', 'action'],
                'unique_together': {('role', 'sub_module', 'action')},
            },
        ),
    ]
