# Generated by Django 5.2 on 2026-03-01 13:47

from django.db import migrations

# Inline the seed data so the migration doesn't depend on live app code.

SYSTEM_ROLES = [
    ("Developer Executive", "developer-executive", "Full platform access for C-suite executives and managing directors."),
    ("Project Director", "project-director", "Manages development projects, properties, and project teams."),
    ("Sales Manager", "sales-manager", "Manages sales pipeline, customer relationships, and unit availability."),
    ("Finance Controller", "finance-controller", "Full control over financial operations including bills, invoices, and approvals."),
    ("Procurement Officer", "procurement-officer", "Manages the full procurement lifecycle from requisitions to goods receipts."),
    ("Governance Officer", "governance-officer", "Oversees compliance, document governance, and organizational policies."),
    ("Legal", "legal", "Legal review and advisory access across contracts and compliance."),
    ("External Consultant", "external-consultant", "Limited read-only access for external advisors and consultants."),
    ("Auditor", "auditor", "Read-only access with export capability for audit purposes."),
    ("Board Viewer", "board-viewer", "Dashboard and report viewing only for board members."),
]

# Permission registry: sub_module -> available actions
_REGISTRY = {
    "properties.properties": ["view", "create", "edit", "delete", "export"],
    "properties.units": ["view", "create", "edit", "delete"],
    "properties.images": ["view", "create", "delete"],
    "properties.documents": ["view", "create", "delete", "export"],
    "properties.valuations": ["view", "create", "edit", "delete"],
    "properties.ownerships": ["view", "create", "edit", "delete"],
    "properties.encumbrances": ["view", "create", "edit", "delete"],
    "projects.projects": ["view", "create", "edit", "delete", "export", "assign"],
    "projects.phases": ["view", "create", "edit", "delete"],
    "projects.tasks": ["view", "create", "edit", "delete", "assign"],
    "projects.milestones": ["view", "create", "edit", "delete"],
    "projects.costs": ["view", "create", "edit", "delete", "approve", "export"],
    "finance.bills": ["view", "create", "edit", "delete", "approve", "export"],
    "finance.invoices": ["view", "create", "edit", "delete", "approve", "export"],
    "finance.customers": ["view", "create", "edit", "delete"],
    "finance.payments": ["view", "create", "edit", "delete"],
    "procurement.vendors": ["view", "create", "edit", "delete", "export"],
    "procurement.requisitions": ["view", "create", "edit", "delete", "approve", "export"],
    "procurement.orders": ["view", "create", "edit", "delete", "approve", "export"],
    "procurement.receipts": ["view", "create", "edit", "delete"],
    "documents.all": ["view", "create", "edit", "delete", "approve", "export"],
    "analytics.all": ["view", "export"],
    "crm.all": ["view", "create", "edit", "delete", "export"],
    "tenants.all": ["view", "create", "edit", "delete", "export"],
    "contractors.all": ["view", "create", "edit", "delete", "export"],
    "compliance.all": ["view", "create", "edit", "delete", "export"],
    "settings.company_profile": ["view", "edit"],
    "settings.subsidiaries": ["view", "create", "edit", "delete"],
    "settings.hierarchy": ["view", "create", "edit", "delete"],
    "settings.roles": ["view", "create", "edit", "delete"],
}


def _view_only(prefixes):
    return [(sm, ["view"]) for sm in _REGISTRY if any(sm.startswith(p + ".") for p in prefixes) and "view" in _REGISTRY[sm]]

def _view_export(prefixes):
    result = []
    for sm, actions in _REGISTRY.items():
        if any(sm.startswith(p + ".") for p in prefixes):
            granted = [a for a in ["view", "export"] if a in actions]
            if granted:
                result.append((sm, granted))
    return result

def _full(prefixes):
    return [(sm, actions) for sm, actions in _REGISTRY.items() if any(sm.startswith(p + ".") for p in prefixes)]

def _all():
    return [(sm, actions) for sm, actions in _REGISTRY.items()]


DEFAULT_PERMS = {
    "developer-executive": _all(),
    "project-director": _full(["properties", "projects"]) + _view_only(["finance", "procurement", "documents", "analytics", "settings"]),
    "sales-manager": [
        ("properties.properties", ["view", "edit", "export"]),
        ("properties.units", ["view", "edit"]),
        ("properties.images", ["view"]),
        ("properties.documents", ["view"]),
        ("properties.valuations", ["view"]),
        ("properties.ownerships", ["view"]),
        ("properties.encumbrances", ["view"]),
    ] + _view_only(["projects", "finance"]) + _full(["crm", "tenants"]) + _view_only(["analytics", "settings"]),
    "finance-controller": _full(["finance"]) + [
        ("procurement.vendors", ["view"]),
        ("procurement.requisitions", ["view", "approve"]),
        ("procurement.orders", ["view", "approve"]),
        ("procurement.receipts", ["view"]),
    ] + _view_only(["properties", "projects", "documents", "analytics", "settings"]),
    "procurement-officer": _full(["procurement"]) + _view_only(["properties", "projects", "finance", "documents", "analytics", "settings"]),
    "governance-officer": _full(["compliance", "documents"]) + [
        ("settings.company_profile", ["view", "edit"]),
        ("settings.subsidiaries", ["view", "edit"]),
        ("settings.hierarchy", ["view", "edit"]),
        ("settings.roles", ["view"]),
    ] + _view_only(["properties", "projects", "finance", "procurement", "analytics"]),
    "legal": _view_export(["properties", "projects", "finance", "procurement", "analytics"]) + _full(["compliance", "documents"]) + _view_only(["settings"]),
    "external-consultant": _view_only(["properties", "projects"]),
    "auditor": _view_export(["properties", "projects", "finance", "procurement", "documents", "analytics", "compliance", "crm", "tenants", "contractors", "settings"]),
    "board-viewer": _view_only(["analytics", "properties", "projects", "finance"]),
}


def seed_roles(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    Role = apps.get_model("settings", "Role")
    RolePermission = apps.get_model("settings", "RolePermission")

    for org in Organization.objects.all():
        for name, slug, description in SYSTEM_ROLES:
            role, created = Role.objects.get_or_create(
                organization=org,
                slug=slug,
                defaults={"name": name, "description": description, "is_system": True},
            )
            if created:
                perms = []
                for sub_module, actions in DEFAULT_PERMS.get(slug, []):
                    module = sub_module.split(".")[0]
                    for action in actions:
                        perms.append(RolePermission(
                            role=role, module=module,
                            sub_module=sub_module, action=action,
                        ))
                RolePermission.objects.bulk_create(perms)


def unseed_roles(apps, schema_editor):
    Role = apps.get_model("settings", "Role")
    Role.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_assigned_role"),
        ("settings", "0002_role_rolepermission"),
    ]

    operations = [
        migrations.RunPython(seed_roles, unseed_roles),
    ]
