# Generated by Django 5.2 on 2026-03-01

from django.db import migrations, models

DOCUMENT_ACTIONS_BY_ROLE = {
    "developer-executive": [
        "view",
        "comment",
        "upload_version",
        "approve",
        "archive",
        "admin_override",
    ],
    "project-director": [
        "view",
        "comment",
        "upload_version",
        "approve",
        "archive",
    ],
    "sales-manager": ["view", "comment", "upload_version"],
    "finance-controller": ["view", "comment", "approve"],
    "procurement-officer": ["view", "comment", "upload_version"],
    "governance-officer": [
        "view",
        "comment",
        "upload_version",
        "approve",
        "archive",
        "admin_override",
    ],
    "legal": [
        "view",
        "comment",
        "upload_version",
        "approve",
        "archive",
        "admin_override",
    ],
    "external-consultant": ["view"],
    "auditor": ["view"],
    "board-viewer": ["view"],
}


def sync_document_permissions(apps, schema_editor):
    Role = apps.get_model("settings", "Role")
    RolePermission = apps.get_model("settings", "RolePermission")

    roles = Role.objects.filter(is_system=True)
    for role in roles:
        actions = DOCUMENT_ACTIONS_BY_ROLE.get(role.slug)
        if actions is None:
            continue

        RolePermission.objects.filter(
            role=role,
            sub_module="documents.all",
        ).delete()

        RolePermission.objects.bulk_create(
            [
                RolePermission(
                    role=role,
                    module="documents",
                    sub_module="documents.all",
                    action=action,
                )
                for action in actions
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_seed_default_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("comment", "Comment"),
                    ("create", "Create"),
                    ("edit", "Edit"),
                    ("upload_version", "Upload Version"),
                    ("approve", "Approve"),
                    ("archive", "Archive"),
                    ("admin_override", "Admin Override"),
                    ("delete", "Delete"),
                    ("export", "Export"),
                    ("assign", "Assign"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(sync_document_permissions, noop_reverse),
    ]
