# Generated by Django 5.2 on 2026-03-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_add_accounts_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='sub_module',
            field=models.CharField(choices=[('properties.properties', 'Properties'), ('properties.units', 'Units'), ('properties.images', 'Images'), ('properties.documents', 'Documents'), ('properties.valuations', 'Valuations'), ('properties.ownerships', 'Ownerships'), ('properties.encumbrances', 'Encumbrances'), ('projects.projects', 'Projects'), ('projects.phases', 'Phases'), ('projects.tasks', 'Tasks'), ('projects.milestones', 'Milestones'), ('projects.costs', 'Costs'), ('finance.bills', 'Bills'), ('finance.invoices', 'Invoices'), ('finance.customers', 'Customers'), ('finance.payments', 'Payments'), ('finance.accounts', 'Chart of Accounts'), ('procurement.vendors', 'Vendors'), ('procurement.requisitions', 'Requisitions'), ('procurement.orders', 'Purchase Orders'), ('procurement.receipts', 'Goods Receipts'), ('documents.all', 'Documents'), ('analytics.all', 'Analytics'), ('crm.all', 'CRM'), ('tenants.all', 'Tenants'), ('contractors.all', 'Contractors'), ('compliance.all', 'Compliance'), ('settings.company_profile', 'Company Profile'), ('settings.subsidiaries', 'Subsidiaries'), ('settings.hierarchy', 'Hierarchy'), ('settings.roles', 'Roles & Permissions')], max_length=50),
        ),
    ]
