# Generated by Django 5.2 on 2026-03-01 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('settings', '0008_add_budgets_submodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='sub_module',
            field=models.CharField(choices=[('properties.properties', 'Properties'), ('properties.units', 'Units'), ('properties.images', 'Images'), ('properties.documents', 'Documents'), ('properties.valuations', 'Valuations'), ('properties.ownerships', 'Ownerships'), ('properties.encumbrances', 'Encumbrances'), ('projects.projects', 'Projects'), ('projects.phases', 'Phases'), ('projects.tasks', 'Tasks'), ('projects.milestones', 'Milestones'), ('projects.costs', 'Costs'), ('finance.bills', 'Bills'), ('finance.invoices', 'Invoices'), ('finance.customers', 'Customers'), ('finance.payments', 'Payments'), ('finance.accounts', 'Chart of Accounts'), ('finance.budgets', 'Budgets'), ('procurement.vendors', 'Vendors'), ('procurement.requisitions', 'Requisitions'), ('procurement.orders', 'Purchase Orders'), ('procurement.receipts', 'Goods Receipts'), ('documents.all', 'Documents'), ('analytics.all', 'Analytics'), ('crm.all', 'CRM'), ('tenants.all', 'Tenants'), ('contractors.all', 'Contractors'), ('compliance.all', 'Compliance'), ('settings.company_profile', 'Company Profile'), ('settings.subsidiaries', 'Subsidiaries'), ('settings.hierarchy', 'Hierarchy'), ('settings.roles', 'Roles & Permissions'), ('settings.security', 'Security Controls')], max_length=50),
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfa_enforced', models.BooleanField(default=False)),
                ('password_min_length', models.PositiveSmallIntegerField(default=8)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_lowercase', models.BooleanField(default=True)),
                ('password_require_digits', models.BooleanField(default=True)),
                ('password_require_special', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=30)),
                ('ip_restriction_enabled', models.BooleanField(default=False)),
                ('whitelisted_cidrs', models.JSONField(blank=True, default=list)),
                ('geo_blocking_enabled', models.BooleanField(default=False)),
                ('blocked_countries', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
    ]
