# Generated by Django 5.2 on 2026-03-02 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('settings', '0012_add_system_preferences_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='sub_module',
            field=models.CharField(choices=[('properties.properties', 'Properties'), ('properties.units', 'Units'), ('properties.images', 'Images'), ('properties.documents', 'Documents'), ('properties.valuations', 'Valuations'), ('properties.ownerships', 'Ownerships'), ('properties.encumbrances', 'Encumbrances'), ('projects.projects', 'Projects'), ('projects.phases', 'Phases'), ('projects.tasks', 'Tasks'), ('projects.milestones', 'Milestones'), ('projects.costs', 'Costs'), ('finance.bills', 'Bills'), ('finance.invoices', 'Invoices'), ('finance.customers', 'Customers'), ('finance.payments', 'Payments'), ('finance.accounts', 'Chart of Accounts'), ('finance.budgets', 'Budgets'), ('procurement.vendors', 'Vendors'), ('procurement.requisitions', 'Requisitions'), ('procurement.orders', 'Purchase Orders'), ('procurement.receipts', 'Goods Receipts'), ('documents.all', 'Documents'), ('analytics.all', 'Analytics'), ('crm.all', 'CRM'), ('tenants.all', 'Tenants'), ('contractors.all', 'Contractors'), ('compliance.all', 'Compliance'), ('settings.company_profile', 'Company Profile'), ('settings.subsidiaries', 'Subsidiaries'), ('settings.hierarchy', 'Hierarchy'), ('settings.roles', 'Roles & Permissions'), ('settings.security', 'Security Controls'), ('settings.system_preferences', 'System Preferences'), ('settings.audit_compliance', 'Audit & Compliance')], max_length=50),
        ),
        migrations.CreateModel(
            name='AuditComplianceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_logging_enabled', models.BooleanField(default=True)),
                ('audit_retention_days', models.PositiveIntegerField(default=365)),
                ('mandatory_fields_enforced', models.BooleanField(default=False)),
                ('financial_period_locking', models.BooleanField(default=False)),
                ('locked_before_date', models.DateField(blank=True, null=True)),
                ('change_approval_required', models.BooleanField(default=False)),
                ('access_log_retention_days', models.PositiveIntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_compliance_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Audit & Compliance Settings',
                'verbose_name_plural': 'Audit & Compliance Settings',
            },
        ),
    ]
