# Generated by Django 5.2 on 2026-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_add_audit_compliance_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='sub_module',
            field=models.CharField(choices=[('properties.properties', 'Properties'), ('properties.units', 'Units'), ('properties.images', 'Images'), ('properties.documents', 'Documents'), ('properties.valuations', 'Valuations'), ('properties.ownerships', 'Ownerships'), ('properties.encumbrances', 'Encumbrances'), ('projects.projects', 'Projects'), ('projects.phases', 'Phases'), ('projects.tasks', 'Tasks'), ('projects.milestones', 'Milestones'), ('projects.costs', 'Costs'), ('finance.bills', 'Bills'), ('finance.invoices', 'Invoices'), ('finance.customers', 'Customers'), ('finance.payments', 'Payments'), ('finance.accounts', 'Chart of Accounts'), ('finance.budgets', 'Budgets'), ('procurement.vendors', 'Vendors'), ('procurement.requisitions', 'Requisitions'), ('procurement.orders', 'Purchase Orders'), ('procurement.receipts', 'Goods Receipts'), ('documents.all', 'Documents'), ('analytics.all', 'Analytics'), ('crm.all', 'CRM'), ('tenants.all', 'Tenants'), ('contractors.all', 'Contractors'), ('compliance.all', 'Compliance'), ('settings.company_profile', 'Company Profile'), ('settings.subsidiaries', 'Subsidiaries'), ('settings.hierarchy', 'Hierarchy'), ('settings.roles', 'Roles & Permissions'), ('settings.security', 'Security Controls'), ('settings.system_preferences', 'System Preferences'), ('settings.audit_compliance', 'Audit & Compliance'), ('settings.workflow_templates', 'Workflow Templates'), ('settings.approval_policies', 'Approval Policies'), ('settings.delegations', 'Delegations')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systempreferences',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('NGN', 'Nigerian Naira (₦)'), ('EUR', 'Euro (€)')], default='USD', max_length=3),
        ),
    ]
