# Generated by Django 5.2 on 2026-03-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('settings', '0016_seed_workflow_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGovernanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_gate_enforcement_enabled', models.BooleanField(default=True)),
                ('require_template_selection', models.BooleanField(default=True)),
                ('risk_assessment_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_governance_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Project Governance Settings',
                'verbose_name_plural': 'Project Governance Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('residential', 'Residential'), ('mixed_use', 'Mixed-Use'), ('commercial', 'Commercial'), ('infrastructure', 'Infrastructure')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['template_type', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_type', models.CharField(choices=[('financial', 'Financial'), ('regulatory', 'Regulatory'), ('construction', 'Construction'), ('market', 'Market'), ('operational', 'Operational'), ('environmental', 'Environmental'), ('legal', 'Legal'), ('technical', 'Technical')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_categories', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'risk categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskScoreMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_config', models.JSONField(default=dict, help_text='Likelihood, impact, and threshold configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score_matrix', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Risk Score Matrix',
                'verbose_name_plural': 'Risk Score Matrices',
            },
        ),
        migrations.CreateModel(
            name='StageGateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('feasibility', 'Feasibility'), ('design', 'Design'), ('pre_sales', 'Pre-Sales'), ('construction_start', 'Construction Start'), ('handover', 'Handover')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_gate_rules', to='accounts.organization')),
                ('template', models.ForeignKey(blank=True, help_text='If null, applies to all projects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_gate_rules', to='settings.projecttemplate')),
            ],
            options={
                'ordering': ['stage', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StageGateChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='settings.stagegaterule')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplatePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Typical duration in days', null=True)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative weight for progress calculation')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='settings.projecttemplate')),
            ],
            options={
                'verbose_name_plural': 'template phases',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('days_from_phase_start', models.PositiveIntegerField(blank=True, help_text='Typical days from phase start', null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='settings.templatephase')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateComplianceCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('regulatory_reference', models.CharField(blank=True, max_length=200)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checkpoints', to='settings.templatephase')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('permit', 'Permit/Approval'), ('contract', 'Contract'), ('plan', 'Plan/Drawing'), ('report', 'Report/Assessment'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='settings.templatephase')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskMitigationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('escalation_required', models.BooleanField(default=False)),
                ('response_time_hours', models.PositiveIntegerField(blank=True, help_text='Required response time in hours', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_to_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_mitigation_assignments', to='settings.role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_mitigation_rules', to='accounts.organization')),
                ('risk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_rules', to='settings.riskcategory')),
            ],
            options={
                'ordering': ['severity', 'risk_category'],
                'unique_together': {('organization', 'risk_category', 'severity')},
            },
        ),
    ]
