# Generated by Django 5.2 on 2026-03-02

from django.db import migrations


def seed_project_governance_defaults(apps, schema_editor):
    """
    Seed default project templates, risk categories, and stage-gate rules
    for real estate development projects.
    """
    Organization = apps.get_model("accounts", "Organization")
    ProjectTemplate = apps.get_model("settings", "ProjectTemplate")
    TemplatePhase = apps.get_model("settings", "TemplatePhase")
    TemplateMilestone = apps.get_model("settings", "TemplateMilestone")
    TemplateRequiredDocument = apps.get_model("settings", "TemplateRequiredDocument")
    TemplateComplianceCheckpoint = apps.get_model("settings", "TemplateComplianceCheckpoint")
    StageGateRule = apps.get_model("settings", "StageGateRule")
    StageGateChecklistItem = apps.get_model("settings", "StageGateChecklistItem")
    RiskCategory = apps.get_model("settings", "RiskCategory")

    for org in Organization.objects.all():
        # -----------------------------------------------------------------------
        # 1. RESIDENTIAL DEVELOPMENT TEMPLATE
        # -----------------------------------------------------------------------
        residential_template = ProjectTemplate.objects.create(
            organization=org,
            name="Residential Development",
            template_type="residential",
            description="Standard template for residential property development projects",
            is_active=True,
            is_system=True,
        )

        # Residential Phases
        phases_residential = [
            {
                "name": "Feasibility & Site Acquisition",
                "description": "Market analysis, due diligence, and land purchase",
                "duration_days": 90,
                "weight": 10,
                "milestones": [
                    {"name": "Market Study Completed", "days": 30},
                    {"name": "Site Due Diligence Completed", "days": 60},
                    {"name": "Purchase Agreement Signed", "days": 90},
                ],
                "documents": [
                    {"name": "Title Report", "category": "report"},
                    {"name": "Environmental Assessment Phase I", "category": "report"},
                    {"name": "Purchase Agreement", "category": "contract"},
                ],
                "compliance": [
                    {"name": "Zoning Verification", "ref": "Local Zoning Code"},
                    {"name": "Environmental Clearance", "ref": "EPA"},
                ],
            },
            {
                "name": "Design & Planning",
                "description": "Architectural design and permit applications",
                "duration_days": 120,
                "weight": 15,
                "milestones": [
                    {"name": "Conceptual Design Approved", "days": 30},
                    {"name": "Detailed Design Completed", "days": 90},
                    {"name": "Building Permit Submitted", "days": 120},
                ],
                "documents": [
                    {"name": "Architectural Plans", "category": "plan"},
                    {"name": "Structural Engineering Report", "category": "report"},
                    {"name": "Building Permit Application", "category": "permit"},
                ],
                "compliance": [
                    {"name": "Building Code Compliance", "ref": "IBC/Local Code"},
                    {"name": "ADA Compliance", "ref": "ADA Standards"},
                ],
            },
            {
                "name": "Pre-Sales & Marketing",
                "description": "Unit sales and marketing activities",
                "duration_days": 180,
                "weight": 10,
                "milestones": [
                    {"name": "Sales Center Opened", "days": 30},
                    {"name": "30% Pre-Sales Achieved", "days": 90},
                    {"name": "50% Pre-Sales Achieved", "days": 180},
                ],
                "documents": [
                    {"name": "Sales & Marketing Plan", "category": "plan"},
                    {"name": "Purchase Agreements", "category": "contract"},
                ],
                "compliance": [],
            },
            {
                "name": "Construction",
                "description": "Site preparation and building construction",
                "duration_days": 540,
                "weight": 50,
                "milestones": [
                    {"name": "Groundbreaking", "days": 0},
                    {"name": "Foundation Completed", "days": 90},
                    {"name": "Structure Completed", "days": 270},
                    {"name": "MEP Installation Completed", "days": 450},
                    {"name": "Final Inspection Passed", "days": 540},
                ],
                "documents": [
                    {"name": "General Contractor Agreement", "category": "contract"},
                    {"name": "Building Permit", "category": "permit"},
                    {"name": "Insurance Certificates", "category": "certificate"},
                ],
                "compliance": [
                    {"name": "OSHA Safety Compliance", "ref": "OSHA 1926"},
                    {"name": "Building Inspections", "ref": "Local Building Dept"},
                ],
            },
            {
                "name": "Handover & Closeout",
                "description": "Final inspections and unit delivery",
                "duration_days": 90,
                "weight": 15,
                "milestones": [
                    {"name": "Certificate of Occupancy Received", "days": 30},
                    {"name": "First Units Handed Over", "days": 60},
                    {"name": "Project Closeout Completed", "days": 90},
                ],
                "documents": [
                    {"name": "Certificate of Occupancy", "category": "certificate"},
                    {"name": "Warranty Documents", "category": "other"},
                    {"name": "As-Built Drawings", "category": "plan"},
                ],
                "compliance": [],
            },
        ]

        for idx, phase_data in enumerate(phases_residential, start=1):
            phase = TemplatePhase.objects.create(
                template=residential_template,
                name=phase_data["name"],
                description=phase_data["description"],
                sort_order=idx,
                duration_days=phase_data["duration_days"],
                weight=phase_data["weight"],
            )
            for m_idx, milestone_data in enumerate(phase_data["milestones"], start=1):
                TemplateMilestone.objects.create(
                    phase=phase,
                    name=milestone_data["name"],
                    sort_order=m_idx,
                    days_from_phase_start=milestone_data["days"],
                )
            for doc_data in phase_data["documents"]:
                TemplateRequiredDocument.objects.create(
                    phase=phase,
                    name=doc_data["name"],
                    category=doc_data["category"],
                    is_mandatory=True,
                )
            for comp_data in phase_data["compliance"]:
                TemplateComplianceCheckpoint.objects.create(
                    phase=phase,
                    name=comp_data["name"],
                    regulatory_reference=comp_data["ref"],
                    is_mandatory=True,
                )

        # -----------------------------------------------------------------------
        # 2. COMMERCIAL DEVELOPMENT TEMPLATE
        # -----------------------------------------------------------------------
        commercial_template = ProjectTemplate.objects.create(
            organization=org,
            name="Commercial Development",
            template_type="commercial",
            description="Standard template for commercial property development",
            is_active=True,
            is_system=True,
        )

        phases_commercial = [
            {"name": "Feasibility & Acquisition", "duration": 120, "weight": 10},
            {"name": "Design & Permitting", "duration": 150, "weight": 15},
            {"name": "Tenant Leasing", "duration": 270, "weight": 10},
            {"name": "Construction", "duration": 630, "weight": 50},
            {"name": "Commissioning & Handover", "duration": 90, "weight": 15},
        ]

        for idx, phase in enumerate(phases_commercial, start=1):
            TemplatePhase.objects.create(
                template=commercial_template,
                name=phase["name"],
                sort_order=idx,
                duration_days=phase["duration"],
                weight=phase["weight"],
            )

        # -----------------------------------------------------------------------
        # 3. MIXED-USE DEVELOPMENT TEMPLATE
        # -----------------------------------------------------------------------
        mixed_use_template = ProjectTemplate.objects.create(
            organization=org,
            name="Mixed-Use Development",
            template_type="mixed_use",
            description="Template for mixed residential and commercial projects",
            is_active=True,
            is_system=True,
        )

        phases_mixed = [
            {"name": "Feasibility & Acquisition", "duration": 120, "weight": 10},
            {"name": "Design & Permitting", "duration": 180, "weight": 15},
            {"name": "Pre-Sales & Leasing", "duration": 210, "weight": 10},
            {"name": "Construction", "duration": 720, "weight": 50},
            {"name": "Handover & Stabilization", "duration": 120, "weight": 15},
        ]

        for idx, phase in enumerate(phases_mixed, start=1):
            TemplatePhase.objects.create(
                template=mixed_use_template,
                name=phase["name"],
                sort_order=idx,
                duration_days=phase["duration"],
                weight=phase["weight"],
            )

        # -----------------------------------------------------------------------
        # 4. INFRASTRUCTURE DEVELOPMENT TEMPLATE
        # -----------------------------------------------------------------------
        infra_template = ProjectTemplate.objects.create(
            organization=org,
            name="Infrastructure Development",
            template_type="infrastructure",
            description="Template for infrastructure and land development projects",
            is_active=True,
            is_system=True,
        )

        phases_infra = [
            {"name": "Feasibility & Planning", "duration": 90, "weight": 15},
            {"name": "Design & Approvals", "duration": 120, "weight": 20},
            {"name": "Site Development", "duration": 360, "weight": 50},
            {"name": "Completion & Handover", "duration": 60, "weight": 15},
        ]

        for idx, phase in enumerate(phases_infra, start=1):
            TemplatePhase.objects.create(
                template=infra_template,
                name=phase["name"],
                sort_order=idx,
                duration_days=phase["duration"],
                weight=phase["weight"],
            )

        # -----------------------------------------------------------------------
        # STAGE-GATE RULES
        # -----------------------------------------------------------------------
        stage_gates = [
            {
                "stage": "feasibility",
                "name": "Feasibility Approval Gate",
                "description": "Requirements to proceed from feasibility to design",
                "template": None,  # Applies to all templates
                "checklist": [
                    "Market study completed and approved",
                    "Site due diligence completed (environmental, title, zoning)",
                    "Financial feasibility analysis shows positive returns",
                    "Board/Investment Committee approval obtained",
                    "Purchase agreement signed or land secured",
                ],
            },
            {
                "stage": "design",
                "name": "Design Freeze Gate",
                "description": "Requirements to freeze design and start procurement",
                "template": None,
                "checklist": [
                    "Detailed design approved by all stakeholders",
                    "Building permit submitted or approved",
                    "Construction budget finalized",
                    "Value engineering completed",
                    "Design complies with all building codes and regulations",
                ],
            },
            {
                "stage": "pre_sales",
                "name": "Pre-Sales Approval Gate",
                "description": "Requirements to achieve minimum pre-sales for construction start",
                "template": residential_template,
                "checklist": [
                    "Minimum 30% pre-sales achieved",
                    "Sales contracts legally binding",
                    "Construction financing committed",
                    "Escrow accounts established",
                ],
            },
            {
                "stage": "construction_start",
                "name": "Construction Start Gate",
                "description": "Requirements to commence construction",
                "template": None,
                "checklist": [
                    "Building permit obtained",
                    "General contractor agreement signed",
                    "Insurance certificates in place (builder's risk, liability)",
                    "Construction financing drawn down",
                    "Site mobilization plan approved",
                    "Safety plan submitted and approved",
                ],
            },
            {
                "stage": "handover",
                "name": "Handover Approval Gate",
                "description": "Requirements for project handover and closeout",
                "template": None,
                "checklist": [
                    "Certificate of Occupancy obtained",
                    "All final inspections passed",
                    "Punch list items completed",
                    "As-built drawings delivered",
                    "Warranty documents provided",
                    "Final lien releases obtained from all contractors",
                ],
            },
        ]

        for gate_data in stage_gates:
            gate = StageGateRule.objects.create(
                organization=org,
                stage=gate_data["stage"],
                template=gate_data["template"],
                name=gate_data["name"],
                description=gate_data["description"],
                is_active=True,
            )
            for idx, item in enumerate(gate_data["checklist"], start=1):
                StageGateChecklistItem.objects.create(
                    rule=gate,
                    item=item,
                    is_mandatory=True,
                    sort_order=idx,
                )

        # -----------------------------------------------------------------------
        # RISK CATEGORIES
        # -----------------------------------------------------------------------
        risk_categories = [
            {"name": "Market Risk", "type": "market", "desc": "Demand fluctuations, pricing pressures"},
            {"name": "Construction Delay Risk", "type": "construction", "desc": "Schedule overruns, contractor delays"},
            {"name": "Cost Overrun Risk", "type": "financial", "desc": "Budget overruns, material cost escalation"},
            {"name": "Regulatory Approval Risk", "type": "regulatory", "desc": "Permit delays, zoning changes"},
            {"name": "Environmental Compliance Risk", "type": "environmental", "desc": "Environmental violations, contamination"},
            {"name": "Financing Risk", "type": "financial", "desc": "Loan covenant breaches, funding gaps"},
            {"name": "Legal & Title Risk", "type": "legal", "desc": "Ownership disputes, easement issues"},
            {"name": "Design Change Risk", "type": "technical", "desc": "Late design changes, rework"},
            {"name": "Safety Incident Risk", "type": "operational", "desc": "Worker injuries, OSHA violations"},
            {"name": "Quality Defect Risk", "type": "construction", "desc": "Construction defects, material failures"},
        ]

        for cat_data in risk_categories:
            RiskCategory.objects.create(
                organization=org,
                name=cat_data["name"],
                category_type=cat_data["type"],
                description=cat_data["desc"],
                is_active=True,
            )


def reverse_seed(apps, schema_editor):
    """Remove seeded data."""
    ProjectTemplate = apps.get_model("settings", "ProjectTemplate")
    StageGateRule = apps.get_model("settings", "StageGateRule")
    RiskCategory = apps.get_model("settings", "RiskCategory")

    ProjectTemplate.objects.filter(is_system=True).delete()
    StageGateRule.objects.all().delete()
    RiskCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_projectgovernancesettings_projecttemplate_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_project_governance_defaults, reverse_seed),
    ]
