# Generated by Django 5.2 on 2026-03-02 20:24

import django.db.models.deletion
from django.db import migrations, models

import apps.settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('settings', '0018_seed_project_governance_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Notification Channel Settings',
                'verbose_name_plural': 'Notification Channel Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=20)),
                ('event_key', models.CharField(help_text='Internal event key, e.g. workflow_pending or permit_expiry_30d.', max_length=120)),
                ('severity_tier', models.CharField(choices=[('info', 'Info'), ('review', 'Review'), ('action_required', 'Action Required'), ('escalation', 'Escalation')], default='info', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list, help_text='Placeholder keys expected in template context.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['channel', 'name'],
                'indexes': [models.Index(fields=['organization', 'channel', 'event_key'], name='settings_no_organiz_4a7e79_idx'), models.Index(fields=['organization', 'is_active'], name='settings_no_organiz_21b85a_idx')],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SlaSeverityTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('review', 'Review'), ('action_required', 'Action Required'), ('escalation', 'Escalation')], max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('response_time_hours', models.PositiveIntegerField(default=24)),
                ('escalation_path', models.JSONField(blank=True, default=list, help_text='Role slugs, team aliases, or emails in escalation order.')),
                ('notification_channels', models.JSONField(blank=True, default=apps.settings.models.default_sla_notification_channels, help_text='List of channel keys: email, in_app, sms, push.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_severity_tiers', to='accounts.organization')),
            ],
            options={
                'ordering': ['sort_order', 'level'],
                'unique_together': {('organization', 'level')},
            },
        ),
    ]
