# Generated by Django 5.2 on 2026-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_seed_notification_sla_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vendor_type', 'Vendor Type'), ('client_type', 'Client / Buyer Type'), ('consultant_specialization', 'Consultant Specialization'), ('contractor_classification', 'Contractor Classification'), ('investor_type', 'Investor Type'), ('property_type', 'Property Type'), ('property_classification', 'Property Classification'), ('unit_typology', 'Unit Typology'), ('asset_category', 'Asset Category'), ('ownership_structure', 'Ownership Structure'), ('maintenance_category', 'Maintenance Category'), ('inspection_type', 'Inspection Type'), ('cost_code', 'Cost Code'), ('material_category', 'Material Category'), ('payment_method', 'Payment Method'), ('currency', 'Currency'), ('risk_category', 'Risk Category'), ('issue_category', 'Issue Category'), ('compliance_category', 'Compliance Category'), ('project_type', 'Project Type'), ('land_status', 'Land Status'), ('document_type', 'Document Type')], db_index=True, max_length=40)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Master data entries',
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('category', 'code')},
            },
        ),
    ]
