# Generated by Django 5.2.10 on 2026-03-04 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('settings', '0021_masterdataentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contractors', 'Contractors'), ('compliance', 'Compliance'), ('settings', 'Settings')], help_text='Module this flag applies to. Blank = platform-wide.', max_length=30)),
                ('flag_type', models.CharField(choices=[('boolean', 'Boolean (on/off)'), ('percentage', 'Percentage Rollout')], default='boolean', max_length=20)),
                ('scope', models.CharField(choices=[('global', 'Global (all orgs)'), ('org', 'Per Organization'), ('project', 'Per Project'), ('region', 'Per Region')], default='org', max_length=20)),
                ('default_enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=0, help_text='For percentage flags: 0-100. Ignored for boolean flags.')),
                ('minimum_tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Master kill switch. If False, flag is off for everyone.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature flag definition',
                'ordering': ['module', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ModuleActivationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_modules', models.JSONField(default=list, help_text='List of Module enum values that are currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_activation_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Module activation settings',
                'verbose_name_plural': 'Module activation settings',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('scoped_project_ids', models.JSONField(blank=True, default=list, help_text='List of Project IDs this flag applies to. Empty = all projects.')),
                ('scoped_regions', models.JSONField(blank=True, default=list, help_text='List of region/country codes. Empty = all regions.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='settings.featureflagdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flag_overrides', to='accounts.organization')),
            ],
            options={
                'ordering': ['flag__module', 'flag__key'],
                'unique_together': {('flag', 'organization')},
            },
        ),
    ]
