# Generated by Django 5.2.10 on 2026-03-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('settings', '0022_featureflagdefinition_moduleactivationsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDisasterRecoverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('every_6h', 'Every 6 Hours'), ('every_12h', 'Every 12 Hours'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('backup_region', models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-west-2', 'US West (Oregon)'), ('eu-west-1', 'EU West (Ireland)'), ('eu-central-1', 'EU Central (Frankfurt)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('af-south-1', 'Africa (Cape Town)'), ('me-south-1', 'Middle East (Bahrain)')], default='us-east-1', max_length=30)),
                ('rto_minutes', models.PositiveIntegerField(default=240, help_text='Recovery Time Objective in minutes')),
                ('rpo_minutes', models.PositiveIntegerField(default=60, help_text='Recovery Point Objective in minutes')),
                ('failover_on_db_failure', models.BooleanField(default=True)),
                ('failover_on_network_outage', models.BooleanField(default=True)),
                ('failover_on_storage_failure', models.BooleanField(default=True)),
                ('failover_on_app_crash', models.BooleanField(default=False)),
                ('failover_on_manual_trigger', models.BooleanField(default=True)),
                ('restore_test_logs', models.JSONField(blank=True, default=list, help_text='Array of restore test entries: [{date, status, duration_seconds, notes}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_dr_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Backup & Disaster Recovery Settings',
                'verbose_name_plural': 'Backup & Disaster Recovery Settings',
            },
        ),
    ]
