# Generated by Django 5.2.10 on 2026-03-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('settings', '0023_backupdisasterrecoverysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationGovernanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_sync_frequency', models.CharField(choices=[('real_time', 'Real-Time'), ('every_5m', 'Every 5 Minutes'), ('every_15m', 'Every 15 Minutes'), ('every_30m', 'Every 30 Minutes'), ('hourly', 'Hourly'), ('every_6h', 'Every 6 Hours'), ('daily', 'Daily')], default='hourly', max_length=20)),
                ('sync_retry_attempts', models.PositiveIntegerField(default=3, help_text='Number of retry attempts on sync failure')),
                ('sync_retry_delay_seconds', models.PositiveIntegerField(default=60, help_text='Delay between retry attempts in seconds')),
                ('sync_enabled', models.BooleanField(default=True)),
                ('conflict_resolution_strategy', models.CharField(choices=[('source_wins', 'Source System Wins'), ('target_wins', 'Target System Wins'), ('most_recent', 'Most Recent Timestamp Wins'), ('manual_review', 'Queue for Manual Review')], default='source_wins', max_length=20)),
                ('conflict_auto_resolve', models.BooleanField(default=True, help_text='Automatically resolve conflicts using the selected strategy')),
                ('conflict_notify_on_resolution', models.BooleanField(default=True, help_text='Send notifications when conflicts are resolved')),
                ('conflict_escalation_after_hours', models.PositiveIntegerField(default=24, help_text='Escalate unresolved conflicts after this many hours')),
                ('primary_source_of_truth', models.CharField(choices=[('erp', 'ERP System'), ('crm', 'CRM Platform'), ('property_management', 'Property Management System'), ('finance_system', 'Finance & Accounting'), ('project_management', 'Project Management'), ('custom', 'Custom / External')], default='erp', max_length=30)),
                ('source_override_allowed', models.BooleanField(default=False, help_text='Allow downstream systems to override source-of-truth data')),
                ('error_routing_email', models.BooleanField(default=True)),
                ('error_routing_webhook', models.BooleanField(default=False)),
                ('error_routing_in_app', models.BooleanField(default=True)),
                ('error_routing_syslog', models.BooleanField(default=False)),
                ('error_webhook_url', models.CharField(blank=True, max_length=500)),
                ('error_email_recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses for error notifications')),
                ('error_severity_threshold', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('sla_target_uptime_pct', models.DecimalField(decimal_places=2, default=99.9, help_text='Target uptime percentage (e.g. 99.9)', max_digits=5)),
                ('sla_max_response_time_ms', models.PositiveIntegerField(default=5000, help_text='Maximum acceptable API response time in milliseconds')),
                ('sla_max_sync_latency_seconds', models.PositiveIntegerField(default=300, help_text='Maximum acceptable sync latency in seconds')),
                ('sla_alert_on_breach', models.BooleanField(default=True, help_text='Send alerts when SLA thresholds are breached')),
                ('version_compatibility_log', models.JSONField(blank=True, default=list, help_text='Array of integration version entries: [{integration_name, current_version, min_compatible_version, status, last_checked}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_governance_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Integration Governance Settings',
                'verbose_name_plural': 'Integration Governance Settings',
            },
        ),
    ]
