# Generated by Django 5.2 on 2026-03-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('settings', '0024_integrationgovernancesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Unique identifier within the org, e.g. COST_VARIANCE_PCT', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('construction', 'Construction'), ('sales', 'Sales'), ('finance', 'Finance'), ('operations', 'Operations'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('procurement', 'Procurement'), ('project_management', 'Project Management'), ('property', 'Property'), ('safety', 'Safety'), ('quality', 'Quality')], max_length=30)),
                ('unit', models.CharField(choices=[('percentage', 'Percentage (%)'), ('currency', 'Currency'), ('count', 'Count'), ('ratio', 'Ratio'), ('days', 'Days'), ('score', 'Score (0–100)')], default='percentage', max_length=20)),
                ('direction', models.CharField(choices=[('higher_is_better', 'Higher is Better'), ('lower_is_better', 'Lower is Better')], default='higher_is_better', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('formula_expression', models.TextField(blank=True, help_text="Human-readable formula, e.g. '(Budget - Actual) / Budget × 100'")),
                ('data_source', models.CharField(blank=True, help_text="Where the data is sourced from, e.g. 'Project cost entries'", max_length=200)),
                ('green_threshold', models.DecimalField(decimal_places=2, help_text='Threshold for green (good) status', max_digits=12)),
                ('amber_threshold', models.DecimalField(decimal_places=2, help_text='Threshold for amber (warning) status', max_digits=12)),
                ('bonus_green_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Bonus multiplier (%) when KPI is green', max_digits=5, null=True)),
                ('bonus_amber_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Bonus multiplier (%) when KPI is amber', max_digits=5, null=True)),
                ('bonus_red_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Bonus multiplier (%) when KPI is red', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_definitions', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'KPI Definition',
                'verbose_name_plural': 'KPI Definitions',
                'ordering': ['category', 'sort_order', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='KpiAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value for this KPI assignment', max_digits=12)),
                ('weight', models.DecimalField(decimal_places=2, default=100, help_text='Relative weight of this KPI (0–100) for composite scoring', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to='settings.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to='accounts.organization')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assignments', to='settings.role')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='settings.kpidefinition')),
            ],
            options={
                'verbose_name': 'KPI Assignment',
                'verbose_name_plural': 'KPI Assignments',
                'ordering': ['kpi__category', 'kpi__sort_order'],
            },
        ),
    ]
