# Generated by Django 5.2.10 on 2026-03-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('settings', '0025_kpidefinition_kpiassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialityLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('strictly_confidential', 'Strictly Confidential')], default='internal', max_length=25)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color for badge display', max_length=7)),
                ('watermark_override', models.BooleanField(default=False, help_text='Force watermark on reports with this label')),
                ('restrict_printing', models.BooleanField(default=False)),
                ('restrict_download', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidentiality_labels', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Confidentiality Label',
                'verbose_name_plural': 'Confidentiality Labels',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ReportingEngineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_size', models.CharField(choices=[('a4', 'A4 (210 × 297 mm)'), ('letter', 'US Letter (8.5 × 11 in)'), ('legal', 'US Legal (8.5 × 14 in)'), ('a3', 'A3 (297 × 420 mm)')], default='a4', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('margin_top_mm', models.PositiveIntegerField(default=20)),
                ('margin_bottom_mm', models.PositiveIntegerField(default=20)),
                ('margin_left_mm', models.PositiveIntegerField(default=15)),
                ('margin_right_mm', models.PositiveIntegerField(default=15)),
                ('header_enabled', models.BooleanField(default=True)),
                ('header_text', models.CharField(blank=True, help_text='Supports placeholders: {org_name}, {report_title}, {date}', max_length=300)),
                ('footer_enabled', models.BooleanField(default=True)),
                ('footer_text', models.CharField(blank=True, default='Page {page} of {total_pages}', help_text='Supports placeholders: {page}, {total_pages}, {date}', max_length=300)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('font_size_pt', models.PositiveIntegerField(default=10)),
                ('include_cover_page', models.BooleanField(default=True)),
                ('include_table_of_contents', models.BooleanField(default=False)),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, default='CONFIDENTIAL', max_length=100)),
                ('watermark_opacity', models.PositiveIntegerField(default=15, help_text='Opacity percentage (1–100)')),
                ('watermark_position', models.CharField(choices=[('center', 'Center'), ('diagonal', 'Diagonal'), ('top', 'Top'), ('bottom', 'Bottom')], default='diagonal', max_length=10)),
                ('watermark_color', models.CharField(default='#CBD5E1', max_length=7)),
                ('board_pack_enabled', models.BooleanField(default=False)),
                ('board_pack_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='quarterly', max_length=15)),
                ('board_pack_recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses for board pack distribution')),
                ('board_pack_sections', models.JSONField(blank=True, default=list, help_text='Ordered list of report template codes to include in the board pack')),
                ('default_dispatch_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (XLSX)'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('dispatch_retention_days', models.PositiveIntegerField(default=90, help_text='Days to retain generated report files')),
                ('dispatch_reply_to_email', models.EmailField(blank=True, help_text='Reply-to address for dispatched reports', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_engine_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Reporting Engine Settings',
                'verbose_name_plural': 'Reporting Engine Settings',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('financial', 'Financial'), ('operational', 'Operational'), ('compliance', 'Compliance'), ('executive', 'Executive Summary'), ('project', 'Project'), ('property', 'Property'), ('custom', 'Custom')], max_length=20)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (XLSX)'), ('csv', 'CSV'), ('pdf_xlsx', 'PDF + Excel')], default='pdf', max_length=10)),
                ('data_sources', models.JSONField(blank=True, default=list, help_text='List of data source entries: [{"module": "...", "entity": "...", "fields": [...], "filters": {...}}]')),
                ('cross_module_joins', models.JSONField(blank=True, default=list, help_text='List of join definitions: [{"left_source": "...", "right_source": "...", "join_key": "...", "join_type": "inner|left|right"}]')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidentiality_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to='settings.confidentialitylabel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['template_type', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledReportDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=15)),
                ('dispatch_time', models.TimeField(default='08:00', help_text='Time of day to dispatch (HH:MM)')),
                ('dispatch_day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly schedules', null=True)),
                ('dispatch_day_of_month', models.PositiveIntegerField(blank=True, help_text='Day of month for monthly/quarterly/annual schedules (1–28)', null=True)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (XLSX)'), ('csv', 'CSV'), ('pdf_xlsx', 'PDF + Excel')], default='pdf', max_length=10)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to receive the report')),
                ('is_active', models.BooleanField(default=True)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_report_dispatches', to='accounts.organization')),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='settings.reporttemplate')),
            ],
            options={
                'verbose_name': 'Scheduled Report Dispatch',
                'verbose_name_plural': 'Scheduled Report Dispatches',
                'ordering': ['report_template__name', 'frequency'],
            },
        ),
    ]
