# Generated by Django 5.2.10 on 2026-03-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('settings', '0026_reporting_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardNotificationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('severity_threshold', 'Severity Threshold'), ('concurrent_issues', 'Concurrent Issues Count'), ('financial_impact', 'Financial Impact'), ('regulatory_breach', 'Regulatory Breach'), ('escalation_exhausted', 'All Escalation Tiers Exhausted'), ('manual', 'Manual Trigger')], max_length=25)),
                ('severity_threshold', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Severity level to trigger board notification', max_length=10)),
                ('concurrent_issue_count', models.PositiveIntegerField(blank=True, help_text='Number of concurrent issues to trigger notification', null=True)),
                ('financial_threshold_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Financial impact threshold to trigger notification', max_digits=15, null=True)),
                ('notification_message_template', models.TextField(blank=True, help_text='Template for the notification message. Supports placeholders: {issue_summary}, {severity}, {count}, {amount}')),
                ('recipients', models.JSONField(default=list, help_text='Email addresses to notify')),
                ('notification_channels', models.JSONField(default=list, help_text='Channels: email, in_app, sms, push')),
                ('cooldown_hours', models.PositiveIntegerField(default=4, help_text='Minimum hours between repeat notifications for same trigger')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_notification_triggers', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Board Notification Trigger',
                'verbose_name_plural': 'Board Notification Triggers',
                'ordering': ['trigger_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationMatrixSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('default_response_time_minutes', models.PositiveIntegerField(default=60, help_text='Default response time before auto-escalation (minutes)')),
                ('max_escalation_levels', models.PositiveIntegerField(default=4, help_text='Maximum number of escalation levels')),
                ('auto_escalation_enabled', models.BooleanField(default=True, help_text='Automatically escalate when response time is breached')),
                ('require_acknowledgment', models.BooleanField(default=True, help_text='Require explicit acknowledgment before timer pauses')),
                ('crisis_mode_enabled', models.BooleanField(default=False)),
                ('crisis_activation_severity', models.CharField(choices=[('high', 'High'), ('critical', 'Critical')], default='critical', max_length=10)),
                ('crisis_activation_threshold', models.PositiveIntegerField(default=3, help_text='Number of concurrent issues at severity to trigger crisis mode')),
                ('crisis_notification_channels', models.JSONField(blank=True, default=list, help_text='Channels to use during crisis mode: email, in_app, sms, push')),
                ('crisis_war_room_enabled', models.BooleanField(default=False, help_text='Auto-create a virtual war room channel on crisis activation')),
                ('crisis_auto_deactivate_hours', models.PositiveIntegerField(default=24, help_text='Auto-deactivate crisis mode after this many hours if unresolved')),
                ('board_notification_enabled', models.BooleanField(default=False)),
                ('board_severity_threshold', models.CharField(choices=[('critical_only', 'Critical Only'), ('high_and_above', 'High & Critical')], default='critical_only', max_length=20)),
                ('board_notification_recipients', models.JSONField(blank=True, default=list, help_text='Email addresses for board-level notifications')),
                ('board_notification_cooldown_hours', models.PositiveIntegerField(default=4, help_text='Minimum hours between board notifications for same issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_matrix_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Escalation Matrix Settings',
                'verbose_name_plural': 'Escalation Matrix Settings',
            },
        ),
        migrations.CreateModel(
            name='EscalationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('tier_level', models.PositiveIntegerField(help_text='Escalation level (1 = first responder, 2 = supervisor, etc.)')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('response_time_minutes', models.PositiveIntegerField(help_text='Expected response time at this tier (minutes)')),
                ('escalate_to_roles', models.JSONField(default=list, help_text='List of role slugs that are notified at this tier')),
                ('notification_channels', models.JSONField(default=list, help_text='Channels to use: email, in_app, sms, push')),
                ('requires_acknowledgment', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_tiers', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Escalation Tier',
                'verbose_name_plural': 'Escalation Tiers',
                'ordering': ['severity', 'tier_level'],
                'unique_together': {('organization', 'severity', 'tier_level')},
            },
        ),
        migrations.CreateModel(
            name='AutoEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('time_based', 'Time-Based Auto-Escalation'), ('parallel', 'Parallel Notification')], default='time_based', max_length=15)),
                ('escalate_after_minutes', models.PositiveIntegerField(blank=True, help_text='Minutes of inaction before auto-escalation', null=True)),
                ('condition_type', models.CharField(choices=[('no_response', 'No Response'), ('no_resolution', 'No Resolution'), ('threshold_breach', 'Threshold Breach'), ('severity_match', 'Severity Match')], default='no_response', max_length=20)),
                ('condition_threshold', models.PositiveIntegerField(blank=True, help_text='Numeric threshold for threshold_breach conditions', null=True)),
                ('notify_original_assignee', models.BooleanField(default=True, help_text='Keep original assignee notified after escalation')),
                ('trigger_severity', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Severity level that triggers parallel notifications', max_length=10)),
                ('parallel_notify_roles', models.JSONField(blank=True, default=list, help_text='Role slugs to notify in parallel')),
                ('parallel_notify_emails', models.JSONField(blank=True, default=list, help_text='External email addresses for parallel notifications')),
                ('parallel_channels', models.JSONField(blank=True, default=list, help_text='Notification channels for parallel escalation')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_escalation_rules', to='accounts.organization')),
                ('source_tier', models.ForeignKey(blank=True, help_text='Source tier for time-based escalation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_rules', to='settings.escalationtier')),
                ('target_tier', models.ForeignKey(blank=True, help_text='Target tier to escalate to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rules', to='settings.escalationtier')),
            ],
            options={
                'verbose_name': 'Auto-Escalation Rule',
                'verbose_name_plural': 'Auto-Escalation Rules',
                'ordering': ['rule_type', 'name'],
            },
        ),
    ]
