# Generated by Django 5.2 on 2026-03-04 17:41

from django.db import migrations, models

import apps.settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_document_automation_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentautomationsettings',
            name='enabled_signature_providers',
            field=models.JSONField(blank=True, default=apps.settings.models.default_document_signature_providers, help_text='Allowed provider keys for e-signature workflows.'),
        ),
    ]
