# Generated by Django 5.2 on 2026-03-04 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('settings', '0029_alter_documentautomationsettings_enabled_signature_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationBrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender_name', models.CharField(blank=True, max_length=200)),
                ('email_sender_address', models.EmailField(blank=True, max_length=254)),
                ('email_reply_to', models.EmailField(blank=True, max_length=254)),
                ('email_header_html', models.TextField(blank=True, help_text='Custom HTML header injected into outbound email templates.')),
                ('email_footer_html', models.TextField(blank=True, help_text='Custom HTML footer injected into outbound email templates.')),
                ('email_primary_color', models.CharField(default='#000000', max_length=7)),
                ('email_logo_url', models.URLField(blank=True)),
                ('notification_brand_color', models.CharField(default='#000000', max_length=7)),
                ('notification_accent_color', models.CharField(default='#3B82F6', max_length=7)),
                ('notification_logo_url', models.URLField(blank=True)),
                ('notification_app_name', models.CharField(blank=True, max_length=200)),
                ('notification_include_logo', models.BooleanField(default=True)),
                ('sms_sender_id', models.CharField(blank=True, max_length=20)),
                ('sms_prefix', models.CharField(blank=True, max_length=50)),
                ('sms_opt_out_message', models.CharField(blank=True, default='Reply STOP to opt out.', max_length=200)),
                ('sms_character_limit', models.PositiveIntegerField(default=160)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('letterhead_header_html', models.TextField(blank=True, help_text='HTML header for branded document generation (contracts, letters, etc.).')),
                ('letterhead_footer_html', models.TextField(blank=True, help_text='HTML footer for branded document generation.')),
                ('letterhead_paper_size', models.CharField(choices=[('a4', 'A4'), ('letter', 'Letter'), ('legal', 'Legal')], default='a4', max_length=10)),
                ('letterhead_margin_top_mm', models.PositiveIntegerField(default=25)),
                ('letterhead_margin_bottom_mm', models.PositiveIntegerField(default=20)),
                ('letterhead_watermark_text', models.CharField(blank=True, max_length=100)),
                ('letterhead_watermark_opacity', models.PositiveIntegerField(default=15, help_text='Opacity percentage (0-100).')),
                ('default_footer_disclaimer', models.TextField(blank=True)),
                ('contract_footer_disclaimer', models.TextField(blank=True)),
                ('invoice_footer_disclaimer', models.TextField(blank=True)),
                ('report_footer_disclaimer', models.TextField(blank=True)),
                ('signature_email_subject', models.CharField(blank=True, default='Signature requested: {document_title}', max_length=255)),
                ('signature_email_body', models.TextField(blank=True)),
                ('signature_reminder_enabled', models.BooleanField(default=True)),
                ('signature_reminder_frequency_hours', models.PositiveIntegerField(default=24)),
                ('signature_expiry_days', models.PositiveIntegerField(default=30)),
                ('signature_branding_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_branding_settings', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Communication & Branding Settings',
                'verbose_name_plural': 'Communication & Branding Settings',
            },
        ),
    ]
