# Generated by Django 5.2 on 2026-03-04 18:58

from django.db import migrations, models


def _rename_contractors_to_contracts(apps, schema_editor):
    RolePermission = apps.get_model("settings", "RolePermission")
    FeatureFlagDefinition = apps.get_model("settings", "FeatureFlagDefinition")
    ModuleActivationSettings = apps.get_model("settings", "ModuleActivationSettings")

    RolePermission.objects.filter(module="contractors").update(module="contracts")
    RolePermission.objects.filter(sub_module="contractors.all").update(
        sub_module="contracts.all"
    )
    FeatureFlagDefinition.objects.filter(module="contractors").update(
        module="contracts"
    )

    for row in ModuleActivationSettings.objects.all():
        enabled = list(row.enabled_modules or [])
        if "contractors" not in enabled:
            continue
        rewritten: list[str] = []
        for key in enabled:
            rewritten.append("contracts" if key == "contractors" else key)
        deduped: list[str] = []
        for key in rewritten:
            if key not in deduped:
                deduped.append(key)
        row.enabled_modules = deduped
        row.save(update_fields=["enabled_modules", "updated_at"])


def _rename_contracts_to_contractors(apps, schema_editor):
    RolePermission = apps.get_model("settings", "RolePermission")
    FeatureFlagDefinition = apps.get_model("settings", "FeatureFlagDefinition")
    ModuleActivationSettings = apps.get_model("settings", "ModuleActivationSettings")

    RolePermission.objects.filter(module="contracts").update(module="contractors")
    RolePermission.objects.filter(sub_module="contracts.all").update(
        sub_module="contractors.all"
    )
    FeatureFlagDefinition.objects.filter(module="contracts").update(
        module="contractors"
    )

    for row in ModuleActivationSettings.objects.all():
        enabled = list(row.enabled_modules or [])
        if "contracts" not in enabled:
            continue
        rewritten: list[str] = []
        for key in enabled:
            rewritten.append("contractors" if key == "contracts" else key)
        deduped: list[str] = []
        for key in rewritten:
            if key not in deduped:
                deduped.append(key)
        row.enabled_modules = deduped
        row.save(update_fields=["enabled_modules", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_alter_rolepermission_sub_module'),
    ]

    operations = [
        migrations.RunPython(
            _rename_contractors_to_contracts,
            _rename_contracts_to_contractors,
        ),
        migrations.AlterField(
            model_name='featureflagdefinition',
            name='module',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('settings', 'Settings')], help_text='Module this flag applies to. Blank = platform-wide.', max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('settings', 'Settings')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='sub_module',
            field=models.CharField(choices=[('properties.properties', 'Properties'), ('properties.units', 'Units'), ('properties.images', 'Images'), ('properties.documents', 'Documents'), ('properties.valuations', 'Valuations'), ('properties.ownerships', 'Ownerships'), ('properties.encumbrances', 'Encumbrances'), ('projects.projects', 'Projects'), ('projects.phases', 'Phases'), ('projects.tasks', 'Tasks'), ('projects.milestones', 'Milestones'), ('projects.costs', 'Costs'), ('finance.bills', 'Bills'), ('finance.invoices', 'Invoices'), ('finance.customers', 'Customers'), ('finance.payments', 'Payments'), ('finance.accounts', 'Chart of Accounts'), ('finance.budgets', 'Budgets'), ('procurement.vendors', 'Vendors'), ('procurement.requisitions', 'Requisitions'), ('procurement.orders', 'Purchase Orders'), ('procurement.receipts', 'Goods Receipts'), ('procurement.rfqs', 'RFQs'), ('procurement.tenders', 'Tender Comparisons'), ('documents.all', 'Documents'), ('analytics.all', 'Analytics'), ('crm.all', 'CRM'), ('tenants.all', 'Tenants'), ('contracts.all', 'Contracts'), ('compliance.all', 'Compliance'), ('settings.company_profile', 'Company Profile'), ('settings.subsidiaries', 'Subsidiaries'), ('settings.hierarchy', 'Hierarchy'), ('settings.roles', 'Roles & Permissions'), ('settings.security', 'Security Controls'), ('settings.system_preferences', 'System Preferences'), ('settings.audit_compliance', 'Audit & Compliance'), ('settings.workflow_templates', 'Workflow Templates'), ('settings.approval_policies', 'Approval Policies'), ('settings.delegations', 'Delegations')], max_length=50),
        ),
    ]
