# Generated by Django 5.2 on 2026-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_alter_masterdataentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('comment', 'Comment'), ('create', 'Create'), ('edit', 'Edit'), ('upload_version', 'Upload Version'), ('approve', 'Approve'), ('archive', 'Archive'), ('admin_override', 'Admin Override'), ('delete', 'Delete'), ('export', 'Export'), ('assign', 'Assign'), ('configure', 'Configure')], max_length=20),
        ),
    ]
