# Generated by Django 5.2 on 2026-03-06

import django.db.models.deletion
from django.db import migrations, models

PERMISSION_REGISTRY_SNAPSHOT = [
    ("properties.properties", ["view", "create", "edit", "delete", "export"]),
    ("properties.units", ["view", "create", "edit", "delete"]),
    ("properties.images", ["view", "create", "delete"]),
    ("properties.documents", ["view", "create", "delete", "export"]),
    ("properties.valuations", ["view", "create", "edit", "delete"]),
    ("properties.ownerships", ["view", "create", "edit", "delete"]),
    ("properties.encumbrances", ["view", "create", "edit", "delete"]),
    ("projects.projects", ["view", "create", "edit", "delete", "export", "assign"]),
    ("projects.phases", ["view", "create", "edit", "delete"]),
    ("projects.tasks", ["view", "create", "edit", "delete", "assign"]),
    ("projects.milestones", ["view", "create", "edit", "delete"]),
    ("projects.costs", ["view", "create", "edit", "delete", "approve", "export"]),
    ("finance.bills", ["view", "create", "edit", "delete", "approve", "export"]),
    ("finance.invoices", ["view", "create", "edit", "delete", "approve", "export"]),
    ("finance.customers", ["view", "create", "edit", "delete"]),
    ("finance.payments", ["view", "create", "edit", "delete", "approve"]),
    ("finance.accounts", ["view", "create", "edit", "delete"]),
    ("finance.budgets", ["view", "create", "edit", "delete", "approve"]),
    ("finance.reports", ["view", "export"]),
    ("procurement.vendors", ["view", "create", "edit", "delete", "export"]),
    ("procurement.requisitions", ["view", "create", "edit", "delete", "approve", "export"]),
    ("procurement.orders", ["view", "create", "edit", "delete", "approve", "export"]),
    ("procurement.receipts", ["view", "create", "edit", "delete"]),
    ("procurement.rfqs", ["view", "create", "edit", "delete", "approve", "export"]),
    ("procurement.tenders", ["view", "create", "edit", "delete", "approve", "export"]),
    ("documents.all", ["view", "comment", "upload_version", "approve", "archive", "admin_override"]),
    ("analytics.all", ["view", "export"]),
    ("crm.all", ["view", "create", "edit", "delete", "export"]),
    ("tenants.all", ["view", "create", "edit", "delete", "export"]),
    ("contracts.all", ["view", "create", "edit", "delete", "export"]),
    ("compliance.all", ["view", "create", "edit", "delete", "export"]),
    ("iam.users", ["view", "create", "edit", "delete"]),
    ("iam.service_accounts", ["view", "create", "edit", "delete"]),
    ("iam.mfa_settings", ["view", "edit"]),
    ("settings.company_profile", ["view", "edit"]),
    ("settings.subsidiaries", ["view", "create", "edit", "delete"]),
    ("settings.hierarchy", ["view", "create", "edit", "delete"]),
    ("settings.roles", ["view", "create", "edit", "delete", "configure"]),
    ("settings.security", ["view", "edit", "configure"]),
    ("settings.system_preferences", ["view", "edit", "configure"]),
    ("settings.audit_compliance", ["view", "edit"]),
    ("settings.workflow_templates", ["view", "create", "edit", "delete"]),
    ("settings.approval_policies", ["view", "create", "edit", "delete"]),
    ("settings.delegations", ["view", "create", "edit", "delete"]),
]


def seed_permission_catalog_and_backfill(apps, schema_editor):
    Permission = apps.get_model("settings", "Permission")
    RolePermission = apps.get_model("settings", "RolePermission")

    for sub_module, actions in PERMISSION_REGISTRY_SNAPSHOT:
        module = sub_module.split(".")[0]
        for action in actions:
            Permission.objects.get_or_create(
                sub_module=sub_module,
                action=action,
                defaults={
                    "module": module,
                    "key": f"{sub_module}.{action}",
                },
            )

    for role_permission in RolePermission.objects.all().iterator():
        permission, _ = Permission.objects.get_or_create(
            sub_module=role_permission.sub_module,
            action=role_permission.action,
            defaults={
                "module": role_permission.sub_module.split(".")[0],
                "key": f"{role_permission.sub_module}.{role_permission.action}",
            },
        )
        RolePermission.objects.filter(pk=role_permission.pk).update(
            permission_id=permission.id,
            module=permission.module,
            sub_module=permission.sub_module,
            action=permission.action,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0036_add_finance_reports_sub_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("properties", "Properties"),
                            ("projects", "Projects"),
                            ("finance", "Finance"),
                            ("procurement", "Procurement"),
                            ("documents", "Documents"),
                            ("analytics", "Analytics"),
                            ("crm", "CRM"),
                            ("tenants", "Tenants"),
                            ("contracts", "Contracts"),
                            ("compliance", "Compliance"),
                            ("iam", "Identity & Access"),
                            ("settings", "Settings"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "sub_module",
                    models.CharField(
                        choices=[
                            ("properties.properties", "Properties"),
                            ("properties.units", "Units"),
                            ("properties.images", "Images"),
                            ("properties.documents", "Documents"),
                            ("properties.valuations", "Valuations"),
                            ("properties.ownerships", "Ownerships"),
                            ("properties.encumbrances", "Encumbrances"),
                            ("projects.projects", "Projects"),
                            ("projects.phases", "Phases"),
                            ("projects.tasks", "Tasks"),
                            ("projects.milestones", "Milestones"),
                            ("projects.costs", "Costs"),
                            ("finance.bills", "Bills"),
                            ("finance.invoices", "Invoices"),
                            ("finance.customers", "Customers"),
                            ("finance.payments", "Payments"),
                            ("finance.accounts", "Chart of Accounts"),
                            ("finance.budgets", "Budgets"),
                            ("finance.reports", "Finance Reports"),
                            ("procurement.vendors", "Vendors"),
                            ("procurement.requisitions", "Requisitions"),
                            ("procurement.orders", "Purchase Orders"),
                            ("procurement.receipts", "Goods Receipts"),
                            ("procurement.rfqs", "RFQs"),
                            ("procurement.tenders", "Tender Comparisons"),
                            ("documents.all", "Documents"),
                            ("analytics.all", "Analytics"),
                            ("crm.all", "CRM"),
                            ("tenants.all", "Tenants"),
                            ("contracts.all", "Contracts"),
                            ("compliance.all", "Compliance"),
                            ("iam.users", "User Management"),
                            ("iam.service_accounts", "Service Accounts"),
                            ("iam.mfa_settings", "MFA Settings"),
                            ("settings.company_profile", "Company Profile"),
                            ("settings.subsidiaries", "Subsidiaries"),
                            ("settings.hierarchy", "Hierarchy"),
                            ("settings.roles", "Roles & Permissions"),
                            ("settings.security", "Security Controls"),
                            ("settings.system_preferences", "System Preferences"),
                            ("settings.audit_compliance", "Audit & Compliance"),
                            ("settings.workflow_templates", "Workflow Templates"),
                            ("settings.approval_policies", "Approval Policies"),
                            ("settings.delegations", "Delegations"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("comment", "Comment"),
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("upload_version", "Upload Version"),
                            ("approve", "Approve"),
                            ("archive", "Archive"),
                            ("admin_override", "Admin Override"),
                            ("delete", "Delete"),
                            ("export", "Export"),
                            ("assign", "Assign"),
                            ("configure", "Configure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(editable=False, max_length=80, unique=True)),
            ],
            options={
                "ordering": ["module", "sub_module", "action"],
                "unique_together": {("sub_module", "action")},
            },
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("properties", "Properties"),
                    ("projects", "Projects"),
                    ("finance", "Finance"),
                    ("procurement", "Procurement"),
                    ("documents", "Documents"),
                    ("analytics", "Analytics"),
                    ("crm", "CRM"),
                    ("tenants", "Tenants"),
                    ("contracts", "Contracts"),
                    ("compliance", "Compliance"),
                    ("iam", "Identity & Access"),
                    ("settings", "Settings"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="sub_module",
            field=models.CharField(
                choices=[
                    ("properties.properties", "Properties"),
                    ("properties.units", "Units"),
                    ("properties.images", "Images"),
                    ("properties.documents", "Documents"),
                    ("properties.valuations", "Valuations"),
                    ("properties.ownerships", "Ownerships"),
                    ("properties.encumbrances", "Encumbrances"),
                    ("projects.projects", "Projects"),
                    ("projects.phases", "Phases"),
                    ("projects.tasks", "Tasks"),
                    ("projects.milestones", "Milestones"),
                    ("projects.costs", "Costs"),
                    ("finance.bills", "Bills"),
                    ("finance.invoices", "Invoices"),
                    ("finance.customers", "Customers"),
                    ("finance.payments", "Payments"),
                    ("finance.accounts", "Chart of Accounts"),
                    ("finance.budgets", "Budgets"),
                    ("finance.reports", "Finance Reports"),
                    ("procurement.vendors", "Vendors"),
                    ("procurement.requisitions", "Requisitions"),
                    ("procurement.orders", "Purchase Orders"),
                    ("procurement.receipts", "Goods Receipts"),
                    ("procurement.rfqs", "RFQs"),
                    ("procurement.tenders", "Tender Comparisons"),
                    ("documents.all", "Documents"),
                    ("analytics.all", "Analytics"),
                    ("crm.all", "CRM"),
                    ("tenants.all", "Tenants"),
                    ("contracts.all", "Contracts"),
                    ("compliance.all", "Compliance"),
                    ("iam.users", "User Management"),
                    ("iam.service_accounts", "Service Accounts"),
                    ("iam.mfa_settings", "MFA Settings"),
                    ("settings.company_profile", "Company Profile"),
                    ("settings.subsidiaries", "Subsidiaries"),
                    ("settings.hierarchy", "Hierarchy"),
                    ("settings.roles", "Roles & Permissions"),
                    ("settings.security", "Security Controls"),
                    ("settings.system_preferences", "System Preferences"),
                    ("settings.audit_compliance", "Audit & Compliance"),
                    ("settings.workflow_templates", "Workflow Templates"),
                    ("settings.approval_policies", "Approval Policies"),
                    ("settings.delegations", "Delegations"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="settings.permission",
            ),
        ),
        migrations.RunPython(seed_permission_catalog_and_backfill, noop_reverse),
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_permissions",
                to="settings.permission",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermission",
            unique_together={("role", "sub_module", "action"), ("role", "permission")},
        ),
    ]
