# Generated by Django 5.2 on 2026-03-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_permission_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflagdefinition',
            name='module',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('iam', 'Identity & Access'), ('settings', 'Settings')], help_text='Module this flag applies to. Blank = platform-wide.', max_length=30),
        ),
    ]
