# Generated by Django 5.2 on 2026-03-06 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_data_scopes(apps, schema_editor):
    DataScope = apps.get_model("settings", "DataScope")
    defaults = [
        (
            "self",
            "Self",
            "Only records owned or directly managed by the current user.",
        ),
        (
            "department",
            "Department",
            "Records tied to users in the same department.",
        ),
        (
            "project",
            "Project",
            "Records for projects assigned to the current user.",
        ),
        (
            "organization",
            "Organization",
            "All records available within the organization boundary.",
        ),
    ]
    for key, label, description in defaults:
        DataScope.objects.update_or_create(
            key=key,
            defaults={
                "label": label,
                "description": description,
                "is_system": True,
            },
        )


def unseed_default_data_scopes(apps, schema_editor):
    DataScope = apps.get_model("settings", "DataScope")
    DataScope.objects.filter(
        key__in=["self", "department", "project", "organization"],
        is_system=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0038_alter_featureflagdefinition_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("department", "Department"),
                            ("project", "Project"),
                            ("organization", "Organization"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_scopes",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="RoleScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("properties", "Properties"),
                            ("projects", "Projects"),
                            ("finance", "Finance"),
                            ("procurement", "Procurement"),
                            ("documents", "Documents"),
                            ("analytics", "Analytics"),
                            ("crm", "CRM"),
                            ("tenants", "Tenants"),
                            ("contracts", "Contracts"),
                            ("compliance", "Compliance"),
                            ("iam", "Identity & Access"),
                            ("settings", "Settings"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "sub_module",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("properties.properties", "Properties"),
                            ("properties.units", "Units"),
                            ("properties.images", "Images"),
                            ("properties.documents", "Documents"),
                            ("properties.valuations", "Valuations"),
                            ("properties.ownerships", "Ownerships"),
                            ("properties.encumbrances", "Encumbrances"),
                            ("projects.projects", "Projects"),
                            ("projects.phases", "Phases"),
                            ("projects.tasks", "Tasks"),
                            ("projects.milestones", "Milestones"),
                            ("projects.costs", "Costs"),
                            ("finance.bills", "Bills"),
                            ("finance.invoices", "Invoices"),
                            ("finance.customers", "Customers"),
                            ("finance.payments", "Payments"),
                            ("finance.accounts", "Chart of Accounts"),
                            ("finance.budgets", "Budgets"),
                            ("finance.reports", "Finance Reports"),
                            ("procurement.vendors", "Vendors"),
                            ("procurement.requisitions", "Requisitions"),
                            ("procurement.orders", "Purchase Orders"),
                            ("procurement.receipts", "Goods Receipts"),
                            ("procurement.rfqs", "RFQs"),
                            ("procurement.tenders", "Tender Comparisons"),
                            ("documents.all", "Documents"),
                            ("analytics.all", "Analytics"),
                            ("crm.all", "CRM"),
                            ("tenants.all", "Tenants"),
                            ("contracts.all", "Contracts"),
                            ("compliance.all", "Compliance"),
                            ("iam.users", "User Management"),
                            ("iam.service_accounts", "Service Accounts"),
                            ("iam.mfa_settings", "MFA Settings"),
                            ("settings.company_profile", "Company Profile"),
                            ("settings.subsidiaries", "Subsidiaries"),
                            ("settings.hierarchy", "Hierarchy"),
                            ("settings.roles", "Roles & Permissions"),
                            ("settings.security", "Security Controls"),
                            ("settings.system_preferences", "System Preferences"),
                            ("settings.audit_compliance", "Audit & Compliance"),
                            ("settings.workflow_templates", "Workflow Templates"),
                            ("settings.approval_policies", "Approval Policies"),
                            ("settings.delegations", "Delegations"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_scopes",
                        to="settings.datascope",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scopes",
                        to="settings.role",
                    ),
                ),
            ],
            options={
                "db_table": "role_scopes",
                "ordering": ["role_id", "module", "sub_module", "data_scope__key"],
                "unique_together": {("role", "module", "sub_module", "data_scope")},
            },
        ),
        migrations.CreateModel(
            name="UserScopeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("properties", "Properties"),
                            ("projects", "Projects"),
                            ("finance", "Finance"),
                            ("procurement", "Procurement"),
                            ("documents", "Documents"),
                            ("analytics", "Analytics"),
                            ("crm", "CRM"),
                            ("tenants", "Tenants"),
                            ("contracts", "Contracts"),
                            ("compliance", "Compliance"),
                            ("iam", "Identity & Access"),
                            ("settings", "Settings"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "sub_module",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("properties.properties", "Properties"),
                            ("properties.units", "Units"),
                            ("properties.images", "Images"),
                            ("properties.documents", "Documents"),
                            ("properties.valuations", "Valuations"),
                            ("properties.ownerships", "Ownerships"),
                            ("properties.encumbrances", "Encumbrances"),
                            ("projects.projects", "Projects"),
                            ("projects.phases", "Phases"),
                            ("projects.tasks", "Tasks"),
                            ("projects.milestones", "Milestones"),
                            ("projects.costs", "Costs"),
                            ("finance.bills", "Bills"),
                            ("finance.invoices", "Invoices"),
                            ("finance.customers", "Customers"),
                            ("finance.payments", "Payments"),
                            ("finance.accounts", "Chart of Accounts"),
                            ("finance.budgets", "Budgets"),
                            ("finance.reports", "Finance Reports"),
                            ("procurement.vendors", "Vendors"),
                            ("procurement.requisitions", "Requisitions"),
                            ("procurement.orders", "Purchase Orders"),
                            ("procurement.receipts", "Goods Receipts"),
                            ("procurement.rfqs", "RFQs"),
                            ("procurement.tenders", "Tender Comparisons"),
                            ("documents.all", "Documents"),
                            ("analytics.all", "Analytics"),
                            ("crm.all", "CRM"),
                            ("tenants.all", "Tenants"),
                            ("contracts.all", "Contracts"),
                            ("compliance.all", "Compliance"),
                            ("iam.users", "User Management"),
                            ("iam.service_accounts", "Service Accounts"),
                            ("iam.mfa_settings", "MFA Settings"),
                            ("settings.company_profile", "Company Profile"),
                            ("settings.subsidiaries", "Subsidiaries"),
                            ("settings.hierarchy", "Hierarchy"),
                            ("settings.roles", "Roles & Permissions"),
                            ("settings.security", "Security Controls"),
                            ("settings.system_preferences", "System Preferences"),
                            ("settings.audit_compliance", "Audit & Compliance"),
                            ("settings.workflow_templates", "Workflow Templates"),
                            ("settings.approval_policies", "Approval Policies"),
                            ("settings.delegations", "Delegations"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scope_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "data_scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_scope_assignments",
                        to="settings.datascope",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_scope_assignments",
                "ordering": ["user_id", "module", "sub_module", "data_scope__key"],
                "unique_together": {("user", "module", "sub_module", "data_scope")},
            },
        ),
        migrations.RunPython(seed_default_data_scopes, unseed_default_data_scopes),
    ]
