# Generated by Django 5.2 on 2026-03-06 21:10

from django.db import migrations

DATA_SCOPE_CATALOG = {
    "self": {
        "label": "Self",
        "description": "Only records owned or directly managed by the current user.",
    },
    "department": {
        "label": "Department",
        "description": "Records tied to users in the same department.",
    },
    "project": {
        "label": "Project",
        "description": "Records for projects assigned to the current user.",
    },
    "organization": {
        "label": "Organization",
        "description": "All records available within the organization boundary.",
    },
}


DEFAULT_ROLE_SCOPE_MATRIX = {
    "developer-executive": {"iam": "organization", "projects": "organization"},
    "project-director": {"iam": "department", "projects": "project"},
    "sales-manager": {"iam": "department", "projects": "project"},
    "finance-controller": {"iam": "department", "projects": "organization"},
    "procurement-officer": {"iam": "department", "projects": "project"},
    "governance-officer": {"iam": "organization", "projects": "organization"},
    "legal": {"iam": "organization", "projects": "organization"},
    "external-consultant": {"iam": "self", "projects": "project"},
    "auditor": {"iam": "organization", "projects": "organization"},
    "board-viewer": {"iam": "organization", "projects": "organization"},
    "super-admin": {"iam": "organization", "projects": "organization"},
    "system-admin": {"iam": "organization", "projects": "organization"},
    "department-admin": {"iam": "department", "projects": "department"},
    "manager": {"iam": "department", "projects": "project"},
    "staff": {"iam": "self", "projects": "project"},
    "external-auditor": {"iam": "organization", "projects": "organization"},
    "guest": {"iam": "self", "projects": "self"},
}


def seed_default_role_scopes(apps, schema_editor):
    DataScope = apps.get_model("settings", "DataScope")
    Role = apps.get_model("settings", "Role")
    RoleScope = apps.get_model("settings", "RoleScope")

    scope_ids = {}
    for key, meta in DATA_SCOPE_CATALOG.items():
        scope, _ = DataScope.objects.get_or_create(
            key=key,
            defaults={
                "label": meta["label"],
                "description": meta["description"],
                "is_system": True,
            },
        )
        scope_ids[key] = scope.id

    roles = Role.objects.filter(slug__in=DEFAULT_ROLE_SCOPE_MATRIX.keys())
    for role in roles.iterator():
        module_scope_map = DEFAULT_ROLE_SCOPE_MATRIX.get(role.slug, {})
        for module_key, scope_key in module_scope_map.items():
            scope_id = scope_ids.get(scope_key)
            if not scope_id:
                continue
            RoleScope.objects.get_or_create(
                role_id=role.id,
                module=module_key,
                sub_module="",
                data_scope_id=scope_id,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0039_data_scope_layer"),
    ]

    operations = [
        migrations.RunPython(seed_default_role_scopes, noop_reverse),
    ]
