# Generated by Django 5.2 on 2026-03-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_invitation_metadata'),
        ('settings', '0040_seed_default_role_scopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, default='', max_length=40)),
                ('sub_module', models.CharField(blank=True, default='', max_length=80)),
                ('action', models.CharField(blank=True, default='', max_length=40)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower numbers are evaluated first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to='accounts.organization')),
            ],
            options={
                'db_table': 'access_policies',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('require_mfa', 'Require MFA'), ('require_office_ip', 'Require Office IP'), ('require_corporate_device', 'Require Corporate Device')], max_length=30)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_actions', to='settings.accesspolicy')),
            ],
            options={
                'db_table': 'policy_actions',
                'ordering': ['access_policy_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('user_role', 'User Role'), ('action', 'Action'), ('ip_restriction', 'IP Restriction'), ('time_restriction', 'Time Restriction'), ('device_restriction', 'Device Restriction'), ('mfa_requirement', 'MFA Requirement'), ('location', 'Location')], max_length=30)),
                ('operator', models.CharField(choices=[('eq', 'Equals'), ('neq', 'Not Equals'), ('in', 'In'), ('not_in', 'Not In'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal'), ('between', 'Between'), ('cidr', 'CIDR Match')], default='eq', max_length=20)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='settings.accesspolicy')),
            ],
            options={
                'db_table': 'policy_conditions',
                'ordering': ['access_policy_id', 'sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='accesspolicy',
            index=models.Index(fields=['organization', 'is_active', 'priority'], name='access_poli_organiz_dc9850_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspolicy',
            index=models.Index(fields=['module', 'sub_module', 'action'], name='access_poli_module_c21cd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accesspolicy',
            unique_together={('organization', 'key')},
        ),
    ]
