# Generated by Django 5.2 on 2026-03-06 20:20

from django.db import migrations


def seed_default_contextual_access_policies(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    AccessPolicy = apps.get_model("settings", "AccessPolicy")
    PolicyCondition = apps.get_model("settings", "PolicyCondition")
    PolicyAction = apps.get_model("settings", "PolicyAction")

    for org in Organization.objects.all().iterator():
        policy, _ = AccessPolicy.objects.get_or_create(
            organization_id=org.id,
            key="finance-manager-approve-requires-mfa",
            defaults={
                "name": "Finance approvals require MFA",
                "description": (
                    "Enforces MFA for finance approval actions when executed "
                    "by finance managerial roles."
                ),
                "module": "finance",
                "sub_module": "",
                "action": "approve",
                "priority": 10,
                "is_active": True,
            },
        )

        PolicyCondition.objects.get_or_create(
            access_policy_id=policy.id,
            condition_type="user_role",
            operator="in",
            defaults={
                "value": ["finance-manager", "finance-controller"],
                "sort_order": 10,
                "is_active": True,
            },
        )

        PolicyAction.objects.get_or_create(
            access_policy_id=policy.id,
            action_type="require_mfa",
            defaults={
                "parameters": {},
                "message": "MFA is required to approve finance actions.",
                "sort_order": 10,
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0041_accesspolicy_policyaction_policycondition_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_contextual_access_policies, noop_reverse),
    ]
