# Generated by Django 5.2 on 2026-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0042_seed_default_contextual_access_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataentry',
            name='category',
            field=models.CharField(choices=[('identity_type', 'Identity Type'), ('partner_type', 'Partner Type'), ('vendor_type', 'Vendor Type'), ('client_type', 'Client / Buyer Type'), ('consultant_specialization', 'Consultant Specialization'), ('contractor_classification', 'Contractor Classification'), ('investor_type', 'Investor Type'), ('property_type', 'Property Type'), ('property_classification', 'Property Classification'), ('unit_typology', 'Unit Typology'), ('asset_category', 'Asset Category'), ('ownership_structure', 'Ownership Structure'), ('maintenance_category', 'Maintenance Category'), ('inspection_type', 'Inspection Type'), ('cost_code', 'Cost Code'), ('material_category', 'Material Category'), ('payment_method', 'Payment Method'), ('currency', 'Currency'), ('risk_category', 'Risk Category'), ('issue_category', 'Issue Category'), ('compliance_category', 'Compliance Category'), ('project_type', 'Project Type'), ('land_status', 'Land Status'), ('document_type', 'Document Type'), ('lead_type', 'Lead Type'), ('lead_archived_reason', 'Lead Archived Reason'), ('communication_channel', 'Communication Channel'), ('campaign_type', 'Campaign Type'), ('call_disposition', 'Call Disposition'), ('meeting_type', 'Meeting Type'), ('follow_up_reason', 'Follow-Up Reason'), ('lead_source_channel', 'Lead Source Channel'), ('commission_type', 'Commission Type'), ('commission_trigger', 'Commission Trigger Stage'), ('spv_entity_type', 'SPV Entity Type'), ('payment_plan_type', 'Payment Plan Type'), ('payment_frequency', 'Payment Frequency'), ('budget_period', 'Budget Period')], db_index=True, max_length=40),
        ),
    ]
