from django.db import migrations, models

SUPPORT_DESK_ROLE_GRANTS = {
    "governance-officer": {
        "support_desk.overview": ["view"],
        "support_desk.tickets": ["view"],
    },
    "auditor": {
        "support_desk.overview": ["view"],
        "support_desk.tickets": ["view"],
    },
    "system-admin": {
        "support_desk.overview": ["view"],
        "support_desk.tickets": ["view", "create", "edit", "delete", "assign", "comment"],
    },
    "department-admin": {
        "support_desk.overview": ["view"],
        "support_desk.tickets": ["view", "create", "edit", "delete", "assign", "comment"],
    },
    "manager": {
        "support_desk.overview": ["view"],
        "support_desk.tickets": ["view", "create", "edit", "assign", "comment"],
    },
    "staff": {
        "support_desk.overview": ["view"],
        "support_desk.tickets": ["view", "create", "edit", "comment"],
    },
    "external-auditor": {
        "support_desk.overview": ["view"],
        "support_desk.tickets": ["view"],
    },
}


def seed_support_desk_permissions(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    ModuleActivationSettings = apps.get_model("settings", "ModuleActivationSettings")
    Permission = apps.get_model("settings", "Permission")
    Role = apps.get_model("settings", "Role")
    RolePermission = apps.get_model("settings", "RolePermission")

    permission_map = {
        ("support_desk.overview", "view"): Permission.objects.get_or_create(
            sub_module="support_desk.overview",
            action="view",
            defaults={
                "module": "support_desk",
                "key": "support_desk.overview.view",
            },
        )[0],
    }

    for action in ["view", "create", "edit", "delete", "assign", "comment"]:
        permission_map[("support_desk.tickets", action)] = Permission.objects.get_or_create(
            sub_module="support_desk.tickets",
            action=action,
            defaults={
                "module": "support_desk",
                "key": f"support_desk.tickets.{action}",
            },
        )[0]

    for org in Organization.objects.all():
        activation, _ = ModuleActivationSettings.objects.get_or_create(
            organization=org,
            defaults={"enabled_modules": ["support_desk"]},
        )
        enabled_modules = list(activation.enabled_modules or [])
        if "support_desk" not in enabled_modules:
            enabled_modules.append("support_desk")
            activation.enabled_modules = enabled_modules
            activation.save(update_fields=["enabled_modules", "updated_at"])

        roles = {
            role.slug: role
            for role in Role.objects.filter(organization=org, slug__in=SUPPORT_DESK_ROLE_GRANTS.keys())
        }
        for slug, grants in SUPPORT_DESK_ROLE_GRANTS.items():
            role = roles.get(slug)
            if role is None:
                continue
            for sub_module, actions in grants.items():
                for action in actions:
                    permission = permission_map[(sub_module, action)]
                    RolePermission.objects.get_or_create(
                        role=role,
                        sub_module=sub_module,
                        action=action,
                        defaults={
                            "permission": permission,
                            "module": "support_desk",
                        },
                    )


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0046_alter_masterdataentry_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("properties", "Properties"),
                    ("projects", "Projects"),
                    ("finance", "Finance"),
                    ("procurement", "Procurement"),
                    ("documents", "Documents"),
                    ("analytics", "Analytics"),
                    ("crm", "CRM"),
                    ("tenants", "Tenants"),
                    ("contracts", "Contracts"),
                    ("compliance", "Compliance"),
                    ("hr", "Human Resources"),
                    ("iam", "Identity & Access"),
                    ("support_desk", "Support Desk"),
                    ("settings", "Settings"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="sub_module",
            field=models.CharField(
                choices=[
                    ("properties.properties", "Properties"),
                    ("properties.units", "Units"),
                    ("properties.images", "Images"),
                    ("properties.documents", "Documents"),
                    ("properties.valuations", "Valuations"),
                    ("properties.ownerships", "Ownerships"),
                    ("properties.encumbrances", "Encumbrances"),
                    ("projects.projects", "Projects"),
                    ("projects.phases", "Phases"),
                    ("projects.tasks", "Tasks"),
                    ("projects.milestones", "Milestones"),
                    ("projects.costs", "Costs"),
                    ("finance.bills", "Bills"),
                    ("finance.invoices", "Invoices"),
                    ("finance.customers", "Customers"),
                    ("finance.payments", "Payments"),
                    ("finance.accounts", "Chart of Accounts"),
                    ("finance.budgets", "Budgets"),
                    ("finance.reports", "Finance Reports"),
                    ("procurement.vendors", "Vendors"),
                    ("procurement.requisitions", "Requisitions"),
                    ("procurement.orders", "Purchase Orders"),
                    ("procurement.receipts", "Goods Receipts"),
                    ("procurement.rfqs", "RFQs"),
                    ("procurement.tenders", "Tender Comparisons"),
                    ("documents.all", "Documents"),
                    ("analytics.all", "Analytics"),
                    ("crm.all", "CRM"),
                    ("tenants.all", "Tenants"),
                    ("contracts.all", "Contracts"),
                    ("compliance.all", "Compliance"),
                    ("hr.org_structure", "Organization Structure"),
                    ("hr.positions", "Positions"),
                    ("hr.budgeting", "Position Budgeting"),
                    ("hr.vacancies", "Vacancies"),
                    ("hr.employee_directory", "Employee Directory"),
                    ("hr.compensation", "Compensation"),
                    ("hr.requisitions", "Job Requisitions"),
                    ("hr.job_listings", "Job Listings"),
                    ("hr.candidates", "Candidates"),
                    ("hr.interviews", "Interviews"),
                    ("hr.offers", "Job Offers"),
                    ("iam.users", "User Management"),
                    ("iam.service_accounts", "Service Accounts"),
                    ("iam.mfa_settings", "MFA Settings"),
                    ("support_desk.overview", "Support Dashboard"),
                    ("support_desk.tickets", "Support Tickets"),
                    ("settings.company_profile", "Company Profile"),
                    ("settings.subsidiaries", "Subsidiaries"),
                    ("settings.hierarchy", "Hierarchy"),
                    ("settings.roles", "Roles & Permissions"),
                    ("settings.security", "Security Controls"),
                    ("settings.system_preferences", "System Preferences"),
                    ("settings.audit_compliance", "Audit & Compliance"),
                    ("settings.workflow_templates", "Workflow Templates"),
                    ("settings.approval_policies", "Approval Policies"),
                    ("settings.delegations", "Delegations"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("properties", "Properties"),
                    ("projects", "Projects"),
                    ("finance", "Finance"),
                    ("procurement", "Procurement"),
                    ("documents", "Documents"),
                    ("analytics", "Analytics"),
                    ("crm", "CRM"),
                    ("tenants", "Tenants"),
                    ("contracts", "Contracts"),
                    ("compliance", "Compliance"),
                    ("hr", "Human Resources"),
                    ("iam", "Identity & Access"),
                    ("support_desk", "Support Desk"),
                    ("settings", "Settings"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="sub_module",
            field=models.CharField(
                choices=[
                    ("properties.properties", "Properties"),
                    ("properties.units", "Units"),
                    ("properties.images", "Images"),
                    ("properties.documents", "Documents"),
                    ("properties.valuations", "Valuations"),
                    ("properties.ownerships", "Ownerships"),
                    ("properties.encumbrances", "Encumbrances"),
                    ("projects.projects", "Projects"),
                    ("projects.phases", "Phases"),
                    ("projects.tasks", "Tasks"),
                    ("projects.milestones", "Milestones"),
                    ("projects.costs", "Costs"),
                    ("finance.bills", "Bills"),
                    ("finance.invoices", "Invoices"),
                    ("finance.customers", "Customers"),
                    ("finance.payments", "Payments"),
                    ("finance.accounts", "Chart of Accounts"),
                    ("finance.budgets", "Budgets"),
                    ("finance.reports", "Finance Reports"),
                    ("procurement.vendors", "Vendors"),
                    ("procurement.requisitions", "Requisitions"),
                    ("procurement.orders", "Purchase Orders"),
                    ("procurement.receipts", "Goods Receipts"),
                    ("procurement.rfqs", "RFQs"),
                    ("procurement.tenders", "Tender Comparisons"),
                    ("documents.all", "Documents"),
                    ("analytics.all", "Analytics"),
                    ("crm.all", "CRM"),
                    ("tenants.all", "Tenants"),
                    ("contracts.all", "Contracts"),
                    ("compliance.all", "Compliance"),
                    ("hr.org_structure", "Organization Structure"),
                    ("hr.positions", "Positions"),
                    ("hr.budgeting", "Position Budgeting"),
                    ("hr.vacancies", "Vacancies"),
                    ("hr.employee_directory", "Employee Directory"),
                    ("hr.compensation", "Compensation"),
                    ("hr.requisitions", "Job Requisitions"),
                    ("hr.job_listings", "Job Listings"),
                    ("hr.candidates", "Candidates"),
                    ("hr.interviews", "Interviews"),
                    ("hr.offers", "Job Offers"),
                    ("iam.users", "User Management"),
                    ("iam.service_accounts", "Service Accounts"),
                    ("iam.mfa_settings", "MFA Settings"),
                    ("support_desk.overview", "Support Dashboard"),
                    ("support_desk.tickets", "Support Tickets"),
                    ("settings.company_profile", "Company Profile"),
                    ("settings.subsidiaries", "Subsidiaries"),
                    ("settings.hierarchy", "Hierarchy"),
                    ("settings.roles", "Roles & Permissions"),
                    ("settings.security", "Security Controls"),
                    ("settings.system_preferences", "System Preferences"),
                    ("settings.audit_compliance", "Audit & Compliance"),
                    ("settings.workflow_templates", "Workflow Templates"),
                    ("settings.approval_policies", "Approval Policies"),
                    ("settings.delegations", "Delegations"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="rolescope",
            name="module",
            field=models.CharField(
                blank=True,
                choices=[
                    ("properties", "Properties"),
                    ("projects", "Projects"),
                    ("finance", "Finance"),
                    ("procurement", "Procurement"),
                    ("documents", "Documents"),
                    ("analytics", "Analytics"),
                    ("crm", "CRM"),
                    ("tenants", "Tenants"),
                    ("contracts", "Contracts"),
                    ("compliance", "Compliance"),
                    ("hr", "Human Resources"),
                    ("iam", "Identity & Access"),
                    ("support_desk", "Support Desk"),
                    ("settings", "Settings"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rolescope",
            name="sub_module",
            field=models.CharField(
                blank=True,
                choices=[
                    ("properties.properties", "Properties"),
                    ("properties.units", "Units"),
                    ("properties.images", "Images"),
                    ("properties.documents", "Documents"),
                    ("properties.valuations", "Valuations"),
                    ("properties.ownerships", "Ownerships"),
                    ("properties.encumbrances", "Encumbrances"),
                    ("projects.projects", "Projects"),
                    ("projects.phases", "Phases"),
                    ("projects.tasks", "Tasks"),
                    ("projects.milestones", "Milestones"),
                    ("projects.costs", "Costs"),
                    ("finance.bills", "Bills"),
                    ("finance.invoices", "Invoices"),
                    ("finance.customers", "Customers"),
                    ("finance.payments", "Payments"),
                    ("finance.accounts", "Chart of Accounts"),
                    ("finance.budgets", "Budgets"),
                    ("finance.reports", "Finance Reports"),
                    ("procurement.vendors", "Vendors"),
                    ("procurement.requisitions", "Requisitions"),
                    ("procurement.orders", "Purchase Orders"),
                    ("procurement.receipts", "Goods Receipts"),
                    ("procurement.rfqs", "RFQs"),
                    ("procurement.tenders", "Tender Comparisons"),
                    ("documents.all", "Documents"),
                    ("analytics.all", "Analytics"),
                    ("crm.all", "CRM"),
                    ("tenants.all", "Tenants"),
                    ("contracts.all", "Contracts"),
                    ("compliance.all", "Compliance"),
                    ("hr.org_structure", "Organization Structure"),
                    ("hr.positions", "Positions"),
                    ("hr.budgeting", "Position Budgeting"),
                    ("hr.vacancies", "Vacancies"),
                    ("hr.employee_directory", "Employee Directory"),
                    ("hr.compensation", "Compensation"),
                    ("hr.requisitions", "Job Requisitions"),
                    ("hr.job_listings", "Job Listings"),
                    ("hr.candidates", "Candidates"),
                    ("hr.interviews", "Interviews"),
                    ("hr.offers", "Job Offers"),
                    ("iam.users", "User Management"),
                    ("iam.service_accounts", "Service Accounts"),
                    ("iam.mfa_settings", "MFA Settings"),
                    ("support_desk.overview", "Support Dashboard"),
                    ("support_desk.tickets", "Support Tickets"),
                    ("settings.company_profile", "Company Profile"),
                    ("settings.subsidiaries", "Subsidiaries"),
                    ("settings.hierarchy", "Hierarchy"),
                    ("settings.roles", "Roles & Permissions"),
                    ("settings.security", "Security Controls"),
                    ("settings.system_preferences", "System Preferences"),
                    ("settings.audit_compliance", "Audit & Compliance"),
                    ("settings.workflow_templates", "Workflow Templates"),
                    ("settings.approval_policies", "Approval Policies"),
                    ("settings.delegations", "Delegations"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userscopeassignment",
            name="module",
            field=models.CharField(
                blank=True,
                choices=[
                    ("properties", "Properties"),
                    ("projects", "Projects"),
                    ("finance", "Finance"),
                    ("procurement", "Procurement"),
                    ("documents", "Documents"),
                    ("analytics", "Analytics"),
                    ("crm", "CRM"),
                    ("tenants", "Tenants"),
                    ("contracts", "Contracts"),
                    ("compliance", "Compliance"),
                    ("hr", "Human Resources"),
                    ("iam", "Identity & Access"),
                    ("support_desk", "Support Desk"),
                    ("settings", "Settings"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userscopeassignment",
            name="sub_module",
            field=models.CharField(
                blank=True,
                choices=[
                    ("properties.properties", "Properties"),
                    ("properties.units", "Units"),
                    ("properties.images", "Images"),
                    ("properties.documents", "Documents"),
                    ("properties.valuations", "Valuations"),
                    ("properties.ownerships", "Ownerships"),
                    ("properties.encumbrances", "Encumbrances"),
                    ("projects.projects", "Projects"),
                    ("projects.phases", "Phases"),
                    ("projects.tasks", "Tasks"),
                    ("projects.milestones", "Milestones"),
                    ("projects.costs", "Costs"),
                    ("finance.bills", "Bills"),
                    ("finance.invoices", "Invoices"),
                    ("finance.customers", "Customers"),
                    ("finance.payments", "Payments"),
                    ("finance.accounts", "Chart of Accounts"),
                    ("finance.budgets", "Budgets"),
                    ("finance.reports", "Finance Reports"),
                    ("procurement.vendors", "Vendors"),
                    ("procurement.requisitions", "Requisitions"),
                    ("procurement.orders", "Purchase Orders"),
                    ("procurement.receipts", "Goods Receipts"),
                    ("procurement.rfqs", "RFQs"),
                    ("procurement.tenders", "Tender Comparisons"),
                    ("documents.all", "Documents"),
                    ("analytics.all", "Analytics"),
                    ("crm.all", "CRM"),
                    ("tenants.all", "Tenants"),
                    ("contracts.all", "Contracts"),
                    ("compliance.all", "Compliance"),
                    ("hr.org_structure", "Organization Structure"),
                    ("hr.positions", "Positions"),
                    ("hr.budgeting", "Position Budgeting"),
                    ("hr.vacancies", "Vacancies"),
                    ("hr.employee_directory", "Employee Directory"),
                    ("hr.compensation", "Compensation"),
                    ("hr.requisitions", "Job Requisitions"),
                    ("hr.job_listings", "Job Listings"),
                    ("hr.candidates", "Candidates"),
                    ("hr.interviews", "Interviews"),
                    ("hr.offers", "Job Offers"),
                    ("iam.users", "User Management"),
                    ("iam.service_accounts", "Service Accounts"),
                    ("iam.mfa_settings", "MFA Settings"),
                    ("support_desk.overview", "Support Dashboard"),
                    ("support_desk.tickets", "Support Tickets"),
                    ("settings.company_profile", "Company Profile"),
                    ("settings.subsidiaries", "Subsidiaries"),
                    ("settings.hierarchy", "Hierarchy"),
                    ("settings.roles", "Roles & Permissions"),
                    ("settings.security", "Security Controls"),
                    ("settings.system_preferences", "System Preferences"),
                    ("settings.audit_compliance", "Audit & Compliance"),
                    ("settings.workflow_templates", "Workflow Templates"),
                    ("settings.approval_policies", "Approval Policies"),
                    ("settings.delegations", "Delegations"),
                ],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="featureflagdefinition",
            name="module",
            field=models.CharField(
                blank=True,
                choices=[
                    ("properties", "Properties"),
                    ("projects", "Projects"),
                    ("finance", "Finance"),
                    ("procurement", "Procurement"),
                    ("documents", "Documents"),
                    ("analytics", "Analytics"),
                    ("crm", "CRM"),
                    ("tenants", "Tenants"),
                    ("contracts", "Contracts"),
                    ("compliance", "Compliance"),
                    ("hr", "Human Resources"),
                    ("iam", "Identity & Access"),
                    ("support_desk", "Support Desk"),
                    ("settings", "Settings"),
                ],
                help_text="Module this flag applies to. Blank = platform-wide.",
                max_length=30,
            ),
        ),
        migrations.RunPython(seed_support_desk_permissions, migrations.RunPython.noop),
    ]
