# Generated by Django 5.2 on 2026-03-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0048_support_desk_extended_submodules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempreferences',
            name='currency_position',
            field=models.CharField(choices=[('prefix', 'Prefix (symbol1,000)'), ('suffix', 'Suffix (1,000symbol)')], default='prefix', max_length=10),
        ),
        migrations.AlterField(
            model_name='systempreferences',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
    ]
