# Generated by Django 5.2 on 2026-03-08

import django.conf
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
        ("settings", "0050_alter_systempreferences_default_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="allow_simple_builder",
            field=models.BooleanField(
                default=False,
                help_text="Allow end users to create simple derivative reports from this template.",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="module_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("properties", "Properties"),
                    ("projects", "Projects"),
                    ("finance", "Finance"),
                    ("procurement", "Procurement"),
                    ("documents", "Documents"),
                    ("analytics", "Analytics"),
                    ("crm", "CRM"),
                    ("tenants", "Tenants"),
                    ("contracts", "Contracts"),
                    ("compliance", "Compliance"),
                    ("hr", "Human Resources"),
                    ("iam", "Identity & Access"),
                    ("support_desk", "Support Desk"),
                    ("settings", "Settings"),
                ],
                default="",
                help_text="Primary module source for categorizing this report.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_report_templates",
                to=django.conf.settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="shared_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_report_templates",
                to="settings.department",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("department", "Department"),
                    ("shared", "Shared"),
                ],
                default="shared",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["organization", "is_active", "visibility"],
                name="settings_rt_org_active_vis_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplate",
            index=models.Index(
                fields=["organization", "module_source", "template_type"],
                name="settings_rt_org_module_type_idx",
            ),
        ),
        migrations.CreateModel(
            name="ReportSavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("column_visibility", models.JSONField(blank=True, default=dict)),
                ("rows_per_page", models.PositiveSmallIntegerField(default=25)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_saved_views",
                        to="accounts.organization",
                    ),
                ),
                (
                    "report_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_views",
                        to="settings.reporttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_saved_views",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "report_template", "name")},
                "indexes": [
                    models.Index(
                        fields=["organization", "user", "is_active"],
                        name="settings_rsv_org_user_active_idx",
                    ),
                    models.Index(
                        fields=["organization", "report_template"],
                        name="settings_rsv_org_template_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=15,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("xlsx", "Excel (XLSX)"),
                            ("csv", "CSV"),
                            ("pdf_xlsx", "PDF + Excel"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "recipients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional additional recipients in email format.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_subscriptions",
                        to="accounts.organization",
                    ),
                ),
                (
                    "report_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="settings.reporttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_subscriptions",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["report_template__name", "frequency"],
                "unique_together": {("user", "report_template", "frequency")},
                "indexes": [
                    models.Index(
                        fields=["organization", "user", "is_active"],
                        name="settings_rs_org_user_active_idx",
                    ),
                    models.Index(
                        fields=["organization", "report_template"],
                        name="settings_rs_org_template_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled Dispatch"),
                            ("subscription", "Subscription"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("xlsx", "Excel (XLSX)"),
                            ("csv", "CSV"),
                            ("pdf_xlsx", "PDF + Excel"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_runs",
                        to="accounts.organization",
                    ),
                ),
                (
                    "report_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="settings.reporttemplate",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_runs",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scheduled_dispatch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="settings.scheduledreportdispatch",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="settings.reportsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "report_template", "created_at"],
                        name="settings_rr_org_template_created_idx",
                    ),
                    models.Index(
                        fields=["organization", "requested_by", "created_at"],
                        name="settings_rr_org_user_created_idx",
                    ),
                    models.Index(
                        fields=["organization", "status", "created_at"],
                        name="settings_rr_org_status_created_idx",
                    ),
                ],
            },
        ),
    ]
