# Generated by Django 5.2 on 2026-03-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0051_reporting_workspace_entities'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportrun',
            new_name='settings_re_organiz_74a420_idx',
            old_name='settings_rr_org_template_created_idx',
        ),
        migrations.RenameIndex(
            model_name='reportrun',
            new_name='settings_re_organiz_41a282_idx',
            old_name='settings_rr_org_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='reportrun',
            new_name='settings_re_organiz_628a75_idx',
            old_name='settings_rr_org_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='reportsavedview',
            new_name='settings_re_organiz_e1dbae_idx',
            old_name='settings_rsv_org_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='reportsavedview',
            new_name='settings_re_organiz_f6e1e8_idx',
            old_name='settings_rsv_org_template_idx',
        ),
        migrations.RenameIndex(
            model_name='reportsubscription',
            new_name='settings_re_organiz_92d913_idx',
            old_name='settings_rs_org_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='reportsubscription',
            new_name='settings_re_organiz_ba2559_idx',
            old_name='settings_rs_org_template_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplate',
            new_name='settings_re_organiz_00e014_idx',
            old_name='settings_rt_org_active_vis_idx',
        ),
        migrations.RenameIndex(
            model_name='reporttemplate',
            new_name='settings_re_organiz_1a5e7e_idx',
            old_name='settings_rt_org_module_type_idx',
        ),
    ]
