# Generated by Django 5.2 on 2026-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0052_rename_settings_rr_org_template_created_idx_settings_re_organiz_74a420_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tier_level', models.PositiveSmallIntegerField(help_text='Ordering: 0 = Essentials, 1 = Growth, 2 = Scale, 3 = Custom')),
                ('is_custom', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('included_modules', models.JSONField(default=list, help_text='List of Module enum values included in this edition.')),
                ('max_users', models.PositiveIntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('max_storage_gb', models.PositiveIntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('api_rate_limit_rpm', models.PositiveIntegerField(blank=True, help_text='Requests per minute; null = unlimited', null=True)),
                ('data_retention_days', models.PositiveIntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('max_projects', models.PositiveIntegerField(blank=True, help_text='null = unlimited', null=True)),
                ('support_tier', models.CharField(choices=[('community', 'Community'), ('standard', 'Standard'), ('priority', 'Priority'), ('dedicated', 'Dedicated')], default='community', max_length=20)),
                ('support_response_hours', models.PositiveIntegerField(blank=True, help_text='SLA: first response time in hours', null=True)),
                ('support_resolution_hours', models.PositiveIntegerField(blank=True, help_text='SLA: resolution target in hours', null=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='null for custom (negotiated)', max_digits=10, null=True)),
                ('annual_price', models.DecimalField(blank=True, decimal_places=2, help_text='null for custom (negotiated)', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform edition',
                'ordering': ['tier_level'],
            },
        ),
        migrations.AlterField(
            model_name='featureflagdefinition',
            name='minimum_tier',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('growth', 'Growth'), ('scale', 'Scale'), ('custom', 'Custom')], default='essentials', max_length=20),
        ),
    ]
