# Generated by Django 5.2 on 2026-03-08

from django.db import migrations, models

import apps.settings.models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0053_platformedition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsubscription",
            name="delivery_channels",
            field=models.JSONField(
                blank=True,
                default=apps.settings.models.default_report_subscription_delivery_channels,
                help_text="Delivery channels for personal report subscriptions.",
            ),
        ),
    ]
