# Generated by Django 5.2 on 2026-03-08

import django.conf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
        ("settings", "0054_reportsubscription_delivery_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpidefinition",
            name="dimensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Canonical dimension keys used for slicing this KPI, e.g. ['department', 'location'].",
            ),
        ),
        migrations.AddField(
            model_name="kpidefinition",
            name="freshness_sla_minutes",
            field=models.PositiveIntegerField(
                default=1440,
                help_text="Maximum allowed data staleness for this KPI in minutes.",
            ),
        ),
        migrations.AddField(
            model_name="kpidefinition",
            name="grain",
            field=models.CharField(
                choices=[
                    ("event", "Event"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("annual", "Annual"),
                    ("snapshot", "Snapshot"),
                ],
                default="daily",
                help_text="Time grain at which this KPI is computed and stored.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="kpidefinition",
            name="is_canonical",
            field=models.BooleanField(
                default=True,
                help_text="Marks this KPI as part of the canonical org-wide metrics contract.",
            ),
        ),
        migrations.AddField(
            model_name="kpidefinition",
            name="owner_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Business owner role accountable for this KPI.",
                null=True,
                on_delete=models.SET_NULL,
                related_name="owned_kpi_definitions",
                to="settings.role",
            ),
        ),
        migrations.AddField(
            model_name="kpidefinition",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct owner user accountable for this KPI.",
                null=True,
                on_delete=models.SET_NULL,
                related_name="owned_kpi_definitions",
                to=django.conf.settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="kpidefinition",
            index=models.Index(
                fields=["organization", "is_canonical", "grain"],
                name="set_kpi_org_contract_idx",
            ),
        ),
    ]
