# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('settings', '0055_kpi_metrics_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='autoescalationrule',
            index=models.Index(fields=['organization', '-created_at'], name='set_aer_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='boardnotificationtrigger',
            index=models.Index(fields=['organization', '-created_at'], name='set_bnt_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='confidentialitylabel',
            index=models.Index(fields=['organization', '-created_at'], name='set_clbl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['organization', '-created_at'], name='set_cc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['organization', '-created_at'], name='set_div_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='escalationtier',
            index=models.Index(fields=['organization', '-created_at'], name='set_etier_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='kpiassignment',
            index=models.Index(fields=['organization', '-created_at'], name='set_kpia_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='kpidefinition',
            index=models.Index(fields=['organization', '-created_at'], name='set_kpi_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['organization', '-created_at'], name='set_pc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['organization', '-created_at'], name='set_ptpl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='riskcategory',
            index=models.Index(fields=['organization', '-created_at'], name='set_rcat_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='riskmitigationrule',
            index=models.Index(fields=['organization', '-created_at'], name='set_rmr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', '-created_at'], name='set_role_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreportdispatch',
            index=models.Index(fields=['organization', '-created_at'], name='set_srd_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='slaseveritytier',
            index=models.Index(fields=['organization', '-created_at'], name='set_sla_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stagegaterule',
            index=models.Index(fields=['organization', '-created_at'], name='set_sgr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='subsidiary',
            index=models.Index(fields=['organization', '-created_at'], name='set_sub_org_created_idx'),
        ),
    ]
