# Generated by Django 5.2 on 2026-03-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0056_autoescalationrule_set_aer_org_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdataentry',
            name='category',
            field=models.CharField(choices=[('identity_type', 'Identity Type'), ('partner_type', 'Partner Type'), ('vendor_type', 'Vendor Type'), ('client_type', 'Client / Buyer Type'), ('consultant_specialization', 'Consultant Specialization'), ('contractor_classification', 'Contractor Classification'), ('investor_type', 'Investor Type'), ('property_type', 'Property Type'), ('property_classification', 'Property Classification'), ('unit_typology', 'Unit Typology'), ('asset_category', 'Asset Category'), ('ownership_structure', 'Ownership Structure'), ('maintenance_category', 'Maintenance Category'), ('inspection_type', 'Inspection Type'), ('cost_code', 'Cost Code'), ('material_category', 'Material Category'), ('payment_method', 'Payment Method'), ('currency', 'Currency'), ('risk_category', 'Risk Category'), ('issue_category', 'Issue Category'), ('compliance_category', 'Compliance Category'), ('project_type', 'Project Type'), ('land_status', 'Land Status'), ('document_type', 'Document Type'), ('lead_type', 'Lead Type'), ('lead_archived_reason', 'Lead Archived Reason'), ('communication_channel', 'Communication Channel'), ('campaign_type', 'Campaign Type'), ('call_disposition', 'Call Disposition'), ('meeting_type', 'Meeting Type'), ('follow_up_reason', 'Follow-Up Reason'), ('lead_source_channel', 'Lead Source Channel'), ('commission_type', 'Commission Type'), ('commission_trigger', 'Commission Trigger Stage'), ('spv_entity_type', 'SPV Entity Type'), ('payment_plan_type', 'Payment Plan Type'), ('payment_frequency', 'Payment Frequency'), ('budget_period', 'Budget Period'), ('employment_type', 'Employment Type'), ('position_level', 'Position Level'), ('emergency_contact_relationship', 'Emergency Contact Relationship'), ('id_document_type', 'Identification Document Type'), ('hr_document_category', 'HR Document Category'), ('compensation_pay_frequency', 'Compensation Pay Frequency'), ('employment_status', 'Employment Status'), ('contract_type', 'Contract Type'), ('requisition_type', 'Requisition Type'), ('candidate_source', 'Candidate Source'), ('interview_type', 'Interview Type'), ('rejection_reason', 'Rejection Reason'), ('status_badge', 'Status Badge')], db_index=True, max_length=40),
        ),
    ]
