# Generated by Django 5.2 on 2026-03-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0057_alter_masterdataentry_add_status_badge_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformedition',
            name='max_properties',
            field=models.PositiveIntegerField(blank=True, help_text='null = unlimited', null=True),
        ),
    ]
