# Generated by Django 5.2 on 2026-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0058_add_max_properties_to_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformedition',
            name='max_entity_maps',
            field=models.PositiveIntegerField(blank=True, help_text='Max entities with map views; null = unlimited', null=True),
        ),
    ]
