# Generated by Django 5.2 on 2026-03-12 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_enable_pg_trgm_and_trigram_index'),
        ('settings', '0059_add_max_entity_maps_to_edition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projecttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='NULL = global system template visible to all organisations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='projecttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'name'), name='unique_org_template_name'),
        ),
        migrations.AddConstraint(
            model_name='projecttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('name',), name='unique_global_template_name'),
        ),
    ]
