# Generated by Django 5.2 on 2026-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0061_entity_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasetemplate',
            name='approval_authority',
            field=models.TextField(blank=True, help_text='Who has final approval authority for this phase.'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='budget_notes',
            field=models.TextField(blank=True, help_text='Additional notes on budget allocation.'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, help_text='[{"name","description","is_mandatory"}]'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='estimated_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Typical duration in calendar days.', null=True),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='exit_criteria',
            field=models.JSONField(blank=True, default=list, help_text='[{"criterion","verification_method"}]'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='key_tasks',
            field=models.JSONField(blank=True, default=list, help_text='[{"name","description"}]'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='lessons_learned_prompt',
            field=models.TextField(blank=True, help_text='Guiding questions for lessons-learned capture.'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='objective',
            field=models.TextField(blank=True, help_text='Primary objective or goal of this phase.'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='out_of_scope',
            field=models.TextField(blank=True, help_text='Items explicitly excluded from this phase.'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='phase_owner_role',
            field=models.CharField(blank=True, help_text='Suggested role for the phase owner.', max_length=200),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='phase_risks',
            field=models.JSONField(blank=True, default=list, help_text='[{"risk","likelihood","impact","mitigation"}]'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='raci_matrix',
            field=models.JSONField(blank=True, default=list, help_text='[{"task","responsible","accountable","consulted","informed"}]'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='resource_requirements',
            field=models.JSONField(blank=True, default=list, help_text='[{"type","description","quantity"}]'),
        ),
        migrations.AddField(
            model_name='phasetemplate',
            name='success_metrics',
            field=models.JSONField(blank=True, default=list, help_text='[{"metric","target","measurement_method"}]'),
        ),
    ]
