# Generated by Django 5.2.10 on 2026-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0062_phase_template_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonetemplate',
            name='approver_role',
            field=models.CharField(blank=True, help_text='Default role that approves this milestone.', max_length=200),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='key_deliverables',
            field=models.JSONField(blank=True, default=list, help_text='[{"name","description","is_mandatory"}]'),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='owner_role',
            field=models.CharField(blank=True, help_text='Default role responsible for this milestone.', max_length=200),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='predecessors',
            field=models.JSONField(blank=True, default=list, help_text='[{"milestone","dependency_type","lag_days"}]'),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='reference_code',
            field=models.CharField(blank=True, help_text='Default milestone ID/code, e.g. MS-001.', max_length=100),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='stakeholders_to_notify',
            field=models.JSONField(blank=True, default=list, help_text='[{"role","notification_trigger"}]'),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='success_criteria',
            field=models.JSONField(blank=True, default=list, help_text='[{"criterion","verification_method"}]'),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='successors',
            field=models.JSONField(blank=True, default=list, help_text='[{"milestone","dependency_type","lag_days"}]'),
        ),
        migrations.AddField(
            model_name='milestonetemplate',
            name='typical_offset_days',
            field=models.PositiveIntegerField(blank=True, help_text='Typical number of days from phase start to this milestone.', null=True),
        ),
    ]
