# Generated by Django 5.2.12 on 2026-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0067_alter_permission_action_alter_permission_sub_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('add_on_type', models.CharField(choices=[('module', 'Module'), ('storage', 'Storage')], max_length=20)),
                ('module_key', models.CharField(blank=True, help_text='Module enum value to enable (for module add-ons)', max_length=50)),
                ('storage_gb', models.PositiveIntegerField(default=0, help_text='Extra GB to add (for storage add-ons)')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscription add-on',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='featureflagdefinition',
            name='module',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings')], help_text='Module this flag applies to. Blank = platform-wide.', max_length=30),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='module_source',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings')], default='', help_text='Primary module source for categorizing this report.', max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rolescope',
            name='module',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userscopeassignment',
            name='module',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings')], default='', max_length=30),
        ),
    ]
