# Generated by Django 5.2.12 on 2026-03-21 07:26

from django.db import migrations, models

import apps.settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0074_templateplanscenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='estimated_effort_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Expected effort in man-hours.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='templateplanscenario',
            name='is_baseline',
            field=models.BooleanField(default=False, help_text='The officially committed plan baseline.'),
        ),
        migrations.AlterField(
            model_name='templateplanscenario',
            name='sensitivity_fx_10pct_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost impact of 10% FX increase.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='templateplanscenario',
            name='sensitivity_material_10pct_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost impact of 10% material price increase.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='custom_holidays',
            field=models.JSONField(blank=True, default=list, help_text='[{"name","date":"YYYY-MM-DD"}]'),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='duration_scalar_pct',
            field=models.DecimalField(decimal_places=1, default=100, help_text='100 = normal. 90 = 10%% faster. 110 = 10%% slower.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='milestone_anchors',
            field=models.JSONField(blank=True, default=list, help_text='[{"task_id","anchor_day","label"}]'),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='outdoor_task_categories',
            field=models.JSONField(default=apps.settings.models.default_outdoor_task_categories, help_text='Task categories affected by weather buffers.'),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='public_holidays',
            field=models.JSONField(default=apps.settings.models.default_nigerian_holidays, help_text='[{"name","month","day"}]'),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='rainy_season_buffer_pct',
            field=models.DecimalField(decimal_places=1, default=15, help_text='% buffer added to outdoor tasks during rainy months.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='rainy_season_months',
            field=models.JSONField(default=apps.settings.models.default_rainy_season_months, help_text='Month numbers (1-12) considered rainy season.'),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='resource_roles',
            field=models.JSONField(default=apps.settings.models.default_resource_roles, help_text='[{"role","capacity","daily_rate"}]'),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='travel_buffer_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Hours added for crew mobilization between sites.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='templateschedulesettings',
            name='work_days',
            field=models.JSONField(default=apps.settings.models.default_work_days, help_text='{"mon":true,"tue":true,...,"sun":false}'),
        ),
    ]
