# Generated by Django 5.2.12 on 2026-03-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0075_alter_tasktemplate_estimated_effort_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='production_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Output per day in output_unit. E.g. 10 m³/day for concrete pouring.', max_digits=10, null=True),
        ),
    ]
