# Generated by Django 5.2.12 on 2026-03-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0076_tasktemplate_production_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgovernancesettings',
            name='allow_multi_boq_merge',
            field=models.BooleanField(default=False, help_text='Allow merging multiple BOMs (Structural + MEP + Architectural) into a single blueprint.'),
        ),
        migrations.AddField(
            model_name='projectgovernancesettings',
            name='auto_recalculate_on_boq_change',
            field=models.BooleanField(default=False, help_text="When a BOM is updated, automatically recalculate any linked blueprint's WBS, durations, and costs."),
        ),
    ]
