# Generated by Django 5.2.12 on 2026-03-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0077_projectgovernancesettings_allow_multi_boq_merge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgovernancesettings',
            name='auto_activate_on_land_acquisition',
            field=models.BooleanField(default=False, help_text='When all land acquisitions for a project are marked complete, auto-activate the project status.'),
        ),
        migrations.AddField(
            model_name='projectgovernancesettings',
            name='auto_create_project_on_approval',
            field=models.BooleanField(default=False, help_text='When a workflow approval for a project setup is completed, auto-create the project with budget shell, document repository, and milestone template.'),
        ),
        migrations.AddField(
            model_name='projectgovernancesettings',
            name='auto_lock_budget_on_approval',
            field=models.BooleanField(default=False, help_text='When a budget is approved, auto-lock it and distribute into construction, procurement, and contingency allocations.'),
        ),
        migrations.AddField(
            model_name='projectgovernancesettings',
            name='auto_provision_consultant_access',
            field=models.BooleanField(default=False, help_text='When a consultant engagement status changes to active, auto-assign roles and grant access to design and submittals.'),
        ),
    ]
