# Generated by Django 5.2.12 on 2026-03-27 02:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0079_functional_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalcontrol',
            name='three_way_match_block_payment',
            field=models.BooleanField(default=False, help_text='Block bill payment if 3-way match fails.'),
        ),
        migrations.AddField(
            model_name='functionalcontrol',
            name='three_way_match_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic 3-way matching (PO vs GRN vs Invoice).'),
        ),
        migrations.AddField(
            model_name='functionalcontrol',
            name='three_way_match_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Variance tolerance % for auto-matching (e.g. 5% = amounts within 5% are considered matched).', max_digits=5),
        ),
    ]
