# Generated by Django 5.2.12 on 2026-03-27 13:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('settings', '0080_functionalcontrol_three_way_match_block_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPolicySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_auto_approve_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='POs below this amount are auto-approved (0 = disabled).', max_digits=15)),
                ('po_single_approval_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='POs below this amount need only 1 approver (0 = use workflow).', max_digits=15)),
                ('po_director_approval_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='POs above this require director-level approval.', max_digits=15)),
                ('min_quotes_required', models.PositiveIntegerField(default=3, help_text='Minimum number of vendor quotes required before PO can be issued.')),
                ('min_quotes_threshold', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='POs above this amount require minimum quotes. Below = single source OK.', max_digits=15)),
                ('sole_source_justification_required', models.BooleanField(default=True, help_text='Require written justification for single-source procurement.')),
                ('require_vendor_compliance', models.BooleanField(default=True, help_text="Vendors must be 'compliant' before POs can be issued to them.")),
                ('block_blacklisted_vendors', models.BooleanField(default=True, help_text='Prevent PO creation for blacklisted vendors.')),
                ('vendor_performance_minimum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum performance rating (0-5) to issue POs. 0 = disabled.', max_digits=3)),
                ('require_budget_code', models.BooleanField(default=False, help_text='Require budget code on all PRs and POs.')),
                ('block_over_budget_po', models.BooleanField(default=False, help_text='Prevent PO creation if it exceeds the linked budget.')),
                ('require_grn_before_payment', models.BooleanField(default=True, help_text='Bills cannot be approved until GRN is recorded.')),
                ('grn_quantity_tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Acceptable over-delivery tolerance % (e.g. 5% = accept 105 when ordered 100).', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_policy', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Procurement Policy',
                'verbose_name_plural': 'Procurement Policies',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. VAT 7.5%, WHT 5%', max_length=100)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('wht', 'Withholding Tax'), ('sales_tax', 'Sales Tax'), ('stamp_duty', 'Stamp Duty'), ('custom_duty', 'Custom Duty'), ('other', 'Other')], default='vat', max_length=20)),
                ('rate_pct', models.DecimalField(decimal_places=3, help_text='Tax rate as percentage, e.g. 7.500', max_digits=6)),
                ('applies_to', models.CharField(choices=[('all', 'All Transactions'), ('purchase_orders', 'Purchase Orders'), ('bills', 'Bills / Vendor Invoices'), ('invoices', 'Customer Invoices'), ('contracts', 'Contracts')], default='all', max_length=20)),
                ('is_compound', models.BooleanField(default=False, help_text='If true, applied on top of other taxes (compound).')),
                ('is_inclusive', models.BooleanField(default=False, help_text='If true, tax is included in the price (not added on top).')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-applied to new transactions.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
