# Generated by Django 5.2.12 on 2026-05-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0081_procurementpolicysettings_taxrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflagdefinition',
            name='module',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings'), ('construction', 'Construction'), ('payroll', 'Payroll'), ('calendar', 'Calendar'), ('mail', 'Mail')], help_text='Module this flag applies to. Blank = platform-wide.', max_length=30),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings'), ('construction', 'Construction'), ('payroll', 'Payroll'), ('calendar', 'Calendar'), ('mail', 'Mail')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='module_source',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings'), ('construction', 'Construction'), ('payroll', 'Payroll'), ('calendar', 'Calendar'), ('mail', 'Mail')], default='', help_text='Primary module source for categorizing this report.', max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings'), ('construction', 'Construction'), ('payroll', 'Payroll'), ('calendar', 'Calendar'), ('mail', 'Mail')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rolescope',
            name='module',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings'), ('construction', 'Construction'), ('payroll', 'Payroll'), ('calendar', 'Calendar'), ('mail', 'Mail')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userscopeassignment',
            name='module',
            field=models.CharField(blank=True, choices=[('properties', 'Properties'), ('projects', 'Projects'), ('finance', 'Finance'), ('procurement', 'Procurement'), ('documents', 'Documents'), ('analytics', 'Analytics'), ('crm', 'CRM'), ('tenants', 'Tenants'), ('contracts', 'Contracts'), ('compliance', 'Compliance'), ('hr', 'Human Resources'), ('iam', 'Identity & Access'), ('support_desk', 'Support Desk'), ('facility_management', 'Facility Management'), ('settings', 'Settings'), ('construction', 'Construction'), ('payroll', 'Payroll'), ('calendar', 'Calendar'), ('mail', 'Mail')], default='', max_length=30),
        ),
    ]
