# Generated by Django 5.2.12 on 2026-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_identityprovider'),
        ('settings', '0082_alter_featureflagdefinition_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='kind',
            field=models.CharField(choices=[('conditional', 'Conditional access'), ('ip_restrictions', 'IP restrictions'), ('device_restrictions', 'Device restrictions'), ('location_restrictions', 'Location restrictions'), ('time_based', 'Time-based access'), ('session_duration', 'Session duration')], default='conditional', help_text='UI discriminator. Kind-specific pages filter on this; the policy engine inspects the underlying PolicyCondition rows regardless.', max_length=24),
        ),
        migrations.AddIndex(
            model_name='accesspolicy',
            index=models.Index(fields=['organization', 'kind'], name='access_poli_organiz_9c020e_idx'),
        ),
    ]
