import { registerResource } from "../index";

registerResource({
  key: "leads",
  module: "crm",
  label: "Lead",
  labelPlural: "Leads",
  endpoint: "/crm/leads/",
  columns: [
    { key: "first_name", label: "First Name", type: "text", sortable: true },
    { key: "last_name", label: "Last Name", type: "text", sortable: true },
    { key: "email", label: "Email", type: "text" },
    { key: "pipeline_stage", label: "Pipeline Stage", type: "badge" },
    { key: "status", label: "Status", type: "badge" },
    { key: "priority", label: "Priority", type: "badge" },
    { key: "source", label: "Source", type: "text" },
    { key: "score", label: "Score", type: "number" },
  ],
  filters: [
    { key: "search", label: "Search", type: "search", placeholder: "Search leads..." },
    {
      key: "pipeline_stage",
      label: "Pipeline Stage",
      type: "select",
      options: [
        { value: "INQUIRY", label: "Inquiry" },
        { value: "QUALIFIED", label: "Qualified" },
        { value: "SITE_VISIT", label: "Site Visit" },
        { value: "OFFER_MADE", label: "Offer Made" },
        { value: "RESERVATION", label: "Reservation" },
        { value: "SPA_ISSUED", label: "SPA Issued" },
        { value: "CLOSED", label: "Closed" },
      ],
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "ACTIVE", label: "Active" },
        { value: "WON", label: "Won" },
        { value: "LOST", label: "Lost" },
        { value: "DISQUALIFIED", label: "Disqualified" },
      ],
    },
    {
      key: "priority",
      label: "Priority",
      type: "select",
      options: [
        { value: "LOW", label: "Low" },
        { value: "MEDIUM", label: "Medium" },
        { value: "HIGH", label: "High" },
        { value: "URGENT", label: "Urgent" },
      ],
    },
  ],
  formFields: [
    { key: "first_name", label: "First Name", type: "text", required: true },
    { key: "last_name", label: "Last Name", type: "text", required: true },
    { key: "email", label: "Email", type: "text", required: true },
    { key: "phone", label: "Phone", type: "text" },
    { key: "company", label: "Company", type: "text" },
    { key: "nationality", label: "Nationality", type: "text" },
    {
      key: "lead_type",
      label: "Lead Type",
      type: "select",
      options: [
        { value: "BUYER", label: "Buyer" },
        { value: "TENANT", label: "Tenant" },
        { value: "INVESTOR", label: "Investor" },
      ],
    },
    {
      key: "pipeline_stage",
      label: "Pipeline Stage",
      type: "select",
      options: [
        { value: "INQUIRY", label: "Inquiry" },
        { value: "QUALIFIED", label: "Qualified" },
        { value: "SITE_VISIT", label: "Site Visit" },
        { value: "OFFER_MADE", label: "Offer Made" },
        { value: "RESERVATION", label: "Reservation" },
        { value: "SPA_ISSUED", label: "SPA Issued" },
        { value: "CLOSED", label: "Closed" },
      ],
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "ACTIVE", label: "Active" },
        { value: "WON", label: "Won" },
        { value: "LOST", label: "Lost" },
        { value: "DISQUALIFIED", label: "Disqualified" },
      ],
    },
    {
      key: "priority",
      label: "Priority",
      type: "select",
      options: [
        { value: "LOW", label: "Low" },
        { value: "MEDIUM", label: "Medium" },
        { value: "HIGH", label: "High" },
        { value: "URGENT", label: "Urgent" },
      ],
    },
    { key: "source", label: "Source", type: "relation_picker", optionsEndpoint: "/crm/sources/" },
    { key: "broker", label: "Broker", type: "relation_picker", optionsEndpoint: "/crm/brokers/" },
    { key: "assigned_to", label: "Assigned To", type: "relation_picker", optionsEndpoint: "/iam/users/" },
    { key: "budget_min", label: "Budget Min", type: "currency" },
    { key: "budget_max", label: "Budget Max", type: "currency" },
    {
      key: "payment_capability",
      label: "Payment Capability",
      type: "select",
      options: [
        { value: "CASH", label: "Cash" },
        { value: "MORTGAGE", label: "Mortgage" },
        { value: "INSTALLMENT", label: "Installment" },
        { value: "MIXED", label: "Mixed" },
        { value: "UNDETERMINED", label: "Undetermined" },
      ],
    },
    { key: "score", label: "Score", type: "number" },
    { key: "notes", label: "Notes", type: "textarea", gridSpan: 2 },
  ],
});
