# Generated by Django 5.2 on 2026-03-04 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0007_add_full_maintenance_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparableSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('sale_date', models.DateField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('property_type', models.CharField(blank=True, choices=[('land', 'Land Parcel'), ('building', 'Building'), ('mixed', 'Mixed-Use'), ('estate', 'Estate'), ('warehouse', 'Warehouse'), ('industrial', 'Industrial')], max_length=20)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proximity_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from reference property in km', max_digits=8, null=True)),
                ('source', models.CharField(choices=[('mls', 'MLS Listing'), ('public_records', 'Public Records'), ('broker', 'Broker Report'), ('auction', 'Auction'), ('other', 'Other')], default='public_records', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, help_text='Optional link to a property in the portfolio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparable_sales', to='properties.property')),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='ValuationAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(choices=[('tax_assessment', 'Tax Assessment'), ('insurance', 'Insurance Valuation'), ('dispute', 'Valuation Dispute')], default='tax_assessment', max_length=20)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('hearing_scheduled', 'Hearing Scheduled'), ('decided', 'Decided'), ('withdrawn', 'Withdrawn')], default='filed', max_length=20)),
                ('filed_date', models.DateField()),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('assessed_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('requested_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('decided_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('filing_reference', models.CharField(blank=True, max_length=100)),
                ('representative', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('upheld', 'Upheld'), ('reduced', 'Reduced'), ('increased', 'Increased'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_appeals', to='properties.property')),
                ('valuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='properties.propertyvaluation')),
            ],
            options={
                'ordering': ['-filed_date'],
            },
        ),
    ]
