# Generated by Django 5.2 on 2026-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('properties', '0010_assetcomponent_prop_ac_org_created_idx_and_more'),
        ('valuations', '0002_add_organization_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comparablesale',
            index=models.Index(fields=['organization', '-created_at'], name='val_cs_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='valuationappeal',
            index=models.Index(fields=['organization', 'status'], name='val_app_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='valuationappeal',
            index=models.Index(fields=['organization', '-created_at'], name='val_app_org_created_idx'),
        ),
    ]
