# Generated by Django 5.2 on 2026-03-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('finance', '0011_journalentry_journalline_ledgerentry_and_more'),
        ('procurement', '0002_vendor'),
        ('projects', '0013_projectmilestone_approval_required_and_more'),
        ('properties', '0008_inspection_compliance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='budget_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='budget_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='finance.budgetlineitem'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cost_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='budget_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requisitions', to='finance.budgetlineitem'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='cost_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requisitions', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procurement_vendors', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('evaluation', 'Under Evaluation'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('issue_date', models.DateField()),
                ('submission_deadline', models.DateField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_code', models.CharField(blank=True, max_length=100)),
                ('cost_code', models.CharField(blank=True, max_length=50)),
                ('selection_notes', models.TextField(blank=True)),
                ('selection_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='finance.budgetlineitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='projects.project')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='properties.property')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='procurement.purchaserequisition')),
                ('selected_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_rfqs', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestForQuotationQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=100)),
                ('quote_date', models.DateField()),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('quoted_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('warranty_terms', models.CharField(blank=True, max_length=255)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('compliance_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('technical_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('commercial_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('winner', 'Winner')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_quotes', to='accounts.organization')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='procurement.requestforquotation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_quotes', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-total_score', 'quoted_amount'],
                'unique_together': {('rfq', 'vendor')},
            },
        ),
    ]
