# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('finance', '0016_account_fin_acct_org_created_idx_and_more'),
        ('procurement', '0003_goodsreceipt_organization_purchaseorder_budget_code_and_more'),
        ('projects', '0018_project_proj_proj_org_status_idx_and_more'),
        ('properties', '0010_assetcomponent_prop_ac_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['organization', 'status'], name='proc_gr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['organization', '-created_at'], name='proc_gr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'status'], name='proc_po_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', '-created_at'], name='proc_po_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'status'], name='proc_pr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', '-created_at'], name='proc_pr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requestforquotation',
            index=models.Index(fields=['organization', 'status'], name='proc_rfq_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requestforquotation',
            index=models.Index(fields=['organization', '-created_at'], name='proc_rfq_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requestforquotationquote',
            index=models.Index(fields=['organization', 'status'], name='proc_rfqq_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='requestforquotationquote',
            index=models.Index(fields=['organization', '-submitted_at'], name='proc_rfqq_org_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['organization', '-created_at'], name='proc_vend_org_created_idx'),
        ),
    ]
