# Generated by Django 5.2 on 2026-03-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_organization_accounts_org_norm_name_trgm'),
        ('procurement', '0004_goodsreceipt_proc_gr_org_status_idx_and_more'),
        ('projects', '0020_project_gps_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProcurementWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_type', models.CharField(choices=[('project_procurement_dashboard', 'Project Procurement Dashboard'), ('vendor_allocation_workspace', 'Vendor Allocation Workspace')], max_length=48)),
                ('name', models.CharField(max_length=120)),
                ('menu_path', models.CharField(max_length=255)),
                ('menu_group', models.CharField(choices=[('dashboard', 'Dashboard'), ('vendor_management', 'Vendor Management')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_procurement_workspaces', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_workspaces', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'workspace_type'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='proc_pws_org_created_idx'), models.Index(fields=['project', 'menu_group'], name='proc_pws_proj_group_idx')],
                'unique_together': {('project', 'workspace_type')},
            },
        ),
    ]
