# Generated by Django 5.2 on 2026-03-18

import decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_remove_organization_accounts_org_norm_name_trgm"),
        ("procurement", "0005_projectprocurementworkspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcurementDemandInsight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_module",
                    models.CharField(
                        choices=[("crm", "CRM"), ("procurement", "Procurement"), ("analytics", "Analytics")],
                        default="crm",
                        max_length=20,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("bulk_buyer_demand", "Bulk Buyer Demand"),
                            ("furnishing_package", "Furnishing Package Trigger"),
                            ("add_on_package", "Add-On Package Trigger"),
                        ],
                        default="bulk_buyer_demand",
                        max_length=32,
                    ),
                ),
                ("area_name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("demand_share_percent", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=6)),
                ("lead_count", models.PositiveIntegerField(default=0)),
                ("qualified_lead_count", models.PositiveIntegerField(default=0)),
                ("won_lead_count", models.PositiveIntegerField(default=0)),
                ("bulk_buyer_lead_count", models.PositiveIntegerField(default=0)),
                ("window_days", models.PositiveIntegerField(default=90)),
                ("threshold_percent", models.DecimalField(decimal_places=2, default=decimal.Decimal("25.00"), max_digits=6)),
                ("min_bulk_leads", models.PositiveIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("first_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="procurement_demand_insights", to="accounts.organization"),
                ),
            ],
            options={
                "ordering": ["-demand_share_percent", "-updated_at"],
                "indexes": [
                    models.Index(fields=["organization", "source_module", "insight_type", "is_active"], name="proc_di_org_type_act_idx"),
                    models.Index(fields=["organization", "-updated_at"], name="proc_di_org_updated_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "insight_type", "area_name"), name="unique_org_proc_demand_insight"),
                ],
            },
        ),
    ]
