# Generated by Django 5.2.12 on 2026-03-26 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_boq_cost_code_bridge'),
        ('procurement', '0006_procurementdemandinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='bom_item',
            field=models.ForeignKey(blank=True, help_text='Links this PO line item back to a specific BOQ item for traceability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='inventory.bomitem'),
        ),
    ]
