# Generated by Django 5.2.12 on 2026-03-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_management', '0011_seed_celery_beat_health_safety_compliance_workflows'),
        ('inventory', '0018_boq_lifecycle_and_rates'),
        ('procurement', '0007_po_item_bom_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='facility_incident',
            field=models.ForeignKey(blank=True, help_text='Links to facility incident that triggered this PR.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requisitions', to='facility_management.facilityincident'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='source_module',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('project', 'Project (Task/Milestone)'), ('construction', 'Construction (BOQ/Work Package)'), ('facility', 'Facility Management (Maintenance)'), ('inventory', 'Inventory (Reorder Threshold)')], default='manual', help_text='Which module originated this requisition.', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='bom_item',
            field=models.ForeignKey(blank=True, help_text='Links this PR line item to a specific BOQ item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_items', to='inventory.bomitem'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Links to a specific inventory item for reorder-triggered PRs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_items', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rfq_issued', 'RFQ Issued'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('ordered', 'Ordered')], default='draft', max_length=20),
        ),
    ]
