# Generated by Django 5.2.12 on 2026-03-26 11:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_pr_source_module_and_boq_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='advance_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated or manually set advance amount.', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='advance_payment_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance payment as % of total (e.g. 20% mobilization).', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='early_payment_discount_days',
            field=models.PositiveIntegerField(default=0, help_text='Days within which early payment discount applies.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='early_payment_discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount % for early payment (e.g. 2/10 Net 30 → 2%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_due_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days after invoice date for payment.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('letter_of_credit', 'Letter of Credit'), ('escrow', 'Escrow'), ('other', 'Other')], default='bank_transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='retention_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retention % held back per payment (e.g. 5%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(blank=True, help_text="Free-text summary, e.g. 'Net 30'", max_length=255),
        ),
    ]
