# Generated by Django 5.2.12 on 2026-03-26 18:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_boq_lifecycle_and_rates'),
        ('procurement', '0009_po_structured_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='average_quote_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running average of quoted amounts across all RFQs.', max_digits=15),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_rfqs_participated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_rfqs_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='win_rate_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of RFQs won out of total participated.', max_digits=5),
        ),
        migrations.CreateModel(
            name='RFQLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_of_measure', models.CharField(default='ea', max_length=50)),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Budget estimate rate for comparison.', max_digits=15, null=True)),
                ('specification', models.TextField(blank=True, help_text='Technical specification or requirement.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bom_item', models.ForeignKey(blank=True, help_text='Links to specific BOQ item for traceability.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_line_items', to='inventory.bomitem')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.requestforquotation')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RFQQuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: rfq_line_item.quantity × quoted_unit_price', max_digits=15)),
                ('delivery_days', models.PositiveIntegerField(default=0, help_text='Delivery lead time for this item.')),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='procurement.requestforquotationquote')),
                ('rfq_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_responses', to='procurement.rfqlineitem')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('quote', 'rfq_line_item')},
            },
        ),
    ]
