# Generated by Django 5.2.12 on 2026-03-26 18:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('procurement', '0010_rfq_line_items_and_vendor_location'),
        ('projects', '0055_contracts_and_agreements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, help_text='Auto-generated as CTR-##### when blank.', max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('contract_type', models.CharField(choices=[('construction', 'Construction Contract'), ('supply', 'Supply Agreement'), ('service', 'Service Agreement'), ('framework', 'Framework Agreement'), ('consultancy', 'Consultancy Agreement'), ('lease', 'Equipment Lease'), ('subcontract', 'Subcontract'), ('jv', 'Joint Venture Agreement'), ('other', 'Other')], default='construction', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('negotiation', 'Under Negotiation'), ('pending_approval', 'Pending Approval'), ('executed', 'Executed / Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('original_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('revised_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original + approved amendments.', max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('is_price_locked', models.BooleanField(default=False, help_text='Prices locked for the contract duration.')),
                ('price_escalation_clause', models.TextField(blank=True, help_text="e.g. 'CPI-linked annual escalation of 5% max'.")),
                ('locked_rates', models.JSONField(blank=True, default=list, help_text='[{"item":"Cement OPC 42.5","unit":"bag","rate":6500,"valid_until":"2027-03-31"}]')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, help_text='Auto-renewal date for framework agreements.', null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=30, help_text='Days notice required for termination.')),
                ('payment_terms_summary', models.CharField(blank=True, help_text="e.g. 'Net 30, 5% retention'.", max_length=255)),
                ('advance_payment_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('retention_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('defects_liability_months', models.PositiveIntegerField(default=12)),
                ('sla_response_hours', models.PositiveIntegerField(blank=True, help_text='Max hours for vendor to respond to issues.', null=True)),
                ('sla_resolution_hours', models.PositiveIntegerField(blank=True, help_text='Max hours for vendor to resolve issues.', null=True)),
                ('sla_uptime_pct', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 99.5% uptime guarantee.', max_digits=5, null=True)),
                ('sla_penalty_per_breach', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty amount per SLA breach.', max_digits=12)),
                ('sla_notes', models.TextField(blank=True)),
                ('insurance_required', models.BooleanField(default=True)),
                ('insurance_minimum_cover', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('performance_bond_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('liquidated_damages_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of contract value per day/week of delay.', max_digits=5)),
                ('liquidated_damages_cap_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Maximum LD as % of contract value.', max_digits=5)),
                ('signed_by_org', models.CharField(blank=True, max_length=255)),
                ('signed_by_vendor', models.CharField(blank=True, max_length=255)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('witness', models.CharField(blank=True, max_length=255)),
                ('scope_of_work', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('dispute_resolution', models.TextField(blank=True, help_text='e.g. Arbitration under Lagos Arbitration Law.')),
                ('governing_law', models.CharField(blank=True, default='Laws of the Federal Republic of Nigeria', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.project')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='PO that originated this contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='procurement.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.CharField(help_text='e.g. AMD-01, AMD-02', max_length=50)),
                ('amendment_type', models.CharField(choices=[('scope_change', 'Scope Change'), ('price_adjustment', 'Price Adjustment'), ('time_extension', 'Time Extension'), ('terms_change', 'Terms & Conditions Change'), ('supplemental', 'Supplemental Agreement')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('value_change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Positive = increase, negative = decrease.', max_digits=15)),
                ('time_extension_days', models.IntegerField(default=0)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='procurement.contract')),
            ],
            options={
                'ordering': ['amendment_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_number', models.CharField(help_text='e.g. 12.1, 15.3', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('payment', 'Payment Terms'), ('performance', 'Performance Requirements'), ('warranty', 'Warranty & Defects'), ('insurance', 'Insurance & Indemnity'), ('termination', 'Termination'), ('dispute', 'Dispute Resolution'), ('confidentiality', 'Confidentiality'), ('force_majeure', 'Force Majeure'), ('variation', 'Variations & Changes'), ('compliance', 'Regulatory Compliance'), ('health_safety', 'Health & Safety'), ('ip', 'Intellectual Property'), ('other', 'Other')], default='other', max_length=20)),
                ('body', models.TextField(help_text='Full clause text.')),
                ('is_critical', models.BooleanField(default=False, help_text='Flags clauses requiring special attention.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='procurement.contract')),
            ],
            options={
                'ordering': ['sort_order', 'clause_number'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'status'], name='proc_ctr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'contract_type'], name='proc_ctr_org_type_idx'),
        ),
    ]
