# Generated by Django 5.2.12 on 2026-03-26 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_management', '0011_seed_celery_beat_health_safety_compliance_workflows'),
        ('procurement', '0011_contracts_and_agreements'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='facility_incident',
            field=models.ForeignKey(blank=True, help_text='Links delivery to a facility maintenance incident.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='facility_management.facilityincident'),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='inspected_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='inspected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='quality_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='quality_status',
            field=models.CharField(choices=[('pending', 'Pending Inspection'), ('passed', 'Passed'), ('failed', 'Failed'), ('conditional', 'Conditional Accept')], default='pending', max_length=20),
        ),
    ]
