# Generated by Django 5.2.12 on 2026-03-27 02:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('finance', '0034_bill_match_status_billlineitem_po_item'),
        ('procurement', '0012_grn_quality_and_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='match_status',
            field=models.CharField(blank=True, default='', help_text='3-way match result: full_match, partial_match, variance, mismatch, no_grn, pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ThreeWayMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.CharField(choices=[('full_match', 'Full Match'), ('partial_match', 'Partial Match'), ('variance', 'Variance Detected'), ('mismatch', 'Mismatch'), ('no_grn', 'No Goods Receipt'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('po_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('grn_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('po_invoice_variance_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('grn_invoice_variance_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Tolerance % used for this match.', max_digits=5)),
                ('issues', models.JSONField(blank=True, default=list, help_text='["PO vs Invoice variance: 7.2%"]')),
                ('line_item_matches', models.JSONField(blank=True, default=list, help_text='[{"po_item_id","description","po_qty","po_amount","grn_qty","bill_qty","bill_amount","status"}]')),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='finance.bill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_way_matches', to='accounts.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['-match_date'],
                'indexes': [models.Index(fields=['organization', 'match_status'], name='proc_3wm_org_status_idx')],
            },
        ),
    ]
