# Generated by Django 5.2.12 on 2026-03-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('procurement', '0013_purchaseorder_match_status_threewaymatchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('materials', 'Materials'), ('contractor', 'Contractor'), ('consultant', 'Consultant'), ('other', 'Other')], default='other', help_text='Legacy fixed category. Use vendor_category for org-configurable classification.', max_length=20),
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_categories', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical classification (e.g. Materials > Concrete).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='procurement.vendorcategory')),
            ],
            options={
                'verbose_name_plural': 'Vendor Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_category',
            field=models.ForeignKey(blank=True, help_text='Org-configurable category with sub-categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='procurement.vendorcategory'),
        ),
    ]
