# Generated by Django 5.2.12 on 2026-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_alter_vendor_category_vendorcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Manufacturer batch/lot number.', max_length=100),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for perishable materials.', null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Warehouse bay or storage location.', max_length=255),
        ),
    ]
