# Generated by Django 5.2.12 on 2026-03-28 19:28

import apps.procurement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_goodsreceiptitem_batch_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of unit price at time of receipt.', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='GoodsReceiptPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.procurement.models.grn_photo_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('photo_type', models.CharField(choices=[('delivery', 'Proof of Delivery'), ('damage', 'Damage Evidence'), ('grade', 'Material Grade Tag'), ('label', 'Label / Certificate'), ('other', 'Other')], default='delivery', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='procurement.goodsreceipt')),
                ('receipt_item', models.ForeignKey(blank=True, help_text='Link photo to a specific line item (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='procurement.goodsreceiptitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
