# Generated by Django 5.2 on 2026-02-28 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_bill_bill_number'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='procurement.purchaseorder'),
        ),
    ]
