# Generated by Django 5.2 on 2026-03-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('finance', '0005_remove_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('sub_type', models.CharField(choices=[('current_asset', 'Current Asset'), ('fixed_asset', 'Fixed Asset'), ('other_asset', 'Other Asset'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long-Term Liability'), ('owners_equity', "Owner's Equity"), ('retained_earnings', 'Retained Earnings'), ('operating_revenue', 'Operating Revenue'), ('other_revenue', 'Other Revenue'), ('operating_expense', 'Operating Expense'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('other_expense', 'Other Expense')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.account')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
