# Generated by Django 5.2 on 2026-03-01 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('finance', '0007_seed_default_accounts'),
        ('settings', '0006_alter_rolepermission_sub_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billlineitem',
            name='account',
            field=models.ForeignKey(blank=True, help_text='GL account this expense is coded to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='settings.costcenter'),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='settings.department'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='annual', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overspend_tolerance_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentage above budget before critical alert (e.g. 10.00 = 10%)', max_digits=5)),
                ('warning_threshold_pct', models.DecimalField(decimal_places=2, default=80, help_text='Percentage of budget consumed before warning alert (e.g. 80.00 = 80%)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.organization')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(help_text='GL account this budget line allocates funds to', on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='finance.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.budget')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='settings.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='settings.department')),
            ],
            options={
                'ordering': ['sort_order', 'account__code'],
                'unique_together': {('budget', 'account', 'department', 'cost_center')},
            },
        ),
        migrations.CreateModel(
            name='ReforecastSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Auto-generated explanation of why reforecast was suggested')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reforecasts', to='finance.budget')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReforecastLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('suggested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_spent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delta', models.DecimalField(decimal_places=2, help_text='suggested_amount - current_amount', max_digits=15)),
                ('budget_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reforecast_items', to='finance.budgetlineitem')),
                ('reforecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.reforecastsuggestion')),
            ],
            options={
                'ordering': ['budget_line_item__sort_order'],
            },
        ),
    ]
