# Generated by Django 5.2 on 2026-03-02 16:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('finance', '0009_seed_celery_beat_budget_digest'),
        ('projects', '0004_phase6_project_compliance_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('investor_type', models.CharField(choices=[('individual', 'Individual'), ('institutional', 'Institutional'), ('family_office', 'Family Office'), ('fund', 'Fund'), ('corporate', 'Corporate')], default='individual', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('entity_name', models.CharField(blank=True, help_text='Legal entity name if different from investor name', max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage (0.00 - 100.00)', max_digits=5)),
                ('capital_committed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total capital committed by investor', max_digits=15)),
                ('capital_contributed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual capital contributed to date', max_digits=15)),
                ('total_capital_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative capital distributions received', max_digits=15)),
                ('total_profit_distributed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative profit distributions received', max_digits=15)),
                ('custom_profit_split_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Override profit split % for this investor (if different from project default)', max_digits=5, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_investments', to='finance.investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'sort_order', 'investor__name'],
                'unique_together': {('project', 'investor')},
            },
        ),
        migrations.CreateModel(
            name='CapitalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contribution_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='finance.projectinvestor')),
            ],
            options={
                'ordering': ['-contribution_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterfallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_profit_split_pct', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Percentage of Tier 2 profits to investors (e.g., 80.00 for 80/20 split)', max_digits=5)),
                ('sponsor_profit_split_pct', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percentage of Tier 2 profits to sponsor/GP', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_config', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WaterfallDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('distribution_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount available for distribution', max_digits=15)),
                ('tier1_capital_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount allocated to Tier 1 (return of capital)', max_digits=15)),
                ('tier2_profit_split', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount allocated to Tier 2 (profit split)', max_digits=15)),
                ('sponsor_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to sponsor/GP (from Tier 2)', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_distributions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='projects.project')),
            ],
            options={
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='DistributionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier1_capital_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tier 1: Return of capital', max_digits=15)),
                ('tier2_profit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tier 2: Profit split', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total for this investor (tier1 + tier2)', max_digits=15)),
                ('capital_returned_to_date', models.DecimalField(decimal_places=2, help_text='Cumulative capital returned after this distribution', max_digits=15)),
                ('profit_distributed_to_date', models.DecimalField(decimal_places=2, help_text='Cumulative profit distributed after this distribution', max_digits=15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project_investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='finance.projectinvestor')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.waterfalldistribution')),
            ],
            options={
                'ordering': ['distribution', 'sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='waterfalldistribution',
            index=models.Index(fields=['project', 'status', 'distribution_date'], name='finance_wat_project_c5f693_idx'),
        ),
        migrations.AddIndex(
            model_name='distributionlineitem',
            index=models.Index(fields=['distribution', 'project_investor'], name='finance_dis_distrib_242231_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='distributionlineitem',
            unique_together={('distribution', 'project_investor')},
        ),
    ]
