# Generated by Django 5.2 on 2026-03-04 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_subscription_tier'),
        ('finance', '0011_journalentry_journalline_ledgerentry_and_more'),
        ('procurement', '0003_goodsreceipt_organization_purchaseorder_budget_code_and_more'),
        ('projects', '0013_projectmilestone_approval_required_and_more'),
        ('properties', '0008_inspection_compliance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPVEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('company', 'Company'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('fund', 'Fund'), ('llc', 'Limited Liability Company'), ('other', 'Other')], default='company', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('dissolved', 'Dissolved'), ('under_formation', 'Under Formation')], default='active', max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registered_address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('jurisdiction', models.CharField(blank=True, max_length=200)),
                ('authorized_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('paid_up_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose/objective of the SPV')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spv_entities', to='accounts.organization')),
                ('parent_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='finance.spventity')),
            ],
            options={
                'verbose_name': 'SPV Entity',
                'verbose_name_plural': 'SPV Entities',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('plan_type', models.CharField(choices=[('fixed_installment', 'Fixed Installment'), ('milestone_based', 'Milestone-Based'), ('percentage_based', 'Percentage-Based'), ('custom', 'Custom Schedule')], default='fixed_installment', max_length=20)),
                ('direction', models.CharField(choices=[('receivable', 'Receivable (Customer owes us)'), ('payable', 'Payable (We owe vendor)')], default='receivable', max_length=15)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('one_time', 'One-Time')], default='monthly', max_length=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('number_of_installments', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_plans', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='finance.customer')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='finance.investor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='projects.project')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='properties.unit')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='procurement.vendor')),
                ('spv_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plans', to='finance.spventity')),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('scheduled_date', models.DateField()),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('percentage_of_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('due', 'Due'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='projects.projectmilestone')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.paymentplan')),
            ],
            options={
                'verbose_name': 'Payment Installment',
                'ordering': ['payment_plan', 'installment_number'],
                'unique_together': {('payment_plan', 'installment_number')},
            },
        ),
    ]
