# Generated by Django 5.2 on 2026-03-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_spventity_paymentplan_paymentinstallment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('institutional', 'Institutional'), ('family_office', 'Family Office'), ('fund', 'Fund'), ('corporate', 'Corporate'), ('jv_partner', 'JV Partner')], default='individual', max_length=20),
        ),
    ]
