# Generated by Django 5.2 on 2026-03-07 06:01

import apps.settings.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_investor_investor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='currency',
            field=models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3),
        ),
    ]
