# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('finance', '0015_add_organization_fk'),
        ('procurement', '0003_goodsreceipt_organization_purchaseorder_budget_code_and_more'),
        ('projects', '0017_add_organization_fk'),
        ('properties', '0010_assetcomponent_prop_ac_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', '-created_at'], name='fin_acct_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['organization', 'status'], name='fin_bill_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['organization', '-created_at'], name='fin_bill_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['organization', 'status'], name='fin_budg_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', '-created_at'], name='fin_cust_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['organization', '-created_at'], name='fin_invr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='fin_inv_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', '-created_at'], name='fin_inv_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['organization', 'status'], name='fin_pplan_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['organization', '-created_at'], name='fin_pplan_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectinvestor',
            index=models.Index(fields=['organization', '-created_at'], name='fin_pinv_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='spventity',
            index=models.Index(fields=['organization', 'status'], name='fin_spv_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='spventity',
            index=models.Index(fields=['organization', '-created_at'], name='fin_spv_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='waterfalldistribution',
            index=models.Index(fields=['organization', 'status'], name='fin_wfall_org_status_idx'),
        ),
    ]
