# Generated by Django 5.2 on 2026-03-10 12:30

from django.db import migrations, models
import django.db.models.deletion


def bootstrap_existing_project_financial_framework(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectLedger = apps.get_model("finance", "ProjectLedger")
    ProjectCostCenter = apps.get_model("finance", "ProjectCostCenter")
    ProjectRevenueCenter = apps.get_model("finance", "ProjectRevenueCenter")

    for project in Project.objects.all().iterator():
        suffix = f"{project.id:06d}"
        ProjectLedger.objects.get_or_create(
            project_id=project.id,
            defaults={
                "organization_id": project.organization_id,
                "code": f"PRJ-LDG-{suffix}",
                "name": f"Project Ledger - {project.name}",
            },
        )
        ProjectCostCenter.objects.get_or_create(
            project_id=project.id,
            defaults={
                "organization_id": project.organization_id,
                "code": f"PRJ-COST-{suffix}",
                "name": f"Project Cost Center - {project.name}",
            },
        )
        ProjectRevenueCenter.objects.get_or_create(
            project_id=project.id,
            defaults={
                "organization_id": project.organization_id,
                "code": f"PRJ-REV-{suffix}",
                "name": f"Project Revenue Center - {project.name}",
            },
        )


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_account_fin_acct_org_created_idx_and_more"),
        ("projects", "0019_project_number_of_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCostCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_cost_centers", to="accounts.organization"),
                ),
                (
                    "project",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="project_cost_center", to="projects.project"),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.CreateModel(
            name="ProjectLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_ledgers", to="accounts.organization"),
                ),
                (
                    "project",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="project_ledger", to="projects.project"),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.CreateModel(
            name="ProjectRevenueCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_revenue_centers", to="accounts.organization"),
                ),
                (
                    "project",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="project_revenue_center", to="projects.project"),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.AddIndex(
            model_name="projectcostcenter",
            index=models.Index(fields=["organization", "-created_at"], name="fin_pcc_org_created_idx"),
        ),
        migrations.AddIndex(
            model_name="projectledger",
            index=models.Index(fields=["organization", "-created_at"], name="fin_pldg_org_created_idx"),
        ),
        migrations.AddIndex(
            model_name="projectrevenuecenter",
            index=models.Index(fields=["organization", "-created_at"], name="fin_prc_org_created_idx"),
        ),
        migrations.RunPython(bootstrap_existing_project_financial_framework, reverse_noop),
    ]
