# Generated by Django 5.2 on 2026-03-12 06:10

from datetime import date, timedelta
from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def bootstrap_existing_project_budgets(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Budget = apps.get_model("finance", "Budget")

    for project in Project.objects.all().iterator():
        start_date = project.start_date or date.today()
        end_date = project.target_end_date
        if not end_date or end_date < start_date:
            end_date = start_date + timedelta(days=365)
        total_amount = project.budget if project.budget is not None else Decimal("0.00")
        suffix = f"{project.id:06d}"

        Budget.objects.get_or_create(
            project_id=project.id,
            defaults={
                "organization_id": project.organization_id,
                "name": f"Project Budget - {project.name} ({suffix})",
                "status": "draft",
                "period_type": "annual",
                "start_date": start_date,
                "end_date": end_date,
                "total_amount": total_amount,
                "notes": "Auto-created project budget container.",
            },
        )


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0017_project_financial_framework"),
        ("projects", "0020_project_gps_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="project",
            field=models.OneToOneField(
                blank=True,
                help_text="Linked project when this budget is a project budget container.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_container",
                to="projects.project",
            ),
        ),
        migrations.RunPython(bootstrap_existing_project_budgets, reverse_noop),
    ]
