# Generated by Django 5.2 on 2026-03-12 06:35

from decimal import Decimal

from django.db import migrations

PROJECT_BUDGET_CATEGORY_TEMPLATES = [
    {
        "account_code": "PRJ-LAND",
        "category_name": "Land acquisition",
        "sub_type": "operating_expense",
    },
    {
        "account_code": "PRJ-DESIGN",
        "category_name": "Design",
        "sub_type": "operating_expense",
    },
    {
        "account_code": "PRJ-CONSTR",
        "category_name": "Construction",
        "sub_type": "operating_expense",
    },
    {
        "account_code": "PRJ-PERMIT",
        "category_name": "Permits & regulatory",
        "sub_type": "operating_expense",
    },
    {
        "account_code": "PRJ-MKTSALES",
        "category_name": "Marketing & sales",
        "sub_type": "operating_expense",
    },
    {
        "account_code": "PRJ-FINCHRG",
        "category_name": "Finance charges",
        "sub_type": "other_expense",
    },
    {
        "account_code": "PRJ-CONTG",
        "category_name": "Contingency",
        "sub_type": "operating_expense",
    },
]


def initialize_project_budget_categories(apps, schema_editor):
    Budget = apps.get_model("finance", "Budget")
    Account = apps.get_model("finance", "Account")
    BudgetLineItem = apps.get_model("finance", "BudgetLineItem")

    project_budgets = Budget.objects.filter(project__isnull=False).select_related("organization")

    for budget in project_budgets.iterator():
        for sort_order, template in enumerate(PROJECT_BUDGET_CATEGORY_TEMPLATES):
            account, _ = Account.objects.get_or_create(
                organization_id=budget.organization_id,
                code=template["account_code"],
                defaults={
                    "name": template["category_name"],
                    "account_type": "expense",
                    "sub_type": template["sub_type"],
                    "is_system": True,
                    "is_active": True,
                },
            )

            BudgetLineItem.objects.get_or_create(
                budget_id=budget.id,
                account_id=account.id,
                department_id=None,
                cost_center_id=None,
                defaults={
                    "budgeted_amount": Decimal("0.00"),
                    "notes": template["category_name"],
                    "sort_order": sort_order,
                },
            )


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0018_budget_project_container"),
    ]

    operations = [
        migrations.RunPython(initialize_project_budget_categories, reverse_noop),
    ]
