# Generated by Django 5.2 on 2026-03-12 09:10

from django.db import migrations, models
import django.db.models.deletion


PROJECT_COA_MAPPING_TEMPLATES = [
    {
        "field_name": "construction_cost_account",
        "account_code_prefix": "PRJ-COA-CC",
        "account_name": "Project Construction Costs",
        "account_type": "expense",
        "sub_type": "cost_of_goods_sold",
    },
    {
        "field_name": "capex_account",
        "account_code_prefix": "PRJ-COA-CX",
        "account_name": "Project Capex",
        "account_type": "asset",
        "sub_type": "fixed_asset",
    },
    {
        "field_name": "development_expense_account",
        "account_code_prefix": "PRJ-COA-DE",
        "account_name": "Project Development Expenses",
        "account_type": "expense",
        "sub_type": "operating_expense",
    },
    {
        "field_name": "sales_revenue_account",
        "account_code_prefix": "PRJ-COA-SR",
        "account_name": "Project Sales Revenue",
        "account_type": "revenue",
        "sub_type": "operating_revenue",
    },
]


def bootstrap_existing_project_account_mappings(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Account = apps.get_model("finance", "Account")
    ProjectAccountMapping = apps.get_model("finance", "ProjectAccountMapping")

    for project in Project.objects.all().iterator():
        suffix = f"{project.id:06d}"
        mapped_accounts = {}
        for template in PROJECT_COA_MAPPING_TEMPLATES:
            account, _ = Account.objects.get_or_create(
                organization_id=project.organization_id,
                code=f"{template['account_code_prefix']}-{suffix}",
                defaults={
                    "name": template["account_name"],
                    "account_type": template["account_type"],
                    "sub_type": template["sub_type"],
                    "is_system": True,
                    "is_active": True,
                },
            )
            mapped_accounts[template["field_name"]] = account

        mapping, created = ProjectAccountMapping.objects.get_or_create(
            project_id=project.id,
            defaults={
                "organization_id": project.organization_id,
                **{f"{field_name}_id": account.id for field_name, account in mapped_accounts.items()},
            },
        )
        if created:
            continue

        update_fields = []
        if mapping.organization_id != project.organization_id:
            mapping.organization_id = project.organization_id
            update_fields.append("organization")

        for field_name, account in mapped_accounts.items():
            if getattr(mapping, f"{field_name}_id") != account.id:
                setattr(mapping, f"{field_name}_id", account.id)
                update_fields.append(field_name)

        if update_fields:
            mapping.save(update_fields=update_fields)


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0019_initialize_project_budget_categories"),
        ("projects", "0020_project_gps_coordinates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAccountMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capex_account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_capex_mappings", to="finance.account"),
                ),
                (
                    "construction_cost_account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_construction_cost_mappings", to="finance.account"),
                ),
                (
                    "development_expense_account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_development_expense_mappings", to="finance.account"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="project_account_mappings", to="accounts.organization"),
                ),
                (
                    "project",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="chart_of_accounts_mapping", to="projects.project"),
                ),
                (
                    "sales_revenue_account",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="project_sales_revenue_mappings", to="finance.account"),
                ),
            ],
            options={
                "ordering": ["project"],
            },
        ),
        migrations.AddIndex(
            model_name="projectaccountmapping",
            index=models.Index(fields=["organization", "-created_at"], name="fin_pam_org_created_idx"),
        ),
        migrations.RunPython(bootstrap_existing_project_account_mappings, reverse_noop),
    ]
