# Generated by Django 5.2 on 2026-03-12 13:45

from django.db import migrations, models
import django.db.models.deletion


PROJECT_FINANCE_ARTIFACT_TEMPLATES = [
    {
        "artifact_type": "project_budget_dashboard",
        "name": "Project Budget Dashboard",
        "menu_path": "/finance/budgets",
        "menu_group": "budget",
    },
    {
        "artifact_type": "cashflow_forecast",
        "name": "Cashflow Forecast",
        "menu_path": "/finance/dashboard",
        "menu_group": "forecast",
    },
    {
        "artifact_type": "cost_tracker",
        "name": "Cost Tracker",
        "menu_path": "/finance",
        "menu_group": "cost",
    },
    {
        "artifact_type": "variance_analysis",
        "name": "Variance Analysis",
        "menu_path": "/finance/variance-analysis",
        "menu_group": "analytics",
    },
]


def bootstrap_existing_project_finance_artifacts(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectFinanceArtifact = apps.get_model("finance", "ProjectFinanceArtifact")

    for project in Project.objects.all().iterator():
        for template in PROJECT_FINANCE_ARTIFACT_TEMPLATES:
            ProjectFinanceArtifact.objects.get_or_create(
                project_id=project.id,
                artifact_type=template["artifact_type"],
                defaults={
                    "organization_id": project.organization_id,
                    "name": template["name"],
                    "menu_path": template["menu_path"],
                    "menu_group": template["menu_group"],
                    "is_active": True,
                },
            )


def reverse_noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0020_project_account_mapping"),
        ("projects", "0020_project_gps_coordinates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFinanceArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("project_budget_dashboard", "Project Budget Dashboard"),
                            ("cashflow_forecast", "Cashflow Forecast"),
                            ("cost_tracker", "Cost Tracker"),
                            ("variance_analysis", "Variance Analysis"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("menu_path", models.CharField(max_length=255)),
                (
                    "menu_group",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("forecast", "Forecast"),
                            ("cost", "Cost"),
                            ("analytics", "Analytics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_finance_artifacts",
                        to="accounts.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_artifacts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "artifact_type"],
                "unique_together": {("project", "artifact_type")},
            },
        ),
        migrations.AddIndex(
            model_name="projectfinanceartifact",
            index=models.Index(fields=["organization", "-created_at"], name="fin_pfa_org_created_idx"),
        ),
        migrations.AddIndex(
            model_name="projectfinanceartifact",
            index=models.Index(fields=["project", "menu_group"], name="fin_pfa_proj_group_idx"),
        ),
        migrations.RunPython(bootstrap_existing_project_finance_artifacts, reverse_noop),
    ]
