# Generated by Django 5.2 on 2026-03-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0021_project_finance_artifacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="journal_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
