# Generated by Django 5.2.12 on 2026-03-17 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_activesubscriptionaddon'),
        ('finance', '0023_paymentvoucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('funding_account_label', models.CharField(blank=True, help_text="Display label, e.g. 'Main Operations - Zenith Bank'", max_length=200)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_runs', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_payment_runs', to=settings.AUTH_USER_MODEL)),
                ('funding_account', models.ForeignKey(blank=True, help_text='GL account from which funds will be drawn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_runs', to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_runs', to='accounts.organization')),
                ('vouchers', models.ManyToManyField(blank=True, related_name='payment_runs', to='finance.paymentvoucher')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='fin_pr_org_status_idx'), models.Index(fields=['organization', '-created_at'], name='fin_pr_org_created_idx')],
            },
        ),
    ]
