# Generated by Django 5.2.12 on 2026-03-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_payment_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='priority',
            field=models.CharField(choices=[('standard', 'Standard'), ('high', 'High')], default='standard', max_length=10),
        ),
    ]
