# Generated by Django 5.2.12 on 2026-03-17 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_voucher_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='funding_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of funding account balance at time of review', max_digits=15, null=True),
        ),
    ]
