# Generated by Django 5.2.12 on 2026-03-17 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_activesubscriptionaddon'),
        ('finance', '0026_payment_run_approval_balance'),
        ('procurement', '0005_projectprocurementworkspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank NIP or internal transfer reference', max_length=200)),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('settled', 'Settled'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='successful', max_length=20)),
                ('payment_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('payer_account', models.CharField(blank=True, help_text='Funding bank account used', max_length=200)),
                ('payee_account', models.CharField(blank=True, help_text='Vendor bank account credited', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='accounts.organization')),
                ('payment_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='finance.paymentrun')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='procurement.vendor')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='finance.paymentvoucher')),
            ],
            options={
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['organization', 'status'], name='fin_rcpt_org_status_idx'), models.Index(fields=['organization', '-payment_date'], name='fin_rcpt_org_date_idx')],
            },
        ),
    ]
