# Generated by Django 5.2.12 on 2026-03-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='vouchers',
            field=models.ManyToManyField(blank=True, help_text='All vouchers covered by this receipt', related_name='receipt_allocations', to='finance.paymentvoucher'),
        ),
    ]
