# Generated by Django 5.2.12 on 2026-03-17 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_banking_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='api_key_ref',
            field=models.CharField(blank=True, help_text='Reference to stored API key (do not store key directly)', max_length=200),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='api_provider',
            field=models.CharField(blank=True, help_text='Integration provider: mono, flutterwave, manual', max_length=30),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Users with transfer permissions on this account', related_name='authorized_bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='daily_transfer_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily outflow for payment runs', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Real-time balance webhook (Mono, Flutterwave)', max_length=500),
        ),
    ]
