# Generated by Django 5.2.12 on 2026-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_bank_account_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='support_ticketing_enabled',
            field=models.BooleanField(default=False, help_text='Enabled automatically after customer onboarding completes.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='support_ticketing_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
