# Generated by Django 5.2.12 on 2026-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_customer_support_ticketing_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('voided', 'Voided'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='draft', max_length=20),
        ),
    ]
