# Generated by Django 5.2.12 on 2026-03-26 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_alter_paymentvoucher_status'),
        ('inventory', '0017_boq_consumed_quantity'),
        ('projects', '0054_bill_project_and_boq_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Links bill to a project for cost tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='projects.project'),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='bom_item',
            field=models.ForeignKey(blank=True, help_text='Links this bill line to a specific BOQ item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='inventory.bomitem'),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='cost_code_budget',
            field=models.ForeignKey(blank=True, help_text='Links this expense to a project cost code for actual cost tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='projects.costcodebudget'),
        ),
    ]
