# Generated by Django 5.2.12 on 2026-03-27 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_bill_project_and_boq_bridge'),
        ('procurement', '0012_grn_quality_and_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='match_status',
            field=models.CharField(blank=True, default='', help_text='3-way match result: full_match, partial_match, variance, mismatch, no_grn, pending', max_length=20),
        ),
        migrations.AddField(
            model_name='billlineitem',
            name='po_item',
            field=models.ForeignKey(blank=True, help_text='Links this bill line to a specific PO line item for 3-way matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='procurement.purchaseorderitem'),
        ),
    ]
