# Generated by Django 5.2.12 on 2026-05-13 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_userprofile_calendar_default_reminder_minutes'),
        ('finance', '0034_bill_match_status_billlineitem_po_item'),
        ('hr', '0024_positionbudget_revision_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('bill', 'Bill'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('adjustment', 'Adjustment'), ('closing', 'Closing Entry'), ('opening', 'Opening Balance'), ('payroll', 'Payroll')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('bill', 'Bill'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('adjustment', 'Adjustment'), ('closing', 'Closing Entry'), ('opening', 'Opening Balance'), ('payroll', 'Payroll')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollGLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_kind', models.CharField(choices=[('gross_salary', 'Gross Salary Expense'), ('employee_deductions', 'Employee Deductions Payable'), ('net_payable', 'Net Salary Payable')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_gl_mappings', to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_gl_mappings', to='accounts.organization')),
            ],
            options={
                'ordering': ['line_kind'],
                'unique_together': {('organization', 'line_kind')},
            },
        ),
        migrations.CreateModel(
            name='PayrollGLPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_postings', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_gl_postings', to='accounts.organization')),
                ('payroll_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gl_posting', to='hr.payrollrun')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payroll_gl_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='fin_pgp_org_status_idx')],
            },
        ),
    ]
