# Generated by Django 5.2 on 2026-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_usernotificationpreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("budget_warning", "Budget Warning"),
                    ("budget_exceeded", "Budget Exceeded"),
                    ("budget_digest", "Budget Digest"),
                    ("reports_ready", "Reports Ready"),
                    ("system", "System"),
                    ("workflow_pending", "Workflow Pending"),
                    ("workflow_approved", "Workflow Approved"),
                    ("workflow_rejected", "Workflow Rejected"),
                    ("workflow_escalated", "Workflow Escalated"),
                    ("workflow_sla_warning", "Workflow SLA Warning"),
                    ("delegation_assigned", "Delegation Assigned"),
                    ("delegation_expired", "Delegation Expired"),
                ],
                default="system",
                max_length=30,
            ),
        ),
    ]
