# Generated by Django 5.2.12 on 2026-05-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('budget_warning', 'Budget Warning'), ('budget_exceeded', 'Budget Exceeded'), ('budget_digest', 'Budget Digest'), ('reports_ready', 'Reports Ready'), ('system', 'System'), ('workflow_pending', 'Workflow Pending'), ('workflow_approved', 'Workflow Approved'), ('workflow_rejected', 'Workflow Rejected'), ('workflow_escalated', 'Workflow Escalated'), ('workflow_sla_warning', 'Workflow SLA Warning'), ('delegation_assigned', 'Delegation Assigned'), ('delegation_expired', 'Delegation Expired'), ('project_update', 'Project Update'), ('project_risk', 'Project Risk'), ('property_status', 'Property Status'), ('property_maint', 'Property Maintenance'), ('procurement_order', 'Procurement Order'), ('procurement_grn', 'Goods Receipt'), ('hr_leave', 'Leave Request'), ('hr_lifecycle', 'HR Lifecycle'), ('partner_onboarding', 'Partner Onboarding'), ('crm_lead', 'CRM Lead'), ('crm_reservation', 'CRM Reservation'), ('calendar_reminder', 'Calendar Reminder'), ('task_reminder', 'Task Reminder')], default='system', max_length=30),
        ),
    ]
