import { registerResource } from "../index";

registerResource({
  key: "candidates",
  module: "hr",
  label: "Candidate",
  labelPlural: "Candidates",
  endpoint: "/hr/candidates/",
  columns: [
    { key: "first_name", label: "First Name", type: "text", sortable: true },
    { key: "last_name", label: "Last Name", type: "text", sortable: true },
    { key: "email", label: "Email", type: "text" },
    { key: "stage", label: "Stage", type: "badge" },
    { key: "source", label: "Source", type: "text" },
    { key: "applied_date", label: "Applied Date", type: "date", sortable: true },
  ],
  filters: [
    { key: "search", label: "Search", type: "search", placeholder: "Search candidates..." },
    {
      key: "stage",
      label: "Stage",
      type: "select",
      options: [
        { value: "APPLIED", label: "Applied" },
        { value: "SCREENING", label: "Screening" },
        { value: "SHORTLISTED", label: "Shortlisted" },
        { value: "INTERVIEW", label: "Interview" },
        { value: "EVALUATION", label: "Evaluation" },
        { value: "OFFER", label: "Offer" },
        { value: "HIRED", label: "Hired" },
        { value: "REJECTED", label: "Rejected" },
      ],
    },
  ],
  formFields: [
    { key: "first_name", label: "First Name", type: "text", required: true },
    { key: "last_name", label: "Last Name", type: "text", required: true },
    { key: "email", label: "Email", type: "text", required: true },
    { key: "phone", label: "Phone", type: "text" },
    {
      key: "source",
      label: "Source",
      type: "select",
      options: [
        { value: "REFERRAL", label: "Referral" },
        { value: "JOB_BOARD", label: "Job Board" },
        { value: "DIRECT", label: "Direct" },
        { value: "AGENCY", label: "Agency" },
        { value: "SOCIAL_MEDIA", label: "Social Media" },
        { value: "INTERNAL", label: "Internal" },
        { value: "OTHER", label: "Other" },
      ],
    },
    { key: "current_title", label: "Current Title", type: "text" },
    { key: "current_employer", label: "Current Employer", type: "text" },
    { key: "expected_salary", label: "Expected Salary", type: "currency" },
    {
      key: "stage",
      label: "Stage",
      type: "select",
      options: [
        { value: "APPLIED", label: "Applied" },
        { value: "SCREENING", label: "Screening" },
        { value: "SHORTLISTED", label: "Shortlisted" },
        { value: "INTERVIEW", label: "Interview" },
        { value: "EVALUATION", label: "Evaluation" },
        { value: "OFFER", label: "Offer" },
        { value: "HIRED", label: "Hired" },
        { value: "REJECTED", label: "Rejected" },
      ],
    },
    { key: "notes", label: "Notes", type: "textarea", gridSpan: 2 },
  ],
});
