# Generated by Django 5.2 on 2026-03-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0007_add_full_maintenance_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('regulatory', 'Regulatory'), ('environmental', 'Environmental'), ('safety', 'Safety'), ('building_code', 'Building Code'), ('zoning', 'Zoning'), ('accessibility', 'Accessibility'), ('fire_safety', 'Fire Safety'), ('occupational_health', 'Occupational Health')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('regulatory_reference', models.CharField(blank=True, help_text='Legal or regulatory reference code', max_length=255)),
                ('renewal_frequency', models.CharField(choices=[('one_time', 'One-Time'), ('annual', 'Annual'), ('biannual', 'Bi-Annual'), ('quarterly', 'Quarterly')], default='annual', max_length=15)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audit_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('regulatory', 'Regulatory')], default='internal', max_length=15)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('auditor', models.CharField(blank=True, max_length=255)),
                ('scope', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('overall_rating', models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non-Compliant')], max_length=25)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_audits', to='properties.property')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('pending_review', 'Pending Review'), ('expired', 'Expired'), ('exempt', 'Exempt'), ('not_applicable', 'Not Applicable')], default='pending_review', max_length=20)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('last_reviewed_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='properties.property')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_records', to='compliance.compliancerequirement')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('property', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('violation_type', models.CharField(choices=[('regulatory', 'Regulatory'), ('environmental', 'Environmental'), ('safety', 'Safety'), ('building_code', 'Building Code'), ('zoning', 'Zoning'), ('accessibility', 'Accessibility'), ('fire_safety', 'Fire Safety'), ('occupational_health', 'Occupational Health')], max_length=25)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], default='moderate', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('remediation', 'Remediation'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('appealed', 'Appealed')], default='open', max_length=15)),
                ('reported_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_violations', to='properties.property')),
                ('compliance_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='compliance.propertycompliance')),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
    ]
