# Generated by Django 5.2 on 2026-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('compliance', '0002_add_organization_fk'),
        ('properties', '0010_assetcomponent_prop_ac_org_created_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['organization', 'status'], name='comp_aud_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['organization', '-created_at'], name='comp_aud_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancerequirement',
            index=models.Index(fields=['organization', '-created_at'], name='comp_req_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceviolation',
            index=models.Index(fields=['organization', 'status'], name='comp_viol_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceviolation',
            index=models.Index(fields=['organization', '-created_at'], name='comp_viol_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycompliance',
            index=models.Index(fields=['organization', 'status'], name='comp_pc_org_status_idx'),
        ),
    ]
