# Generated by Django 5.2 on 2026-03-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_phase3_taxonomy_numbering'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_status_511254_idx',
            old_name='documents_d_status_7ebe10_idx',
        ),
    ]
