# Generated by Django 5.2 on 2026-03-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_phase7_search_index_engine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentsearchindex',
            new_name='documents_d_index_s_6df215_idx',
            old_name='documents_d_index_s_98c1ec_idx',
        ),
    ]
