# Generated by Django 5.2 on 2026-03-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_rename_documents_d_index_s_98c1ec_idx_documents_d_index_s_6df215_idx"),
        ("projects", "0002_project_project_manager_projectphase_and_more"),
        ("settings", "0004_phase4_documents_access_levels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="business_unit_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="settings.department",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="business_unit_division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="settings.division",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["project", "business_unit_division"], name="documents_d_proj_bu_div_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["project", "business_unit_department"], name="documents_d_proj_bu_dept_idx"),
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="documents.document",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentProjectMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_memberships",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["project__name", "user__email"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRoleScope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "project_scope",
                    models.CharField(
                        choices=[
                            ("all_projects", "All Projects"),
                            ("assigned_projects", "Assigned Projects Only"),
                        ],
                        default="all_projects",
                        max_length=30,
                    ),
                ),
                (
                    "business_unit_scope",
                    models.CharField(
                        choices=[
                            ("all_business_units", "All Business Units"),
                            ("assigned_business_units", "Assigned Business Units Only"),
                        ],
                        default="all_business_units",
                        max_length=30,
                    ),
                ),
                (
                    "allowed_confidentiality_levels",
                    models.JSONField(
                        default=["public", "internal", "confidential", "restricted"],
                        help_text="Allowed values from Document.ConfidentialityLevel.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_scope",
                        to="settings.role",
                    ),
                ),
            ],
            options={
                "ordering": ["role__name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentBusinessUnitMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_memberships",
                        to="settings.department",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_memberships",
                        to="settings.division",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_business_unit_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__email", "division__name", "department__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="documentprojectmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "project"),
                name="documents_unique_user_project_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentbusinessunitmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "division", "department"),
                name="documents_unique_user_business_unit_membership",
            ),
        ),
    ]
