# Generated by Django 5.2 on 2026-03-01

from django.db import migrations


DEFAULT_SCOPE_MATRIX = {
    "developer-executive": {
        "project_scope": "all_projects",
        "business_unit_scope": "all_business_units",
        "allowed_confidentiality_levels": ["public", "internal", "confidential", "restricted"],
    },
    "project-director": {
        "project_scope": "assigned_projects",
        "business_unit_scope": "assigned_business_units",
        "allowed_confidentiality_levels": ["public", "internal", "confidential"],
    },
    "sales-manager": {
        "project_scope": "assigned_projects",
        "business_unit_scope": "assigned_business_units",
        "allowed_confidentiality_levels": ["public", "internal"],
    },
    "finance-controller": {
        "project_scope": "assigned_projects",
        "business_unit_scope": "assigned_business_units",
        "allowed_confidentiality_levels": ["public", "internal", "confidential"],
    },
    "procurement-officer": {
        "project_scope": "assigned_projects",
        "business_unit_scope": "assigned_business_units",
        "allowed_confidentiality_levels": ["public", "internal"],
    },
    "governance-officer": {
        "project_scope": "all_projects",
        "business_unit_scope": "all_business_units",
        "allowed_confidentiality_levels": ["public", "internal", "confidential", "restricted"],
    },
    "legal": {
        "project_scope": "all_projects",
        "business_unit_scope": "all_business_units",
        "allowed_confidentiality_levels": ["public", "internal", "confidential", "restricted"],
    },
    "external-consultant": {
        "project_scope": "assigned_projects",
        "business_unit_scope": "assigned_business_units",
        "allowed_confidentiality_levels": ["public"],
    },
    "auditor": {
        "project_scope": "all_projects",
        "business_unit_scope": "all_business_units",
        "allowed_confidentiality_levels": ["public", "internal", "confidential"],
    },
    "board-viewer": {
        "project_scope": "all_projects",
        "business_unit_scope": "all_business_units",
        "allowed_confidentiality_levels": ["public", "internal"],
    },
}


def seed_role_scopes(apps, schema_editor):
    Role = apps.get_model("settings", "Role")
    DocumentRoleScope = apps.get_model("documents", "DocumentRoleScope")

    roles = Role.objects.filter(is_system=True)
    for role in roles:
        defaults = DEFAULT_SCOPE_MATRIX.get(role.slug)
        if not defaults:
            continue

        DocumentRoleScope.objects.get_or_create(
            role=role,
            defaults=defaults,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_phase4_documents_rbac_scope"),
    ]

    operations = [
        migrations.RunPython(seed_role_scopes, noop_reverse),
    ]
