# Generated by Django 5.2 on 2026-03-01 18:31

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_seed_phase4_role_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrolescope',
            name='allowed_confidentiality_levels',
            field=models.JSONField(default=apps.documents.models.default_document_confidentiality_levels, help_text='Allowed values from Document.ConfidentialityLevel.'),
        ),
    ]
