# Generated by Django 5.2 on 2026-03-01

import decimal
import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_document_statuses_forward(apps, schema_editor):
    Document = apps.get_model("documents", "Document")

    mapping = {
        "active": "approved",
        "on_hold": "under_review",
        "retired": "superseded",
    }
    for old_value, new_value in mapping.items():
        Document.objects.filter(status=old_value).update(status=new_value)


def migrate_document_statuses_backward(apps, schema_editor):
    Document = apps.get_model("documents", "Document")

    mapping = {
        "approved": "active",
        "under_review": "on_hold",
        "superseded": "retired",
    }
    for old_value, new_value in mapping.items():
        Document.objects.filter(status=old_value).update(status=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_alter_documentrolescope_allowed_confidentiality_levels"),
        ("projects", "0003_project_risk_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="contract_value",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                help_text="Commercial value used for conditional approval routing.",
                max_digits=15,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("superseded", "Superseded"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_document_statuses_forward, migrate_document_statuses_backward),
        migrations.CreateModel(
            name="DocumentWorkflowTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="DocumentWorkflowTemplateStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                (
                    "approver_label",
                    models.CharField(
                        help_text="Human-readable stage owner label (e.g., Legal, Finance, COO).",
                        max_length=120,
                    ),
                ),
                (
                    "approver_role_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Optional settings.Role slug for strict role mapping.",
                        max_length=120,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="documents.documentworkflowtemplate",
                    ),
                ),
            ],
            options={"ordering": ["template", "sequence", "id"]},
        ),
        migrations.CreateModel(
            name="DocumentWorkflowRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("min_contract_value", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("max_contract_value", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                (
                    "allowed_confidentiality_levels",
                    models.JSONField(
                        default=apps.documents.models.default_workflow_confidentiality_levels,
                        help_text="Allowed document confidentiality levels for this rule.",
                    ),
                ),
                (
                    "allowed_project_risk_ratings",
                    models.JSONField(
                        default=apps.documents.models.default_workflow_project_risk_ratings,
                        help_text="Allowed project risk ratings for this rule.",
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=100, help_text="Lower value is evaluated first.")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_rules",
                        to="documents.documenttype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="documents.documentworkflowtemplate",
                    ),
                ),
            ],
            options={"ordering": ["priority", "id"]},
        ),
        migrations.CreateModel(
            name="DocumentWorkflowInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_instances",
                        to="documents.document",
                    ),
                ),
                (
                    "matched_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_instances",
                        to="documents.documentworkflowrule",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_instances",
                        to="documents.documentworkflowtemplate",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DocumentWorkflowStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("approver_label", models.CharField(max_length=120)),
                ("approver_role_slug", models.SlugField(blank=True, max_length=120)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_workflow_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="documents.documentworkflowinstance",
                    ),
                ),
            ],
            options={"ordering": ["workflow_instance", "sequence", "id"]},
        ),
        migrations.AddIndex(
            model_name="documentworkflowinstance",
            index=models.Index(fields=["document", "state"], name="documents_d_documen_c62186_idx"),
        ),
        migrations.AddConstraint(
            model_name="documentworkflowtemplatestep",
            constraint=models.UniqueConstraint(
                fields=("template", "sequence"),
                name="documents_unique_workflow_template_step_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentworkflowstep",
            constraint=models.UniqueConstraint(
                fields=("workflow_instance", "sequence"),
                name="documents_unique_workflow_instance_step_sequence",
            ),
        ),
    ]
