# Generated by Django 5.2 on 2026-03-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_phase5_workflow_engine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentworkflowinstance',
            new_name='documents_d_documen_646d70_idx',
            old_name='documents_d_documen_c62186_idx',
        ),
    ]
