# Generated by Django 5.2 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_rename_documents_d_documen_c62186_idx_documents_d_documen_646d70_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentexpiry",
            name="alert_30_days_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentexpiry",
            name="alert_90_days_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentexpiry",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentexpiry",
            name="expired_alert_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentexpiry",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentexpiry",
            name="trigger_category",
            field=models.CharField(
                choices=[
                    ("building_permit", "Building Permit Expiry"),
                    ("insurance", "Insurance Expiry"),
                    ("performance_bond", "Performance Bond Expiry"),
                    ("eia_renewal", "EIA Renewal"),
                    ("warranty_end", "Warranty End Date"),
                ],
                default="building_permit",
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="documentexpiry",
            index=models.Index(
                fields=["trigger_category", "expiry_date"],
                name="documents_d_trigger_8b6db4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentexpiry",
            index=models.Index(
                fields=["expiry_date", "alert_90_days", "alert_30_days", "alert_expired"],
                name="documents_d_expiry__4ba2b6_idx",
            ),
        ),
    ]
