# Generated by Django 5.2 on 2026-03-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_seed_phase6_expiry_monitor_periodic_task'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentexpiry',
            new_name='documents_d_trigger_e9d577_idx',
            old_name='documents_d_trigger_8b6db4_idx',
        ),
        migrations.RenameIndex(
            model_name='documentexpiry',
            new_name='documents_d_expiry__84225c_idx',
            old_name='documents_d_expiry__4ba2b6_idx',
        ),
    ]
