# Generated by Django 5.2 on 2026-03-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_rename_documents_d_trigger_8b6db4_idx_documents_d_trigger_e9d577_idx_and_more"),
        ("settings", "0014_add_audit_compliance_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("document_created", "Document Created"),
                            ("metadata_changed", "Metadata Changed"),
                            ("version_uploaded", "Version Uploaded"),
                            ("approval_decision", "Approval Decision"),
                            ("workflow_submitted", "Workflow Submitted"),
                            ("workflow_step_decision", "Workflow Step Decision"),
                            ("comment_added", "Comment Added"),
                            ("document_downloaded", "Document Downloaded"),
                            ("document_shared", "Document Shared"),
                            ("document_archived", "Document Archived"),
                            ("document_superseded", "Document Superseded"),
                            ("document_deleted", "Document Deleted"),
                        ],
                        max_length=40,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("actor_role_name", models.CharField(blank=True, max_length=120)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("document_number_snapshot", models.CharField(blank=True, max_length=100)),
                ("document_title_snapshot", models.CharField(blank=True, max_length=255)),
                ("version_label_snapshot", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_audit_events",
                        to="settings.role",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="documents.document",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="documentauditevent",
            index=models.Index(fields=["document", "created_at"], name="documents_d_documen_b8c25f_idx"),
        ),
        migrations.AddIndex(
            model_name="documentauditevent",
            index=models.Index(fields=["event_type", "created_at"], name="documents_d_event_t_2e5fe2_idx"),
        ),
        migrations.AddIndex(
            model_name="documentauditevent",
            index=models.Index(fields=["actor", "created_at"], name="documents_d_actor_i_b9a9d0_idx"),
        ),
    ]
