# Generated by Django 5.2 on 2026-03-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_phase8_document_audit_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentauditevent',
            new_name='documents_d_documen_832316_idx',
            old_name='documents_d_documen_b8c25f_idx',
        ),
        migrations.RenameIndex(
            model_name='documentauditevent',
            new_name='documents_d_event_t_50d091_idx',
            old_name='documents_d_event_t_2e5fe2_idx',
        ),
        migrations.RenameIndex(
            model_name='documentauditevent',
            new_name='documents_d_actor_i_882108_idx',
            old_name='documents_d_actor_i_b9a9d0_idx',
        ),
    ]
