# Generated by Django 5.2 on 2026-03-04 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_rename_documents_d_documen_b8c25f_idx_documents_d_documen_832316_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentauditevent',
            name='event_type',
            field=models.CharField(choices=[('document_created', 'Document Created'), ('metadata_changed', 'Metadata Changed'), ('version_uploaded', 'Version Uploaded'), ('document_generated', 'Document Generated'), ('approval_decision', 'Approval Decision'), ('workflow_submitted', 'Workflow Submitted'), ('workflow_step_decision', 'Workflow Step Decision'), ('comment_added', 'Comment Added'), ('document_downloaded', 'Document Downloaded'), ('document_shared', 'Document Shared'), ('signature_request_sent', 'Signature Request Sent'), ('signature_completed', 'Signature Completed'), ('signature_cancelled', 'Signature Cancelled'), ('document_archived', 'Document Archived'), ('document_superseded', 'Document Superseded'), ('document_deleted', 'Document Deleted')], max_length=40),
        ),
        migrations.CreateModel(
            name='DocumentGenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_kind', models.CharField(choices=[('contract', 'Contract'), ('invoice', 'Invoice'), ('report', 'Report')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('template_code', models.CharField(blank=True, max_length=120)),
                ('branding_snapshot', models.JSONField(blank=True, default=dict)),
                ('context_payload', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_records', to='documents.document')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_records', to='documents.documentversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_document_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['generation_kind', 'created_at'], name='documents_d_generat_2997e6_idx'), models.Index(fields=['requested_by', 'created_at'], name='documents_d_request_e7d397_idx'), models.Index(fields=['document', 'created_at'], name='documents_d_documen_714bc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('docusign', 'DocuSign'), ('adobe_acrobat_sign', 'Adobe Acrobat Sign'), ('dropbox_sign', 'Dropbox Sign'), ('signnow', 'SignNow')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('provider_envelope_id', models.CharField(blank=True, max_length=255)),
                ('signing_url', models.URLField(blank=True)),
                ('signers', models.JSONField(blank=True, default=list, help_text='Signer rows: [{name, email, role, order, status}]')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='documents.document')),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_requests', to='documents.documentversion')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_document_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'indexes': [models.Index(fields=['document', 'status'], name='documents_d_documen_4909ce_idx'), models.Index(fields=['provider', 'status'], name='documents_d_provide_203cc6_idx'), models.Index(fields=['requested_by', 'requested_at'], name='documents_d_request_a73076_idx')],
            },
        ),
    ]
