from django.db import migrations, models
import django.db.models.deletion


def populate_organization(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    DocumentGovernanceCharter = apps.get_model("documents", "DocumentGovernanceCharter")
    DocumentDomain = apps.get_model("documents", "DocumentDomain")
    ControlledVocabularyTerm = apps.get_model("documents", "ControlledVocabularyTerm")
    DocumentType = apps.get_model("documents", "DocumentType")
    DocumentOwnerRole = apps.get_model("documents", "DocumentOwnerRole")
    DocumentWorkflowPhase = apps.get_model("documents", "DocumentWorkflowPhase")
    DocumentRetentionPolicy = apps.get_model("documents", "DocumentRetentionPolicy")
    Document = apps.get_model("documents", "Document")
    DocumentVersion = apps.get_model("documents", "DocumentVersion")
    DocumentApproval = apps.get_model("documents", "DocumentApproval")
    DocumentExpiry = apps.get_model("documents", "DocumentExpiry")
    DocumentSearchIndex = apps.get_model("documents", "DocumentSearchIndex")
    DocumentComment = apps.get_model("documents", "DocumentComment")
    DocumentAuditEvent = apps.get_model("documents", "DocumentAuditEvent")
    DocumentRoleScope = apps.get_model("documents", "DocumentRoleScope")
    DocumentProjectMembership = apps.get_model("documents", "DocumentProjectMembership")
    DocumentBusinessUnitMembership = apps.get_model("documents", "DocumentBusinessUnitMembership")
    DocumentWorkflowTemplate = apps.get_model("documents", "DocumentWorkflowTemplate")
    DocumentWorkflowTemplateStep = apps.get_model("documents", "DocumentWorkflowTemplateStep")
    DocumentWorkflowRule = apps.get_model("documents", "DocumentWorkflowRule")
    DocumentWorkflowInstance = apps.get_model("documents", "DocumentWorkflowInstance")
    DocumentWorkflowStep = apps.get_model("documents", "DocumentWorkflowStep")
    DocumentSignatureRequest = apps.get_model("documents", "DocumentSignatureRequest")
    DocumentGenerationRecord = apps.get_model("documents", "DocumentGenerationRecord")

    models_to_backfill = [
        DocumentGovernanceCharter,
        DocumentDomain,
        ControlledVocabularyTerm,
        DocumentType,
        DocumentOwnerRole,
        DocumentWorkflowPhase,
        DocumentRetentionPolicy,
        Document,
        DocumentVersion,
        DocumentApproval,
        DocumentExpiry,
        DocumentSearchIndex,
        DocumentComment,
        DocumentAuditEvent,
        DocumentRoleScope,
        DocumentProjectMembership,
        DocumentBusinessUnitMembership,
        DocumentWorkflowTemplate,
        DocumentWorkflowTemplateStep,
        DocumentWorkflowRule,
        DocumentWorkflowInstance,
        DocumentWorkflowStep,
        DocumentSignatureRequest,
        DocumentGenerationRecord,
    ]

    has_null_org_rows = any(
        model.objects.filter(organization__isnull=True).exists()
        for model in models_to_backfill
    )
    if not has_null_org_rows:
        return

    org = Organization.objects.first()
    if org is None:
        org = Organization.objects.create(name="Default Organization")

    for model in models_to_backfill:
        model.objects.filter(organization__isnull=True).update(organization=org)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("accounts", "0001_initial"),
        ("documents", "0017_alter_documentauditevent_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentgovernancecharter",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_governance_charters",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentdomain",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_domains",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="controlledvocabularyterm",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_controlled_vocabulary_terms",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_types",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentownerrole",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_owner_roles",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentworkflowphase",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_phases",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentretentionpolicy",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_retention_policies",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_documents",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_versions",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentapproval",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_approvals",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentexpiry",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_expiries",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentsearchindex",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_search_indices",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentcomment",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_comments",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentauditevent",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_audit_events",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentrolescope",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_role_scopes",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentprojectmembership",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_project_memberships",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentbusinessunitmembership",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_business_unit_memberships",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentworkflowtemplate",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_templates",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentworkflowtemplatestep",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_template_steps",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentworkflowrule",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_rules",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentworkflowinstance",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_instances",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentworkflowstep",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_steps",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentsignaturerequest",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_signature_requests",
                to="accounts.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentgenerationrecord",
            name="organization",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_generation_records",
                to="accounts.organization",
            ),
        ),
        migrations.RunPython(populate_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="documentgovernancecharter",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_governance_charters",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentdomain",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_domains",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="controlledvocabularyterm",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_controlled_vocabulary_terms",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_types",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentownerrole",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_owner_roles",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentworkflowphase",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_phases",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentretentionpolicy",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_retention_policies",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_documents",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_versions",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentapproval",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_approvals",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentexpiry",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_expiries",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentsearchindex",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_search_indices",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentcomment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_comments",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentauditevent",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_audit_events",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentrolescope",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_role_scopes",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentprojectmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_project_memberships",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentbusinessunitmembership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_business_unit_memberships",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentworkflowtemplate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_templates",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentworkflowtemplatestep",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_template_steps",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentworkflowrule",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_rules",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentworkflowinstance",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_instances",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentworkflowstep",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_workflow_steps",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentsignaturerequest",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_signature_requests",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="documentgenerationrecord",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_doc_generation_records",
                to="accounts.organization",
            ),
        ),
    ]
