# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('documents', '0018_add_organization_fk'),
        ('finance', '0015_add_organization_fk'),
        ('procurement', '0003_goodsreceipt_organization_purchaseorder_budget_code_and_more'),
        ('projects', '0017_add_organization_fk'),
        ('properties', '0010_assetcomponent_prop_ac_org_created_idx_and_more'),
        ('settings', '0056_autoescalationrule_set_aer_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='controlledvocabularyterm',
            index=models.Index(fields=['organization', 'status'], name='doc_cvt_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledvocabularyterm',
            index=models.Index(fields=['organization', '-created_at'], name='doc_cvt_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'status'], name='doc_doc_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', '-created_at'], name='doc_doc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['organization', '-timestamp'], name='doc_appr_org_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbusinessunitmembership',
            index=models.Index(fields=['organization', '-created_at'], name='doc_bumem_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['organization', '-created_at'], name='doc_cmnt_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdomain',
            index=models.Index(fields=['organization', '-created_at'], name='doc_dom_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentgovernancecharter',
            index=models.Index(fields=['organization', 'status'], name='doc_gov_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentgovernancecharter',
            index=models.Index(fields=['organization', '-created_at'], name='doc_gov_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentownerrole',
            index=models.Index(fields=['organization', '-created_at'], name='doc_ownr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprojectmembership',
            index=models.Index(fields=['organization', '-created_at'], name='doc_pmem_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentretentionpolicy',
            index=models.Index(fields=['organization', '-created_at'], name='doc_retn_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrolescope',
            index=models.Index(fields=['organization', '-created_at'], name='doc_rscope_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsignaturerequest',
            index=models.Index(fields=['organization', 'status'], name='doc_sig_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['organization', '-created_at'], name='doc_dtype_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['organization', '-uploaded_at'], name='doc_ver_org_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflowinstance',
            index=models.Index(fields=['organization', '-created_at'], name='doc_wfi_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflowphase',
            index=models.Index(fields=['organization', '-created_at'], name='doc_wfph_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflowrule',
            index=models.Index(fields=['organization', '-created_at'], name='doc_wfrul_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflowstep',
            index=models.Index(fields=['organization', '-created_at'], name='doc_wfstp_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflowtemplate',
            index=models.Index(fields=['organization', '-created_at'], name='doc_wftpl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentworkflowtemplatestep',
            index=models.Index(fields=['organization', '-created_at'], name='doc_wfts_org_created_idx'),
        ),
    ]
