# Generated by Django 5.2 on 2026-03-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_organization_accounts_org_norm_name_trgm'),
        ('documents', '0019_controlledvocabularyterm_doc_cvt_org_status_idx_and_more'),
        ('finance', '0018_budget_project_container'),
        ('procurement', '0004_goodsreceipt_proc_gr_org_status_idx_and_more'),
        ('projects', '0020_project_gps_coordinates'),
        ('properties', '0012_populate_property_inventory'),
        ('settings', '0060_global_project_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_app_label',
            field=models.CharField(blank=True, db_index=True, help_text="App label of the module that created this document (e.g. 'projects').", max_length=60),
        ),
        migrations.AddField(
            model_name='document',
            name='source_model_name',
            field=models.CharField(blank=True, help_text="Model name of the source record (e.g. 'ProjectSupportingAttachment').", max_length=60),
        ),
        migrations.AddField(
            model_name='document',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the source record.', null=True),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('source_app_label', ''), _negated=True), fields=('source_app_label', 'source_model_name', 'source_object_id'), name='documents_unique_source_record'),
        ),
    ]
