# Generated by Django 5.2 on 2026-03-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_des_organiz_743db3_idx',
            old_name='sd_ticket_org_status_created',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_des_organiz_441989_idx',
            old_name='sd_ticket_org_priority_created',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_des_organiz_4dcb03_idx',
            old_name='sd_ticket_org_agent_status',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='support_des_organiz_015f58_idx',
            old_name='sd_ticket_org_sla',
        ),
        migrations.RenameIndex(
            model_name='supportticketcomment',
            new_name='support_des_ticket__ee73ba_idx',
            old_name='sd_comment_ticket_type_created',
        ),
    ]
