# Generated by Django 5.2 on 2026-03-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0003_supportknowledgearticle_supportslapolicy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportknowledgearticle',
            new_name='support_des_organiz_34938b_idx',
            old_name='support_des_organiz_79dc59_idx',
        ),
        migrations.RenameIndex(
            model_name='supportknowledgearticle',
            new_name='support_des_organiz_f0a051_idx',
            old_name='support_des_organiz_9df55e_idx',
        ),
        migrations.RenameIndex(
            model_name='supportknowledgearticle',
            new_name='support_des_organiz_b7573c_idx',
            old_name='support_des_organiz_f1f84f_idx',
        ),
        migrations.RenameIndex(
            model_name='supportknowledgearticle',
            new_name='support_des_organiz_15bcb6_idx',
            old_name='support_des_organiz_6eab61_idx',
        ),
        migrations.RenameIndex(
            model_name='supportslapolicy',
            new_name='support_des_organiz_8d3af6_idx',
            old_name='support_des_organiz_d179e8_idx',
        ),
        migrations.RenameIndex(
            model_name='supportslapolicy',
            new_name='support_des_organiz_f42877_idx',
            old_name='support_des_organiz_20595f_idx',
        ),
    ]
