# Generated by Django 5.2 on 2026-03-07 06:59

import django.core.validators
from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    """Skip DB add when the column already exists (branch-merge safety)."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        table_name = to_model._meta.db_table
        field = to_model._meta.get_field(self.name)

        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            }

        if field.column in columns:
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        from_model = from_state.apps.get_model(app_label, self.model_name)
        table_name = from_model._meta.db_table
        field = from_model._meta.get_field(self.name)

        with schema_editor.connection.cursor() as cursor:
            columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor, table_name
                )
            }

        if field.column not in columns:
            return

        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0004_rename_support_des_organiz_79dc59_idx_support_des_organiz_34938b_idx_and_more'),
    ]

    operations = [
        AddFieldIfMissing(
            model_name='supportslapolicy',
            name='agent_notify_threshold_percent',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        AddFieldIfMissing(
            model_name='supportslapolicy',
            name='breach_escalation_role',
            field=models.CharField(default='director', max_length=80),
        ),
        AddFieldIfMissing(
            model_name='supportslapolicy',
            name='manager_notify_threshold_percent',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='supportslapolicy',
            name='notify_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supportslapolicy',
            name='resolution_target_hours',
            field=models.DecimalField(decimal_places=2, default=48, max_digits=6),
        ),
        migrations.AlterField(
            model_name='supportslapolicy',
            name='response_target_hours',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=6),
        ),
    ]
