# Generated by Django 5.2 on 2026-03-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0005_supportslapolicy_agent_notify_threshold_percent_and_more'),
        ('support_desk', '0005_supportslapolicy_enterprise_thresholds'),
    ]

    operations = [
    ]
