# Generated by Django 5.2 on 2026-03-07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_desk", "0006_merge_20260307_0703"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportCommunicationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("ticket_conversation", "Ticket Conversation"),
                            ("internal_note", "Internal Note"),
                            ("email_reply", "Email Reply"),
                            ("chat_transcript", "Chat Transcript"),
                            ("call_log", "Call Log"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="ticket_conversation",
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("internal", "Internal"),
                        ],
                        default="internal",
                        max_length=12,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("portal", "Support Portal"),
                            ("email", "Email"),
                            ("chat", "Chat"),
                            ("phone", "Phone"),
                            ("whatsapp", "WhatsApp"),
                            ("other", "Other"),
                        ],
                        default="portal",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                ("transcript", models.TextField(blank=True)),
                ("participants", models.JSONField(blank=True, default=list)),
                ("call_duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("external_message_id", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("happened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_communication_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_communication_logs",
                        to="accounts.organization",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communication_logs",
                        to="support_desk.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-happened_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="supportcommunicationlog",
            index=models.Index(fields=["organization", "ticket", "-happened_at"], name="support_des_organiz_666f49_idx"),
        ),
        migrations.AddIndex(
            model_name="supportcommunicationlog",
            index=models.Index(fields=["organization", "interaction_type", "-happened_at"], name="support_des_organiz_7c3cf0_idx"),
        ),
        migrations.AddIndex(
            model_name="supportcommunicationlog",
            index=models.Index(fields=["organization", "channel", "-happened_at"], name="support_des_organiz_3594ad_idx"),
        ),
        migrations.AddIndex(
            model_name="supportcommunicationlog",
            index=models.Index(fields=["organization", "direction", "-happened_at"], name="support_des_organiz_a2f0f8_idx"),
        ),
    ]
