# Generated by Django 5.2 on 2026-03-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_desk", "0007_supportcommunicationlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportAutomationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("ticket_created", "Ticket Creation"),
                            ("ticket_updated", "Ticket Update"),
                            ("sla_threshold", "SLA Threshold"),
                            ("status_changed", "Status Change"),
                        ],
                        default="ticket_created",
                        max_length=24,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("actions", models.JSONField(blank=True, default=dict)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("run_once_per_ticket", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_automation_rules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_automation_rules",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["trigger_type", "priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="SupportAutomationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("ticket_created", "Ticket Creation"),
                            ("ticket_updated", "Ticket Update"),
                            ("sla_threshold", "SLA Threshold"),
                            ("status_changed", "Status Change"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("matched", "Matched"), ("failed", "Failed")],
                        default="matched",
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_automation_runs",
                        to="accounts.organization",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="support_desk.supportautomationrule",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_runs",
                        to="support_desk.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="supportautomationrule",
            index=models.Index(fields=["organization", "is_active", "trigger_type", "priority"], name="support_des_organiz_4578f5_idx"),
        ),
        migrations.AddIndex(
            model_name="supportautomationrule",
            index=models.Index(fields=["organization", "name"], name="support_des_organiz_03f6f6_idx"),
        ),
        migrations.AddIndex(
            model_name="supportautomationrun",
            index=models.Index(fields=["organization", "ticket", "-created_at"], name="support_des_organiz_930619_idx"),
        ),
        migrations.AddIndex(
            model_name="supportautomationrun",
            index=models.Index(fields=["organization", "rule", "-created_at"], name="support_des_organiz_9b7f6a_idx"),
        ),
        migrations.AddIndex(
            model_name="supportautomationrun",
            index=models.Index(fields=["organization", "trigger_type", "status", "-created_at"], name="support_des_organiz_612907_idx"),
        ),
    ]
