# Generated by Django 5.2 on 2026-03-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0007_supportcommunicationlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportcommunicationlog',
            new_name='support_des_organiz_d30c2e_idx',
            old_name='support_des_organiz_666f49_idx',
        ),
        migrations.RenameIndex(
            model_name='supportcommunicationlog',
            new_name='support_des_organiz_f144b3_idx',
            old_name='support_des_organiz_7c3cf0_idx',
        ),
        migrations.RenameIndex(
            model_name='supportcommunicationlog',
            new_name='support_des_organiz_1d2322_idx',
            old_name='support_des_organiz_3594ad_idx',
        ),
        migrations.RenameIndex(
            model_name='supportcommunicationlog',
            new_name='support_des_organiz_43173c_idx',
            old_name='support_des_organiz_a2f0f8_idx',
        ),
    ]
