# Generated by Django 5.2 on 2026-03-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0008_rename_support_des_organiz_666f49_idx_support_des_organiz_d30c2e_idx_and_more'),
        ('support_desk', '0008_supportautomationrule_supportautomationrun'),
    ]

    operations = [
    ]
