# Generated by Django 5.2 on 2026-03-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_desk', '0009_merge_20260307_1246'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportautomationrule',
            new_name='support_des_organiz_b54493_idx',
            old_name='support_des_organiz_4578f5_idx',
        ),
        migrations.RenameIndex(
            model_name='supportautomationrule',
            new_name='support_des_organiz_cd7e63_idx',
            old_name='support_des_organiz_03f6f6_idx',
        ),
        migrations.RenameIndex(
            model_name='supportautomationrun',
            new_name='support_des_organiz_bd7a06_idx',
            old_name='support_des_organiz_930619_idx',
        ),
        migrations.RenameIndex(
            model_name='supportautomationrun',
            new_name='support_des_organiz_b1c291_idx',
            old_name='support_des_organiz_9b7f6a_idx',
        ),
        migrations.RenameIndex(
            model_name='supportautomationrun',
            new_name='support_des_organiz_749bb6_idx',
            old_name='support_des_organiz_612907_idx',
        ),
    ]
