# Generated by Django 5.2.12 on 2026-03-18 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_activesubscriptionaddon'),
        ('crm', '0019_seed_celery_beat_procurement_demand_insights'),
        ('finance', '0031_customer_support_ticketing_enabled_and_more'),
        ('settings', '0068_subscriptionaddon_alter_featureflagdefinition_module_and_more'),
        ('support_desk', '0010_rename_support_des_organiz_4578f5_idx_support_des_organiz_b54493_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='contact_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='crm.contactaccount'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='finance.customer'),
        ),
        migrations.AlterField(
            model_name='supportslapolicy',
            name='category',
            field=models.CharField(blank=True, choices=[('access', 'Access'), ('billing', 'Billing'), ('technical', 'Technical'), ('workflow', 'Workflow'), ('account', 'Account'), ('complaint', 'Complaint'), ('request', 'Request'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('access', 'Access'), ('billing', 'Billing'), ('technical', 'Technical'), ('workflow', 'Workflow'), ('account', 'Account'), ('complaint', 'Complaint'), ('request', 'Request'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', 'customer', '-created_at'], name='support_des_organiz_c5dae1_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', 'contact_account', '-created_at'], name='support_des_organiz_9fcab1_idx'),
        ),
    ]
