# Generated by Django 5.2.12 on 2026-03-19 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('crm', '0019_seed_celery_beat_procurement_demand_insights'),
        ('finance', '0032_alter_paymentvoucher_status'),
        ('settings', '0068_subscriptionaddon_alter_featureflagdefinition_module_and_more'),
        ('support_desk', '0011_supportticket_contact_account_supportticket_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='finance.invoice'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', 'invoice', '-created_at'], name='support_des_organiz_b96462_idx'),
        ),
    ]
