# Generated by Django 5.2.12 on 2026-05-09 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_seed_connectors'),
        ('crm', '0019_seed_celery_beat_procurement_demand_insights'),
        ('finance', '0034_bill_match_status_billlineitem_po_item'),
        ('settings', '0083_accesspolicy_kind_and_more'),
        ('support_desk', '0012_supportticket_invoice_and_more'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='team',
            field=models.ForeignKey(blank=True, help_text="Optional workspace team scope. When set, ticket visibility is additionally constrained by the team's visibility (see docs/workspace-teams-design.md §12).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='workspace.team'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['team', '-created_at'], name='supportticket_team_created_idx'),
        ),
    ]
