# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('finance', '0016_account_fin_acct_org_created_idx_and_more'),
        ('inventory', '0002_add_organization_fk'),
        ('procurement', '0004_goodsreceipt_proc_gr_org_status_idx_and_more'),
        ('projects', '0018_project_proj_proj_org_status_idx_and_more'),
        ('settings', '0056_autoescalationrule_set_aer_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['organization', '-created_at'], name='inv_item_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['organization', '-created_at'], name='inv_txn_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementitemmapping',
            index=models.Index(fields=['organization', '-created_at'], name='inv_pim_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['organization', '-created_at'], name='inv_wh_org_created_idx'),
        ),
    ]
