# Generated by Django 5.2 on 2026-03-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_inv_item_org_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='alternative_materials',
            field=models.TextField(blank=True, help_text='Comma-separated list of substitute material names or SKUs.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='compliance_requirements',
            field=models.TextField(blank=True, help_text='Regulatory or compliance notes for this material.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System code for import/export classification.', max_length=20, verbose_name='HS Code'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Typical lead time in days from order to delivery.', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='material_grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quality_specification',
            field=models.TextField(blank=True, help_text='Quality or technical specification reference.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_requirements',
            field=models.TextField(blank=True, help_text="E.g. 'Dry store, avoid moisture', 'Keep below 25°C'."),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
