# Generated by Django 5.2.12 on 2026-03-24 09:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_billofmaterials_bomitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='confidence_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='0=Empty, 100=Fully Quoted'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='margin_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='parent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='inventory.billofmaterials'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='site_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='vat_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.50'), max_digits=5),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='original_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost when draft was created, for drift detection', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='price_volatile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
