# Generated by Django 5.2.12 on 2026-03-24 10:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_billofmaterials_confidence_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='item_markup_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-item profit margin %', max_digits=5),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Estimated delivery days to site'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='price_source',
            field=models.CharField(choices=[('warehouse', 'Warehouse Price'), ('manual', 'Manual Override'), ('quote', 'Supplier Quote')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='section',
            field=models.CharField(blank=True, help_text='Visual grouping section in the builder', max_length=100),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='source_bom',
            field=models.ForeignKey(blank=True, help_text='BOM this item was expanded from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_boq_items', to='inventory.billofmaterials'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='waste_factor_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Breakage/waste buffer %', max_digits=5),
        ),
    ]
