# Generated by Django 5.2.12 on 2026-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_bomitem_item_markup_pct_bomitem_lead_time_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='project_variables',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"panel_count": 100, "floor_area_sqm": 450}'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='quantity_formula',
            field=models.CharField(blank=True, help_text='e.g. "panel_count * 0.8" — references BOM project_variables', max_length=255),
        ),
    ]
