# Generated by Django 5.2.12 on 2026-03-24 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_billofmaterials_project_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='fx_rate_usd_ngn',
            field=models.DecimalField(decimal_places=2, default=Decimal('1550.00'), help_text='USD to NGN exchange rate for FX-linked items', max_digits=10),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='is_fx_linked',
            field=models.BooleanField(default=False, help_text='If True, unit_cost is derived from unit_cost_usd * BOM fx_rate'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='unit_cost_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='USD price — multiplied by BOM FX rate to get NGN unit_cost', max_digits=12),
        ),
    ]
