# Generated by Django 5.2.12 on 2026-03-24 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_billofmaterials_fx_rate_usd_ngn_bomitem_is_fx_linked_and_more'),
        ('procurement', '0006_procurementdemandinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='supplier_vendor',
            field=models.ForeignKey(blank=True, help_text='Linked vendor from procurement database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_items', to='procurement.vendor'),
        ),
    ]
