# Generated by Django 5.2.12 on 2026-03-24 16:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0010_bomitem_supplier_vendor'),
        ('procurement', '0006_procurementdemandinsight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fx_rate_usd_ngn', models.DecimalField(decimal_places=2, default=Decimal('1550.00'), max_digits=10)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rate_books', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_books', to='accounts.organization')),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=50)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_rate_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_fx_linked', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, help_text='e.g. Lagos WH, Abuja, National', max_length=100)),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('labor', 'Labor'), ('machinery', 'Machinery'), ('consumables', 'Consumables'), ('logistics', 'Logistics'), ('fees', 'Fees & Permits'), ('preliminaries', 'Preliminaries'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('floating', 'Floating'), ('expired', 'Expired')], default='floating', max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('handling_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('duty_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_composite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.ratebook')),
                ('supplier_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_items', to='procurement.vendor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'item_code'],
                'unique_together': {('rate_book', 'item_code')},
            },
        ),
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rate_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.rateitem')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RateCompositeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10)),
                ('component_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_composites', to='inventory.rateitem')),
                ('composite_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.rateitem')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
