# Generated by Django 5.2.12 on 2026-03-24 17:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0011_ratebook_rateitem_ratehistory_ratecompositecomponent'),
        ('projects', '0033_equipment_and_machinery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoqTaskMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('delivery_deadline', models.DateField(blank=True, null=True)),
                ('material_status', models.CharField(choices=[('awaiting', 'Awaiting Order'), ('in_transit', 'In Transit'), ('in_warehouse', 'In Warehouse')], default='awaiting', max_length=15)),
                ('has_lead_time_conflict', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_mappings', to='inventory.billofmaterials')),
                ('bom_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_mappings', to='inventory.bomitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_mappings', to='accounts.organization')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_mappings', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_mappings', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_mappings', to='projects.projecttask')),
            ],
            options={
                'ordering': ['bom', 'bom_item__sort_order'],
            },
        ),
    ]
