# Generated by Django 5.2.12 on 2026-03-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_fix_boq_task_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='is_baseline',
            field=models.BooleanField(default=False, help_text='Permanent reference point for comparisons'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='revision_reason',
            field=models.TextField(blank=True, help_text='Why this revision was created'),
        ),
    ]
