# Generated by Django 5.2.12 on 2026-03-24 23:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_billofmaterials_is_baseline_and_more'),
        ('procurement', '0006_procurementdemandinsight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='confidence_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='fx_rate_usd_ngn',
            field=models.DecimalField(decimal_places=2, default=Decimal('1550.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='is_baseline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='project_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='revision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='is_fx_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='item_markup_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='original_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity_formula',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='source_bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_boq_items', to='inventory.billofmaterials'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='supplier_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_items', to='procurement.vendor'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='unit_cost_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='waste_factor_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='rateitem',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
