# Generated by Django 5.2.12 on 2026-03-26 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0014_alter_billofmaterials_confidence_pct_and_more'),
        ('settings', '0076_tasktemplate_production_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoqCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_category', models.CharField(help_text="BOQ item category to match (e.g. 'Concrete', 'Electrical', 'Excavation').", max_length=100)),
                ('default_production_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Fallback production rate (units/day) if task template has none.', max_digits=10, null=True)),
                ('split_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='If BOQ quantity exceeds this, split into multiple tasks by zone/location.', max_digits=12, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_category_mappings', to='accounts.organization')),
                ('template_phase', models.ForeignKey(help_text='Template phase that handles this BOQ category.', on_delete=django.db.models.deletion.CASCADE, related_name='boq_category_mappings', to='settings.templatephase')),
            ],
            options={
                'ordering': ['sort_order', 'boq_category'],
                'unique_together': {('organization', 'boq_category')},
            },
        ),
    ]
