# Generated by Django 5.2.12 on 2026-03-26 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_boqcategorymapping'),
        ('projects', '0051_project_closeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqtaskmapping',
            name='cost_code_budget',
            field=models.ForeignKey(blank=True, help_text='Links this BOQ allocation to a formal budget line.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_mappings', to='projects.costcodebudget'),
        ),
    ]
