# Generated by Django 5.2.12 on 2026-03-26 03:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_boq_cost_code_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqtaskmapping',
            name='consumed_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Aggregated from DailyReportMaterialUsage. Updated by sync.', max_digits=12),
        ),
    ]
