# Generated by Django 5.2.12 on 2026-03-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_boq_consumed_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='actual_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual rate paid (from bills/invoices). May differ from contracted_rate due to variations.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='contracted_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate agreed in the contract (from PO/tender). Differs from unit_cost (estimate).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('estimate', 'Master Estimate'), ('tender', 'Issued for Tender'), ('contract', 'Contract BOQ (Agreed)'), ('execution', 'Execution (Live Tracking)'), ('financial_control', 'Financial Control'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
