# Generated by Django 5.2.12 on 2026-03-27 13:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0018_boq_lifecycle_and_rates'),
        ('projects', '0055_contracts_and_agreements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_se', 'Pending Site Engineer'), ('pending_pm', 'Pending Project Manager'), ('pending_proc', 'Pending Procurement'), ('pending_store', 'Pending Store'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('site_location', models.CharField(blank=True, max_length=255)),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('justification', models.TextField(blank=True)),
                ('cost_code', models.CharField(blank=True, max_length=100)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('current_step', models.CharField(default='site_engineer', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_se', models.CharField(blank=True, max_length=255)),
                ('approved_by_se_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_pm', models.CharField(blank=True, max_length=255)),
                ('approved_by_pm_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_proc', models.CharField(blank=True, max_length=255)),
                ('approved_by_proc_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_by_store', models.CharField(blank=True, max_length=255)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=255)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_requisitions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requisitions', to='accounts.organization')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requisitions', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requisitions', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('field_changed', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.materialrequisition')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inventory.materialrequisition')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Description if not linked to master.', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_of_measure', models.CharField(default='ea', max_length=50)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('phase_area', models.CharField(blank=True, help_text='Zone or work area for this line.', max_length=100)),
                ('line_justification', models.TextField(blank=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('available_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('issued_from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requisition_issues', to='inventory.warehouse')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_lines', to='inventory.inventoryitem')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialrequisition')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='materialrequisition',
            index=models.Index(fields=['organization', 'status'], name='matreq_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequisition',
            index=models.Index(fields=['organization', 'project', '-created_at'], name='matreq_org_proj_idx'),
        ),
    ]
