# Generated by Django 5.2.12 on 2026-03-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_materialrequisition_materialrequisitionauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='gps_coordinates',
            field=models.CharField(blank=True, help_text='Lat,Lng', max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='storage_capacity_units',
            field=models.PositiveIntegerField(default=0, help_text='Max storage capacity in abstract units (pallets, m³, etc.).'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('central', 'Central Warehouse'), ('site', 'Site Store'), ('transit', 'Transit Hub'), ('bonded', 'Bonded Store')], default='site', max_length=20),
        ),
    ]
