# Generated by Django 5.2.12 on 2026-03-29 21:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0020_warehouse_contact_person_warehouse_contact_phone_and_more'),
        ('projects', '0060_stage_gate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('issued', 'Issued'), ('partially_issued', 'Partially Issued'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Work activity or task requiring these materials.')),
                ('cost_code', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_issues', to='accounts.organization')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issues', to='projects.projectphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_issues', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_material_issues', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_issues', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unit_of_measure', models.CharField(default='ea', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('purpose', models.CharField(blank=True, help_text='Specific task or activity.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialissue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_lines', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='materialissue',
            index=models.Index(fields=['organization', 'status'], name='matissue_org_status_idx'),
        ),
    ]
