# Generated by Django 5.2.12 on 2026-03-31 07:10

import apps.inventory.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0021_materialissue_materialissueline_and_more'),
        ('projects', '0060_stage_gate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianceInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('work_package', models.CharField(blank=True, max_length=255)),
                ('root_cause', models.CharField(choices=[('theft', 'Theft / Pilferage'), ('poor_workmanship', 'Poor Workmanship'), ('design_change', 'Design Change'), ('spillage', 'Spillage / Breakage'), ('measurement_error', 'Measurement Error'), ('soil_conditions', 'Unexpected Soil/Site Conditions'), ('rework', 'Rework / Remedial'), ('weather', 'Weather Damage'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=15)),
                ('planned_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('variance_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('variance_pct', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('unit', models.CharField(default='ea', max_length=50)),
                ('supervisor_notes', models.TextField(blank=True, help_text='Site engineer justification for over-consumption.')),
                ('corrective_action', models.TextField(blank=True)),
                ('financial_impact', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_investigations', to='accounts.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variance_investigations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VarianceInvestigationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.inventory.models.variance_photo_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.varianceinvestigation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
