# Generated by Django 5.2.12 on 2026-04-01 05:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0022_varianceinvestigation_varianceinvestigationphoto'),
        ('projects', '0060_stage_gate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('received', 'Received & Confirmed'), ('partially_received', 'Partially Received'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Why this transfer is needed.')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('dispatched_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('dispatched_by', models.CharField(blank=True, max_length=255)),
                ('received_by', models.CharField(blank=True, max_length=255)),
                ('vehicle_details', models.CharField(blank=True, help_text='Truck plate, driver name.', max_length=255)),
                ('waybill_number', models.CharField(blank=True, max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transfers', to='inventory.warehouse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_transfers', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transfers', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_transfers', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unit_of_measure', models.CharField(default='ea', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines', to='inventory.inventoryitem')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialtransfer')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='materialtransfer',
            index=models.Index(fields=['organization', 'status'], name='mattrans_org_status_idx'),
        ),
    ]
