# Generated by Django 5.2.12 on 2026-04-01 13:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('inventory', '0023_materialtransfer_materialtransferline_and_more'),
        ('procurement', '0016_goodsreceiptitem_unit_price_goodsreceiptphoto'),
        ('projects', '0060_stage_gate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('return_type', models.CharField(choices=[('to_warehouse', 'Return to Warehouse'), ('to_vendor', 'Return to Vendor')], default='to_warehouse', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received & Restocked'), ('credit_pending', 'Credit Memo Pending'), ('credit_received', 'Credit Received'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reason', models.CharField(choices=[('excess', 'Excess / Surplus'), ('defective', 'Defective / Damaged'), ('wrong_spec', 'Wrong Specification'), ('project_closure', 'Project Closure'), ('design_change', 'Design Change'), ('expired', 'Expired / Shelf Life'), ('other', 'Other')], default='excess', max_length=20)),
                ('reason_detail', models.TextField(blank=True)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('dispatched_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('credit_memo_number', models.CharField(blank=True, max_length=100)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit_received_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_warehouse', models.ForeignKey(blank=True, help_text='Central warehouse receiving the return.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_returns', to='inventory.warehouse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_returns', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_returns', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_returns', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(help_text='Where the material currently is (site store).', on_delete=django.db.models.deletion.CASCADE, related_name='outbound_returns', to='inventory.warehouse')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_returns', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('unit_of_measure', models.CharField(default='ea', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('expired', 'Expired')], default='good', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_lines', to='inventory.inventoryitem')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialreturn')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='materialreturn',
            index=models.Index(fields=['organization', 'status'], name='matreturn_org_status_idx'),
        ),
    ]
