# Generated by Django 5.2.12 on 2026-05-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0051_userprofile_calendar_default_reminder_minutes'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('external_attendee_emails', models.JSONField(blank=True, default=list, help_text='Free-form list of external (non-org) attendee emails. Used for .ics email invites.')),
                ('kind', models.CharField(choices=[('meeting', 'Meeting'), ('focus', 'Focus block'), ('out_of_office', 'Out of office'), ('reminder', 'Reminder')], default='meeting', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('org', 'Org-wide')], default='private', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', help_text='IANA name (e.g. America/New_York). Used for RRULE expansion + render.', max_length=64)),
                ('recurrence_rule', models.CharField(blank=True, help_text="RFC 5545 RRULE without the 'RRULE:' prefix. Empty = single occurrence.", max_length=400)),
                ('recurrence_end', models.DateTimeField(blank=True, help_text='Denormalised cap derived from RRULE UNTIL/COUNT, or null for open-ended.', null=True)),
                ('reminder_minutes_before', models.PositiveIntegerField(blank=True, help_text='null → use UserProfile.default_reminder_minutes; 0 → no reminder; >0 → override in minutes.', null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts.organization')),
                ('team', models.ForeignKey(blank=True, help_text='Optional. Required when visibility=team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='workspace.team')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='calendar.calendarevent')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_event_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEventOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_start', models.DateTimeField(help_text='The UTC start the RRULE would have produced. Identifies the occurrence.')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='calendar.calendarevent')),
            ],
        ),
        migrations.CreateModel(
            name='IcalFeedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_feed_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['organization', 'starts_at'], name='calendar_event_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['creator', 'starts_at'], name='cal_event_creator_start_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['team', 'starts_at'], name='calendar_event_team_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='calendar_event_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='calendareventattendee',
            index=models.Index(fields=['user', 'event'], name='cal_attendee_user_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendareventattendee',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='calendar_attendee_event_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='calendareventoccurrence',
            index=models.Index(fields=['event', 'original_start'], name='calendar_occ_event_orig_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendareventoccurrence',
            constraint=models.UniqueConstraint(fields=('event', 'original_start'), name='calendar_occurrence_event_original_uniq'),
        ),
        migrations.AddIndex(
            model_name='icalfeedtoken',
            index=models.Index(fields=['user', 'revoked_at'], name='ical_token_user_revoked_idx'),
        ),
    ]
