import { registerResource } from "../index";

registerResource({
  key: "escalations",
  module: "projects",
  label: "Escalation",
  labelPlural: "Escalations",
  endpoint: "/projects/field-operations/escalations/",
  columns: [
    { key: "title", label: "Title", type: "text", sortable: true },
    { key: "project", label: "Project", type: "text" },
    { key: "issue_category", label: "Category", type: "badge" },
    { key: "severity", label: "Severity", type: "badge" },
    { key: "status", label: "Status", type: "badge" },
    { key: "owner_name", label: "Owner", type: "text" },
    { key: "due_date", label: "Due Date", type: "date", sortable: true },
  ],
  filters: [
    { key: "search", label: "Search", type: "search", placeholder: "Search escalations..." },
    {
      key: "severity",
      label: "Severity",
      type: "select",
      options: [
        { value: "INFO", label: "Info" },
        { value: "REVIEW", label: "Review" },
        { value: "ACTION_REQUIRED", label: "Action Required" },
        { value: "ESCALATION", label: "Escalation" },
      ],
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "OPEN", label: "Open" },
        { value: "ACKNOWLEDGED", label: "Acknowledged" },
        { value: "IN_PROGRESS", label: "In Progress" },
        { value: "RESOLVED", label: "Resolved" },
        { value: "CLOSED", label: "Closed" },
      ],
    },
  ],
  formFields: [
    { key: "project", label: "Project", type: "relation_picker", required: true, optionsEndpoint: "/projects/" },
    { key: "title", label: "Title", type: "text", required: true },
    {
      key: "issue_category",
      label: "Issue Category",
      type: "select",
      options: [
        { value: "WEATHER", label: "Weather" },
        { value: "SAFETY", label: "Safety" },
        { value: "QUALITY", label: "Quality" },
        { value: "SCHEDULE", label: "Schedule" },
        { value: "COST", label: "Cost" },
        { value: "WORKFORCE", label: "Workforce" },
        { value: "PROCUREMENT", label: "Procurement" },
        { value: "EQUIPMENT", label: "Equipment" },
        { value: "DESIGN", label: "Design" },
        { value: "COMPLIANCE", label: "Compliance" },
        { value: "OTHER", label: "Other" },
      ],
    },
    {
      key: "severity",
      label: "Severity",
      type: "select",
      options: [
        { value: "INFO", label: "Info" },
        { value: "REVIEW", label: "Review" },
        { value: "ACTION_REQUIRED", label: "Action Required" },
        { value: "ESCALATION", label: "Escalation" },
      ],
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "OPEN", label: "Open" },
        { value: "ACKNOWLEDGED", label: "Acknowledged" },
        { value: "IN_PROGRESS", label: "In Progress" },
        { value: "RESOLVED", label: "Resolved" },
        { value: "CLOSED", label: "Closed" },
      ],
    },
    { key: "owner_name", label: "Owner Name", type: "text" },
    { key: "due_date", label: "Due Date", type: "date" },
    { key: "impact_summary", label: "Impact Summary", type: "textarea", gridSpan: 2 },
    { key: "root_cause", label: "Root Cause", type: "textarea", gridSpan: 2 },
    { key: "immediate_action", label: "Immediate Action", type: "textarea", gridSpan: 2 },
  ],
});
