import { registerResource } from "../index";

registerResource({
  key: "inspections",
  module: "projects",
  label: "Inspection",
  labelPlural: "Inspections",
  endpoint: "/projects/field-operations/quality-inspections/",
  columns: [
    { key: "inspection_number", label: "Inspection #", type: "text", sortable: true },
    { key: "project", label: "Project", type: "text" },
    { key: "inspection_type", label: "Type", type: "badge" },
    { key: "status", label: "Status", type: "badge" },
    { key: "inspected_on", label: "Inspected On", type: "date", sortable: true },
    { key: "overall_score", label: "Overall Score", type: "number" },
  ],
  filters: [
    { key: "search", label: "Search", type: "search", placeholder: "Search inspections..." },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "PLANNED", label: "Planned" },
        { value: "IN_PROGRESS", label: "In Progress" },
        { value: "PASSED", label: "Passed" },
        { value: "FAILED", label: "Failed" },
        { value: "BLOCKED", label: "Blocked" },
        { value: "CLOSED", label: "Closed" },
      ],
    },
    {
      key: "inspection_type",
      label: "Inspection Type",
      type: "select",
      options: [
        { value: "MATERIAL_RECEIPT", label: "Material Receipt" },
        { value: "WORKMANSHIP", label: "Workmanship" },
        { value: "MEP", label: "MEP" },
        { value: "FINISHES", label: "Finishes" },
        { value: "SAFETY_QUALITY", label: "Safety & Quality" },
        { value: "PRE_HANDOVER", label: "Pre-Handover" },
        { value: "OTHER", label: "Other" },
      ],
    },
  ],
  formFields: [
    { key: "project", label: "Project", type: "relation_picker", required: true, optionsEndpoint: "/projects/" },
    {
      key: "inspection_type",
      label: "Inspection Type",
      type: "select",
      required: true,
      options: [
        { value: "MATERIAL_RECEIPT", label: "Material Receipt" },
        { value: "WORKMANSHIP", label: "Workmanship" },
        { value: "MEP", label: "MEP" },
        { value: "FINISHES", label: "Finishes" },
        { value: "SAFETY_QUALITY", label: "Safety & Quality" },
        { value: "PRE_HANDOVER", label: "Pre-Handover" },
        { value: "OTHER", label: "Other" },
      ],
    },
    { key: "inspected_on", label: "Inspected On", type: "date", required: true },
    {
      key: "shift",
      label: "Shift",
      type: "select",
      options: [
        { value: "DAY", label: "Day" },
        { value: "NIGHT", label: "Night" },
        { value: "FULL_DAY", label: "Full Day" },
      ],
    },
    { key: "work_package", label: "Work Package", type: "text" },
    { key: "location", label: "Location", type: "text" },
    { key: "inspector_name", label: "Inspector Name", type: "text" },
    { key: "inspector_role", label: "Inspector Role", type: "text" },
    { key: "overall_score", label: "Overall Score", type: "number" },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { value: "PLANNED", label: "Planned" },
        { value: "IN_PROGRESS", label: "In Progress" },
        { value: "PASSED", label: "Passed" },
        { value: "FAILED", label: "Failed" },
        { value: "BLOCKED", label: "Blocked" },
        { value: "CLOSED", label: "Closed" },
      ],
    },
    { key: "observations", label: "Observations", type: "textarea", gridSpan: 2 },
    { key: "corrective_actions", label: "Corrective Actions", type: "textarea", gridSpan: 2 },
  ],
});
