# Generated by Django 5.2 on 2026-02-28 07:52

import django.db.models.deletion
from django.db import migrations, models

import apps.properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.properties.models.property_document_path)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('deed', 'Deed'), ('contract', 'Contract'), ('survey', 'Survey'), ('permit', 'Permit'), ('inspection', 'Inspection Report'), ('appraisal', 'Appraisal'), ('insurance', 'Insurance'), ('tax', 'Tax Document'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.properties.models.property_image_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['sort_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valuation_type', models.CharField(choices=[('appraisal', 'Professional Appraisal'), ('internal', 'Internal Estimate'), ('market', 'Market Comparable'), ('tax', 'Tax Assessment')], default='internal', max_length=20)),
                ('appraiser', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.property')),
            ],
            options={
                'ordering': ['-valuation_date'],
            },
        ),
    ]
