# Generated by Django 5.2 on 2026-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('land', 'Land Parcel'), ('building', 'Building'), ('mixed', 'Mixed-Use'), ('estate', 'Estate'), ('warehouse', 'Warehouse'), ('industrial', 'Industrial')], max_length=20),
        ),
    ]
