# Generated by Django 5.2 on 2026-02-28 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='classification',
            field=models.CharField(choices=[('owned', 'Owned'), ('lease', 'Lease'), ('concession', 'Concession'), ('under_development', 'Under Development')], default='owned', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude in decimal degrees (-90 to 90)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude in decimal degrees (-180 to 180)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='document_type',
            field=models.CharField(choices=[('deed', 'Deed'), ('contract', 'Contract'), ('survey', 'Survey'), ('permit', 'Permit'), ('inspection', 'Inspection Report'), ('appraisal', 'Appraisal'), ('insurance', 'Insurance'), ('tax', 'Tax Document'), ('certificate_of_occupancy', 'Certificate of Occupancy'), ('lease_agreement', 'Lease Agreement'), ('easement', 'Easement'), ('mortgage', 'Mortgage'), ('government_approval', 'Government Approval'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='PropertyEncumbrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encumbrance_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('lien', 'Lien'), ('legal_dispute', 'Legal Dispute'), ('court_case', 'Court Case'), ('tax_arrears', 'Tax Arrears')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('pending', 'Pending')], default='active', max_length=20)),
                ('date_filed', models.DateField()),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encumbrances', to='properties.property')),
            ],
            options={
                'ordering': ['-date_filed'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_owner_name', models.CharField(max_length=255)),
                ('ownership_structure', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('trust', 'Trust'), ('joint_venture', 'Joint Venture')], default='individual', max_length=20)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of ownership (0.00 - 100.00)', max_digits=5)),
                ('title_deed_number', models.CharField(max_length=100)),
                ('registration_authority', models.CharField(max_length=255)),
                ('date_of_registration', models.DateField()),
                ('deed_expiry', models.DateField(blank=True, help_text='Applicable for leasehold properties', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'property ownerships',
                'ordering': ['-ownership_percentage'],
            },
        ),
    ]
