# Generated by Django 5.2 on 2026-03-03 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_add_work_order_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('specialization', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('structural', 'Structural'), ('mechanical', 'Mechanical'), ('fire_safety', 'Fire & Safety'), ('elevator', 'Elevators'), ('generator', 'Generators'), ('water_systems', 'Water Systems'), ('security', 'Security Systems'), ('cleaning', 'Cleaning'), ('landscaping', 'Landscaping'), ('painting', 'Painting'), ('general', 'General')], default='general', max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Vendor rating (0.0 - 5.0)', max_digits=3, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('structural', 'Structural'), ('mechanical', 'Mechanical'), ('cleaning', 'Cleaning'), ('landscaping', 'Landscaping'), ('security', 'Security'), ('painting', 'Painting'), ('fire_safety', 'Fire Safety'), ('elevator', 'Elevator'), ('generator', 'Generator'), ('water_systems', 'Water Systems'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(help_text='Unique asset identifier (e.g. AST-0001)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('structural', 'Structural'), ('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('fire_safety', 'Fire & Safety'), ('elevator', 'Elevators'), ('generator', 'Generators'), ('water_systems', 'Water Systems'), ('security', 'Security Systems')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location_description', models.CharField(blank=True, help_text='Physical location within the property', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('expected_useful_life_years', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=10)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_components', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_components', to='properties.unit')),
            ],
            options={
                'ordering': ['component_id'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='asset_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='properties.assetcomponent'),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inspection_type', models.CharField(choices=[('routine', 'Routine'), ('safety', 'Safety'), ('compliance', 'Compliance'), ('pre_handover', 'Pre-Handover'), ('post_incident', 'Post-Incident'), ('condition_survey', 'Condition Survey')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('inspector', models.CharField(blank=True, max_length=255)),
                ('findings', models.TextField(blank=True)),
                ('rating', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass')], max_length=15)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='properties.assetcomponent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='properties.unit')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='properties.maintenancevendor'),
        ),
        migrations.CreateModel(
            name='PreventiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('structural', 'Structural'), ('mechanical', 'Mechanical'), ('cleaning', 'Cleaning'), ('landscaping', 'Landscaping'), ('security', 'Security'), ('painting', 'Painting'), ('fire_safety', 'Fire Safety'), ('elevator', 'Elevator'), ('generator', 'Generator'), ('water_systems', 'Water Systems'), ('general', 'General')], default='general', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=15)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('next_due_date', models.DateField()),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_schedules', to='properties.assetcomponent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventive_schedules', to='properties.property')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_schedules', to='properties.maintenancevendor')),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('structural', 'Structural'), ('mechanical', 'Mechanical'), ('cleaning', 'Cleaning'), ('landscaping', 'Landscaping'), ('security', 'Security'), ('painting', 'Painting'), ('fire_safety', 'Fire Safety'), ('elevator', 'Elevator'), ('generator', 'Generator'), ('water_systems', 'Water Systems'), ('general', 'General')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('requested_by', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='properties.property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='properties.unit')),
                ('work_order', models.ForeignKey(blank=True, help_text='Work order created from this service request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='properties.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
