# Generated by Django 5.2 on 2026-03-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_full_maintenance_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='compliance_status',
            field=models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('pending_review', 'Pending Review')], max_length=20),
        ),
        migrations.AddField(
            model_name='inspection',
            name='corrective_action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('routine', 'Routine'), ('safety', 'Safety'), ('compliance', 'Compliance'), ('pre_handover', 'Pre-Handover'), ('post_incident', 'Post-Incident'), ('condition_survey', 'Condition Survey'), ('fire_safety', 'Fire Safety'), ('electrical', 'Electrical Inspection'), ('structural_integrity', 'Structural Integrity'), ('elevator_certification', 'Elevator Certification'), ('environmental_audit', 'Environmental Audit'), ('health_safety', 'Health & Safety')], default='routine', max_length=25),
        ),
    ]
