# Generated by Django 5.2 on 2026-03-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('properties', '0009_add_organization_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assetcomponent',
            index=models.Index(fields=['organization', '-created_at'], name='prop_ac_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['organization', '-created_at'], name='prop_insp_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancevendor',
            index=models.Index(fields=['organization', '-created_at'], name='prop_mven_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='preventiveschedule',
            index=models.Index(fields=['organization', 'status'], name='prop_ps_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='preventiveschedule',
            index=models.Index(fields=['organization', '-created_at'], name='prop_ps_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['organization', '-created_at'], name='prop_prop_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydocument',
            index=models.Index(fields=['organization', '-uploaded_at'], name='prop_doc_org_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyencumbrance',
            index=models.Index(fields=['organization', 'status'], name='prop_enc_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyencumbrance',
            index=models.Index(fields=['organization', '-created_at'], name='prop_enc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['organization', '-uploaded_at'], name='prop_img_org_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyownership',
            index=models.Index(fields=['organization', '-created_at'], name='prop_own_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvaluation',
            index=models.Index(fields=['organization', '-created_at'], name='prop_val_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'status'], name='prop_sr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', '-created_at'], name='prop_sr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['organization', 'status'], name='prop_unit_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['organization', '-created_at'], name='prop_unit_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'status'], name='prop_wo_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', '-created_at'], name='prop_wo_org_created_idx'),
        ),
    ]
