# Generated by Django 5.2 on 2026-03-08 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_demorequest'),
        ('crm', '0007_broker_crm_brkr_org_status_idx_and_more'),
        ('properties', '0010_assetcomponent_prop_ac_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude in decimal degrees (-90 to 90)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude in decimal degrees (-180 to 180)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='location_description',
            field=models.CharField(blank=True, help_text='Textual location within the property (e.g., Block A, Level 3, East Wing)', max_length=255),
        ),
        migrations.CreateModel(
            name='PropertyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('leased', 'Leased'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('held_by', models.CharField(blank=True, help_text='Name or identifier of who placed the hold', max_length=255)),
                ('held_until', models.DateTimeField(blank=True, help_text='When the hold automatically expires', null=True)),
                ('allocated_to', models.CharField(blank=True, help_text='Buyer or tenant name', max_length=255)),
                ('allocated_on', models.DateField(blank=True, null=True)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current listing price (may differ from Unit.asking_price catalog price)', max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_property_inventories', to='accounts.organization')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_records', to='crm.unitreservation')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='properties.unit')),
            ],
            options={
                'verbose_name': 'Property Inventory',
                'verbose_name_plural': 'Property Inventories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('listed', 'Listed'), ('held', 'Held'), ('hold_released', 'Hold Released'), ('hold_expired', 'Hold Expired'), ('reserved', 'Reserved'), ('reservation_cancelled', 'Reservation Cancelled'), ('sold', 'Sold'), ('leased', 'Leased'), ('made_unavailable', 'Made Unavailable'), ('made_available', 'Made Available'), ('price_changed', 'Price Changed'), ('note_added', 'Note Added')], max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible data (e.g., price change details, hold duration)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inventory_events', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='properties.propertyinventory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_property_inventory_events', to='accounts.organization')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='crm.unitreservation')),
            ],
            options={
                'verbose_name': 'Property Inventory Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertyinventory',
            index=models.Index(fields=['organization', 'status'], name='prop_inv_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinventory',
            index=models.Index(fields=['organization', '-updated_at'], name='prop_inv_org_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinventoryevent',
            index=models.Index(fields=['organization', '-created_at'], name='prop_inv_evt_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyinventoryevent',
            index=models.Index(fields=['inventory', '-created_at'], name='prop_inv_evt_inv_created_idx'),
        ),
    ]
