# Generated by Django 5.2 on 2026-03-08 16:29

from django.db import migrations


def create_inventory_for_existing_units(apps, schema_editor):
    Unit = apps.get_model("properties", "Unit")
    PropertyInventory = apps.get_model("properties", "PropertyInventory")
    PropertyInventoryEvent = apps.get_model("properties", "PropertyInventoryEvent")

    for unit in Unit.objects.select_related("property").all():
        inv, created = PropertyInventory.objects.get_or_create(
            unit=unit,
            defaults={
                "organization_id": unit.organization_id,
                "status": unit.status,
                "list_price": unit.asking_price,
            },
        )
        if created:
            PropertyInventoryEvent.objects.create(
                organization_id=unit.organization_id,
                inventory=inv,
                event_type="listed",
                from_status="",
                to_status=unit.status,
                actor_name="System",
                notes="Initial inventory record created by migration",
            )


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_add_unit_gps_and_inventory'),
    ]

    operations = [
        migrations.RunPython(
            create_inventory_for_existing_units,
            reverse_noop,
        ),
    ]
