# Generated by Django 5.2.12 on 2026-03-17 12:50

from django.db import migrations, models


def backfill_unit_categories(apps, schema_editor):
    Unit = apps.get_model("properties", "Unit")
    for unit in Unit.objects.select_related("property").iterator(chunk_size=500):
        property_type = getattr(unit.property, "property_type", "")
        if property_type == "land":
            next_category = "land"
        elif property_type in {"warehouse", "industrial"}:
            next_category = "warehouse"
        else:
            next_category = "apartment"
        if unit.unit_category != next_category:
            Unit.objects.filter(pk=unit.pk).update(unit_category=next_category)


def reverse_backfill_unit_categories(apps, schema_editor):
    Unit = apps.get_model("properties", "Unit")
    Unit.objects.update(unit_category="apartment")


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_populate_property_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="unit_category",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("townhouse", "Townhouse"),
                    ("penthouse", "Penthouse"),
                    ("studio", "Studio"),
                    ("duplex", "Duplex"),
                    ("office", "Office"),
                    ("retail", "Retail"),
                    ("warehouse", "Warehouse"),
                    ("land", "Land"),
                    ("other", "Other"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_unit_categories,
            reverse_code=reverse_backfill_unit_categories,
        ),
    ]
