# Generated by Django 5.2.12 on 2026-03-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('facility_management', '0002_facility_facilityfloor_facilityzone_and_more'),
        ('properties', '0014_asset_management_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictiveMaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('urgent', 'Urgent')], default='high', max_length=10)),
                ('trigger_type', models.CharField(choices=[('iot_offline', 'IoT Offline'), ('iot_fault', 'IoT Fault'), ('runtime_hours', 'Runtime Hours'), ('cycle_count', 'Cycle Count')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('work_order_created', 'Work Order Created'), ('resolved', 'Resolved')], default='open', max_length=25)),
                ('runtime_hours_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cycle_reading', models.PositiveIntegerField(blank=True, null=True)),
                ('iot_status', models.CharField(blank=True, max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-triggered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveMaintenanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('urgent', 'Urgent')], default='high', max_length=10)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('sla_target_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime_hours_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cycle_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('runtime_hours_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cycle_reading', models.PositiveIntegerField(blank=True, null=True)),
                ('alert_on_offline', models.BooleanField(default=True)),
                ('alert_on_fault', models.BooleanField(default=True)),
                ('auto_create_work_order', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='auto_create_work_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_schedules', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='facility_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventive_schedules', to='facility_management.facilityunitspace'),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='generate_days_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='last_generated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='last_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.workorder'),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='preventiveschedule',
            name='sla_target_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='facility_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='facility_management.facilityunitspace'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_breakdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='maintenance_mode',
            field=models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive'), ('predictive', 'Predictive')], default='corrective', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='preventive_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_work_orders', to='properties.preventiveschedule'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='sla_target_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='verified_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='open', max_length=15),
        ),
        migrations.AddIndex(
            model_name='preventiveschedule',
            index=models.Index(fields=['organization', 'facility'], name='prop_ps_org_facility_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'maintenance_mode'], name='prop_wo_org_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'facility'], name='prop_wo_org_facility_idx'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancealert',
            name='asset_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictive_alerts', to='properties.assetcomponent'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancealert',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictive_alerts', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancealert',
            name='facility_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictive_alerts', to='facility_management.facilityunitspace'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancealert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_predictive_maintenance_alerts', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancealert',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_maintenance_alerts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancealert',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictive_alerts', to='properties.workorder'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancerule',
            name='asset_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictive_rules', to='properties.assetcomponent'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancerule',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictive_rules', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancerule',
            name='facility_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictive_rules', to='facility_management.facilityunitspace'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancerule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_predictive_maintenance_rules', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancerule',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_maintenance_rules', to='properties.property'),
        ),
        migrations.AddField(
            model_name='predictivemaintenancealert',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='properties.predictivemaintenancerule'),
        ),
        migrations.AddIndex(
            model_name='predictivemaintenancerule',
            index=models.Index(fields=['organization', 'is_active'], name='prop_pr_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivemaintenancerule',
            index=models.Index(fields=['organization', 'facility'], name='prop_pr_org_facility_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivemaintenancealert',
            index=models.Index(fields=['organization', 'status'], name='prop_pa_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='predictivemaintenancealert',
            index=models.Index(fields=['organization', 'rule'], name='prop_pa_org_rule_idx'),
        ),
    ]
