# Generated by Django 5.2.12 on 2026-03-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0016_servicerequest_assigned_agent_and_more"),
        ("tenants", "0009_tenantprofile_satisfaction_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="tenant_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="tenants.tenantprofile",
            ),
        ),
    ]
