# Generated by Django 5.2 on 2026-03-07 05:38

import apps.hr.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_accounts_us_user_id_fb1424_idx_accounts_us_user_id_7d84e2_idx_and_more'),
        ('hr', '0004_continuousfeedback_documentcollectionitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('issuing_body', models.CharField(max_length=300)),
                ('credential_id', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('verification_url', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.hr.models.hr_certification_upload_to)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.organization')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_area', models.CharField(max_length=200)),
                ('assessment_date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('strengths', models.TextField(blank=True)),
                ('gaps', models.TextField(blank=True)),
                ('development_plan', models.TextField(blank=True)),
                ('next_assessment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to='accounts.organization')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=200)),
                ('issuing_authority', models.CharField(max_length=300)),
                ('jurisdiction', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending Renewal'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.hr.models.hr_license_upload_to)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_licenses', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_licenses', to='accounts.organization')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('management', 'Management'), ('soft', 'Soft Skill'), ('domain', 'Domain Knowledge'), ('regulatory', 'Regulatory')], default='technical', max_length=15)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=15)),
                ('years_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('provider', models.CharField(blank=True, max_length=300)),
                ('delivery_method', models.CharField(choices=[('in_person', 'In-Person'), ('online', 'Online'), ('hybrid', 'Hybrid'), ('self_paced', 'Self-Paced')], default='in_person', max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='enrolled', max_length=15)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('certificate', models.FileField(blank=True, null=True, upload_to=apps.hr.models.hr_training_upload_to)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='accounts.organization')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
