# Generated by Django 5.2 on 2026-03-07 06:01

import apps.settings.currency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_certification_competencyassessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='currency',
            field=models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3),
        ),
        migrations.AlterField(
            model_name='compensationrecord',
            name='currency',
            field=models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='currency',
            field=models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='currency',
            field=models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3),
        ),
        migrations.AlterField(
            model_name='jobrequisition',
            name='currency',
            field=models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='currency',
            field=models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3),
        ),
    ]
