# Generated by Django 5.2 on 2026-03-07 06:59

import apps.settings.currency
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_accounts_us_user_id_fb1424_idx_accounts_us_user_id_7d84e2_idx_and_more'),
        ('hr', '0008_leavetype_leaverequest_overtimerequest_attendancelog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('housing', 'Housing'), ('transport', 'Transport'), ('meal', 'Meal'), ('phone', 'Phone'), ('medical', 'Medical'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=12)),
                ('name', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One-Time')], default='monthly', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_allowances', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('performance', 'Performance'), ('annual', 'Annual'), ('signing', 'Signing'), ('referral', 'Referral'), ('project', 'Project'), ('other', 'Other')], default='other', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bonuses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_bonuses', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'bonuses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('tax', 'Tax'), ('insurance', 'Insurance'), ('pension', 'Pension'), ('loan', 'Loan Repayment'), ('union', 'Union Dues'), ('other', 'Other')], default='other', max_length=12)),
                ('name', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_time', 'One-Time')], default='monthly', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_deductions', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('run_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='accounts.organization')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], default='draft', max_length=14)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='accounts.organization')),
                ('payroll_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='hr.payrollrun')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('grade_level', models.PositiveIntegerField(blank=True, help_text='Numeric grade level for ordering', null=True)),
                ('min_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='accounts.organization')),
            ],
            options={
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='e.g. 2025-2026', max_length=9)),
                ('tax_type', models.CharField(choices=[('income_tax', 'Income Tax'), ('social_security', 'Social Security'), ('municipal', 'Municipal Tax'), ('other', 'Other')], default='income_tax', max_length=16)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('filing_status', models.CharField(choices=[('pending', 'Pending'), ('filed', 'Filed'), ('assessed', 'Assessed'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='hr.employeerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_tax_records', to='accounts.organization')),
            ],
            options={
                'ordering': ['-fiscal_year', 'tax_type'],
            },
        ),
    ]
