# Generated by Django 5.2 on 2026-03-07 08:16

import apps.settings.currency
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_accounts_us_user_id_fb1424_idx_accounts_us_user_id_7d84e2_idx_and_more'),
        ('hr', '0010_disciplinaryrecord_exitmanagement_exitinterview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStaffingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('department', models.CharField(max_length=200)),
                ('budgeted_positions', models.PositiveIntegerField(default=0)),
                ('filled_positions', models.PositiveIntegerField(default=0)),
                ('vacant_positions', models.PositiveIntegerField(default=0)),
                ('pending_hires', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_dept_staffing_reports', to='accounts.organization')),
            ],
            options={
                'ordering': ['-report_date', 'department'],
            },
        ),
        migrations.CreateModel(
            name='DiversityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=200)),
                ('dimension', models.CharField(choices=[('gender', 'Gender'), ('age_group', 'Age Group'), ('ethnicity', 'Ethnicity'), ('nationality', 'Nationality'), ('disability', 'Disability')], max_length=16)),
                ('category_value', models.CharField(help_text='e.g. Male, Female, 25-34, etc.', max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_diversity_metrics', to='accounts.organization')),
            ],
            options={
                'ordering': ['-snapshot_date', 'dimension', '-count'],
            },
        ),
        migrations.CreateModel(
            name='HeadcountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('department', models.CharField(blank=True, max_length=200)),
                ('team', models.CharField(blank=True, max_length=200)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('inactive_count', models.PositiveIntegerField(default=0)),
                ('new_hires', models.PositiveIntegerField(default=0)),
                ('departures', models.PositiveIntegerField(default=0)),
                ('contractors', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_headcount_snapshots', to='accounts.organization')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='HiringFunnelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('department', models.CharField(blank=True, max_length=200)),
                ('requisitions_opened', models.PositiveIntegerField(default=0)),
                ('applications_received', models.PositiveIntegerField(default=0)),
                ('candidates_screened', models.PositiveIntegerField(default=0)),
                ('candidates_interviewed', models.PositiveIntegerField(default=0)),
                ('offers_made', models.PositiveIntegerField(default=0)),
                ('offers_accepted', models.PositiveIntegerField(default=0)),
                ('avg_time_to_hire_days', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('avg_cost_per_hire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_hiring_funnel_metrics', to='accounts.organization')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='TurnoverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('department', models.CharField(blank=True, max_length=200)),
                ('starting_headcount', models.PositiveIntegerField(default=0)),
                ('ending_headcount', models.PositiveIntegerField(default=0)),
                ('voluntary_departures', models.PositiveIntegerField(default=0)),
                ('involuntary_departures', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_turnover_records', to='accounts.organization')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceCostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('department', models.CharField(blank=True, max_length=200)),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_benefits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_overtime', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default=apps.settings.currency.get_default_currency_code, max_length=3)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_workforce_cost_reports', to='accounts.organization')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
    ]
