# Generated by Django 5.2 on 2026-03-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_accounts_us_user_id_fb1424_idx_accounts_us_user_id_7d84e2_idx_and_more'),
        ('hr', '0011_workforce_analytics_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('regulation', 'Regulation'), ('certification', 'Certification'), ('audit_report', 'Audit Report'), ('legal', 'Legal'), ('policy', 'Policy'), ('other', 'Other')], default='policy', max_length=16)),
                ('status', models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('pending_review', 'Pending Review'), ('archived', 'Archived')], default='current', max_length=16)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_compliance_documents', to='accounts.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHandbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handbook_version', models.CharField(blank=True, max_length=30)),
                ('section_number', models.CharField(help_text='e.g. 1.0, 2.3', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_handbook_sections_updated', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_handbook_sections', to='accounts.organization')),
            ],
            options={
                'ordering': ['order', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='HRDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('contract', 'Contract'), ('warning_letter', 'Warning Letter'), ('termination', 'Termination'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('general', 'General'), ('other', 'Other')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Template body with placeholders')),
                ('version', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_document_templates_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_document_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HRPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('general', 'General'), ('employment', 'Employment'), ('compensation', 'Compensation'), ('leave', 'Leave'), ('conduct', 'Code of Conduct'), ('safety', 'Health & Safety'), ('data_privacy', 'Data Privacy'), ('other', 'Other')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('version', models.CharField(blank=True, max_length=30)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, help_text='Full policy text or rich content')),
                ('department', models.CharField(blank=True, help_text='Leave blank for org-wide policies', max_length=200)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_policies_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_policies_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_policies', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'HR Policies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_policy_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_policy_acknowledgements', to='accounts.organization')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='hr.hrpolicy')),
            ],
            options={
                'ordering': ['-acknowledged_date'],
                'unique_together': {('employee', 'policy')},
            },
        ),
    ]
