# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('hr', '0012_hr_documents_policies_models'),
        ('settings', '0056_autoescalationrule_set_aer_org_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='allowance',
            index=models.Index(fields=['organization', '-created_at'], name='hr_alw_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['organization', 'status'], name='hr_att_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['organization', '-created_at'], name='hr_att_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['organization', 'status'], name='hr_bon_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['organization', '-created_at'], name='hr_bon_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['organization', '-created_at'], name='hr_cand_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateevaluation',
            index=models.Index(fields=['organization', '-created_at'], name='hr_cevl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['organization', 'status'], name='hr_cert_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['organization', '-created_at'], name='hr_cert_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='certificationexpiryalert',
            index=models.Index(fields=['organization', 'status'], name='hr_cea_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='certificationexpiryalert',
            index=models.Index(fields=['organization', '-created_at'], name='hr_cea_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationrecord',
            index=models.Index(fields=['organization', 'status'], name='hr_comp_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationrecord',
            index=models.Index(fields=['organization', '-created_at'], name='hr_comp_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyassessment',
            index=models.Index(fields=['organization', 'status'], name='hr_cass_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='competencyassessment',
            index=models.Index(fields=['organization', '-created_at'], name='hr_cass_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancedocument',
            index=models.Index(fields=['organization', 'status'], name='hr_cdoc_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancedocument',
            index=models.Index(fields=['organization', '-created_at'], name='hr_cdoc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='continuousfeedback',
            index=models.Index(fields=['organization', '-created_at'], name='hr_cfb_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['organization', 'status'], name='hr_cenr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['organization', '-created_at'], name='hr_cenr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deduction',
            index=models.Index(fields=['organization', '-created_at'], name='hr_ded_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentstaffingreport',
            index=models.Index(fields=['organization', '-created_at'], name='hr_dsr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinaryrecord',
            index=models.Index(fields=['organization', 'status'], name='hr_disc_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinaryrecord',
            index=models.Index(fields=['organization', '-created_at'], name='hr_disc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='diversitymetric',
            index=models.Index(fields=['organization', '-created_at'], name='hr_dvm_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollectionitem',
            index=models.Index(fields=['organization', 'status'], name='hr_dci_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollectionitem',
            index=models.Index(fields=['organization', '-created_at'], name='hr_dci_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['organization', '-created_at'], name='hr_econ_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='employeehandbooksection',
            index=models.Index(fields=['organization', 'status'], name='hr_ehbs_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employeehandbooksection',
            index=models.Index(fields=['organization', '-created_at'], name='hr_ehbs_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['organization', '-created_at'], name='hr_erec_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentallocation',
            index=models.Index(fields=['organization', 'status'], name='hr_eqal_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentallocation',
            index=models.Index(fields=['organization', '-created_at'], name='hr_eqal_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='exitinterview',
            index=models.Index(fields=['organization', '-created_at'], name='hr_eint_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='exitmanagement',
            index=models.Index(fields=['organization', 'clearance_status'], name='hr_exit_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exitmanagement',
            index=models.Index(fields=['organization', '-created_at'], name='hr_exit_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='headcountsnapshot',
            index=models.Index(fields=['organization', '-created_at'], name='hr_hsnp_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringfunnelmetric',
            index=models.Index(fields=['organization', '-created_at'], name='hr_hfm_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdocument',
            index=models.Index(fields=['organization', '-created_at'], name='hr_hdoc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdocumenttemplate',
            index=models.Index(fields=['organization', 'status'], name='hr_dtpl_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdocumenttemplate',
            index=models.Index(fields=['organization', '-created_at'], name='hr_dtpl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpolicy',
            index=models.Index(fields=['organization', 'status'], name='hr_hpol_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hrpolicy',
            index=models.Index(fields=['organization', '-created_at'], name='hr_hpol_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='identificationdocument',
            index=models.Index(fields=['organization', '-created_at'], name='hr_idoc_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['organization', 'status'], name='hr_intv_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['organization', '-created_at'], name='hr_intv_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['organization', 'status'], name='hr_jlst_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['organization', '-created_at'], name='hr_jlst_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['organization', 'status'], name='hr_jofr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['organization', '-created_at'], name='hr_jofr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['organization', 'status'], name='hr_jreq_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequisition',
            index=models.Index(fields=['organization', '-created_at'], name='hr_jreq_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['organization', 'status'], name='hr_lres_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['organization', '-created_at'], name='hr_lres_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['organization', '-created_at'], name='hr_lbal_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['organization', 'status'], name='hr_lreq_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['organization', '-created_at'], name='hr_lreq_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['organization', '-created_at'], name='hr_ltyp_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='managerevaluation',
            index=models.Index(fields=['organization', '-created_at'], name='hr_mevl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtask',
            index=models.Index(fields=['organization', 'status'], name='hr_obtsk_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtask',
            index=models.Index(fields=['organization', '-created_at'], name='hr_obtsk_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['organization', '-created_at'], name='hr_obtpl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orientationchecklistitem',
            index=models.Index(fields=['organization', '-created_at'], name='hr_oci_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['organization', 'status'], name='hr_otr_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['organization', '-created_at'], name='hr_otr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['organization', 'status'], name='hr_prun_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['organization', '-created_at'], name='hr_prun_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['organization', 'status'], name='hr_pslp_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['organization', '-created_at'], name='hr_pslp_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='peerreview',
            index=models.Index(fields=['organization', 'status'], name='hr_peer_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='peerreview',
            index=models.Index(fields=['organization', '-created_at'], name='hr_peer_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='performancegoal',
            index=models.Index(fields=['organization', 'status'], name='hr_pgoal_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='performancegoal',
            index=models.Index(fields=['organization', '-created_at'], name='hr_pgoal_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceimprovementplan',
            index=models.Index(fields=['organization', 'status'], name='hr_pip_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='performanceimprovementplan',
            index=models.Index(fields=['organization', '-created_at'], name='hr_pip_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['organization', 'status'], name='hr_prev_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['organization', '-created_at'], name='hr_prev_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgement',
            index=models.Index(fields=['organization', '-created_at'], name='hr_pack_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organization', 'status'], name='hr_pos_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['organization', '-created_at'], name='hr_pos_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='positionassignment',
            index=models.Index(fields=['organization', '-created_at'], name='hr_pasn_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='positionbudget',
            index=models.Index(fields=['organization', 'status'], name='hr_pbud_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='positionbudget',
            index=models.Index(fields=['organization', '-created_at'], name='hr_pbud_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='probationrecord',
            index=models.Index(fields=['organization', 'status'], name='hr_prob_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='probationrecord',
            index=models.Index(fields=['organization', '-created_at'], name='hr_prob_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallicense',
            index=models.Index(fields=['organization', 'status'], name='hr_plic_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='professionallicense',
            index=models.Index(fields=['organization', '-created_at'], name='hr_plic_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['organization', 'status'], name='hr_promo_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['organization', '-created_at'], name='hr_promo_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteworklog',
            index=models.Index(fields=['organization', 'status'], name='hr_rwl_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='remoteworklog',
            index=models.Index(fields=['organization', '-created_at'], name='hr_rwl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='rolechange',
            index=models.Index(fields=['organization', 'status'], name='hr_rchg_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rolechange',
            index=models.Index(fields=['organization', '-created_at'], name='hr_rchg_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='salarystructure',
            index=models.Index(fields=['organization', '-created_at'], name='hr_sal_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['organization', '-created_at'], name='hr_skill_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['organization', 'filing_status'], name='hr_tax_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrecord',
            index=models.Index(fields=['organization', '-created_at'], name='hr_tax_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['organization', '-created_at'], name='hr_team_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcompletion',
            index=models.Index(fields=['organization', '-created_at'], name='hr_tcom_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['organization', 'status'], name='hr_tcrs_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingcourse',
            index=models.Index(fields=['organization', '-created_at'], name='hr_tcrs_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['organization', 'status'], name='hr_tpln_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingplan',
            index=models.Index(fields=['organization', '-created_at'], name='hr_tpln_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['organization', 'status'], name='hr_trec_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['organization', '-created_at'], name='hr_trec_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['organization', 'status'], name='hr_tran_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['organization', '-created_at'], name='hr_tran_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='turnoverrecord',
            index=models.Index(fields=['organization', '-created_at'], name='hr_turn_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['organization', 'status'], name='hr_vac_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['organization', '-created_at'], name='hr_vac_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workforcecostreport',
            index=models.Index(fields=['organization', '-created_at'], name='hr_wcr_org_created_idx'),
        ),
    ]
