# Generated by Django 5.2 on 2026-03-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_allowance_hr_alw_org_created_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="team_type",
            field=models.CharField(
                choices=[
                    ("permanent", "Permanent"),
                    ("project_based", "Project-Based"),
                ],
                default="permanent",
                max_length=20,
            ),
        ),
    ]

