# Generated by Django 5.2 on 2026-03-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_team_team_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="position_roles", to="accounts.organization")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="position",
            name="role",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="positions", to="hr.positionrole"),
        ),
        migrations.AddIndex(
            model_name="positionrole",
            index=models.Index(fields=["organization", "-created_at"], name="hr_prol_org_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="positionrole",
            constraint=models.UniqueConstraint(condition=~models.Q(code=""), fields=("organization", "code"), name="hr_positionrole_org_code_uniq"),
        ),
    ]
