# Generated by Django 5.2 on 2026-03-15 02:04

import apps.hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_positionrole_position_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=apps.hr.models.hr_leave_attachment_upload_to),
        ),
    ]
