# Generated by Django 5.2 on 2026-03-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0015_positionrole_position_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionrole",
            name="grade",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="positionrole",
            name="hard_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="positionrole",
            name="key_responsibilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="positionrole",
            name="kpi_metrics",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="positionrole",
            name="soft_skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
