# Generated by Django 5.2 on 2026-03-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_leaverequest_attachment'),
        ('hr', '0017_positionrole_core_role_specs'),
    ]

    operations = [
    ]
