# Generated by Django 5.2 on 2026-03-15 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_merge_20260315_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='salary_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='hr.salarystructure'),
        ),
        migrations.AddField(
            model_name='position',
            name='slot_status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('filled', 'Filled'), ('proposed', 'Proposed')], default='vacant', max_length=10),
        ),
    ]
