# Generated by Django 5.2 on 2026-03-15 16:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0019_position_salary_structure_position_slot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="slot_status",
            field=models.CharField(
                choices=[("vacant", "Vacant"), ("filled", "Filled"), ("proposed", "Proposed")],
                default="proposed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="cfo_override_approved",
            field=models.BooleanField(
                default=False,
                help_text="Set when CFO-approved salary override is granted.",
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="cfo_override_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="cfo_override_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cfo_overridden_job_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="cfo_override_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="position",
            name="criticality_score",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0-100 score used to identify succession-critical roles.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="vacancy_alert_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp for last critical vacancy escalation alert.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="vacant_since",
            field=models.DateField(
                blank=True,
                help_text="Date the position last became vacant.",
                null=True,
            ),
        ),
    ]
