import { registerResource } from "../index";

registerResource({
  key: "kpi-definitions",
  module: "settings",
  label: "KPI Definition",
  labelPlural: "KPI Definitions",
  endpoint: "/settings/kpi-definitions/",
  columns: [
    { key: "id", label: "ID", type: "number", width: "w-16" },
    { key: "name", label: "Name", type: "text", sortable: true },
    { key: "code", label: "Code", type: "text" },
    { key: "category", label: "Category", type: "text", sortable: true },
    { key: "unit", label: "Unit", type: "text" },
    { key: "frequency", label: "Frequency", type: "text" },
    { key: "is_active", label: "Active", type: "boolean" },
  ],
  filters: [
    { key: "search", label: "Search", type: "search", placeholder: "Search KPI definitions..." },
    {
      key: "category",
      label: "Category",
      type: "select",
      options: [
        { value: "construction", label: "Construction" },
        { value: "sales", label: "Sales" },
        { value: "finance", label: "Finance" },
        { value: "operations", label: "Operations" },
        { value: "compliance", label: "Compliance" },
        { value: "hr", label: "HR" },
        { value: "procurement", label: "Procurement" },
        { value: "project_management", label: "Project Management" },
        { value: "property", label: "Property" },
        { value: "safety", label: "Safety" },
        { value: "quality", label: "Quality" },
      ],
    },
  ],
  formFields: [
    { key: "name", label: "Name", type: "text", required: true },
    { key: "code", label: "Code", type: "text", required: true },
    {
      key: "category",
      label: "Category",
      type: "select",
      required: true,
      options: [
        { value: "construction", label: "Construction" },
        { value: "sales", label: "Sales" },
        { value: "finance", label: "Finance" },
        { value: "operations", label: "Operations" },
        { value: "compliance", label: "Compliance" },
        { value: "hr", label: "HR" },
        { value: "procurement", label: "Procurement" },
        { value: "project_management", label: "Project Management" },
        { value: "property", label: "Property" },
        { value: "safety", label: "Safety" },
        { value: "quality", label: "Quality" },
      ],
    },
    {
      key: "unit",
      label: "Unit",
      type: "select",
      required: true,
      options: [
        { value: "percentage", label: "Percentage" },
        { value: "currency", label: "Currency" },
        { value: "count", label: "Count" },
        { value: "ratio", label: "Ratio" },
        { value: "days", label: "Days" },
        { value: "score", label: "Score" },
      ],
    },
    {
      key: "direction",
      label: "Direction",
      type: "select",
      options: [
        { value: "higher_is_better", label: "Higher is Better" },
        { value: "lower_is_better", label: "Lower is Better" },
      ],
    },
    {
      key: "frequency",
      label: "Frequency",
      type: "select",
      required: true,
      options: [
        { value: "daily", label: "Daily" },
        { value: "weekly", label: "Weekly" },
        { value: "monthly", label: "Monthly" },
        { value: "quarterly", label: "Quarterly" },
        { value: "annual", label: "Annual" },
      ],
    },
    { key: "description", label: "Description", type: "textarea", gridSpan: 2 },
    { key: "green_threshold", label: "Green Threshold", type: "number" },
    { key: "amber_threshold", label: "Amber Threshold", type: "number" },
    { key: "is_active", label: "Active", type: "boolean", defaultValue: true },
  ],
});
