# Generated by Django 5.2.10 on 2026-03-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0029_demorequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_hour', models.DateTimeField()),
                ('procurement_cycle_time_days', models.JSONField(default=dict)),
                ('cost_variance_per_project_pct', models.JSONField(default=dict)),
                ('vendor_reliability_score', models.JSONField(default=dict)),
                ('emergency_purchases_pct', models.JSONField(default=dict)),
                ('budget_overrun_frequency_pct', models.JSONField(default=dict)),
                ('average_approval_time_hours', models.JSONField(default=dict)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('computed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_board_kpi_snapshots', to='accounts.organization')),
            ],
            options={
                'ordering': ['-snapshot_hour'],
                'indexes': [models.Index(fields=['organization', '-snapshot_hour'], name='ana_bkpi_org_hour_idx')],
                'unique_together': {('organization', 'snapshot_hour')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_acquisition', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('property_count', models.IntegerField(default=0)),
                ('total_area_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_price_per_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unrealized_gain', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('type_distribution', models.JSONField(default=list)),
                ('classification_breakdown', models.JSONField(default=list)),
                ('valuation_history', models.JSONField(default=list)),
                ('unit_occupancy', models.JSONField(default=list)),
                ('project_budget_summary', models.JSONField(default=list)),
                ('top_appreciating', models.JSONField(default=list)),
                ('top_depreciating', models.JSONField(default=list)),
                ('encumbrance_summary', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_portfolio_snapshots', to='accounts.organization')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['organization', '-snapshot_date'], name='ana_port_org_date_idx')],
                'unique_together': {('organization', 'snapshot_date')},
            },
        ),
    ]
