# Generated by Django 5.2 on 2026-03-08 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_seed_celery_beat_snapshot_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False, help_text='If True, this dashboard loads on login for this user.')),
                ('layout', models.JSONField(default=list, help_text='List of widget configs: [{"widget_type": "board_kpi_card", "kpi_key": "procurement_cycle_time_days", "position": {"x": 0, "y": 0, "w": 4, "h": 2}, "config": {}}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='ana_cdash_user_updated_idx')],
            },
        ),
    ]
