# Generated by Django 5.2 on 2026-03-02 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userprofile_assigned_role'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('settings', '0015_alter_rolepermission_sub_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('financial_threshold', 'Financial Threshold'), ('procurement_threshold', 'Procurement Threshold'), ('contract_review', 'Contract Review Trigger'), ('change_order', 'Change Order Escalation')], max_length=30)),
                ('amount_field', models.CharField(default='total_amount', help_text='Field path on target model for threshold evaluation.', max_length=100)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = evaluated first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Target model this policy applies to.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_policies', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'approval policies',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_step_mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_content_types', models.ManyToManyField(blank=True, help_text='Content types this template can be attached to.', related_name='workflow_templates', to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('escalated', 'Escalated')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('matched_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='workflows.approvalpolicy')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_workflows', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalpolicy',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='workflows.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=160)),
                ('step_type', models.CharField(choices=[('approval', 'Approval'), ('notification', 'Notification Only'), ('condition', 'Conditional Branch')], default='approval', max_length=20)),
                ('execution_mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('approver_role_slug', models.SlugField(blank=True, help_text='settings.Role slug for the approver.', max_length=120)),
                ('sla_hours', models.PositiveIntegerField(blank=True, help_text='Hours to complete this step before escalation.', null=True)),
                ('escalation_role_slug', models.SlugField(blank=True, help_text='Role to escalate to when SLA breaches.', max_length=120)),
                ('condition_field', models.CharField(blank=True, help_text='Field path on target object to evaluate.', max_length=100)),
                ('condition_operator', models.CharField(blank=True, help_text='Operator: gt, gte, lt, lte, eq, in.', max_length=20)),
                ('condition_value', models.CharField(blank=True, help_text="Value to compare against (JSON-encoded for 'in').", max_length=255)),
                ('condition_true_step', models.PositiveIntegerField(blank=True, help_text='Sequence to jump to if condition is true.', null=True)),
                ('condition_false_step', models.PositiveIntegerField(blank=True, help_text='Sequence to jump to if condition is false.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_user', models.ForeignKey(blank=True, help_text='Specific user override (takes precedence over role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_template_steps', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['template', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='UserDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.TextField(blank=True, help_text="E.g. 'Out of office'.")),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('content_type_scope', models.ForeignKey(blank=True, help_text='If set, delegation only for this content type.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('delegate', models.ForeignKey(help_text='User receiving delegated authority.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_delegations', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(help_text='User delegating their authority.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_delegations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='accounts.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_delegations', to=settings.AUTH_USER_MODEL)),
                ('role_scope', models.ForeignKey(blank=True, help_text="If set, delegation only applies for this role's approvals.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.role')),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['delegator', 'status', 'starts_at', 'ends_at'], name='workflows_u_delegat_956ddb_idx'), models.Index(fields=['delegate', 'status', 'starts_at', 'ends_at'], name='workflows_u_delegat_f05016_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('workflow_created', 'Workflow Created'), ('workflow_submitted', 'Workflow Submitted'), ('step_assigned', 'Step Assigned'), ('step_decision', 'Step Decision'), ('step_escalated', 'Step Escalated'), ('step_delegated', 'Step Delegated'), ('workflow_approved', 'Workflow Approved'), ('workflow_rejected', 'Workflow Rejected'), ('workflow_cancelled', 'Workflow Cancelled'), ('sla_breached', 'SLA Breached'), ('delegation_created', 'Delegation Created'), ('delegation_revoked', 'Delegation Revoked')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='workflows.workflowinstance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_instance', 'created_at'], name='workflows_w_workflo_f192b7_idx'), models.Index(fields=['event_type', 'created_at'], name='workflows_w_event_t_66d206_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=160)),
                ('execution_mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('approver_role_slug', models.SlugField(blank=True, max_length=120)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acting_on_behalf_of', models.ForeignKey(blank=True, help_text='Original assignee if decision was made via delegation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_workflow_decisions', to=settings.AUTH_USER_MODEL)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_decisions', to=settings.AUTH_USER_MODEL)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowinstance')),
            ],
            options={
                'ordering': ['workflow_instance', 'sequence'],
                'unique_together': {('workflow_instance', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['content_type', 'object_id'], name='workflows_w_content_9e540a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['state', 'created_at'], name='workflows_w_state_dbf100_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplatestep',
            unique_together={('template', 'sequence')},
        ),
    ]
