# Generated by Django 5.2 on 2026-03-06 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_invitation_metadata'),
        ('settings', '0041_accesspolicy_policyaction_policycondition_and_more'),
        ('workflows', '0002_seed_celery_beat_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='accounts.organization')),
                ('role', models.ForeignKey(blank=True, help_text='Functional platform role used to resolve approvers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_approvers', to='settings.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_approver_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approvers',
                'ordering': ['organization_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_key', models.SlugField(help_text='Business process key, e.g. procurement.', max_length=80)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('sequence', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_workflow_steps', to='accounts.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_workflow_steps', to='workflows.workflowtemplate')),
                ('template_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_workflow_steps', to='workflows.workflowtemplatestep')),
            ],
            options={
                'db_table': 'workflow_steps',
                'ordering': ['organization_id', 'process_key', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('responsibility', models.CharField(choices=[('responsible', 'Responsible'), ('accountable', 'Accountable'), ('consulted', 'Consulted'), ('informed', 'Informed')], default='responsible', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_roles', to='accounts.organization')),
            ],
            options={
                'db_table': 'workflow_roles',
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_type', models.CharField(choices=[('responsible', 'Responsible'), ('accountable', 'Accountable'), ('consulted', 'Consulted'), ('informed', 'Informed')], default='responsible', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='workflows.approver')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_authorities', to='accounts.organization')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='workflows.processworkflowstep')),
                ('workflow_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorities', to='workflows.workflowrole')),
            ],
            options={
                'db_table': 'process_authority',
                'ordering': ['workflow_step_id', 'sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='approver',
            name='workflow_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvers', to='workflows.workflowrole'),
        ),
        migrations.AddIndex(
            model_name='processworkflowstep',
            index=models.Index(fields=['organization', 'process_key', 'sequence'], name='workflow_st_organiz_a8a611_idx'),
        ),
        migrations.AddIndex(
            model_name='processworkflowstep',
            index=models.Index(fields=['template', 'template_step'], name='workflow_st_templat_673c98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processworkflowstep',
            unique_together={('organization', 'process_key', 'code'), ('organization', 'process_key', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowrole',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='processauthority',
            index=models.Index(fields=['organization', 'authority_type', 'is_active'], name='process_aut_organiz_34c065_idx'),
        ),
        migrations.AddIndex(
            model_name='processauthority',
            index=models.Index(fields=['workflow_step', 'is_active'], name='process_aut_workflo_883ceb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='processauthority',
            unique_together={('workflow_step', 'workflow_role', 'approver', 'authority_type')},
        ),
        migrations.AddConstraint(
            model_name='approver',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('role__isnull', False), _connector='OR'), name='approvers_user_or_role_required'),
        ),
        migrations.AlterUniqueTogether(
            name='approver',
            unique_together={('organization', 'user', 'role', 'workflow_role')},
        ),
    ]
