# Generated by Django 5.2 on 2026-03-06 20:21

from django.db import migrations

WORKFLOW_ROLES = [
    {
        "code": "requester",
        "name": "Requester",
        "responsibility": "responsible",
        "description": "Initiates the process request.",
    },
    {
        "code": "manager",
        "name": "Manager",
        "responsibility": "accountable",
        "description": "Owns first-level approval accountability.",
    },
    {
        "code": "procurement",
        "name": "Procurement",
        "responsibility": "responsible",
        "description": "Performs procurement governance review.",
    },
    {
        "code": "finance",
        "name": "Finance",
        "responsibility": "accountable",
        "description": "Owns financial approval accountability.",
    },
    {
        "code": "ceo",
        "name": "CEO",
        "responsibility": "accountable",
        "description": "Final executive authority for high-value approvals.",
    },
]


PROCUREMENT_STEPS = [
    {"process_key": "procurement", "code": "requester-submit", "name": "Requester", "sequence": 1},
    {"process_key": "procurement", "code": "manager-review", "name": "Manager Review", "sequence": 2},
    {"process_key": "procurement", "code": "procurement-review", "name": "Procurement Review", "sequence": 3},
    {"process_key": "procurement", "code": "finance-review", "name": "Finance Review", "sequence": 4},
    {"process_key": "procurement", "code": "ceo-approval", "name": "CEO Approval", "sequence": 5},
]


AUTHORITY_MATRIX = [
    {
        "step_code": "manager-review",
        "workflow_role_code": "manager",
        "authority_type": "accountable",
        "role_slugs": ["manager", "department-admin"],
    },
    {
        "step_code": "procurement-review",
        "workflow_role_code": "procurement",
        "authority_type": "responsible",
        "role_slugs": ["procurement-officer"],
    },
    {
        "step_code": "finance-review",
        "workflow_role_code": "finance",
        "authority_type": "accountable",
        "role_slugs": ["finance-controller"],
    },
    {
        "step_code": "ceo-approval",
        "workflow_role_code": "ceo",
        "authority_type": "accountable",
        "role_slugs": ["developer-executive", "super-admin"],
    },
]


def seed_default_process_authority(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    Role = apps.get_model("settings", "Role")
    WorkflowRole = apps.get_model("workflows", "WorkflowRole")
    ProcessWorkflowStep = apps.get_model("workflows", "ProcessWorkflowStep")
    Approver = apps.get_model("workflows", "Approver")
    ProcessAuthority = apps.get_model("workflows", "ProcessAuthority")

    for org in Organization.objects.all().iterator():
        workflow_role_ids = {}
        for row in WORKFLOW_ROLES:
            workflow_role, _ = WorkflowRole.objects.get_or_create(
                organization_id=org.id,
                code=row["code"],
                defaults={
                    "name": row["name"],
                    "responsibility": row["responsibility"],
                    "description": row["description"],
                    "is_active": True,
                },
            )
            workflow_role_ids[row["code"]] = workflow_role.id

        step_ids = {}
        for row in PROCUREMENT_STEPS:
            step, _ = ProcessWorkflowStep.objects.get_or_create(
                organization_id=org.id,
                process_key=row["process_key"],
                code=row["code"],
                defaults={
                    "name": row["name"],
                    "sequence": row["sequence"],
                    "is_active": True,
                },
            )
            step_ids[row["code"]] = step.id

        for row in AUTHORITY_MATRIX:
            workflow_role_id = workflow_role_ids.get(row["workflow_role_code"])
            step_id = step_ids.get(row["step_code"])
            if not workflow_role_id or not step_id:
                continue

            for role_slug in row["role_slugs"]:
                role = Role.objects.filter(
                    organization_id=org.id,
                    slug=role_slug,
                ).first()
                if role is None:
                    continue

                approver, _ = Approver.objects.get_or_create(
                    organization_id=org.id,
                    user_id=None,
                    role_id=role.id,
                    workflow_role_id=workflow_role_id,
                    defaults={
                        "title": row["workflow_role_code"].replace("-", " ").title(),
                        "is_active": True,
                    },
                )

                ProcessAuthority.objects.get_or_create(
                    organization_id=org.id,
                    workflow_step_id=step_id,
                    workflow_role_id=workflow_role_id,
                    approver_id=approver.id,
                    authority_type=row["authority_type"],
                    defaults={
                        "sort_order": 10,
                        "is_active": True,
                    },
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0042_seed_default_contextual_access_policies"),
        ("workflows", "0003_approver_processworkflowstep_workflowrole_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_process_authority, noop_reverse),
    ]
