# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('settings', '0056_autoescalationrule_set_aer_org_created_idx_and_more'),
        ('workflows', '0004_seed_default_process_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalpolicy',
            index=models.Index(fields=['organization', '-created_at'], name='wf_apol_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='approver',
            index=models.Index(fields=['organization', '-created_at'], name='wf_appr_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrole',
            index=models.Index(fields=['organization', '-created_at'], name='wf_role_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplate',
            index=models.Index(fields=['organization', '-created_at'], name='wf_tmpl_org_created_idx'),
        ),
    ]
