# Generated by Django 5.2.12 on 2026-03-19 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0039_org_platform_flag'),
        ('properties', '0013_unit_category_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('safety', 'Safety'), ('security', 'Security'), ('fire', 'Fire'), ('environmental', 'Environmental'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('occurred_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_incidents', to='accounts.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_incidents', to='properties.property')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_incidents', to='properties.workorder')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='fac_inc_org_status_idx'), models.Index(fields=['organization', 'severity'], name='fac_inc_org_severity_idx'), models.Index(fields=['organization', '-occurred_at'], name='fac_inc_org_occurred_idx')],
            },
        ),
        migrations.CreateModel(
            name='UtilityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('electricity_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('water_m3', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('diesel_liters', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gas_m3', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_utility_readings', to='accounts.organization')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_utility_readings', to='properties.property')),
            ],
            options={
                'ordering': ['-reading_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', '-reading_date'], name='fac_util_org_reading_idx')],
            },
        ),
    ]
