# Generated by Django 5.2.12 on 2026-03-19 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=50)),
                ('facility_classification', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed_use', 'Mixed Use')], default='residential', max_length=20)),
                ('ownership_type', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('managed', 'Managed'), ('mixed', 'Mixed')], default='owned', max_length=20)),
                ('lease_start_date', models.DateField(blank=True, null=True)),
                ('lease_end_date', models.DateField(blank=True, null=True)),
                ('lease_party_name', models.CharField(blank=True, max_length=255)),
                ('lease_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lease_terms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_registry', to='accounts.organization')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_registry', to='properties.property')),
            ],
            options={
                'ordering': ['property__name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('floor_code', models.CharField(blank=True, max_length=50)),
                ('floor_number', models.IntegerField()),
                ('gross_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_type', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='facility_management.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_floors', to='accounts.organization')),
            ],
            options={
                'ordering': ['facility', 'floor_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('zone_code', models.CharField(max_length=50)),
                ('zone_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('common', 'Common Area'), ('amenity', 'Amenity'), ('service', 'Service'), ('other', 'Other')], default='other', max_length=20)),
                ('gross_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='facility_management.facility')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='facility_management.facilityfloor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_zones', to='accounts.organization')),
            ],
            options={
                'ordering': ['facility', 'floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityUnitSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_label', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_spaces', to='facility_management.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_unit_spaces', to='accounts.organization')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_space', to='properties.unit')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_spaces', to='facility_management.facilityzone')),
            ],
            options={
                'ordering': ['facility', 'zone', 'unit__unit_number'],
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['organization', 'facility_classification'], name='fac_reg_org_class_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['organization', 'ownership_type'], name='fac_reg_org_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('organization', 'facility_code'), name='fac_reg_org_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='facilityfloor',
            index=models.Index(fields=['organization', 'facility'], name='fac_floor_org_fac_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilityfloor',
            constraint=models.UniqueConstraint(fields=('facility', 'floor_number'), name='fac_floor_unique_number'),
        ),
        migrations.AddIndex(
            model_name='facilityzone',
            index=models.Index(fields=['organization', 'facility'], name='fac_zone_org_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityzone',
            index=models.Index(fields=['organization', 'zone_type'], name='fac_zone_org_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilityzone',
            constraint=models.UniqueConstraint(fields=('floor', 'zone_code'), name='fac_zone_floor_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='facilityunitspace',
            index=models.Index(fields=['organization', 'facility'], name='fac_space_org_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityunitspace',
            index=models.Index(fields=['organization', 'zone'], name='fac_space_org_zone_idx'),
        ),
    ]
