# Generated by Django 5.2.12 on 2026-03-19 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('crm', '0019_seed_celery_beat_procurement_demand_insights'),
        ('facility_management', '0004_seed_celery_beat_service_request_workflows'),
        ('finance', '0032_alter_paymentvoucher_status'),
        ('settings', '0068_subscriptionaddon_alter_featureflagdefinition_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitySpaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_type', models.CharField(choices=[('desk', 'Desk'), ('room', 'Room'), ('meeting_room', 'Meeting Room'), ('tenant_suite', 'Tenant Suite'), ('hot_desk', 'Hot Desk'), ('storage', 'Storage'), ('other', 'Other')], default='room', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_bookable', models.BooleanField(default=False)),
                ('booking_requires_approval', models.BooleanField(default=False)),
                ('requires_check_in', models.BooleanField(default=False)),
                ('default_booking_duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_space', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_profile', to='facility_management.facilityunitspace')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_space_profiles', to='accounts.organization')),
            ],
            options={
                'ordering': ['facility_space__facility__facility_code', 'facility_space__unit__unit_number'],
                'indexes': [models.Index(fields=['organization', 'status'], name='fac_occ_prof_org_status_idx'), models.Index(fields=['organization', 'space_type'], name='fac_occ_prof_org_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpaceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_type', models.CharField(choices=[('employee', 'Employee'), ('department', 'Department'), ('tenant', 'Tenant')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('ending_soon', 'Ending Soon'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('occupant_count', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_space_allocations', to='settings.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_space_allocations', to=settings.AUTH_USER_MODEL)),
                ('facility_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_allocations', to='facility_management.facilityunitspace')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_space_allocations', to='accounts.organization')),
                ('tenant_contact_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_space_allocations', to='crm.contactaccount')),
                ('tenant_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_space_allocations', to='finance.customer')),
            ],
            options={
                'ordering': ['start_date', 'facility_space__unit__unit_number', 'id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='fac_space_alloc_org_status_idx'), models.Index(fields=['organization', 'facility_space'], name='fac_space_alloc_org_space_idx'), models.Index(fields=['organization', 'allocation_type'], name='fac_space_alloc_org_type_idx'), models.Index(fields=['organization', 'end_date'], name='fac_space_alloc_org_end_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('attendee_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_space_bookings_approved', to=settings.AUTH_USER_MODEL)),
                ('facility_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_bookings', to='facility_management.facilityunitspace')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_space_bookings', to='accounts.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_space_bookings_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at', 'facility_space__unit__unit_number', 'id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='fac_space_book_org_status_idx'), models.Index(fields=['organization', 'facility_space'], name='fac_space_book_org_space_idx'), models.Index(fields=['organization', 'start_at'], name='fac_space_book_org_start_idx'), models.Index(fields=['organization', 'end_at'], name='fac_space_book_org_end_idx')],
            },
        ),
    ]
