# Generated by Django 5.2.12 on 2026-03-19 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('facility_management', '0006_seed_celery_beat_space_occupancy_workflows'),
        ('finance', '0032_alter_paymentvoucher_status'),
        ('procurement', '0006_procurementdemandinsight'),
        ('properties', '0016_servicerequest_assigned_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=120)),
                ('utility_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas'), ('diesel', 'Diesel')], default='electricity', max_length=20)),
                ('unit_of_measure', models.CharField(blank=True, max_length=30)),
                ('location_label', models.CharField(blank=True, max_length=255)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('is_smart_meter', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_utility_meters', to='accounts.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_utility_meters', to='properties.property')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_meters', to='procurement.vendor')),
            ],
            options={
                'ordering': ['property__name', 'utility_type', 'meter_number'],
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('utility_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas'), ('diesel', 'Diesel')], default='electricity', max_length=20)),
                ('bill_number', models.CharField(max_length=120)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('usage_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('unit_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance_bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_bill_record', to='finance.bill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_utility_bills', to='accounts.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_utility_bills', to='properties.property')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_bills', to='procurement.vendor')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='facility_management.utilitymeter')),
            ],
            options={
                'ordering': ['-billing_period_end', '-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UtilityMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_at', models.DateTimeField()),
                ('reading_date', models.DateField()),
                ('reading_value', models.DecimalField(decimal_places=3, max_digits=16)),
                ('consumption_delta', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('is_estimated', models.BooleanField(default=False)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_utility_meter_readings_entered', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='facility_management.utilitymeter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_utility_meter_readings', to='accounts.organization')),
            ],
            options={
                'ordering': ['-reading_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='utilitymeter',
            index=models.Index(fields=['organization', 'utility_type'], name='fac_util_meter_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitymeter',
            index=models.Index(fields=['organization', 'property'], name='fac_util_meter_org_prop_idx'),
        ),
        migrations.AddConstraint(
            model_name='utilitymeter',
            constraint=models.UniqueConstraint(fields=('organization', 'meter_number'), name='fac_util_meter_org_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='utilitybill',
            index=models.Index(fields=['organization', 'status'], name='fac_util_bill_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitybill',
            index=models.Index(fields=['organization', 'utility_type'], name='fac_util_bill_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitybill',
            index=models.Index(fields=['organization', 'property'], name='fac_util_bill_org_prop_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitybill',
            index=models.Index(fields=['organization', 'due_date'], name='fac_util_bill_org_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='utilitybill',
            constraint=models.UniqueConstraint(fields=('organization', 'bill_number'), name='fac_util_bill_org_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='utilitymeterreading',
            index=models.Index(fields=['organization', 'meter'], name='fac_util_read_org_meter_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitymeterreading',
            index=models.Index(fields=['organization', '-reading_at'], name='fac_util_read_org_at_idx'),
        ),
        migrations.AddIndex(
            model_name='utilitymeterreading',
            index=models.Index(fields=['organization', 'is_anomaly'], name='fac_util_read_org_anom_idx'),
        ),
    ]
