# Generated by Django 5.2.12 on 2026-03-19 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.facility_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_seed_platform_roles'),
        ('compliance', '0003_complianceaudit_comp_aud_org_status_idx_and_more'),
        ('facility_management', '0008_seed_celery_beat_utility_energy_workflows'),
        ('properties', '0016_servicerequest_assigned_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityComplianceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('checklist_type', models.CharField(choices=[('safety', 'Safety'), ('fire_safety', 'Fire Safety'), ('electrical', 'Electrical'), ('environmental', 'Environmental'), ('occupational_health', 'Occupational Health'), ('regulatory', 'Regulatory'), ('housekeeping', 'Housekeeping'), ('incident_follow_up', 'Incident Follow-Up')], default='safety', max_length=25)),
                ('frequency', models.CharField(choices=[('one_time', 'One-Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='one_time', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('compliant_items_count', models.PositiveIntegerField(default=0)),
                ('total_items_count', models.PositiveIntegerField(default=0)),
                ('auto_create_violation', models.BooleanField(default=True)),
                ('auto_create_follow_up_inspection', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityComplianceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_compliant', models.BooleanField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('blueprint', 'Facility Blueprint'), ('drawing', 'Technical Drawing'), ('equipment_manual', 'Equipment Manual'), ('maintenance_log', 'Maintenance Log'), ('compliance_certificate', 'Compliance Certificate'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(blank=True, upload_to=apps.facility_management.models.facility_document_path)),
                ('description', models.TextField(blank=True)),
                ('version_label', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('review_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review_due', 'Review Due'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Upload'), ('generated', 'Generated')], default='manual', max_length=20)),
                ('generated_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_type', 'title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityRegulatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('valid', 'Valid'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='pending_review', max_length=20)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('review_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['expiry_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FacilitySafetyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('incident', 'Incident'), ('inspection', 'Inspection'), ('checklist', 'Checklist'), ('document', 'Document'), ('compliance', 'Compliance'), ('workflow', 'Workflow')], max_length=20)),
                ('event_type', models.CharField(choices=[('incident_reported', 'Incident Reported'), ('incident_resolved', 'Incident Resolved'), ('follow_up_inspection_created', 'Follow-Up Inspection Created'), ('corrective_work_order_created', 'Corrective Work Order Created'), ('inspection_scheduled', 'Inspection Scheduled'), ('inspection_completed', 'Inspection Completed'), ('checklist_created', 'Checklist Created'), ('checklist_completed', 'Checklist Completed'), ('violation_created', 'Compliance Violation Created'), ('regulatory_document_uploaded', 'Regulatory Document Uploaded'), ('regulatory_document_flagged', 'Regulatory Document Flagged'), ('compliance_synced', 'Compliance Synced'), ('workflow_synced', 'Workflow Synced')], max_length=40)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='facilityincident',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='facilityincident',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='facilityincident',
            name='facility_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='facility_management.facilityunitspace'),
        ),
        migrations.AddField(
            model_name='facilityincident',
            name='follow_up_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_incident_follow_ups', to='properties.inspection'),
        ),
        migrations.AddField(
            model_name='facilityincident',
            name='incident_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facilityincident',
            name='requires_regulatory_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='facilityincident',
            index=models.Index(fields=['organization', 'facility'], name='fac_inc_org_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityincident',
            index=models.Index(fields=['organization', 'incident_code'], name='fac_inc_org_code_idx'),
        ),
        migrations.AddField(
            model_name='facilitycompliancechecklist',
            name='compliance_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_compliance_checklists', to='compliance.compliancerequirement'),
        ),
        migrations.AddField(
            model_name='facilitycompliancechecklist',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checklists', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='facilitycompliancechecklist',
            name='facility_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checklists', to='facility_management.facilityunitspace'),
        ),
        migrations.AddField(
            model_name='facilitycompliancechecklist',
            name='linked_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checklists', to='facility_management.facilityincident'),
        ),
        migrations.AddField(
            model_name='facilitycompliancechecklist',
            name='linked_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_compliance_checklists', to='properties.inspection'),
        ),
        migrations.AddField(
            model_name='facilitycompliancechecklist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_compliance_checklists', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='facilitycompliancechecklist',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_compliance_checklists', to='properties.property'),
        ),
        migrations.AddField(
            model_name='facilitycompliancechecklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facility_management.facilitycompliancechecklist'),
        ),
        migrations.AddField(
            model_name='facilitydocument',
            name='asset_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='properties.assetcomponent'),
        ),
        migrations.AddField(
            model_name='facilitydocument',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='facilitydocument',
            name='facility_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='facility_management.facilityunitspace'),
        ),
        migrations.AddField(
            model_name='facilitydocument',
            name='linked_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='properties.inspection'),
        ),
        migrations.AddField(
            model_name='facilitydocument',
            name='linked_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_records', to='properties.workorder'),
        ),
        migrations.AddField(
            model_name='facilitydocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_documents', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='facilitydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_documents', to='properties.property'),
        ),
        migrations.AddField(
            model_name='facilitydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilityregulatorydocument',
            name='compliance_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_regulatory_documents', to='compliance.compliancerequirement'),
        ),
        migrations.AddField(
            model_name='facilityregulatorydocument',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_documents', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='facilityregulatorydocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_regulatory_documents', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='facilityregulatorydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_regulatory_documents', to='properties.property'),
        ),
        migrations.AddField(
            model_name='facilityregulatorydocument',
            name='property_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_regulatory_record', to='properties.propertydocument'),
        ),
        migrations.AddField(
            model_name='facilityregulatorydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_regulatory_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitysafetyauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_safety_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitysafetyauditlog',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_audit_logs', to='facility_management.facility'),
        ),
        migrations.AddField(
            model_name='facilitysafetyauditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_safety_audit_logs', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='facilitysafetyauditlog',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_safety_audit_logs', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='facilitycompliancechecklist',
            index=models.Index(fields=['organization', 'status'], name='fac_chk_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycompliancechecklist',
            index=models.Index(fields=['organization', 'due_date'], name='fac_chk_org_due_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycompliancechecklist',
            index=models.Index(fields=['organization', 'checklist_type'], name='fac_chk_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitycompliancechecklist',
            index=models.Index(fields=['organization', 'facility'], name='fac_chk_org_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitydocument',
            index=models.Index(fields=['organization', 'document_type'], name='fac_doc_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitydocument',
            index=models.Index(fields=['organization', 'status'], name='fac_doc_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitydocument',
            index=models.Index(fields=['organization', 'facility'], name='fac_doc_org_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitydocument',
            index=models.Index(fields=['organization', 'review_due_date'], name='fac_doc_org_review_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitydocument',
            index=models.Index(fields=['organization', 'expiry_date'], name='fac_doc_org_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityregulatorydocument',
            index=models.Index(fields=['organization', 'status'], name='fac_regdoc_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityregulatorydocument',
            index=models.Index(fields=['organization', 'expiry_date'], name='fac_regdoc_org_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityregulatorydocument',
            index=models.Index(fields=['organization', 'facility'], name='fac_regdoc_org_fac_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitysafetyauditlog',
            index=models.Index(fields=['organization', 'created_at'], name='fac_hsc_audit_org_at_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitysafetyauditlog',
            index=models.Index(fields=['organization', 'event_type'], name='fac_hsc_audit_org_evt_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitysafetyauditlog',
            index=models.Index(fields=['organization', 'entity_type'], name='fac_hsc_audit_org_ent_idx'),
        ),
    ]
