# Generated by Django 5.2 on 2026-03-05 04:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0001_initial'),
        ('finance', '0012_spventity_paymentplan_paymentinstallment'),
        ('procurement', '0002_vendor'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('client', 'Client'), ('contractor', 'Contractor'), ('investor', 'Investor')], max_length=20)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_onboarding_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Leave blank for global templates available to all organizations.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_onboarding_templates', to='accounts.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_partner_onboarding_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['partner_type', 'organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('approval_role_label', models.CharField(blank=True, max_length=120)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('auto_complete', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='partners.onboardingtemplate')),
            ],
            options={
                'ordering': ['template_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOnboardingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('client', 'Client'), ('contractor', 'Contractor'), ('investor', 'Investor')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contract_reference', models.CharField(blank=True, max_length=120)),
                ('investment_vehicle_reference', models.CharField(blank=True, max_length=120)),
                ('portal_access_granted', models.BooleanField(default=False)),
                ('portal_access_granted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partner_onboarding_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_onboarding_cases', to=settings.AUTH_USER_MODEL)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_cases', to='partners.onboardingtemplatestage')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_cases', to='finance.customer')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_cases', to='finance.investor')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_cases', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_onboarding_cases', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_cases', to='projects.project')),
                ('spv_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_cases', to='finance.spventity')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_cases', to='partners.onboardingtemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_partner_onboarding_cases', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_cases', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOnboardingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('case_created', 'Case Created'), ('stages_initialized', 'Stages Initialized'), ('stage_status_changed', 'Stage Status Changed'), ('case_status_changed', 'Case Status Changed'), ('approval_recorded', 'Approval Recorded'), ('entitlement_provisioned', 'Entitlement Provisioned'), ('portal_access_granted', 'Portal Access Granted')], max_length=40)),
                ('actor_role_label', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_audit_events', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='partners.partneronboardingcase')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_role', models.CharField(choices=[('client', 'Client'), ('contractor', 'Contractor'), ('investor', 'Investor'), ('lead_investor', 'Lead Investor')], max_length=20)),
                ('contract_reference', models.CharField(blank=True, max_length=120)),
                ('investment_vehicle_reference', models.CharField(blank=True, max_length=120)),
                ('budget_scope', models.CharField(choices=[('none', 'No Budget Visibility'), ('boq_only', 'BOQ-Only'), ('aggregated', 'Aggregated Budget View'), ('full', 'Full Budget Visibility')], default='none', max_length=20)),
                ('can_view_other_investors', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_comment', models.BooleanField(default=True)),
                ('can_download_documents', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partner_entitlements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_entitlements', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_entitlements', to='projects.project')),
                ('spv_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_entitlements', to='finance.spventity')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='partners.partneronboardingcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOnboardingStageProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('waived', 'Waived'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence_links', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='partners.partneronboardingcase')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_partner_onboarding_stage_progress', to=settings.AUTH_USER_MODEL)),
                ('template_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_progress', to='partners.onboardingtemplatestage')),
            ],
            options={
                'ordering': ['template_stage__sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOnboardingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_required', 'Changes Required')], max_length=20)),
                ('approver_role_label', models.CharField(blank=True, max_length=120)),
                ('comments', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_approvals', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='partners.partneronboardingcase')),
                ('stage_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='partners.partneronboardingstageprogress')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'partner_type', 'code', 'version'), name='unique_partner_onboarding_template_version'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplatestage',
            constraint=models.UniqueConstraint(fields=('template', 'sequence'), name='unique_onboarding_stage_sequence'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplatestage',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_onboarding_stage_code'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingcase',
            index=models.Index(fields=['organization', 'partner_type', 'status'], name='partners_pa_organiz_737c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingcase',
            index=models.Index(fields=['partner_type', 'portal_access_granted'], name='partners_pa_partner_a81ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingcase',
            index=models.Index(fields=['project', 'spv_entity'], name='partners_pa_project_044def_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingauditlog',
            index=models.Index(fields=['case', 'created_at'], name='partners_pa_case_id_f9f9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='partners_pa_event_t_770661_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerentitlement',
            index=models.Index(fields=['organization', 'portal_role', 'is_active'], name='partners_pa_organiz_bf17d3_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerentitlement',
            index=models.Index(fields=['project', 'spv_entity'], name='partners_pa_project_a2c958_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerentitlement',
            index=models.Index(fields=['contract_reference', 'investment_vehicle_reference'], name='partners_pa_contrac_8b1b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingstageprogress',
            index=models.Index(fields=['case', 'status'], name='partners_pa_case_id_540bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingstageprogress',
            index=models.Index(fields=['template_stage', 'status'], name='partners_pa_templat_3f216b_idx'),
        ),
        migrations.AddConstraint(
            model_name='partneronboardingstageprogress',
            constraint=models.UniqueConstraint(fields=('case', 'template_stage'), name='unique_case_template_stage_progress'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingapproval',
            index=models.Index(fields=['case', 'decision', 'decided_at'], name='partners_pa_case_id_489652_idx'),
        ),
    ]
