# Generated by Django 5.2 on 2026-03-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerportallegalacceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneronboardingauditlog',
            name='event_type',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('stages_initialized', 'Stages Initialized'), ('stage_status_changed', 'Stage Status Changed'), ('case_status_changed', 'Case Status Changed'), ('approval_recorded', 'Approval Recorded'), ('entitlement_provisioned', 'Entitlement Provisioned'), ('portal_access_granted', 'Portal Access Granted'), ('erp_entity_created', 'ERP Entity Created'), ('lead_archived', 'Lead Archived')], max_length=40),
        ),
    ]
