# Generated by Django 5.2 on 2026-03-05 18:23

import apps.partners.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_documentauditevent_event_type_and_more'),
        ('partners', '0003_alter_partneronboardingauditlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTemplateDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('accepted_sources', models.JSONField(blank=True, default=list, help_text='Allowed values from PartnerOnboardingIntakeDocument.SourceChannel.')),
                ('allowed_extensions', models.JSONField(blank=True, default=list, help_text="Optional list of file extensions (e.g. ['pdf', 'jpg']).")),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requirements', to='partners.onboardingtemplatestage')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='partners.onboardingtemplate')),
            ],
            options={
                'ordering': ['template_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOnboardingIntakeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.SlugField(max_length=80)),
                ('document_name', models.CharField(max_length=200)),
                ('source_channel', models.CharField(choices=[('physical_scan', 'Physical Submission (Scanned)'), ('email', 'Email'), ('secure_upload_link', 'Secure Upload Link'), ('tender_portal', 'Tender Portal'), ('data_room', 'Data Room'), ('internal_generated', 'Internal Generated'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.partners.models.partner_intake_upload_path)),
                ('external_reference_url', models.URLField(blank=True)),
                ('external_reference_number', models.CharField(blank=True, max_length=120)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waived', 'Waived')], default='received', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_documents', to='partners.partneronboardingcase')),
                ('linked_repository_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_onboarding_intake_documents', to='documents.document')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_documents', to='partners.onboardingtemplatedocumentrequirement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_onboarding_intake_documents', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_partner_onboarding_intake_documents', to=settings.AUTH_USER_MODEL)),
                ('template_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_documents', to='partners.onboardingtemplatestage')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='onboardingtemplatedocumentrequirement',
            index=models.Index(fields=['template', 'is_required'], name='partners_on_templat_08e5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingtemplatedocumentrequirement',
            index=models.Index(fields=['applies_to_stage', 'is_required'], name='partners_on_applies_aee130_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtemplatedocumentrequirement',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_onboarding_template_document_requirement_code'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingintakedocument',
            index=models.Index(fields=['case', 'status'], name='partners_pa_case_id_e3f792_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingintakedocument',
            index=models.Index(fields=['requirement', 'status'], name='partners_pa_require_987700_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingintakedocument',
            index=models.Index(fields=['source_channel', 'status'], name='partners_pa_source__9bf7e1_idx'),
        ),
    ]
