# Generated by Django 5.2 on 2026-03-08 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_apikey_acc_apikey_sa_active_idx_and_more'),
        ('crm', '0007_broker_crm_brkr_org_status_idx_and_more'),
        ('finance', '0016_account_fin_acct_org_created_idx_and_more'),
        ('partners', '0004_onboardingtemplatedocumentrequirement_and_more'),
        ('procurement', '0004_goodsreceipt_proc_gr_org_status_idx_and_more'),
        ('projects', '0018_project_proj_proj_org_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='onboardingtemplate',
            index=models.Index(fields=['organization', '-created_at'], name='part_tmpl_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerentitlement',
            index=models.Index(fields=['organization', '-created_at'], name='part_ent_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingcase',
            index=models.Index(fields=['organization', 'status'], name='part_case_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='partneronboardingcase',
            index=models.Index(fields=['organization', '-created_at'], name='part_case_org_created_idx'),
        ),
    ]
